### ISSUE TITLE
🐛[BUG][Quest] Shattering Stars (BRD Maat) - Maat is too strong, Asuran Fists OP

### ISSUE THREAD

**Issue by KiplingFFXI** [HorizonFFXI/HorizonXI-Issues#10]
**What does this bug affect?**

Asuran Fists seems very overtuned. Wiki strategies says it should do ~350+, but it was hitting me for 800-1200 across 4 attempts each time, often with double Minne up. I am linking a video attempt of me doing it where you can see I have very basic/trash gear and a reasonable amount of meds, but Asuran Fists still seems generally not survivable - Wiki reference: https://ffxiclopedia.fandom.com/wiki/Shattering_Stars/Bard 

**Steps to Reproduce**

Fight Maat as a BRD and get blasted

**Expected behavior**

See above.

**Screenshots**

![Kipling_2022 07 18_202323 - Kipling FFXI](https://user-images.githubusercontent.com/111715243/187093109-49233864-0960-404d-a3e3-b4a25d8c18f4.png)

One of my attempts: https://www.youtube.com/watch?v=eYeBBK2ruCg

**Setup Information**

N/A - Older report.

**Additional context**

N/A

**Comment by dallano** [comment]
This seems to have been corrected. I'm getting hit for around 300-450 dmg

**Comment by dallano** [comment]
Went through a few maat fights with lvl 60ish gear and dmg seems appropriate now.

**Comment by DrakoGereck** [comment]
this is not corrected i got one shot on to attempts full AF gear and all necessary pots,  I made a post he killed me within 30 second on second attempt .
