### ISSUE TITLE
🐛[BUG] KSNM - Double Dragonian

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#100]
**What does this bug affect?**
NMs using incorrect TP moves based on discord capture. Currently both can use Petro Eyes / Flame Breath / Wind Breath / Poison Breath. Minstrel also uses Body Slam / Heavy Stomp.

**Steps to Reproduce**
Go in to the fight and feed the NMs TP to check which moves they do.

**Expected behavior**
Based on the capture video, the NMs should only use the following:
Berserker uses: Mighty Strikes (War 2hr), Body Slam (Heavy AOE Damage), Chaos Blade (Cone AOE Curse), Heavy Stomp (Heavy AOE Damage + Paralyze)
Minstrel uses: Soul Voice (BRD 2hr), Songs: Army's Paeon V / Battlefield Elegy / Foe Requiem VI / Knight's Minne IV / Mage's Ballad II / Uncanny Etude / Swift Etude / Horde Lullaby, Chaos Blade (Cone AOE Curse), Thornsong (100~150 damage spikes effect), Voidsong (Large AOE Status negation), Lodesong (AOE Gravity)

**Setup Information**
Version 30220802_3

**Comment by dallano** [comment]
Fixed in PR: https://github.com/AirSkyBoat/AirSkyBoat/pull/376
