### ISSUE TITLE
🐛[BUG][System] Gysahl Greens stack issues

### ISSUE THREAD

**Issue by hookstar** [HorizonFFXI/HorizonXI-Issues#1000]
**What does this bug affect?**

Vendors offer greens at stack of 99 but only can purchase 12.
**Steps to Reproduce**

**Expected behavior**

buy 99
**Screenshots**

**Setup Information**

**Additional context**

Dat mod it would seem like...

**Comment by bliven-was-taken** [comment]
https://github.com/HorizonFFXI/HorizonXI-Issues/issues/742

**Comment by hookstar** [comment]
Thanks!
