### ISSUE TITLE
🐛[BUG][System] Bronze Knife desynth does not work

### ISSUE THREAD

**Issue by Caiusballad78** [HorizonFFXI/HorizonXI-Issues#1001]
**What does this bug affect?**
Bronze Knife & Lightning Crystal Synthesis recipe does not work.

**Comment by gtarrantiii** [comment]
Recipe not present in ASB database and likely not on Horizon as a result.
![image](https://user-images.githubusercontent.com/16801070/220241057-ee39bedb-aed9-463d-9e2e-8300218ef09b.png)

Recipe did appear in previous DSP/Topaz database scripts:
![image](https://user-images.githubusercontent.com/16801070/220241275-c5dcf33a-006c-4393-a64c-1bef28017612.png)

INSERT INTO `synth_recipes` (`ID`, `Desynth`, `KeyItem`, `Wood`, `Smith`, `Gold`, `Cloth`, `Leather`, `Bone`, `Alchemy`, `Cook`, `Crystal`, `HQCrystal`, `Ingredient1`, `Ingredient2`, `Ingredient3`, `Ingredient4`, `Ingredient5`, `Ingredient6`, `Ingredient7`, `Ingredient8`, `Result`, `ResultHQ1`, `ResultHQ2`, `ResultHQ3`, `ResultQty`, `ResultHQ1Qty`, `ResultHQ2Qty`, `ResultHQ3Qty`, `ResultName`,`ContentTag`) VALUES (**need id here**, 1, 0, 0, 5, 0, 0, 0, 0, 0, 0, 4100, 4242, 16465, 0, 0, 0, 0, 0, 0, 0, 649, 649, 715, 715, 1, 1, 1, 1, 'Bronze Ingot', NULL);

ffxiclopedia has a revision back to 2006 with the desynth recipe there so it is an era valid recipe.
