### ISSUE TITLE
🐛[BUG][Combat] Evasion skillups on too weak mobs

### ISSUE THREAD

**Issue by Ayzher** [HorizonFFXI/HorizonXI-Issues#1003]
**System/Combat**
**What does this bug affect?** Getting Skill up on evasion on low level mobs 
**Level 60 war/thf farming in bubu dhalmel and crawler and i get a lot of skills up from evasion ( shouldn't be )**

**Steps to Reproduce** 

**It seems to only happens as WARRIOR MAIN JOB** Don't know what else to say, pulling 4-5 mobs at a time and I got skill up.
**Expected behavior**
**Nothing. No skill up.**

**Screenshots**

![image](https://user-images.githubusercontent.com/124313472/216461557-2d5ad0d7-9e10-4b02-bb66-c8ce80a5982d.png)

**Setup Information**

**Not sure.**
**Additional context**

**It's very simple, as a lv 60 WAR farming lv 20-23 mobs you shouldn't get evasion skill up, I was 189 at that time, got to 190 super quick and then later 2-3 dayx after same thing happened.**

**Comment by CriticalXI** [comment]
Duplicate #873
