### ISSUE TITLE
Cannot obtain Conquest point item: Royal Knight's Breeches

### ISSUE THREAD

**Issue by shon81** [HorizonFFXI/HorizonXI-Issues#1005]
Cannot purchase a Rank 6 Conquest item from any guard. I am rank 6. When I try to obtain the item I get the response:

Your rank is too low to purchase the .

The item is Royal Knight's breeches.

**Comment by bliven-was-taken** [comment]
It requires Sandy in 1st place.

**Comment by TracentEden** [comment]
Duplicate of https://github.com/HorizonFFXI/HorizonXI-Issues/issues/991
