### ISSUE TITLE
🐛[BUG]NPC - Xolotl wasnt killed waited for next night and it didnt respawn

### ISSUE THREAD

**Issue by Linkinfate** [HorizonFFXI/HorizonXI-Issues#1007]
**What does this bug affect?**
Server came up i saw it up got party out for next night to kill it @ 20:00 it didnt respawn.  Currently waitng for next night just incase it will pop

**Expected behavior**
suppose to respawn next night if it hasn't been killed

**Comment by TracentEden** [comment]
This issue should be fixed, can reopen if it happens again.
