### ISSUE TITLE
🐛[BUG] KSNM - Seasons Greatings

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#101]
**What does this bug affect?**
Ulagohvsdi Tlugvi uses TP move Emetic Discharge instead of Pinecone Bomb. Goga Tlugvi uses TP move Emetic Discharge instead of Leafstorm. Gola Tlugvi uses Emetic Discharge instead of Drill Branch.

**Steps to Reproduce**
Go into the fight and feed the NMs TP to check what move it uses.

**Expected behavior**
Ulagohvsdi Tlugvi (NIN) should only use Pinecone Bomb for TP move. Goga Tlugvi (MNK) should only use Leafstorm for TP move. Gola Tlugvi (DRK) should only use Drill Branch for TP move.

**Setup Information**
Version 30220802_3

**Additional context**
Just wanted to note that the WHM NM used high level magic such as Dia 3 and Banish 4, and the NIN NM used SAN level ninjutsu (Ustusemi: San was fun). Not sure if this is correct or not as there's no capture / youtube available for it and nothing mentioned in wiki. Gilagoge Tlugvi (WHM) was the only one using it's correct TP move of only Entangle.

**Comment by dallano** [comment]
Bug fix in PR:https://github.com/AirSkyBoat/AirSkyBoat/pull/376
