### ISSUE TITLE
🐛[BUG][Combat] KV not spawning

### ISSUE THREAD

**Issue by ChaosofHorizon** [HorizonFFXI/HorizonXI-Issues#1010]
**What does this bug affect?**

been Caming king vinegarroon for a couple days have seen multiple earth/ double earth weather and he still hasnt spawned as of writing this i have been up for 24hours and still havent seen him.
**Steps to Reproduce**

**Expected behavior**

21-24hr window from last death/despawn if not popped in that window will pop in the next earth storm
**Screenshots**

**Setup Information**

**Additional context**

**Comment by TracentEden** [comment]
This should now be fixed, can reopen if it is not the case.
