### ISSUE TITLE
🐛[BUG][Mission]

### ISSUE THREAD

**Issue by PrinceOfParallax** [HorizonFFXI/HorizonXI-Issues#1011]
**What does this bug affect?**
Out of Era Cut Sceene When Entering PROMMIE

**Steps to Reproduce**
ENTER PROMMMY

**Expected behavior**
I am getting the CS with Lion inside the crag  (this one - https://youtu.be/FlUyPvMDZ_E?t=586 )

This is 1-7 from Rhapsodies of Vana'Diel  and OUT OF ERA

**Screenshots**

**Setup Information**

**Additional context**

**Comment by TracentEden** [comment]
Duplicate of https://github.com/HorizonFFXI/HorizonXI-Issues/issues/936
