### ISSUE TITLE
🐛[BUG][System] Burdock

### ISSUE THREAD

**Issue by PrinceOfParallax** [HorizonFFXI/HorizonXI-Issues#1013]
**What does this bug affect?**
GARDENING

**Steps to Reproduce**
Copper Pot - Fire Crystal

**Expected behavior**
Should not exist in Era

**Screenshots**

**Setup Information**
Gardening created a Burdock - this is out of era and is a Wing item

**Additional context**
Saw someone eating one in Jeuno today.

**Comment by TracentEden** [comment]
Will be fixed in a completed PR (watch patch notes), thanks for reporting.
