### ISSUE TITLE
🐛[BUG][Mission]The Root of the Problem - BLM AF3

### ISSUE THREAD

**Issue by PrinceOfParallax** [HorizonFFXI/HorizonXI-Issues#1016]
**What does this bug affect?**
Not sure Quest isn't flagging correctly in the game for me 

**Steps to Reproduce**
All I need to do is keep talking to Chumimi again and it triggers the temp item to be given and the cutscene

**Expected behavior**
Should only be able to be done once?

**Screenshots**
![image](https://user-images.githubusercontent.com/38820735/216804424-a39eeb25-de4b-4bac-a148-cace76c080cd.png)

**Setup Information**

**Additional context**

**Comment by dallano** [comment]
Your flag should be properly set. I will fix this bug though. Thank you for the report.
