### ISSUE TITLE
🐛[BUG]Launcher] error with a .zip file in the download

### ISSUE THREAD

**Issue by Fultron13** [HorizonFFXI/HorizonXI-Issues#1018]
**What does this bug affect?**

EPERM: error with a .zip file in the download
**Steps to Reproduce**

click "start file download" and error pops up right away but progress bar still shows all other files downloading
**Expected behavior**

Download files to selected folder for extraction so game can be downloaded
**Screenshots**

**Setup Information**

Horizon XI launcher v1.1.4, Windows 11, downloaded from Google Chrome
**Additional context**

When attempting to access the file that the error is associated with i can not get permission to extract the .zip folder and i have attempted to change permissions multiple ways to no avail.

**Comment by hookstar** [comment]
Run as administrator?

**Comment by Flam9** [comment]
Late to this issue but going to close as stale. Please open a thread in the Discord (launcher-support forum) with additional information, such as a screenshot of the error pop up.
