### ISSUE TITLE
🐛[BUG]Combat Benediction does not remove curse

### ISSUE THREAD

**Issue by PfistoFFXI** [HorizonFFXI/HorizonXI-Issues#1019]
**What does this bug affect?**

Benediction does not remove curse.
**Steps to Reproduce**

Get cursed, use benediction
**Expected behavior**

Removal of curse.
**Screenshots**

![ffxi_2023 02 05_13 48 55](https://user-images.githubusercontent.com/40551158/216838820-c47a20cc-457b-4dd3-8602-ab01e72d4068.jpg)
if you look, you can see curse still on the bar.
**Setup Information**

/version does not yield any results. Taken Sunday February 5
**Additional context**

https://ffxiclopedia.fandom.com/wiki/Benediction

someone else has said it's not unique to curse either, but I don't have any knowledge of that.

**Comment by TracentEden** [comment]
Benediction did not remove status ailments in era (was added in ToAU, see [here](http://www.playonline.com/pcd/update/ff11us/2006041883vPh1/detail.html))

**Comment by hookstar** [comment]
Benediction added status removal in ToAU. 

As of the April 28th 2006 Update, Benediction now cures status ailments.

Might still have that curse on ya when ToAU rolls around.
