### ISSUE TITLE
🐛[BUG] KSNM - E-vase-ive Action

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#102]
**What does this bug affect?**
If you cast magic near the pots the Fire Pot NM aggros you. Wiki states the NMs are highly resistant or immune to silence, however I was able to silence all pots multiple times as a naked 75 rdm / whm. All pots missing ancient magic spells. Fire Pot spell list incorrect, casts spells outside of it's element. Earth Pot used Slow II instead of normal Slow. 

TL:DR: Pots aggro magic when they shouldn't. Check silence resistance. All pots missing AM. Need to fix pot's spell list.

**Steps to Reproduce**
Go into the fight and cast magic near the pots. Allow Fire Pot to cast spells on you and check what spells they cast. Silence pots to see if it lands.

**Expected behavior**
No capture found on discord. Per wiki: "They do not aggro - to magic or otherwise - until attacked." 
Each pot should only cast spells from their element: "Each Pot has Chainspell as well as various spells of its element - typically a DoT (eg. Rasp), an enfeebling spell (eg. Slow), an enhancing spell (eg. Enstone), a Tier 4 single target nuke (eg. Stone IV), a Tier 3 AoE spell (eg. Stonega III) and an AM (eg. Quake)."
https://www.youtube.com/watch?v=d7xieJG24kg video is from 2011, but it shows the player casting in the middle of the pots with no aggro and the earth pot casted quake (AM) within 2:30.

**Setup Information**
Version 30220802_3

**Additional context**
Tested all of the pots. All pots absorb their element.

**Comment by dallano** [comment]
Fix in PR: https://github.com/AirSkyBoat/AirSkyBoat
