### ISSUE TITLE
🐛[BUG][NPC] Spiny Spipi (NM) placeholders not spawning in certain locations.

### ISSUE THREAD

**Issue by Bigmoose08** [HorizonFFXI/HorizonXI-Issues#1023]
**What does this bug affect?**
Spiny Spipi (NM) spawning. (Not spawning)

**Steps to Reproduce**
I've checked before and after server restarts and the crawler placeholders for the Spiny Spipi NM in East Sarutabaruta aren't spawning at (K-6) and (J-6). (Check Mist Silk Cape price on AH.. rather high for a level 10 cloak with a decent drop rate.)

**Expected behavior**
Crawler place holders should be spawning at K-6 and J-6 in East Sarutabaruta.

**Screenshots**
I don't think this is necessary. It would just be a blank picture with my character at each location.

**Setup Information**
Horizon Launcher. 

**Additional context**
N/A

**Comment by TracentEden** [comment]
As can be seen in ASB [here](https://github.com/AirSkyBoat/AirSkyBoat/blob/staging/scripts/zones/East_Sarutabaruta/IDs.lua), Spiny Spipi has only a single placeholder, so just need to kill that one.

**Comment by Bigmoose08** [comment]
https://ffxiclopedia.fandom.com/wiki/Spiny_Spipi?oldid=647521

If it's a lottery spawn.. how does it only have a single placeholder?

**Comment by TracentEden** [comment]
I mean a lot of lottery NMs only have single PH, just kill the PH until it appears. Still a lottery because you do not know how long it will take to spawn, could be after 1 PH kill or 30.

**Comment by Bigmoose08** [comment]
Understood. Can you confirm if the two crawlers that are supposed to spawn in the river at K-6 and J-6 actually spawn? I haven't seen them spawn there in quite some time.
