### ISSUE TITLE
🐛[BUG][Quest] Waking Dreams possibly giving multiple rewards

### ISSUE THREAD

**Issue by TiberonKalkaz** [HorizonFFXI/HorizonXI-Issues#1025]
**What does this bug affect?**
The Quest appears to give multiple rewards per completiion

**Steps to Reproduce**
Did waking dreams, flagged and turned in same RL day (prob doesnt matter)
Text said I got the earring (which I chose) and 15k gil.
I dont know for sure if I got 15k gil - I dont know my pre-quest complete gil amount.
I def got the earring as expected.
I'm told if you chose pact, you get the pact and the earring.

**Expected behavior**
1 reward per win

**Screenshots**
![image](https://user-images.githubusercontent.com/105882290/216893438-ac481628-637f-4b2b-94fc-dbf446931ff8.png)

**Setup Information**
N/A
**Additional context**
N/A

**Comment by TracentEden** [comment]
Yep will be fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2711

**Comment by TiberonKalkaz** [comment]
Ha, I titled it as "possibly" because for the life of me I couldn't figure
it out looking at the source.

Turns out I was looking at the already fixed code in as 🤣
