### ISSUE TITLE
🐛[BUG][Quest "Inside the Belly" rewarding Stolid Breastplate which should be OoE]

### ISSUE THREAD

**Issue by synari-whitemane** [HorizonFFXI/HorizonXI-Issues#1026]
**Quest "Inside the Belly" rewarding an item that is OoE** 
Item in question is Stolid Breastplate, which is sellable via AH. BG-wiki lists the item as being added in the March 23, 2010 patch.

The item being in doesn't really affect a whole lot, it is a good item for it's level (45). I just reached out for clarification about its OoE status prior to spending gil to buy one and was directed to make a post about it here. I suppose it could affect fishing more, if the fish became worthless without the item being available.

**Steps to Reproduce**
Item can be obtained by turning in Armored Pisces for the quest, but it is listed as a "VR" drop so number required to obtain one could be high.

**Additional context**
I am unfamiliar with the quest "Inside the Belly" from retail, so I'm not really sure when it was added itself. The whole thing could be OoE which would make this post kind of silly. I saw Stolid Breastplate on a gear list and started looking into how to obtain it, which led to the bg-wiki page for the quest. I noticed that the item was from the March 23, 2010 patch and decided to ask about it prior to trying to buy the one in AH or turn in fish to get one to drop.

**Comment by hookstar** [comment]
Thanks, it was patched the other day but didn't make it in, it seems. 

Thanks for reporting.
