### ISSUE TITLE
🐛[BUG] KSNM - Eye of the Storm

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#103]
**What does this bug affect?**
Able to land lullaby somewhat reliably as a naked 75 brd, and able to land sleep magic without elemental seal. Hate doesn't seem to be linked together, though I could only test this as smn with summoned pet. Used Fenrir in godmode and did a high damage Eclipse Bite after pulling initial aggro and had the three that fenrir wasn't attacking on me with no change.

**Steps to Reproduce**
Go into the fight and try to land lullaby / sleep magic (without elemental seal) to see if it lands.

**Expected behavior**
No capture or youtube available so unable to verify the below. 
https://ffxiclopedia.fandom.com/wiki/Eye_of_the_Storm/Strategies 
Wiki suggests:
Practically immune to Lullaby (full merits and Soul Voice had 10% success).
Elemental Seal plus Sleepga II will stick. However, Sleep without Elemental Seal will not stick.
Hate seems to be linked together, making kiting difficult. (Not sure if this is valid)

**Setup Information**
Version 30220802_3

**Additional context**
All NMs use their correct breath move. Not sure if the linked hate part is valid or not.

**Comment by dallano** [comment]
Bug fixed in PR: https://github.com/AirSkyBoat/AirSkyBoat
Will confirm sharing of hate. From captures I saw, I didn't see this behavior.
