### ISSUE TITLE
🐛[BUG][Combat] Divine Might is undertuned. NM's are probably just set to the wrong level. 

### ISSUE THREAD

**Issue by Singers30** [HorizonFFXI/HorizonXI-Issues#1030]
**What does this bug affect?**
The experience of completing an epic fight was ruined by the undertuning of the NM's in Divine Might.

**Steps to Reproduce**
Do Divine Might. Be bored at the ease. 

**Expected behavior**
Monsters should have been much harder to kill and more dangerous, AKA set to a higher level.
Should not be hitting these NM's as hard as I was. They must be set to like level 70 or something. 

**Screenshots**
[](https://imgur.com/a/xAijVaA)

**Setup Information**
Windows. Regular Horizon client. 

**Additional context**
There's no shot that this fight was this easy back in the day. We smoked it way too quickly and the SAM 2 hour didn't even kill me. Too weak.

**Comment by dallano** [comment]
Sorry! We try to reserve bug reports for bugged content, rather than balancing. Not denying your claims to be false or anything, but conversations for balance are welcome and encouraged in our public group chat. Thank you for your time and concern!
