### ISSUE TITLE
🐛[BUG] Hakutaku Eye Cluster not crit breaking on fail.

### ISSUE THREAD

**Issue by Slynkee** [HorizonFFXI/HorizonXI-Issues#1031]
**What does this bug affect?**
Hakutaku Eye Cluster should crit break on synth failure.

**Steps to Reproduce**
Fail a Hakutaku Eye Cluster synth.

**Expected behavior**
All materials should be lost when you fail the synth.

**Comment by TracentEden** [comment]
Will be fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2638
