### ISSUE TITLE
Sex/race/hair change addon bugs

### ISSUE THREAD

**Issue by macroboy12** [HorizonFFXI/HorizonXI-Issues#1032]
sexchange/race/hairchange causes some noticeable bugs

1) when you unequip a piece of gear, you wont be able to equip it back. as if youre too low to wear it when youre not. logging out only seems to fix this.
2) any JA and WS animations will not occur anymore, only the damage will show.

**Comment by CriticalXI** [comment]
This bug needs to be raised with the addon developer.
