### ISSUE TITLE
Norg Fame -  (Beauty and the Galka) & Zinc Quest (Shady Business)

### ISSUE THREAD

**Issue by Riftsan** [HorizonFFXI/HorizonXI-Issues#1041]
When starting the quest the NPC asks to trade one zinc to start (Beauty and the Galka) quest. Once completed it will then ask you to trade 4 zinc's at a time activating the Zinc Quest (Shady Business) quest. The problem is that it continues to accept to trade 1 zinc at a time while in beauty and the galka quest. I mistakenly traded all zincs one at a time and it did not provide any norg fame whatsoever. 

I don't believe it should allow you to continue to accept one zinc.
This will prevent players from loosing on 35k that costs 8 stacks 😢.

Player: Riftsan

**Comment by hookstar** [comment]
Did you get a ton of bronze knifes?

**Comment by Riftsan** [comment]
I did not because to get the knife you have to talk to another NPC and then come back to get the knife. When I traded all the zincs was without talking to the other NPC.

**Comment by hookstar** [comment]
Okie, Put in a GM ticket please. I will work on getting this worked out code wise. Thanks!

**Comment by Riftsan** [comment]
Awesome! Thank you. What is the possibility of getting my gil back? 😢

**Comment by hookstar** [comment]
> Awesome! Thank you. What is the possibility of getting my gil back? 😢

That will be up to the GM team, I'm just a lowly dev.

**Comment by hookstar** [comment]
Updated. Thanks for the report.
