### ISSUE TITLE
🐛[BUG][Item] Bhuj is OoE

### ISSUE THREAD

**Issue by TheUndeadFish1** [HorizonFFXI/HorizonXI-Issues#1046]
**What does this bug affect?**
This item should come out with the Treasures of Aht Urhgan expansion

**Steps to Reproduce**
Saw someone running around with it being equipped, checked AH and saw that they are being regularly sold so the crafting recipe is probably enabled by mistake.

**Expected behavior**
Seeing this content released when Aht Urhgan is released.

**Screenshots**
![image](https://user-images.githubusercontent.com/3422025/218211559-7da3c8c1-b540-4f47-8137-8db7d20db161.png)

**Comment by hookstar** [comment]
https://ffxi.allakhazam.com/db/item.html?fitem=3501
