### ISSUE TITLE
🐛[BUG][Combat] Aspidochelone takes full damage from Spirits Within

### ISSUE THREAD

**Issue by lkamieniecki** [HorizonFFXI/HorizonXI-Issues#1047]
**What does this bug affect?**
Aspidochelone takes full damage from Sprits Within, trivializing the encounter by negating the high regen while inside the shell. 
Aspidochelone should be taking reduced damage from Spirits Within while inside the shell

**Steps to Reproduce**
1. Claim/Spawn Aspidochelone. 
2. Gain 3000 TP while using a Sword
3. Fight until Aspid goes inside the shell. 
4. Pop 2-3 Spirits Within
5. Watch Aspid come back outside the shell. 

**Expected behavior**
Aspid should take reduced damage from Spirits Within as with other weaponskills while in the shell

**Screenshots**

**Setup Information**

**Additional context**

**Comment by SpaggiG** [comment]
updating.

Apparently this quest currently skips that part and puts you right at 'completion'. talking to Ondieulix will give you the quest reward

**Comment by TracentEden** [comment]
This should be fixed.
