### ISSUE TITLE
🐛[BUG][Quest] DRG AF quest sequence

### ISSUE THREAD

**Issue by SoftlyStrawberry** [HorizonFFXI/HorizonXI-Issues#1049]
**What does this bug affect?**
Sequence Break. Mixed up the AF questlines for DRG. Went to Port Sandoria thinking my AF weapon started there. Talked to NPC and flagged the level 51+ questline at level 44. Also flagged it *before* I even did my weapon. 

**Steps to Reproduce**
Flag AF at level 44 DRG.

**Expected behavior**
Should not be able to flag AF armor until 51+ and previous quest complete

**Screenshots**

**Setup Information**

**Additional context**

**Comment by hookstar** [comment]
Which quest in particular were you able to flag?

**Comment by SoftlyStrawberry** [comment]
Flagged Chasing Quotas (Drachen Brais) before flagging or even completing A
Craftsmans work (DRG AF weapon) at level 44

**Comment by hookstar** [comment]
Got it. Thanks!
