### ISSUE TITLE
🐛[BUG] KSNM - Today's Horoscope

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#105]
**What does this bug affect?**
Mob's attack speed seems slower than what is seen in the capture.

**Steps to Reproduce**
Go into the fight and let the NM smack away at you and observe attack speed.

**Expected behavior**
Mob should attack very fast, similar to Hundred Fist effect based on capture.

**Setup Information**
Version 30220802_3

**Additional context**
The mob seems to do it's sleep / regen hp mechanic after Petribreath, which I believe is correct.

**Comment by dallano** [comment]
Aye over 1min of footage, I could time 1 attack per 2 seconds. Which should equate to 2 * 60 = 120 delay

**Comment by Squinkerdoodle** [comment]
What was it set to prior, just curious.
