### ISSUE TITLE
🐛[BUG][Quest] OOE items in the quest Inside the Belly

### ISSUE THREAD

**Issue by trodeghero** [HorizonFFXI/HorizonXI-Issues#1052]
Quest Inside the Belly and OOE items
**What does this bug affect?**
Today I got a Stolid Breastplate from turning in an armored pisces for this quest. Was later told it is OOE and a bug report should be made.

**Steps to Reproduce**
Turn in an armored pisces with 'inside the belly' active for a chance at this item.

**Expected behavior**
Unclear, but this particular item is not available in this area unless allowed on Horizon

**Screenshots**
None available, can provide if really needed

**Setup Information**
/ver 30221103_1

**Additional context**
None, just reporting per Aerec's recommendation :)

**Comment by hookstar** [comment]
There is a fix pending for this. Thanks for reporting.
