### ISSUE TITLE
BCNM 60 Legion XI Comitatensis Bug

### ISSUE THREAD

**Issue by TrunksSS** [HorizonFFXI/HorizonXI-Issues#1053]
After you complete the BCNM and open the coffer you appear in the room with the crystals of ZM 6.
You can't complete more than a run without warping and comeback all the way.

**Comment by hookstar** [comment]
oh that doesnt sound like fun at all

**Comment by hookstar** [comment]
There will be a temp fix put in place until we can dissect the root cause. (clicking the door will let you out)
