### ISSUE TITLE
🐛[BUG] KSNM - Royal Ramble

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#106]
**What does this bug affect?**
King of Swords's initial placement incorrect. Able to land sleep magic and lullaby on the NMs, capture showed they are immune to it. NMs casts Dia 3 instead of Dia 2, Banishga 3 instead of Banishga 2, and Diaga 3 instead of Diaga 2. Once this fight is cleared and attempted again, both Queens can be seen dead on the floor in the arena and do not spawn after a King is engaged (Seems similar to what was happening with Let Sleeping Dogs Die BCNM). Mobs HP values may be set a big high, Queen of cups has about 12000, Queen of Batons hass 8900 King NMs have 17500, may want to double check their HP though I can't find a source on how high it should be exaclty.

**Steps to Reproduce**
Go into the fight and observe initial mob placement and what spells they cast.

**Expected behavior**
Capture has all 4 in a straight line facing the arena entrance for initial starting position. Capture shows the mobs casting Dia II, Diaga II, and Baishga II instead of the tier 3 of those spells. Queens do not show up dead in arena when attempting the fight again after clearing it (this is preventing them from spawning after a king is engaged).

**Setup Information**
Version 30220802_3

**Additional context**
I did not witness the rage mechanic in the capture, nor did I see it happen while testing so I can't verify if this should be a thing or not.
Wiki seems incorrect on the part that the NMs have additional effects on melees, I did not see this in the capture nor while testing.
The hate reset mechanic on TP move Deal Out seems to be working correctly. Tested Deal Out as smn with carby and when used the NM would swap from me to carby, did not check the other moves.

**Comment by dallano** [comment]
Ah yes. The HP values I set were taken from a capture that didn't take into account the mobs being healed from things like cures and benediction. Also fixed the queens not spawning. Nice catches as always :)
Mob positioning not being correct is again due to that DAMNED module :'(
