### ISSUE TITLE
🐛[BUG][Combat] Bastok 9-2 is laughably easy and can be done while asleep

### ISSUE THREAD

**Issue by Singers30** [HorizonFFXI/HorizonXI-Issues#1063]
**What does this bug affect?**
This affects a player's ability to have fun with a hype fight. 

**Steps to Reproduce**
Do the fight. Try not to fall asleep. Actually, you won't even have time to.

**Expected behavior**
As the penultimate fight for Bastok missions, this should be challenging for max level players IMO.

**Screenshots**
<Don't have much to add, the fight ended too quickly. 

**Setup Information**
Normal Horizon launcher. 

**Additional context**

**Comment by TracentEden** [comment]
Fixed in https://github.com/AirSkyBoat/AirSkyBoat/pull/3496
