### ISSUE TITLE
🐛[BUG][ENM] Like the Wind - Drop rate?

### ISSUE THREAD

**Issue by ThiefFFXI** [HorizonFFXI/HorizonXI-Issues#1068]
**What does this bug affect?**

Drop rate in ENM "Like the Wind". Got nothing, seems like using past drop tables that this should be a 1% or less chance. Just wanted to confirm we are SUPER unlikely and this isn't bugged.
**Steps to Reproduce**

Complete the ENM and open the chest that appears at the end.
**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/123122366/218647840-0cfb15b1-568c-4f4d-875f-c7ddd3c7a61a.png)

**Setup Information**

Windower
**Additional context**

Chance of these drops seems super unlikely, want to confirm it is not bugged.

**Comment by TracentEden** [comment]
I just did it on test server and got double maneater, so I think it is working. Yeah chance of nothing is about 2% so just unlucky.
