### ISSUE TITLE
🐛[BUG][System]Bomb core not applying the attack stat

### ISSUE THREAD

**Issue by TaodR** [HorizonFFXI/HorizonXI-Issues#1069]
**What does this bug affect?**
This bug affect anybody with a bomb core.

**Steps to Reproduce**
Equip a bomb core, /checkparam <me>, unequip bomb core, /checkparam <me>, the equip menu also shows this

**Expected behavior**
your attack should rise by 12 equipping the bomb core

**Screenshots**

**Setup Information**

**Additional context**

**Comment by TracentEden** [comment]
Will be fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2749
