### ISSUE TITLE
🐛[BUG] - Storms of Fate (Bahamut V1 fight)

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#107]
**What does this bug affect?**
During the battlefiled Bahamut's scripting gets messed up. On the initial fight everything worked fine during the first 10% of his HP. Upon reaching 90% he did megaflare which is correct, however after the first megaflare he then proceeded to spam the move repeatedly (still at 90% hp). I ran away from the fight hoping to reset it, and upon entering the fight again for a second attempt Bahamut does not auto attack or use spells until 90% HP, at which point he proceeds to spam Megaflare again.

The above issue may be affecting the use of Gigaflare as well, I pushed him down to 9% and he still continued to spam Megaflare and did not use Gigaflare.

**Steps to Reproduce**
Go into the fight and see if Bahamut auto attacks or casts spells at the beginning of the fight. Lower his HP to 90% and see if he spams Megaflare.

**Expected behavior**
Bahamut should act like it did on the first attempt where it will auto attack and cast spells as normal. At 90% he should do his first Megaflare and then at each 10% HP lost after that he should use Megaflare once again. At 10% HP left (90% HP lost) he should use Gigaflare instead and then will be able to use Gigaflare at will as a normal TP move while at/under 10% HP.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/190665786-6d1dfe92-f26e-4afa-952b-9911fd9eecc1.png)
![image](https://user-images.githubusercontent.com/112344508/190666297-cc11196a-4cea-4aa0-8605-b63c9b8ffbee.png)

**Setup Information**
Version 30220906_0

**Additional context**
Tested solo with godmode. Everything else outside of the fight worked for this quest.

**Comment by dallano** [comment]
More fixes! https://github.com/AirSkyBoat/AirSkyBoat/pulls
