### ISSUE TITLE
🐛[BUG][Combat] Cure Soft Caps being treated as Hard Caps

### ISSUE THREAD

**Issue by Andrew6ta** [HorizonFFXI/HorizonXI-Issues#1074]
**What does this bug affect?**
The Cure line of spells is hard capped at the upper soft cap value. 

**Steps to Reproduce**
Cast Cure at level 75 with no day/weather synergy and no cure potency. Observe the cure healing for only 30 hp.

**Expected behavior**
After reaching the second soft cap of cure power, the healing should continue to scale upward (albeit much more slowly).

**Screenshots**
N/A

**Setup Information**
N/A

**Additional context**
Here is a link to the documented historical cure value from BG-wiki: https://www.bg-wiki.com/index.php?title=Cure_Formula&oldid=82830

Another user also provided a youtube video showing a whm with no cure potency casting cure 3 for 194 hp against Maat in December of 2006: https://www.youtube.com/watch?v=p-P-VwEihEM

**Comment by Shozokui** [comment]
Replated PR: https://github.com/AirSkyBoat/AirSkyBoat/pull/2777
