### ISSUE TITLE
Wool Gambison/Wool Hat crafts missing

### ISSUE THREAD

**Issue by Cyphane** [HorizonFFXI/HorizonXI-Issues#1077]
Wool Gambison and Wool Hat crafts are not currently implemented in-game and cannot be crafted even with the correct skills.

Items are from 2005 and Wool Gambison is required the 'Brygid the Stylist Returns' quest.

https://ffxiclopedia.fandom.com/wiki/Wool_Gambison
https://ffxiclopedia.fandom.com/wiki/Wool_Hat

**Comment by TracentEden** [comment]
Wool Gambison will be fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2739

**Comment by hookstar** [comment]
and wool hat is in https://github.com/AirSkyBoat/AirSkyBoat/pull/2775
