### ISSUE TITLE
🐛[BUG] Ouryu Cometh

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#108]
**What does this bug affect?**
Ouryu missing TP move Geotic Breath.

**Steps to Reproduce**
Go into fight and monitor TP moves Ouryu uses while on the ground.

**Expected behavior**
Ouryu should use Geotic Breath while on the ground in addition to Horrid Roar & Absolute Terror.

**Setup Information**
Version 30220906_0

**Comment by dallano** [comment]
Fixed!
