### ISSUE TITLE
🐛[BUG][NPC] Vouivre has wrong hp

### ISSUE THREAD

**Issue by TristtHXI** [HorizonFFXI/HorizonXI-Issues#1080]
**What does this bug affect?**
Currently vouivre has like 4k hp, which is way too low. Seems to be an issue with a few nms, I know Novv the Whitehearted and Taxim had wrong hp values also, unsure if they have been fixed yet. In some cases the nms have less hp then their placeholders...

**Comment by hookstar** [comment]
I have asked for some captures of these mobs. Will update when we get correct values. Thank you.

**Comment by siknoz** [comment]
Vouivre seems to be about 30k'ish. Retail Capture: https://youtu.be/naSerAW98U0

Regen is 1% per 18s.

Remember that at the end it reports 32.8-33.1k but it regen a bit over the 2 1/2 minute fight. That's why I estimate about 30k, but feel free to double check the math. 

Will try to get Taxim and Novv tomorrow.

**Comment by hookstar** [comment]
@siknoz Thank you, friend!

**Comment by siknoz** [comment]
Novv the Whitehearted has about 3700hp, it has a potent innate regen (it never casted Regen) which came out to 1% per 4s which means it's about 37-40/tick. 

Source: https://youtu.be/_GG486pu04I

Feel free to double check math, I based it on bendiction being used at 33% healing for 2447 which means 66% = 2447 which puts 100% around ~3700. Spirit taker did 53% at 1925 which also lines up.

**Comment by siknoz** [comment]
Since you're bumping these hp's, can you also do Friar Rush? 

Retail Capture: https://youtu.be/T8TU4mxB97Y

HP - ~8650

**Comment by hookstar** [comment]
Sure can - once this or goes through I'll switch branches and plug novv and that one in. Thanks for doing the heavy lifting!
