### ISSUE TITLE
🐛[BUG][System/Combat] Others Merit section incorrectly capped at 4 total instead of 8.

### ISSUE THREAD

**Issue by SnarfyBobo** [HorizonFFXI/HorizonXI-Issues#1083]
**What does this bug affect?**

Anyone trying to max more than one category of the Others merit section.
**Steps to Reproduce**

Upgrade any combination of merits in Other 4 times. When you try merit anything else, nothing is blued out, and it still says 4/8 in the bottom left corner, but you won't actually be able to spend merits anymore.
**Expected behavior**

Should be able to spend merits to get 8 total from this category.
**Screenshots**

https://discord.com/channels/933423693848260678/1075241464226918440
**Setup Information**

**Additional context**

**Comment by KiplingFFXI** [comment]
Looks like in era the cap for each item was 4, and the category was 8 - https://ffxiclopedia.fandom.com/wiki/Category:Merit_Points?oldid=731908

**Comment by SnarfyBobo** [comment]
Yea, that's not what's happening right now. Currently each item is capped at 4, and the category is also capped at 4.

**Comment by KiplingFFXI** [comment]
Yep, just adding evidence to your bug report.

**Comment by SnarfyBobo** [comment]
Perfect, thanks! Rereading my bug report made me realize how confusing I made it sound, and the way you summed it up was much clearer.

**Comment by Butsuon** [comment]
This bug is still present on March 31st, over a month later.

**Comment by samson-ffxi** [comment]
Seeing this as well still.

**Comment by TracentEden** [comment]
This has been fixed.
