### ISSUE TITLE
🐛[BUG][Crafting] Minnow Recipe is wrong. GSM is set to 10 instead of 2 when using Copper Ingot.

### ISSUE THREAD

**Issue by ffxiWaxer** [HorizonFFXI/HorizonXI-Issues#1085]
**What does this bug affect?**
Alchemy/GSM
**Steps to Reproduce**
I'm 

29alch
0gsm

break rate 100% so far.

**Expected behavior**
Should be gsm 2 with copper ingot. gsm10 with brass ingot
**Screenshots**
![image](https://user-images.githubusercontent.com/94857791/219815444-96602ead-17e7-4334-b6dc-e20886760c07.png)
![image](https://user-images.githubusercontent.com/94857791/219815697-9d432570-ff0b-4bb8-9727-3901f3b8e0b8.png)
![image](https://user-images.githubusercontent.com/94857791/219815768-8907e3b9-c343-4583-b48e-fb964e61bef2.png)

(61501,0,0,0,0,**11**,0,0,0,31,0,4096,4238,648,933,0,0,0,0,0,0,17407,17400,17400,17400,1,1,1,1,'Minnow');

**Setup Information**

**Additional context**

**Comment by hookstar** [comment]
https://ffxiclopedia.fandom.com/wiki/Minnow?direction=prev&oldid=842355

should be era appropriate at this time.
