### ISSUE TITLE
🐛[BUG]Requiem of Sin mobs could not be attacked or cast on.

### ISSUE THREAD

**Issue by KushertonCapn** [HorizonFFXI/HorizonXI-Issues#1094]
In the Requiem of Sin battlefield, the Shikaree's were not able to be attacked or agrod at all except Shikaree Z. Shikaree Z seemed to work properly using weaponskills and summoning its wyvern.

They Shikaree mobs should agro or be able to be pulled before agro. A GM came into the battlefield and tried moving the mobs but we still couldn't interact with them.
![Capnk_2023 02 19_195005](https://user-images.githubusercontent.com/125845530/220001052-5303877a-89c8-4bb3-8fba-b6c56f695839.png)

On HorizonXI February 17th, 2023 patch

**Comment by rafiina** [comment]
Just dropping in to say we encountered the same issue.  Exact same details.

**Comment by tumps7** [comment]
Still a problem, will this be fixed in 1.1?
