### ISSUE TITLE
🐛[BUG][Quest/NPC]Twinstone Bonding Quest not accepting Twinstone Earrings.

### ISSUE THREAD

**Issue by ArchiveXI** [HorizonFFXI/HorizonXI-Issues#1098]
Twinstone Bonding Quest not accepting Twinstone Earrings.

After receiving enough fame, I flagged the Twinstone bonding quest with Gioh Ajihri, but she will not accept any earrings.
After help with GM support from Revel, even after resetting the quest twice, it continues to act the same way.

All the twinstone earrings i have are from killing the server+ mobs (Dust Lizards) in meriphataud mountains. Not sure if that relates to anything.

**Comment by gtarrantiii** [comment]
Was only able to reproduce once using the latest staging build of ASB. 
I set the flag with a gm command  (!addquest 2 62).

Then tried to trade to her, she ignored me, no response at all. 
So I setup some logging of that script:
![image](https://user-images.githubusercontent.com/16801070/220225386-3ac15d00-d0d1-4711-ab7e-0a9940e67da2.png)
(Trade 1) Tried to trade anything to test what the event firing had present. (last variable False)
(Trade 2) Tried to trade the earring to confirm that was being recognized. (last variable True)
I then talked to her first, where she asked for the earring and I then added item to inventory with GM command (!additem 133360).
(Trade 3) Traded after that, she accepted it and gave me the bow. 
![image](https://user-images.githubusercontent.com/16801070/220224257-4840114c-53e0-40eb-a33a-051698d5b8ff.png)

(Trade 4) Traded a random item to check the variables, variable 2 showed True (I needed to zone).
Next I talked to her again she talked about the earring so I needed to zone. 
![image](https://user-images.githubusercontent.com/16801070/220224461-969f2523-6b6a-45f7-a912-253b11a4102d.png)

After zoning I talked to her again she then asked me to go find her one again. 
(Trade 5) bogus item to see that the quest was flagged properly.
![image](https://user-images.githubusercontent.com/16801070/220225947-a660fb37-e04a-4bec-9e25-26f9965496ac.png)
(Trade 6) traded earring without zoning and got 900g.
Talked to her again, same info dialog about the earrings, had to zone again. She once again restarted the quest. 
![image](https://user-images.githubusercontent.com/16801070/220224617-d72491c9-d8ef-48f4-9a4d-9d69c9c7d190.png)

It is of note that the quest was recently refactored mid January from a quest on the npc file to the new quest framework where it uses the char_vars for tracking the quest progress. (variable 1 in my logging 'Prog') 


If it was initially flagged prior to that update having been merged, it is likely that the player will have their log in an invalid state. 
Each time it completes the event it removes the flag and requires a rezone before you can flag it again.

GM commands to flag the quest for the player will not add the additional data to char_vars, a limitation of the dsp gm tools when migrating quests that should probably have its own ticket.

**Comment by hookstar** [comment]
I would imagine that the last portion is the cause there. Thanks.

**Comment by hookstar** [comment]
@ArchiveXI can you send me a message in discord with your in game name?

Thanks -

**Comment by ArchiveXI** [comment]
Heya. My name on the game is Archive. Apologies for the delay
