### ISSUE TITLE
🐛[BUG][System/Combat] General Dynamis Feedback - Zone Crashes

### ISSUE THREAD

**Issue by KiplingFFXI** [HorizonFFXI/HorizonXI-Issues#11]
**What does this bug affect?**

These issues seem to affect all Dynamis zones. Issues include:

(1) Mobs using 2 hours seemed to crash the zone. 
(2) Pet mobs dying while their pet was still alive seemed to crash the zone.
(3) Stats had wrong magic resist but I believe that was fixed after our first run.

**Steps to Reproduce**

Do dynamis and fight pet master mobs.

**Expected behavior**

The zone should not be crashing when mobs use two hours or die while their pets are still up.

**Screenshots**

N/A - we crashed when it happened.

**Setup Information**

N/A - older report

**Additional context**

N/A

**Comment by OpheliaXI** [comment]
All of these were fixed as of last patch.
