### ISSUE TITLE
🐛[BUG] Waking the Beast

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#110]
**What does this bug affect?**
Getting message "You cannot enter the battlefield at present. Please wait a little longer" when trying to enter the battlefield "Waking the Beast" at the elemental protocrystals in the avatar's cloisters. Only Titan worked and I was able to fight it. Additionally getting the same unable to enter message at Full Moon Fountain while in posession of the 6 "Eye of ...." key items. During the Titan fight, Titan used Ifrit's AF Inferno instead of his own, and the elementals did not cast any spells on him to heal him with. Additionally the Earth Elementals during the Titan fight use Slow 2 instead of normal Slow 1.

**Steps to Reproduce**
Try to enter Waking the Beast at the protocrystal in each avatar's cloister.

**Expected behavior**
Entry should be allowed. Titan should use the proper AF Earthen Fury. Elementals should cast their spells on the prime avatar which should heal the avatar. Earth elementals should use Slow 1 instead of Slow 2.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/190688837-dc324c91-0ae7-4848-875c-7493a30c5654.png)

**Setup Information**
Version 30220906_0

**Additional context**
I was able to get the eye of tremors key item from the titan fight. I gave myself the other 5 "Eye of ..." key items and tried to enter the fight at the Full Moon Fountain and received the same "You cannot enter the battlefield at present. Please wait a little longer" message.

**Comment by dallano** [comment]
So the elementals not casting on the primes is a known issue. As of now there's no lua command I can use to make this happen. We'll have to write more core for this to work. Which I plan on doing together with someone more experienced than me lol. I'll make sure to fix titan's skill list and perhaps review the other avatars.
And again... waiting for the module to hit horizon for those "unable to enter" issues with all the battlefields. Should be soon! Oph, Crit, and Frank worked on it last night. For these you can always !togglegm and enter the fight to test the mechanics.

**Comment by Squinkerdoodle** [comment]
It gives the message with the !togglegm command enabled as well.

**Comment by dallano** [comment]
Bugs fixed! :)
