### ISSUE TITLE
🐛[BUG][System/Combat] The Last Shadow of Utsusemi Causes Status Effects from TP Moves to go Through

### ISSUE THREAD

**Issue by KiplingFFXI** [HorizonFFXI/HorizonXI-Issues#1100]
**What does this bug affect?**

When you cast utsusemi and a monster uses a TP move that has a status effect tied to it (like petrify on medusa javelin), you will take 0 damage + lose the shadow + still get the status effect. So for example, if I have one shadow left and an aern uses medusa javelin, I will lose the shadow, take 0 dmg, and end up still petrified.

**Steps to Reproduce**

1. Cast Utsusemi
2. Have 1 shadow remaining
3. Mob uses TP move
4. If the TP move has a status effect, you still get the effect even if it eats your last shadow

**Expected behavior**

You should not be eating status effects when you have an utsusemi shadow to absorb a TP move.

**Screenshots**

N/A - didn't take any but seen it happen in multiple instances.

**Setup Information**

N/A

**Additional context**

Bug finder thread with more context and pictures - https://discord.com/channels/933423693848260678/1063619508859830372/1063619508859830372

**Comment by TiberonKalkaz** [comment]
I dont have rights to assign to me, but im taking this one - PR up in a min
