### ISSUE TITLE
🐛[BUG][System] Hoo Mjuu the Torrent, PH respawn time is wrong

### ISSUE THREAD

**Issue by mwillman1996** [HorizonFFXI/HorizonXI-Issues#1101]
**What does this bug affect?**
The respawn timer for Hoo Mjuu the torrent's Place holder is 16 minutes

PH respawn is 16 minutes instead of era accurate 8min
**Steps to Reproduce**

**Expected behavior**

ph respawns on 8 minute timer
**Screenshots**

https://ffxi.allakhazam.com/db/bestiary.html?fmob=117
![Capture](https://user-images.githubusercontent.com/29699431/220213146-9f8efe08-4af2-4bf5-b598-561af5802d7e.PNG)
**Setup Information**

**Additional context**

**Comment by TheUndeadFish1** [comment]
Horizon is on patch April 17, 2006, and you post was from over a year and a half after.

**Comment by HorizonPotato** [comment]
Theres a post on Page 10 listing it as 10 Minute PH timer dated 2005.  Still far below 16minutes.

**Comment by TracentEden** [comment]
This should now be fixed.
