### ISSUE TITLE
🐛[BUG][Combat] Tachi: Kasha never paralyzes

### ISSUE THREAD

**Issue by masamuneCS** [HorizonFFXI/HorizonXI-Issues#1104]
**What does this bug affect?**

- Mobs never get paralyzed by Tachi: Kasha, from Too Weak - Incredibly Tough

- Removes a critical debuff from low-man/solo SAM play

**Steps to Reproduce**

- Kasha all the things
- Never see a paralyze proc in chat log

**Expected behavior**

- Kasha should be paralyzing mobs at a fairly high rate (see Gekko or Yukikaze rates)

**Screenshots**

**Setup Information**

- 30221103_1

**Additional context**

**Comment by gtarrantiii** [comment]
Please confirm which enemies you are fighting and at what level (char stats, skill, etc.).

**Comment by TracentEden** [comment]
Fixed by https://github.com/HorizonFFXI/HorizonXI/pull/1531
