### ISSUE TITLE
🐛[BUG][System/Combat] Proto-Omega (Central Apollyon) Has Incorrect Damage Resistances

### ISSUE THREAD

**Issue by KiplingFFXI** [HorizonFFXI/HorizonXI-Issues#1113]
**What does this bug affect?**

Proto-Omega's damage resistance is tuned too high. He often takes 0 damage from melee attacks, even though he is supposed to be heavily resistant, but not fully immune. He also seems to take largely reduced magic damage along the same vein.

**Steps to Reproduce**

1. Obtain 4 chips from Apollyon
2. Enter Central Temenos
3. Fight Omega
4. Do 0 damage at times

**Expected behavior**

Even in super melee/magic resistant forms, omega should still take some damage.

Era evidence - https://www.youtube.com/watch?v=UF9siH8SlbE ; 

**Screenshots**

![Kipling_2023 02 18_200002](https://user-images.githubusercontent.com/111715243/220717229-5ad63028-27c2-4b43-8c2f-a67b2c95b496.png)

**Setup Information**

ver: 30221103_1

**Additional context**

N/A

**Comment by jmcmorris** [comment]
This is almost certainly fixed by @Frankie-hz with a recent fix to UDMG modifiers being doubled.
