### ISSUE TITLE
🐛[BUG][Crafting] Carapace Subligar GP turn in has the Horn +1 ID 17371 instead of 12837

### ISSUE THREAD

**Issue by ffxiWaxer** [HorizonFFXI/HorizonXI-Issues#1115]
**What does this bug affect?**
Carapace Subligar item is not working for GP turn in. Only HQ
**Steps to Reproduce**
Try to turn it in
**Expected behavior**
Should give 1540 gp
**Screenshots**

**Setup Information**
1103_1
**Additional context**
```
-- Bonecraft / Apprentice
INSERT INTO `guild_item_points` VALUES (6, 17352, 4, 780, 12960, 0); -- Horn (780 / 12960)
INSERT INTO `guild_item_points` VALUES (6, **17371**, 4, 840, 12960, 0); -- Horn +1 (840 / 12960)
INSERT INTO `guild_item_points` VALUES (6, **17371**, 4, 1540, 15840, 1); -- Carapace Subligar (1540 / 15840)
INSERT INTO `guild_item_points` VALUES (6, 12914, 4, 1610, 15840, 1); -- Carapace Subligar +1 (1610 / 15840)
```

![image](https://user-images.githubusercontent.com/94857791/220753846-8794d78a-4bab-4b48-b3e0-e4de69ea046b.png)

**Comment by hookstar** [comment]
Thanks! Pushed.
