### ISSUE TITLE
🐛[BUG] Requiem of Sin (fight)

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#112]
**What does this bug affect?**
Same issues present as reported for Tango With a Tracker - https://github.com/HorizonFFXI/HorizonXI-Issues/issues/111
NMs do not move / attack. Able to sleep all easily / repeatedly as naked 75 rdm without elemental seal.

**Steps to Reproduce**
Go into the fight and engage the NMs to see if they do anything. Try to sleep the NMs without elemental seal to see if it lands repeatedly.

**Expected behavior**
NMs should attack / move once aggroed or engaged. Not sure if the mithras should be immune to sleep or not, but the rabbit and wyvern should be in addition to being able to be effected by gravity.

**Setup Information**
Version 30220906_0

**Additional context**
Felt even worse this time, it felt like they knew what was about to happen as they stared and watched me down them one by one. Though the treasure chest spawned correctly after finishing them all off so the loot made it better.

**Comment by dallano** [comment]
And I suspect the NMs not having any behaviour a Horizon issue, because I've tested this fight 20+ times as I was implementing it and it worked beautifully. I'll look into that!
