### ISSUE TITLE
Mog expansion quests. 

### ISSUE THREAD

**Issue by Shodannoka** [HorizonFFXI/HorizonXI-Issues#1122]
Since I was having issue getting the first mog quest completed based on info I found from retail(thanks for clarifying how it works on horizon btw).. Can I get confirmation that the other two mog expansion quest are available and working after the "give moogle a break" quest?... also do they all trigger after the conquest update just like the first one?

**Comment by bliven-was-taken** [comment]
Yes I have done all 3, and all 3 required conquest tally after putting in the bed, and then jp midnight after trading the items.
