### ISSUE TITLE
🐛[BUG][Launcher] Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by RavynArcher** [HorizonFFXI/HorizonXI-Issues#1127]
**What does this bug affect?**

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by RavynArcher** [comment]
![Horizon Report](https://user-images.githubusercontent.com/46797362/221285685-21d610c2-6917-443a-9c7c-497a78ec9be5.png)
happens while trying to install

**Comment by Flam9** [comment]
Going to need more information like:
- Operating system
- Does this prevent the install from completing successfully?
- When exactly does it happen?
- Have you tried searching the discord for similar issues?

**Comment by RavynArcher** [comment]
I don't remember reporting an issue as it's been a pretty hectic week and I
haven't actually had time to play since last week. Remind me again what I
reported if you're able and don't mind. :)

**Comment by Flam9** [comment]
Check this link https://github.com/HorizonFFXI/HorizonXI-Issues/issues/1127
:D

**Comment by RavynArcher** [comment]
Ohhh right right. You can go ahead and close this ticket. The game has been
opening just fine lately lol Thank you!
