### ISSUE TITLE
🐛[BUG][Quest] Hitting the Marquisate

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#113]
**What does this bug affect?**
Note: I was the one that tested this quest originally and still had it in my log. I used the !delquest command to drop the quest and deleted any related key items to try to start it over. If there's a different, better way to reset progress let me know and I'll give it another try. ***If these's no other way then someone else may need to check this quest and this bug report can be closed.***

After deleting the quest and any related key items I was able to get the quest again from Nanaa Mihgo and received the key item Cat Burglar's Note. That is where my progress stopped because Hagain in Mhaura did not give the cutscene / blomb incense key item, and Yatniel in Lower Jeuno still gave the dialogue asking for quake grenades, though the item is missing from his dialogue.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/190835422-67144bc8-8958-4911-a3a8-cfbbd2a1fb45.png)

**Setup Information**
Version 30220906_0

**Comment by dallano** [comment]
So quests have variables used to track progress. It's possible that these vars weren't reset?

**Comment by Squinkerdoodle** [comment]
I did try setting the quest var to 0 and 1 (wasn't sure which was proper) and it's the same result

**Comment by dallano** [comment]
Try using the three commands
!exec player:getCharVar("Quest[2][71]yatnielProg", 0)
!exec player:getCharVar("Quest[2][71]hagainProg", 0)
!exec player:getCharVar("Quest[2][71]nanaaProg", 0)

Also what cause you to start over? Was the quest working fine until then? If this bug only occurs under the circumstance that you deleted the quest artificially, I wouldn't consider it a bug.

**Comment by Squinkerdoodle** [comment]
No the quest didn't work on the initial test either.

**Comment by dallano** [comment]
Think I found a fix. Put it in this PR: https://github.com/AirSkyBoat/AirSkyBoat/pull/401
