### ISSUE TITLE
🐛[BUG]Senjuinrikio/WeaponskillUnlock/Latentaffect/

### ISSUE THREAD

**Issue by lost-rabbit** [HorizonFFXI/HorizonXI-Issues#1130]
**What does this bug affect?**
Cant unlock the bonus damage and crit rate

**Steps to Reproduce**

GM VERIFIED I HAVE THE 500 WS POINTS 
**Expected behavior**

**Screenshots**

![Screenshot 2023-02-24 202647](https://user-images.githubusercontent.com/74441808/221333834-804a884a-c087-469f-8dd8-3cbbb5587dd9.png)

**Comment by TracentEden** [comment]
Confirmed to be working, was misunderstanding.
