### ISSUE TITLE
🐛[BUG][Combat] Fire in the Sky ENM not correct

### ISSUE THREAD

**Issue by siknoz** [HorizonFFXI/HorizonXI-Issues#1131]
**What does this bug affect?**
There are a few issues with the mob:

1. Does not take additional magic damage - Source: https://ffxiclopedia.fandom.com/wiki/Fire_in_the_Sky "He is extremely weak to magic damage of all types." -> https://www.youtube.com/watch?v=w848yLhC3kI you can see here he takes 290 from water2, you can youtube search for others, seems to do 280-310 depending on INT. The video I linked shows an equipment screen with the +int  so you know what to work with. I'm guessing it's supposed to do 2x-2.5x dmg cause our RDM didn't land one more than 112. 
2. Takes 0 dmg from physical - He has very high pdt/def but I couldn't hit for more than 0 dmg. Source: https://www.youtube.com/watch?v=nHn5lKaMUKM Ifrits in this video hit for 3-8 dmg, there's another video of a rdm htiting for 3-6 a hit. So I think this is overtuned.
3. Self destruct does not trigger at certain %'s - In fact in our run he never used self-destruct at all. If you check ANY fire in the sky video you'll see it is triggered certainly at HP thresholds. Though because they use chainspell and nukes that take large chunks I don't know exact %'s and might need retail testing. It seems to be about 70% and 30% or maybe 66/33, but need confirmation. The final self-destruct I'm not sure what the trigger is. The dmg of the self-destructs are based on hp thresholds as well, same wiki source - "IE, if he has full life when he explodes the first time, he will deal upwards of 600 damage; if he has under 66% life, he will deal 0. " 
4. Razon is too resisty, possibly his INT is too high? Our RDM was resisted about 90% of his nukes almost fully, stone2 doing 12dmg on most. He had ONE hit for 112. However, looking at this video https://www.youtube.com/watch?v=Jp1CTF4r6pk you can see the RDM skill up to elemental 110 which means hes ~30 skill UNDER cap and he only gets resisted a few times. Leads me to believe that this mob is supposed to be a nukers dream, possibly has lower resists than normal. This would compensate for the -98% pdt or w/e it  is supposed to have.

Those are the 4 main issues, there's another potential issue I see in the code that I did not test in this run but if someone is fixing this should check these as well just in case...

Wiki says "Blood Pact magical damage will never cause him to instantly self-destruct." but looking at the ASB coding I don't know if BP's will trigger it or not.

**Steps to Reproduce**
Enter Fire in the Sky in Monarch Linn, need Monarch Beard Keyitem, test using what I listed above.

**Expected behavior**
1. Should take Somewhere between 2-2.5x dmg from magic, can verify from the videos I provided. There's 5+ others, just search ffxi fire in the sky on youtube for more.
2. Physical should do somewhere between 1-10 a hit probably? Again check the videos above, Ifrit hit for 3-8, RDM hit for 3-6. Definitely not 0.
3. Self Destruct should trigger at HP thresholds or if element is used.
4. Shouldn't resist nukes very much even if underskilled.

**Screenshots**
![image](https://user-images.githubusercontent.com/78240569/221347862-140b2215-e793-4318-ae58-751cc030f417.png)

**Comment by dallano** [comment]
Upon reexamination of this ENM, I was able to determine the following:
- Razon didn't have stoneskin upon start like previously assumed.
- Magic evasion and magic dmg taken was definitely reduced.
- However there was no sure evidence that Razon was self destructing as a normal cluster mob would. If that were the case, then players have a chance to lose the battlefield at any given moment below 33% HP. It was only determined to be brought on be attacking razon with the incorrect element.
- Removing the stoneskin effect will stop players from always hitting 0, and should increase the base dmg phys values
- Razon currently has an maintains a -75% phys and ranged dmg taken, but reduced it to be -50%.
