### ISSUE TITLE
🐛[BUG][Combat] Multi-hit Weapon Skills not hitting enough times while dual wielding

### ISSUE THREAD

**Issue by avogadro-war** [HorizonFFXI/HorizonXI-Issues#1135]
**What does this bug affect?**

Any multi-hit weapon skill while dual wielding. Rampage, Jin, Chi, Dancing Edge, Vorpal Blade, Swift Blade, etc.

**Steps to Reproduce**

Use a multi-hit WS while dual wielding.

**Expected behavior**

Blade: Jin should hit with MH + OH, then another hit, then another hit. Ergo, TP return should be MH + OH TP with 20 additional TP for the additional two hits. Instead, TP is awarded as if hits are: MH + OH + hit, meaning a second 10 TP hit is lost. It's as if the weapon skills are being expected to hit x number of times and are stopping as soon as that number of hits is reached instead of processing the dual wield hits correctly.

**Comment by avogadro-war** [comment]
![image](https://user-images.githubusercontent.com/109310871/221486831-314ab6ac-f991-46c4-8de1-5a83c1f0c935.png)
![image](https://user-images.githubusercontent.com/109310871/221486845-947d693e-ac04-430f-8871-cb3b4c1f4c18.png)
![image](https://user-images.githubusercontent.com/109310871/221486857-3ee5804b-add1-4fef-87af-74d990ddbed2.png)

**Comment by CriticalXI** [comment]
Fixed in a recent patch, feel free to re-open if still experiencing.
