### ISSUE TITLE
🐛[BUG]Dynamis Out of Era Loot

### ISSUE THREAD

**Issue by Singers30** [HorizonFFXI/HorizonXI-Issues#1137]
**What does this bug affect?**
Wrong era loot

**Steps to Reproduce**
Run Dynamis San'Doria

**Expected behavior**
Shouldn't be here.

**Screenshots**
https://imgur.com/a/l6UGHDE

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment]
Fixed in AirSkyBoat/AirSkyBoat#2824
