### ISSUE TITLE
🐛[BUG]Dynamis HP/MP Back Statues Killing Blow Ally Only

### ISSUE THREAD

**Issue by Singers30** [HorizonFFXI/HorizonXI-Issues#1138]
**What does this bug affect?**
Dynamis statues that give back MP/HP are not giving back zonewide. Only to ally with killing blow. 

**Steps to Reproduce**
Kill a +HP/MP statue with multiple allies in Dynamis. 

**Expected behavior**
Not sure if expected, but all members in zone should be refreshed. 

**Screenshots**
Hard to screenshot this but people were confirming.

**Comment by TracentEden** [comment]
From my understanding in era the statues only refilled players within a certain radius of the statue (see [here](https://ffxiclopedia.fandom.com/wiki/Category:Simulacra?oldid=957936)).
