### ISSUE TITLE
🐛[BUG][Combat] -BCNM 60 Celery - Mob Curses but when cursna'd Gravity effect remains

### ISSUE THREAD

**Issue by Skeletor4424** [HorizonFFXI/HorizonXI-Issues#1143]
**What does this bug affect?**

The bug affects the BCNM 60 - Celery. The mob uses an ability to curse the players. When the curse it removed, the gravity effect persists. I am currently out of the BCNM and still under the effects. This prevents us from running away during large casts. Which resulted in our death during 2 attempts.
**Steps to Reproduce**

Get him to curse you, remove curse. Stay gravity'd
**Expected behavior**

The curse and all effects should be removed. The gravity shouldn't persist.
**Screenshots**

I can add a SS, but it won't show me moving slowly. If a GM would come to my location. I am still under the effect.
**Setup Information**

**Additional context**

**Comment by TracentEden** [comment]
Will be fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2787
