### ISSUE TITLE
🐛[BUG][Quest] Out of the Depths - Cannot advance part way through.

### ISSUE THREAD

**Issue by Dhalmeltoe** [HorizonFFXI/HorizonXI-Issues#1144]
**What does this bug affect?**

Completeing the quest, and therefore quest line
**Steps to Reproduce**

I did the hoary bomb ash trade in, 1,2,3,4 got the 4 KI, went to Bastok, turned it all in, went back, turned in 1, selected the "no Thanks" as instructed, got a KI, went back to bastok, which is when I noticed it gave me the wrong KI. I then ran all the way back there trying to get the KI and I can't get any of them, I have tried trading 1,2,3,4 again as I have 14 on me. and will not take any. For starters this is supposed to be repeatable until you get the final KI which i am assuming the game thinks I did because i selected the "No Thanks" option, it gave me a dusty tome which is the "1" trade option from the start instead of an Old Nametag. NPC has no dialogue either at this point.
**Expected behavior**

It proceeded properly up to the return to Brakobrik where you trade 1 more Hoary Bomb Ash, select No Thanks from the dialogue and I should've recieved a KI "Old Nametag" to continue the quest
**Screenshots**

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment]
Duplcate of #916
