### ISSUE TITLE
🐛[BUG] Carmine Dobsonfly drop rate audit

### ISSUE THREAD

**Issue by ThoseWhoFight** [HorizonFFXI/HorizonXI-Issues#1148]
**What does this bug affect?**
Hearing this NM has a very low drop rate in ASB and Horizon currently, these are the current ASB drop tiers:

![image](https://user-images.githubusercontent.com/37572397/221423996-0d6c87c7-4e5b-419a-937a-4e5d71877314.png)

and they match up with what I have heard the drop rate is here as well, with a group getting only 2 helmets over the span of 3 weeks of camping. I believe the drop rates should be bumped a tier higher (Sallet to uncommon) possibly 2 in the case of bandanna as it would usually drop off nearly every fly in era, but it's set to 10% base here. There is plenty of video evidence to support this as well. Wiki has a decent sample size and reflects the drop rates more accurately

![image](https://user-images.githubusercontent.com/37572397/221424083-7aa7bd69-ae0c-4d38-b6e0-98d8767274ab.png)

**Comment by HorizonPotato** [comment]
I'd also like to add some information to this for the Devs at least in terms of Dobson Bandana being set WAY too low at Uncommon tier.   It was definitely significantly more common than Jaeger Ring, dropping from almost every single fly with TH1.

https://www.youtube.com/watch?v=MnsU5Y6xfyk
https://www.youtube.com/watch?v=gnZfkKkHcyY + https://bucket.bluegartr.com/d10455aa2b8cf073b9eb53462141a412.png

Two Videos from 15+ Years ago showing very high drop rate on Dobson Bandana.  I know its not significant but I also have personal experience with them being extremely common. 

I can't confirm Jaeger/Voyage other than Jaeger was the more common of the two with Voyager being the rarest drop, but im nigh confident that the Dobson Bandana was "VC" tier I.E 24% Pre-TH.

**Comment by KiplingFFXI** [comment]
Further evidence from 2005 wiki page: https://ffxiclopedia.fandom.com/wiki/Carmine_Dobsonfly?oldid=47883

"Item Drops: A Dobson Bandanna is 100% drop from every Dobsonfly. Also, a Jaeger Ring drops around 30% of the time; a Voyager Sallet drops around 10% of the time."
