### ISSUE TITLE
🐛[BUG][NPCSystem/Combat] Aern Reraise Issues

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#1151]
**What does this bug affect?**
**If a pet gets the kill or is the aern's target on death and is then dismissed before the re-raise it seems to always crash if the aern would have re-raise.** 
Additionally, occasionally aern will play the reraise animation but still be dead on the floor. Usually when this occurs the cluster will crash a few minutes later.

**Steps to Reproduce**
Kill an aern with a pet (easier with SMN pet) and dismiss the pet before the aern re-raises.

**Expected behavior**
Aern should either die and stay dead, or re-raise with no crashes.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/221673681-9912c1e7-36a2-4f29-9d16-d35badc33fb8.png)

**Setup Information**
Version 30221103_1

**Additional context**
This has been observed both on the inside and outside sea zones with various levels of aerns.

**Comment by The-Aerec** [comment]
I know the fix, i'll get on this right away.
