### ISSUE TITLE
🐛[BUG][System] Fulm-Long Salmon Sub

### ISSUE THREAD

**Issue by clanofartisans** [HorizonFFXI/HorizonXI-Issues#1152]
**What does this bug affect?**
I have Fulm-Long Salmon Subs up for sale on the Auction House but the item isn't actually visible anywhere for someone to purchase.

**Steps to Reproduce**
Make some Fulm-Long Salmon Subs and list them for sale on the Auction House. Visit Breads&Rice, where Salmon Subs are located, and look for Fulm-Long Salmon Subs.

**Expected behavior**
Fulm-Long Salmon Subs should be listed for purchase in Breads&Rice.

**Comment by TracentEden** [comment]
This will be fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2769.
