### ISSUE TITLE
🐛[BUG][Combat] Contaminated Colosseum Extremely Bad Breath Ready Time is broken

### ISSUE THREAD

**Issue by bangplaysgames** [HorizonFFXI/HorizonXI-Issues#1159]
**What does this bug affect?**
The KS30 Contaminated Colosseum is unbeatable by any comps that are comprised of anything other than SMNs due to Extremely Bad Breath having no ready time. 

**Steps to Reproduce**
Fight Evil Oscar
Extremely Bad Breath is happening randomly and with an instant ready time.

**Expected behavior**
3 messages stating that Evil Oscar is filling his lungs with foul air followed by a ~10 second ready time for Extremely Bad Breath.

**Screenshots**
![image](https://user-images.githubusercontent.com/69700079/222306568-3ec3062d-5d71-44e0-9b90-370b9cadc3c0.png)
![image](https://user-images.githubusercontent.com/69700079/222306582-4108d406-30e0-4f99-9c9a-8c8fa7c18c9a.png)
![image](https://user-images.githubusercontent.com/69700079/222306610-6505ec6f-95e9-4c21-954d-353daeb11888.png)
![image](https://user-images.githubusercontent.com/69700079/222306620-5df51496-aab1-42a9-9742-ee040ba9aa1e.png)

**Setup Information**
Windows 10

**Additional context**

**Comment by TracentEden** [comment]
I am seeing the messages on the test server, when you try next time could you disable the chat addon to see if you get them then? Also the readying time should be 6 seconds based on retail information, I see that readying time on test server as well, not sure why you are seeing shorter times.

**Comment by bangplaysgames** [comment]
Others who weren't using battlemod were experiencing the exact same behavior.  We also had instances in the fight where people were dying far outside of the range that the attack is supposed to be. (they were more than 30 yalms away).

**Comment by bangplaysgames** [comment]
The issue also wasn't exclusive to the chat log.  The casting animation (red lines coming from the mob) was also not happening.  It was quite literally an instant cast.

Oscar is also not supposed to move while readying the ability.  It's supposed to be possible to move when the ready message shows up and get out of range.  In our attempt yesterday, even attempting to kite him resulted in instant death every time he used it unless the target was a pet that got heeled from a long distance away.

**Comment by bangplaysgames** [comment]
I would suggest taking GM characters into the BC and seeing how it's behaving yourselves.  It's quite irresponsible to ask 6 players to use their seals and time to Guinea pig on something that is broken when the dev team can simply test the issue with no expenditure.

**Comment by TracentEden** [comment]
> I would suggest taking GM characters into the BC and seeing how it's behaving yourselves. It's quite irresponsible to ask 6 players to use their seals and time to Guinea pig on something that is broken when the dev team can simply test the issue with no expenditure.

The issue is a lot of the time these issues are not easily reproducible. Were there other groups doing the same BCNM at the same time?

**Comment by bangplaysgames** [comment]
I would be happy to spend my resources and time in game to test this for you, but I would ONLY do so if there be some form of compensation for doing so.  Due to the time investment required to test this and the amount of people involved,  simply refunding the orb used is not an adequate compensation.

**Comment by TracentEden** [comment]
> I would be happy to spend my resources and time in game to test this for you, but I would ONLY do so if there be some form of compensation for doing so. Due to the time investment required to test this and the amount of people involved, simply refunding the orb used is not an adequate compensation.

No thanks, devs will look at it and make adjustments if needed.
