### ISSUE TITLE
🐛[BUG][NPC/Combat] Demon Knight's have access to Absorb-TP, an Out-of-Era spell.

### ISSUE THREAD

**Issue by HorizonPotato** [HorizonFFXI/HorizonXI-Issues#1160]
**What does this bug affect?**
Demon Knight spell list.

**Steps to Reproduce**
Fight Demon Knights (Xarcabard), they can cast Absorb-TP.

**Expected behavior**
Absorb-TP Is out of Era and should not be in their spell list.

**Screenshots**
https://bucket.bluegartr.com/aaf7d84e8bee3d1ced98b7b3f1219861.png

**Additional context**
Player DRKs, as far as I know, dont have access to this spell, stands to reason enemies should not either as it was not added to their Magic pool until DRKs got it.

**Comment by cegees** [comment]
Fairly sure Gobo DRKS (Tinkerers?) have Absorb-TP, even in Tahrongi Canyon.
