### ISSUE TITLE
🐛[BUG][NPC/Remedy has improper buyback price at 480gil]

### ISSUE THREAD

**Issue by LionelGrimm** [HorizonFFXI/HorizonXI-Issues#1168]
**What does this bug affect?**
In era, Remedy should npc for around 3.2k to a NPC with high fame.

**Steps to Reproduce**
<Sell a remedy to NPC>

**Expected behavior**
<Should vendor for 3.2k with high fame>

**Screenshots**

**Setup Information**

**Additional context**
This is basically an alchemy killer if it is going to stay , its an effort synth.  I don't understand why certain prints are nerfed vs much easier prints that are not nerfed.

**Comment by TracentEden** [comment]
This is an intended era+ change, can post in suggestions on the horizon discord to suggestion a change.
