### ISSUE TITLE
🐛[BUG] KSNM - Moa Constrictors

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#117]
**What does this bug affect?**
No reward chest spawned after beating both NMs. NMs not using Contamination after Contagion Transfer, or at all. Additional effect: TP drain doesn't seem to be working, or at least did not go off during my testing. https://youtu.be/vdvCRv3RLbs?t=3370 timestamp 56:10 shows it going off in the capture, witnessed it happen a few times in the capture though the tested was lvl 99 and the NMs were missing frequently. At 1:05:30 in the capture witnessed Toxic Pick land but gave no debuffs. Not sure if this is intentional but wanted to mention it. In the other capture https://youtu.be/_Tx7fPtT708?t=407 timestamp 6:45 Toxic Pick landed but only gave Plague debuff.

**Setup Information**
Version 30220906_0

**Additional context**
The Toxic Pick TP move seems to not always give the Plague debuff? The times I witnessed it landing in the captures did not give Poison or Gravity effects. May need to double check this to verify in case I missed something.

**Comment by dallano** [comment]
sadly I have this working on my local ASB branch. so this must be another horizon specific issue with the modules :'(
