### ISSUE TITLE
🐛[BUG][System] Uncapped FPS allows you to craft faster

### ISSUE THREAD

**Issue by Polarthief** [HorizonFFXI/HorizonXI-Issues#1171]
**What does this bug affect?**
Crafting Speed

**Steps to Reproduce**
/fps 0 to uncap your FPS.
This allows you to start your next craft nearly twice as fast.

**Expected behavior**
I'm actually unsure if this is intended or not. A vet friend told me to report this right away.

**Screenshots**
N/A

**Setup Information**
Game: v1.0(?)
Launcher: v1.1.4

**Additional context**
I was able to get next crafts in about 12s, while /fps 1 (60 FPS) was about 22s.

**Comment by cegees** [comment]
The whole game/physics runs faster. It was for 30fps PS2 cap. Even running, although they balance speed by locking move speed server or client, still feels different at 60fps vs 30 (kinda glidey). You can also use other mechanics, say menus like AH or NPCs this much faster, depending on your FPS / 30. Waiting 22-30s for craft is what stops me from crafting. I wish it was shorter... Fix would likely be setting a hard cooldown, I suppose. And answer to this is pure design choice, as people playing the AH with uncapped FPS will have huge advantage in the same way.
