### ISSUE TITLE
🐛[BUG][System] Gustav Tunnel Blizzard Scrolls Incorrect Drop Rate

### ISSUE THREAD

**Issue by SarithLekit** [HorizonFFXI/HorizonXI-Issues#1172]
**What does this bug affect?**

All blizzard scrolls off BLM skeletons have horrible drop rate, not even close to WIKI numbers

**Steps to Reproduce**

Had a WHM burn party from 64 to 67 (killed probably over 200+ BLM skeletons) and only got 1 scroll

**Expected behavior**

total combined drop rate should be 10% for any scroll but instead seems like 0.5%.  0.5% should be for the one scroll FREEZE.

**Screenshots**

**Setup Information**

**Additional context**

**Comment by SarithLekit** [comment]
We even killed Taxim (the NM) which is suppose to have higher drop rate and still got 0 drops.

**Comment by montijin** [comment]
![image](https://user-images.githubusercontent.com/2160211/223194615-e6e4e402-db61-4d18-81ff-1e924d6284d4.png)

http://ffxidb.com/zones/212/doom-warlock

**Comment by TracentEden** [comment]
The base drop rates are 
Scroll Of Blizzard III (Very Rare, 1%)
Scroll Of Blizzaga II (Very Rare, 1%)
Scroll Of Blizzard IV (Very Rare, 1%)
Scroll Of Blizzaga III (Very Rare, 1%)
Scroll Of Freeze (Super Rare, .5%)
I think these are taken from ffxidb and rounding or truncating to nearest TH level.
