### ISSUE TITLE
🐛[BUG][NPC] Ul'xzomit Mother has the wrong Droptable

### ISSUE THREAD

**Issue by Deathlos** [HorizonFFXI/HorizonXI-Issues#1174]
**What does this bug affect?**

Ul'xzomit mother is followed by 2 "babies" , the mother should have a 100% drop rate on nq organ while the babies do not. However this is not the case here. 
**Steps to Reproduce**

Kill the Ul'xzomit "Mother".
Don't receive a Nq organ 100% of the time.
**Expected behavior**

Nq Organ should drop 100% of the time.
**Screenshots**

https://ffxiclopedia.fandom.com/wiki/Ul%27xzomit
**Setup Information**

**Additional context**

**Comment by siknoz** [comment]
Confirmed on retail: https://youtu.be/UdkEx_QpNDY should be 100% drop from mothers.
