### ISSUE TITLE
Dynamis transporting issue

### ISSUE THREAD

**Issue by Nanners189** [HorizonFFXI/HorizonXI-Issues#118]
Tried to go into Dynamis-Jeuno and Dynamis-Bastok using Timeless hourglass. Upon trading I got a "Cannot connect to server." and also when it changed over to the Perpetual Hourglass, it said I was "You do not meet the requirements." but it let me enter. Inside, stone mobs were moving but i could not cast on them, attack them or get them to spawn by sight.

**Comment by Squinkerdoodle** [comment]
@Nanners189 did you use !addkeyitem vial_of_shrouded_sand prior to trying to go in? I was able to get into Dyna - Bastok after trading the Perpetual Hourglass to the trail markings. Seems to be working properly so far.

![image](https://user-images.githubusercontent.com/112344508/190873150-12f6ea16-8a04-4c4d-bcd5-00e7da81434c.png)

**Comment by Squinkerdoodle** [comment]
Verified mobs in all dynamis zones are moving / spawning properly.

**Comment by OpheliaXI** [comment]
All messages are also good with the newest patch. Closing.
