### ISSUE TITLE
🐛[BUG][Combat/ No Kill Claim from DOT on white mob]

### ISSUE THREAD

**Issue by Lilrayray1988** [HorizonFFXI/HorizonXI-Issues#1184]
**What does this bug affect?**

No exp or items dropped from DOT on a white mob that still has hate on you. However if you AOE kill them with a WS or spell you still receive the loot/exp.

**Steps to Reproduce**

DOT a mob and kill other mob allowing that one to go white.

**Expected behavior**

You should receive loot/exp.

**Screenshots**

![Lilrayray_2023 03 03_184255](https://user-images.githubusercontent.com/122132550/222862340-e03918c5-9a13-4b43-bea4-e15d1ff00bdd.png)
![Lilrayray_2023 03 03_184316](https://user-images.githubusercontent.com/122132550/222862341-e1474d15-1109-42d5-b663-e841f74226da.png)

**Comment by HorizonPotato** [comment]
Yes, this is retail accurate behavior and always has been.  Any White/Unclaimed mob that dies from a DoT will not yield Exp or drops regardless of if its currently engaged in combat/you have enmity on it.
