### ISSUE TITLE
🐛[BUG][Combat]

### ISSUE THREAD

**Issue by trentondyck** [HorizonFFXI/HorizonXI-Issues#1188]
**What does this bug affect?**

Stroper Chyme

**Steps to Reproduce**

Stroper Chyme claimshield was lost after the recent update to Claimshield behavior

**Expected behavior**

Claim shield works

**Screenshots**

N/A

**Setup Information**

N/A

**Additional context**

They used to have it before the latest update, I assume it was lost by accident.

**Comment by TracentEden** [comment]
Fixed
