### ISSUE TITLE
🐛[BUG] Claimshield Issue

### ISSUE THREAD

**Issue by JadedXI** [HorizonFFXI/HorizonXI-Issues#1189]
**What does this bug affect?**
Claimshield seems to be broken for Valkurm Emperor since this mornings patch. 
![image](https://user-images.githubusercontent.com/118323118/222877600-97e824f6-e18b-4d33-8961-59a48e0696ea.png)
I use charm, then Lubu uses charm, then 8 seconds after I originally charm and get the message that i lost the lottery, Tetz uses provoke and gets the claim on VE. Not sure If this is now intended behavior for claimshield on VE but I dont believe it should last 8 seconds. 

![image](https://user-images.githubusercontent.com/118323118/222877638-780af72f-8355-4361-afc4-4bd2fe56867a.png)
This is just to show no one actioned prior to me or Lubu.

**Steps to Reproduce**
Spawn VE, try to claim it, see how long claimshield lasts. This may also be a bug with Charm as both Lubu and I used charm without success and Tetz used provoke to instantly claim VE.

**Expected behavior**
If claimshield says you lose out of 2 players, then 1 of the 2 players who actioned on the mob should get the claim.

**Screenshots**
above

**Setup Information**
horizon

**Comment by TracentEden** [comment]
Fixed
