### ISSUE TITLE
🐛[BUG][System] You can not perform that Action.

### ISSUE THREAD

**Issue by PrinceOfParallax** [HorizonFFXI/HorizonXI-Issues#1195]
**What does this bug affect?**
I think it means I need to log in and log out again.

**Steps to Reproduce**
I changed my Job, from BST/THF to BLM/WHM in Sandy and I left my MH to N. Sand - I walked straight to the rail to fish.

I attempted to fish without holding a rod.

I then attempted to equip bait and rod.

**Expected behavior**
I should be able to equip things

**Screenshots**
![image](https://user-images.githubusercontent.com/38820735/222922459-dff88c1c-0328-4030-ab7f-b23f3093c0ca.png)

**Setup Information**
ON default Horizion clinet

**Additional context**

**Comment by ZellithS** [comment]
I think Ive had this trigger when I ran out of bait.  Had to relog to get it working again.
