### ISSUE TITLE
🐛[BUG][Mission/Combat] Ancient Vows - Yellow Liquid not working

### ISSUE THREAD

**Issue by dolomedes03** [HorizonFFXI/HorizonXI-Issues#1197]
During the Ancient Vows battle we were using Yellow Liquid to prevent Transmogrification however it doesn't work.  

When used it is supposed to prevent Transmogrification for at least 30 seconds however you can see from the timestamps in the screencap that only 9 seconds elapsed after use when Transmogrification happened.

This happened several times but I only have the screenshot of the one because the chat log was limited.

Our party was Umbra, Dolomedes, Aile, Schana, Mystiq and Delft.

![Umbra_2023 03 04_135754](https://user-images.githubusercontent.com/111464593/222929097-6e382b46-e4bf-43f4-99ab-fe4bb15e5584.png)

**Comment by HorizonPotato** [comment]
I'm sorry maybe this is poorly worded or I'm misunderstanding, but the only thing Yellow Liquid does is stop them from switching jobs.   If he was already on MNK/H2h form when you used the Liquid he can still use TP moves and will still have access to Transmogrification.

**Comment by dolomedes03** [comment]
Looks like I just misunderstood the mechanic.   I thought transmogrification was the mechanic that caused them to switch jobs.  My fault.  Disregard report.
