### ISSUE TITLE
🐛[BUG][Combat] Mob Astral Flow doing too much damage

### ISSUE THREAD

**Issue by TracentEden** [HorizonFFXI/HorizonXI-Issues#1199]
**What does this bug affect?**
Mob Astral Flow doing too much damage (was likely broken on March 3rd update)

**Steps to Reproduce**
Check for example the NM in ZM4 BCNM

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by jwest384** [comment]
This seems to be happening on all beastman with an avatar that can Astral Flow.  Is happening on CoP 7-4 Cryptonberry Assassin as well as Crimson-toothed Pawberry.  The following image is from the associated bug report thread in Discord:

![astral flow](https://user-images.githubusercontent.com/77185044/224120802-d4c8cc6c-8357-4e4b-b87f-1bfad476db84.png)

**Comment by jwest384** [comment]
Wiki says it's supposed to be doing around 800dmg.
