### ISSUE TITLE
🐛[BUG][Quest/Combat] Quest "Under Oath" Mob did not use 2hr

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#12]
**What does this bug affect?**
In the quest "Under Oath", One-eyed Gwajboj did not use Invincible.

**Steps to Reproduce**
Dropped item Well Weight and spawned NM again, once again the NM did not use Invincible during the fight.

**Expected behavior**
Per the wiki this NM should use the 2hr Invincible.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
NM does all other abilities / spells that it should, just missing the 2HR ability Invincible.

**Comment by dallano** [comment]
Fix incoming!
