### ISSUE TITLE
🐛[BUG][System] Cactuar Cantautor PH absence 

### ISSUE THREAD

**Issue by Capricioushs** [HorizonFFXI/HorizonXI-Issues#1202]
**What does this bug affect?**

**Previously present Cactuar appears to be missing at F-11 Western Altepa**. Last Spotted Feb 20th when Cactuar Cantautor spawned in its place. Previous visits have shown there to be 2 Cactuar at f-11, and 3 at G-11. (not counting the very south Cactuar in each square) 

In addition, 1 Cactuar and 1 Antica Secutor at G-11 roam north to south and then despawn. (uncertain if this issue is related)

Have used /fillmode in attempts to find missing mob in walls, floors, etc to no avail.

**Steps to Reproduce**

- Visit the location.

- Audit all known Cactuar in the areas of F-11 and G-11 vs server records.

- Repair it with dev magic if faults are found.

**Expected behavior**

The missing Cactuar would be there. Cactuar Cantautor would spawn in 7 hours or less because said Cactuar was present.

**Screenshots**

Can't SS what's not there.

**Setup Information**

Horizon v1.0, Horizon Launcher, Windows 10 
**Additional context**

**Comment by TracentEden** [comment]
I checked and it is there and respawning, can post here if it happen again.
