### ISSUE TITLE
🐛[BUG][Combat] Dune Boots do not grant any additional damage to kick attacks

### ISSUE THREAD

**Issue by amille14** [HorizonFFXI/HorizonXI-Issues#1203]
**What does this bug affect?**
Dune Boots should be granting kick attacks +30 base damage, however they instead grant no additional damage to kick attacks or dragon kick.

**Steps to Reproduce**
Equip Dune Boots. Kick stuff. Be sad when your kicks do significantly less damage than your punches instead of more. Then unequip the boots and kick stuff. Kick damage is exactly the same as with the boots.

**Expected behavior**
With Dune Boots equipped, kick attacks should be dealing damage as if you were using a h2h weapon with +30 dmg instead of your actual equipped weapon's base damage. This also affects kung fu shoes (+25 kick damage), wulong shoes (+27 kick damage), and wulong shoes +1 (+30 kick damage).

**Screenshots**

**Setup Information**
![image](https://user-images.githubusercontent.com/640065/222992251-20a2cf95-b04a-4d92-a6ee-ba185f1c9544.png)

**Additional context**
ASB Issue: https://github.com/AirSkyBoat/AirSkyBoat/issues/2795

Proposed ASB fix: https://github.com/AirSkyBoat/AirSkyBoat/pull/2796

**Comment by CriticalXI** [comment]
Fixed in a recent patch
