### ISSUE TITLE
🐛[BUG][System] AH Selling Order

### ISSUE THREAD

**Issue by benwelker** [HorizonFFXI/HorizonXI-Issues#1208]
**What does this bug affect?**
Items on the AH seems to be sold in reverse order based on time (incorrect sort maybe) where items listed most recently at the same price will sell before an item listed previously at the same price. Impacts the ability of players selling items on the auction house.

**Steps to Reproduce**

1.  Place an item on the AH at X price on character 1
2.  Place the same item on the AH at the same X price on character 2
3. Purchase the item on one of the characters or another
4. See that the item first sold was to player 2 who listed the item AFTER player 1.

**Expected behavior**
Honestly, I'm unsure if this is the intended behavior, but I would think if someone listed something at the same price as another, the player who listed the item first should be prioritized.  If that's not the case feel free to close this.

**Screenshots**
I don't have one currently, I can get one at some point if I remember (sorry)

**Setup Information**
N/A

**Additional context**
N/A

**Comment by CriticalXI** [comment]
Should be fixed in Patch 1.1

**Comment by Shayemz** [comment]
This still seems to be broken as of today (5/28/23) I had items listed on my one char from 4 days ago, yet the ones listed today on my other character for the same exact price sold first. The ones listed 4 days ago should have sold first and didn't.
