### ISSUE TITLE
🐛[BUG][Launcher]?

### ISSUE THREAD

**Issue by thtasiandad** [HorizonFFXI/HorizonXI-Issues#1209]
**What does this bug affect?**

When trying to start the game, takes me to an error code screen
spawn C:\Windows\system32\cmd.exe ENOENT
Cant open game anymore
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by TracentEden** [comment]
Please check and post in the tech support section of discord
