### ISSUE TITLE
🐛[BUG] - Chocobo Digging

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#121]
**What does this bug affect?**
Chocobo Digging - waiting 10 minutes in Konschtat Highlands and Pashow Marshlands without being able to dig. Kept receiving "You must wait longer to perform that action." error message.

**Steps to Reproduce**
Rent a chocobo and wait 5-10 minutes in a zone and try to dig with chocobo.

**Expected behavior**
Should be able to perform digging while on a rented chocobo and in a zone for longer than 1-2 minutes.

**Setup Information**
Version 30220906_0

**Additional context**
I've done the chocobo license quest and have a license / was on a rented chocobo from the dem crag. I did have a stack of Gysahl Greens in my inventory when trying to dig.

**Comment by OpheliaXI** [comment]
Fix is live.

**Comment by OpheliaXI** [comment]
Fix will be live in next patch.

**Comment by Squinkerdoodle** [comment]
Fixed now. Able to dig.
