### ISSUE TITLE
🐛[BUG][Quest] Tango with a Tracker does not reward 10k gil

### ISSUE THREAD

**Issue by rafiina** [HorizonFFXI/HorizonXI-Issues#1212]
**What does this bug affect?**
Tango with a Tracker Quest

**Steps to Reproduce**
Win Tango with a Tracker fight, completing quest

**Expected behavior**
Obtain 10k gil

**Screenshots**
![image](https://user-images.githubusercontent.com/14363298/223320004-16a2758b-3806-4ec2-84fe-3860eb374f0a.png)

**Additional context**
None -- it's pretty straight forward

**Comment by The-Tsukuyomiii** [comment]
Submitted a PR that should fix this issue [here](https://github.com/AirSkyBoat/AirSkyBoat/pull/2922).

**Comment by dallano** [comment]
I believe this issue was fixed. It was indeed rewarding 10k, however it wasn't reporting it to the player. thank you for the report! The issue should be fixed.
