### ISSUE TITLE
🐛[BUG] [MISSION] One to be feared

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#122]
**What does this bug affect?**

The start cutscene for one to be feared repeats itself. 
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by paladindamarus** [comment]
@Birdy-gif is this still happening?  I just tested locally on both an ASB and a Horizon install and it's working ok.  Haven't tested it on the live server yet.

**Comment by dallano** [comment]
LSB recently gutted Cid's lua. I suspect at the time of testing it was calling the same event in his lua and the new framework.
