### ISSUE TITLE
🐛[BUG][System/Crafting] Fuma Shuriken

### ISSUE THREAD

**Issue by zpiper85** [HorizonFFXI/HorizonXI-Issues#1226]
**What does this bug affect?**

The Synth recipe for Fuma Shurikens Shows that the amount created is x33
It only gives x12 Shurikens
The shurikens also only stack in x12s Not the expected change of 99.

**Steps to Reproduce**

Wind crystal: 1x Gold Ingot  1x  Mythril Sheet  1x Tama-Hagane 1x Mercury

**Expected behavior**

The craft should output a quantity of 33 Fuma Shurikens to match the log.

**Screenshots**

![image](https://user-images.githubusercontent.com/99561115/224460949-0a00d574-05fa-444e-b1e6-8b572ee87b81.png)
![image](https://user-images.githubusercontent.com/99561115/224460960-80a88f23-1c1c-480b-ab76-3374e4eec0ca.png)
![image](https://user-images.githubusercontent.com/99561115/224460978-2c3562da-dc65-4a25-ae2b-6e6f386259b2.png)
![image](https://user-images.githubusercontent.com/99561115/224460934-e4ae1762-d96b-43ba-8ad4-9eb971a27eb5.png)

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment]
Adjusted in a recent Shuriken overhaul in patch 1.1
