### ISSUE TITLE
🐛[BUG] - Bard song radius with harp

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#123]
**What does this bug affect?**
Bard song radius seems too wide for some songs when using a harp.

**Steps to Reproduce**
Equip a harp on bard and check song's radius.

**Expected behavior**
Songs should have the proper radius, like when singing / using a flute.

**Setup Information**
Version 30220906_0

**Additional context**
Flute / Singing radius seems correct, may be worth a double check to be sure.

**Comment by CriticalXI** [comment]
Looks like Bard song radius is correct. You can see on the table provided on this page for the song radius based on your skill: https://ffxiclopedia.fandom.com/wiki/String_Instrument_Skill?oldid=992763
