### ISSUE TITLE
🐛[BUG][Combat] Not parrying while shadows are up. 

### ISSUE THREAD

**Issue by avogadro-war** [HorizonFFXI/HorizonXI-Issues#1253]
**What does this bug affect?**

Avoidance/mitigation order seems incorrect unless intentionally changed. Parry is not occurring while shadows are active. Ergo, parry and shadow retention while receiving attacks are substantially weaker.

**Steps to Reproduce**

Have shadows up, watch for parry.

**Expected behavior**

anticipate > evade > parry > shadow/blink > counter > block > guard > retaliate

**Screenshots**

![image](https://user-images.githubusercontent.com/109310871/225469294-a84da290-06f2-4817-ac83-1adaf2bf52f6.png)

**Comment by avogadro-war** [comment]
See this guide circa 2007: https://www.staronion.com/maiev/nfblog/?page_id=279

**Comment by JonaldDuck** [comment]
![image](https://user-images.githubusercontent.com/128080587/225704760-2b7f6c11-4606-4f51-a29a-d53004e4d2cf.png)
Potentially helpful example.  Got a parry skillup with no parry while shadows are up

**Comment by mousseng** [comment]
era video evidence of parrying with shadows up: https://www.youtube.com/watch?v=HywIWjRnZJ8&t=53s
it's timestamped at the exact moment and the log moves fast so i snagged a screenshot:
![image](https://user-images.githubusercontent.com/8106757/226143566-cdce1c90-6870-4f18-81f6-5fe7e5418c19.png)
