### ISSUE TITLE
🐛[BUG][NPC/Quest/Mission/System/Combat/Launcher/Website]

### ISSUE THREAD

**Issue by PanderXe** [HorizonFFXI/HorizonXI-Issues#1261]
**What does this bug affect?** 
Me, my character is stuck in-game. Black screened as i zoned purchasing a Chocobo. Please Assist!

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**
 Character Name - Pander

**Comment by TracentEden** [comment]
This is an issue for which you should file a GM ticket.
