### ISSUE TITLE
Sever says online but getting error POL-0033

### ISSUE THREAD

**Issue by Shodannoka** [HorizonFFXI/HorizonXI-Issues#1262]
I saw that they were trying to do maintenance today at 11:30 but since 10:30 I have not been able to join.  What time zone is the server in?  And when will it be back up if it's down.  Sorry I'm just confused because the launcher says it's online with almost 2000 players and I can't seem to join.  So correct me if it's just down and displaying this during the maintenance.

Thank you for your time!

**Comment by TracentEden** [comment]
Ask about these types of issues in tech support section of discord

**Comment by Shodannoka** [comment]
Sorry for my ignorance, but I can't seem to find any tech support
specifically named section.
