### ISSUE TITLE
🐛[BUG][NPC]  Cosmo Cleanse says 15k cost in NPC dialoge but took 50k

### ISSUE THREAD

**Issue by bangplaysgames** [HorizonFFXI/HorizonXI-Issues#1265]
**What does this bug affect?**
Buying Cosmo-Cleanse took 50k Gil instead of 15k

**Steps to Reproduce**
Buy Cosmo Cleanse

**Expected behavior**
Only 15k taken from gil.

**Screenshots**
I didn't even notice it until after apollyon, but next time I'll take video evidence of it.  I had 63k gil before purchasing cosmo-cleanse, did nothing else which would take gil away other than buying cosmo-cleanse, ran Apollyon, and noticed I had only 13k left.

**Comment by bliven-was-taken** [comment]
The bug is actually the npc text saying it costs 15k but should say 50k in this era.

**Comment by CriticalXI** [comment]
A recent in game warning was added to the NPC telling the 50k cost
