### ISSUE TITLE
🐛[BUG][NPC/Combat]Zoredonite has permanent Invincible Effect inside shell - Unkillable by Melee jobs.

### ISSUE THREAD

**Issue by HorizonPotato** [HorizonFFXI/HorizonXI-Issues#1267]
**What does this bug affect?**
The NM, "Zoredonite", on the Manaclipper.

**Steps to Reproduce**
When fighting the NM, when it goes inside its shell it gains Invincible and becomes undamagable by physical attacks.

**Expected behavior**
It should use Invincible once during the fight, and while inside its shell it gains a considerable defense boost (But its still damageable and thus you're able to gain TP from hitting it and also slowly trickle at its potent regen).

**Screenshots**
https://bucket.bluegartr.com/21f98e73c3de7a9545d80f79bfd294ff_1280.png  - heres just one example of it being in its shell and we're doing 0 damage.   Weaponskills also did 0 damage, critical hits, SA, TA, everything did 0 damage while in its shell.

**Setup Information**
Current.

**Additional context**
There are several testimonies from melee jobs, and I've personally killed this NM on Retail as 75 THF, its completely killable by a Melee job by gaining TP during "Inside shell" phase and Weaponskilling it when it comes out.  It can sometimes be very close, but its 100% killable by Melee jobs in Retail. 

In Horizon right now, every time it enters its shell (Which is literally 2-4 seconds after leaving it), it gains Invincible and regens to full shortly thereafter, and is completely unkillable by any melee job unless you somehow one-shot it while its out of its shell.

**Comment by TracentEden** [comment]
@HorizonPotato Yeah this is due to an issue with the physical damage down effect that should be fixed in next update or two (fixed via https://github.com/AirSkyBoat/AirSkyBoat/pull/2862), the physical damage reduction should be only 95%, with the bug is roughly 100%.
