### ISSUE TITLE
🐛[BUG] Rose Garden/Voluptuous Vilma not spawning

### ISSUE THREAD

**Issue by migadogit** [HorizonFFXI/HorizonXI-Issues#1271]
Rose Garden / Voluptuous Vilma NM in Yuhtunga Jungle not spawning

The Rose Garden will not spawn based on the legacy conditions, which were to be undisturbed for 10.5 hours, not aggroing anyone or being killed. This gives no chance for Voluptuous Vilma to spawn, and therefore no access to Vilma's Ring.
**Steps to Reproduce**
Monitor the Overgrown Rose at I-7 in Yuhtunga Jungle for a long period of time and ensure it doesn't aggro anyone or is engaged by anyone. Expected spawn is 10 - 10.5 hours after sitting undisturbed.

**Expected behavior**
If left undisturbed for 10-10.5 hours, Overgrown Rose should despawn, and Rose Garden takes it's place. If Rose Garden is undisturbed for a period which is undefine to me, Rose Garden despawns and Voluptuous Vilma should take it's place.

**Screenshots**

**Setup Information**

**Additional context**

![Migado_2023 03 18_111635](https://user-images.github
![Migado_2023 03 18_113045](https://user-images.githubusercontent.com/118323387/226115390-c615de09-41ce-44c5-8ebb-bdf9c2c7d31a.png)

![Migado_2023 03 18_111732](https://user-images.githubusercontent.com/118323387/226115387-9ef1f374-2913-48c8-b137-25fc24e5eaeb.png)

![Migado_2023 03 18_111727](https://user-images.githubusercontent.com/118323387/226115382-beb81857-85ec-4a53-9e4f-848d8ebfa397.png)

![Migado_2023 03 18_111723](https://user-images.githubusercontent.com/118323387/226115379-d491d98d-f031-4070-b8aa-cf487a7e198b.png)

![Migado_2023 03 18_111720](https://user-images.githubusercontent.com/118323387/226115377-0b628d3d-c0fb-4c75-90f0-2c1f4051be06.png)

![Migado_2023 03 18_111716](https://user-images.githubusercontent.com/118323387/226115375-43a4be18-e752-4095-93d7-c87ac1a767a2.png)

![Migado_2023 03 18_111648](https://user-images.githubusercontent.com/118323387/226115372-65988887-987d-4275-88e0-3d265ec25485.png)

![Migado_2023 03 18_111645](https://user-images.githubusercontent.com/118323387/226115369-717eb215-371f-423b-a7a6-172e037a9aa4.png)

![Migado_2023 03 18_111642](https://user-images.githubusercontent.com/118323387/226115366-e3d18be6-55ff-482d-840f-5271eabbf721.png)

![Migado_2023 03 18_111639](https://user-images.githubusercontent.com/118323387/226115363-e8b9b0c2-4a48-4f0d-9f64-c95cb2f72f5d.png)
usercontent.com/118323387/226115353-c38fb1db-5454-4e5a-8f03-ccaa5e2f723c.png)

**Comment by TracentEden** [comment]
@migadogit If the zone crashes or resets then the timer also currently resets, this might be what caused the issue

**Comment by migadogit** [comment]
@TracentEden The zone was up for the full 12 hour duration I was there, and the mob was not disturbed. I put the logs in from 12:00AM to 11:30AM when I was watching it, although your point stands if the zone crashes at all.

**Comment by TracentEden** [comment]
@migadogit I tested this on test server and it popped as it should. How did you determine it was not disturbed? video?

**Comment by migadogit** [comment]
@TracentEden I followed it and watched it for 12 hours. A combination of masochism and genuine curiosity. I turned all my filters off as well on the off chance I could miss something, but it was never engaged nor aggrod to anyone while I was there. If there's more testing I can do I'm happy to do so.

**Comment by CriticalXI** [comment]
I can confirm Rose Garden is popping on our internal test server which is an exact copy of the live game. I assume you may have missed someone aggroing it during the 12 hours.

![image](https://user-images.githubusercontent.com/48370698/232884443-6129b2d9-fd33-40e3-b691-87a19ff6e2ae.png)
