### ISSUE TITLE
🐛[BUG][System] Congestion message when trying to send Pilgrim's Wand to alt on same account

### ISSUE THREAD

**Issue by Shiravalen** [HorizonFFXI/HorizonXI-Issues#1272]
**What does this bug affect?**
The Fandom wiki says Pilgrim's Wand can be sent to another character on the same account, but every time I try, I get the delay and the "Communications seem to be congested" message, cancelling the delivery. I'm levelling multiple characters on the same account, and Pilgrim's Wand is fairly annoying to get on this server, so I hope it can be easily fixed, although I think most people only really level one character.

**Steps to Reproduce**
Attempt to send Pilgrim's Wand to another character on the same account. I can send other items without the congestion error. I don't have any other Ex sendable items to test further.

**Expected behavior**
It should be sent normally, since it's a type of Ex item that can be sent to characters on the same account (some can, some can't).

**Setup Information**
Game version: whatever Horizon is
OS: Windows 10

**Screenshots**
![Abudih_2023 03 18_191406](https://user-images.githubusercontent.com/128263935/226145140-d3b6a215-1483-42bb-befa-eec6c47005f8.png)
![Abudih_2023 03 18_191359](https://user-images.githubusercontent.com/128263935/226145127-40cd573d-435b-422f-809f-b726da108915.png)

**Comment by TracentEden** [comment]
From my understanding such items cannot be sent to chars on same account on Horizon.
