### ISSUE TITLE
🐛[BUG][Combat] - Pets disappear when charm wears off in combat.

### ISSUE THREAD

**Issue by Taelis1** [HorizonFFXI/HorizonXI-Issues#1273]
Combat related bug.

**What does this bug affect?**
Anyone that uses charm. When charm wears off in combat the pet will either disappear (If outside spawn range) or slowly walk back to spawn (If close to spawn range). Currently if the charmed pet is not in combat it will correctly attack the player that charmed it.

**Steps to Reproduce**
Charm a pet, fight with it. If its fighting when charm wears off the above behavior will be observed 100% of the time.

**Expected behavior**
Any time charm wears off naturally (IE: Not through Leave) the charmed pet should attack the player that charmed it regardless of whether or not the pet is in combat or not. This has been the behavior of Charm throughout Era and still persists to this day.

**Additional context**
"When Charm expires, the former pet will attack you unless you are at least [30'] away; mobs that track by scent may track you unless you are under [Deodorize] effect."

-Source: https://ffxiclopedia.fandom.com/wiki/Charm

**Comment by Dejey1** [comment]
Just a little added context that could assist in finding the problem. The mob will depop when it is fighting and outside it's spawn zone. However if you keep the mob in the spawn zone and it is fighting, the glitch takes form in a different manner, the mob will stop attacking and walk back to the spawn rather than attack you.

**Comment by Taelis1** [comment]
Suggested potential solution:

Have pets either automatically Stay or Heel when there is 1 second left on the charm. This will ensure they always attack the charmer as opposed to dissapear/leash.
