### ISSUE TITLE
🐛[BUG][NPC] Coeurls/Wolves share placeholders.

### ISSUE THREAD

**Issue by Kirak-FM** [HorizonFFXI/HorizonXI-Issues#1278]
**What does this bug affect?**
Coeurls and Wolves in Meriphataud Mountains and Sanctuary of Zi'Tah share placeholders, wolves will not spawn unless Coeurls are killed and Coeurls will not spawn if Wolves are spawned.

Additionally Wolves that dissappear at night will continue to block Coeurl respawns and will spawn early (~18:00 instead of 20:00)

**Steps to Reproduce**
Wait for wolves near zone to Zi'Tah to spawn while all Coeurl spawns are up. They will not.
Kill Coeurls. Those that repop as wolves will not respawn, even during the day,

**Expected behavior**
Coeurls and wolves should not share the same placeholders. 
If this is intended, wolves should not be spawning early and Coeurls should respawn during the day instead of being locked out by wolves spawns.

**Additional context**
I have not tested the spawning early in Zi'Tah but have seen spawns locked out by Wolves and they do not respawn during the day either.

SS of Wolf spawned at 17:40
![Untitled](https://user-images.githubusercontent.com/128334057/226225189-a70393f2-00a5-40d8-a214-99aef4b7e009.png)

**Comment by CriticalXI** [comment]
Working as intended, this is retail behavior.
