### ISSUE TITLE
🐛[BUG] Temenos not implemented

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#128]
**What does this bug affect?**

Same as title
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by Squinkerdoodle** [comment]
To expand, when clicking to enter Temenos the menu to select North / West / East does not come up. When using !togglegm the menu does come up, but when you enter it gives you the message about not being able to enter and there are no mobs at all inside.

**Comment by Shuu-37** [comment]
Sounds like Temenos is implemented from other reports now.
