### ISSUE TITLE
🐛[BUG][Combat]Hpemde mobs behaviour

### ISSUE THREAD

**Issue by xperian** [HorizonFFXI/HorizonXI-Issues#1287]
Hpemde mobs have a couple things not working properly:
-Open mouth magic damage taken: instead of being 100% more it is actually being reduced by 50% when it opens it's mouth. I think this issue has already been reported in the ASB git, will just mention it.
-Open to closed / closed to open mouth: whenever the mob changes from one stance to the other it will move and chase you down regardless if it's bound and/or slept. This leads at times for the mob not being sleepable if it has already been slept. Similar thing can happen if you land spell on the exact moment it is changing stance, but in this case even with the spell landing it will continue to attack and chase you down. The third issue comes if it uses a TP move while he is changing stances as this can lead to it using TP moves back to back, up to 5 times in a row.

**Steps to Reproduce**
Engage a Hpemde and sleep/bind try to kill normally

**Expected behavior**
For it to take x100% magic damage when mouth is open and to not move while slept / bound

**Screenshots**
![image](https://user-images.githubusercontent.com/13814117/226992923-01f9ee60-35e9-4e46-aa7f-9b62f51e11bb.png)

**Setup Information**
ver 30221103_1

**Additional context**
If you need any testing let me know.

**Comment by JuffuJuffu** [comment]
Screenshot of TP move spam. I dont think it did actually use the move though, just spammed it a bunch in this case and went wonky with animations. 
![Juffu_2023 03 20_202713](https://user-images.githubusercontent.com/91141010/226991182-e4f1991c-766d-4f2c-aaa7-dadb9606a6f3.png)

**Comment by lapislosh** [comment]
also reported on ASB here https://github.com/AirSkyBoat/AirSkyBoat/issues/2753
