### ISSUE TITLE
🐛[BUG] - Summoner 2hr w/Diabolos missing

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#129]
**What does this bug affect?**
Ruinous Omen not showing up in Diabolos's rage blood pacts while the summoner is under the effect of 2hr Astral Flow.

**Steps to Reproduce**
Summon Diabolos, use Astral Flow and then check rage blood pacts for Diabolos.

**Expected behavior**
Ruinous Omen should be available while Astral Flow is active.

**Setup Information**
Version 30220906_0

**Additional context**
All other 2hr Astral Flows are listed.

**Comment by Squinkerdoodle** [comment]
@Abdiah / @dallano I wonder if this came after the change to the Diabolos fights in the CoP mission where it wasn't supposed to use this move. I haven't been on SMN in a while so I hadn't thought to check.

**Comment by paladindamarus** [comment]
Testing required.  Ruinous Omen does a random percentage of damage, but we need more data on this.  I'm also reading that it does additional damage.

**Comment by paladindamarus** [comment]
Pushing a draft of this ability into ASB for testing.  It at least gives us a framework so that we can test values once we get some data out of retail.

**Comment by OpheliaXI** [comment]
@paladindamarus did we ever get this 100%?

**Comment by paladindamarus** [comment]
> @paladindamarus did we ever get this 100%?

Right now, no ... I have everything "active" but no real accurate data for Ruinous Omen yet.

**Comment by Squinkerdoodle** [comment]
@paladindamarus just checking in, no change on this one yet?

**Comment by paladindamarus** [comment]
None.  I'll check my horizon install today -- I don't even remember where I left off with this

**Comment by StyrkaGG** [comment]
currently is in the game now

**Comment by Squinkerdoodle** [comment]
@paladindamarus seems it's active like you said, would you like this ticket to stay open as a reminder / so you can get accurate data for tuning?

**Comment by paladindamarus** [comment]
No, can close it.  I'm still tracking RO offline anyway.
