### ISSUE TITLE
🐛[BUG]Roaming Groundskeeper aggroing by sight after Despot Killed

### ISSUE THREAD

**Issue by Shuhasu** [HorizonFFXI/HorizonXI-Issues#1293]
**What does this bug affect?**
Groundskeeper Aggro abilities

**Steps to Reproduce**
Kill Despot
Walk Around
Get aggroed by wandering Groundskeeper (not the ones in blue areas)

**Expected behavior**
should only aggro by magic

**Screenshots**

**Setup Information**
ver 30221103_1

**Additional context**
some party members killed Despot, then complained about being aggroed by every groundskeeper nearby. 
we came by after another nm kill, but one of our bards got aggroed just by running near the north entrance.

**Comment by lapislosh** [comment]
I think I noticed this too, was sure I was running down the center and got aggroed. Made me start second-guessing myself if I had roamed too far to the side without realizing it.

**Comment by Squinkerdoodle** [comment]
If someone zones one of the dolls in the cubby then it will aggro anyone that gets close to it when it's walking back to it's home.

**Comment by TracentEden** [comment]
Yep, I think this is intended behavior from zoning one of the PHs, thanks for reporting.

**Comment by TracentEden** [comment]
> As far as we could tell nothing was zoned when this happened, nothing was heading back to the cubby holes, if anything they were moving the opposite direction.

I think they sometimes get a bit lost, I looked on test server and could not find any groundskeepers in that area besides the despot placeholders that aggro.
