### ISSUE TITLE
🐛[BUG] Gemini Subligar shows up in Ammo list 

### ISSUE THREAD

**Issue by cajunn** [HorizonFFXI/HorizonXI-Issues#1297]
**What does this bug affect?**

If Gemini subligar is in your inventory, it shows up in your Ammo list 

**Steps to Reproduce**

- Have Gemini subligar in your inventory 
- go to equip -> Ammo slot 

**Expected behavior**

Should only be ammo in the list

**Screenshots**

![image](https://user-images.githubusercontent.com/20643851/226802615-fa447f69-215c-4e68-903a-8a8c6b45623d.png)

I had an Arbalest+1 equipped at the time

**Comment by CriticalXI** [comment]
Seems like its showing up because it was in your inventory period. It only sorts it once you've clicked into the slot which I can see you haven't done in this screenshot.
