### ISSUE TITLE
🐛[BUG][NPC/Quest] - A Craftsman's Work

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#13]
**What does this bug affect?**
During the quest A Craftsman's Work, Decurio I-III did not use Invincible. Other than that the quest work fine and was completed.

**Steps to Reproduce**
Spawn and fight mob.

**Expected behavior**
Decurio I-III should use Invincible at least once during the fight.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Comment by CriticalXI** [comment]
Fixed in https://github.com/AirSkyBoat/AirSkyBoat/pull/370
