### ISSUE TITLE
🐛[BUG][Item] Checkered Scarf says it gives +12 HP but it actually reduces max HP

### ISSUE THREAD

**Issue by Fr0zt** [HorizonFFXI/HorizonXI-Issues#1300]
**What does this bug affect?**

The item "Checkered Scarf" says it gives HP +12, it actually gives HP -12.

**Steps to Reproduce**

Equip and unequip the item, watch max HP.

**Expected behavior**

Should give +12 HP

**Screenshots**

![image](https://user-images.githubusercontent.com/10720170/227023067-3bda1bb7-fe82-4f06-9bfc-3e6380e06dc1.png)
![image](https://user-images.githubusercontent.com/10720170/227023259-ef553a16-7597-43d8-9ee6-d043a728d5dc.png)
![image](https://user-images.githubusercontent.com/10720170/227023623-fa620d30-612a-4330-85cb-3d03b8660025.png)

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment]
Fixed in HorizonFFXI/HorizonDats#1
