### ISSUE TITLE
🐛[BUG] Combat skill capping at incorrect level at 75 for Ninja

### ISSUE THREAD

**Issue by Paradoxx004** [HorizonFFXI/HorizonXI-Issues#1306]
Katana Skill currently caps out at 269 for Ninja when its supposed to be at 276 at lv 75. Ninja has A+ skill in Katana and all jobs with A+ skill caps at 276

**Comment by siknoz** [comment]
In-era NIN Katana Skill was actually A- 

Source: https://ffxiclopedia.fandom.com/wiki/Category:Katana?oldid=36702

Unless you can find a source that shows the contrary, prolly won't be changed.
