### ISSUE TITLE
🐛[BUG][NPC/Quest/Mission/System/Combat/Launcher/Website]?

### ISSUE THREAD

**Issue by KayOttick** [HorizonFFXI/HorizonXI-Issues#1307]
**What does this bug affect?** Launcher. Upon Launch, A window appears stating,  "Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT at ChildProcess._handle.onexit (node:internal/child_process:478:16) at process.processTicksAndRejections (node:internal/process/task_queues:83:21)"  

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by LordShoAllah** [comment]
I got this error today and it prevented me from playing. Apparently, my G drive that had some game information wasn't showing up in my list of drives. I tightened the connections on the drive inside my computer and it worked.

**Comment by CriticalXI** [comment]
This is an issue with the launcher. Please request help in the launcher support section on discord.
