### ISSUE TITLE
🐛[BUG] Dynamis-Windurst Time Extensions & Issues

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#131]
**What does this bug affect?**
When the SMN NM used TP moves, it's summoned avatar (Shiva) would use Carbuncle's Rage / Ward blood pacts instead of Shiva's.
One of the SMN mobs used Garuda, which uses Ramuh's astral flow move instead of Garuda's.
One of the SMN mobs summoned Ifrit, which used Garuda's astral flow move instead of Inferno.
One of the SMN mobs summoned Ramuh, which used Titan's astral flow move instead of Judgement Bolt.

Occasionally BST & SMN mobs would do the summoning spell animation but would not actually summon a pet. This seems to happen randomly, but more common when there's 2 BST or SMN in a group pull.

RDM NM did not spawn from statue 116, preventing mega boss from spawning due to not being able to kill the RDM NM.

Statue 115 did not spawn until after 114 was killed.
Statue 114 was up before pulling 116, and spawned 2 statues, which summoned 1 mob each.

Statue 041 is up on a ledge and does not aggro when you run in front of it.

20 min time ext given by statue 011 or one of the mobs it summons.
20 min time ext given by a Prelate from statue 023.
20 min time ext given by a Persecutor from statue 029.
20 min time ext given by a Visionary from statue 033.
20 min time ext given by a Prelate from statue 037
20 min time ext given by a Skirmisher in the statue 046 / 047 / 048 / 049 group.
20 min time ext given by a Skirmisher from statue 069.
20 min time ext given by an Assassin from statue 073(?)
20 min time ext given by a Priest from statue 067 / 068.
20 min time ext given by an Exemplar from statue 079.
20 min time ext given by a Prelate from statue 119 / 120.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/192007014-72bd67fa-f51d-498b-8238-4902454764c6.png)
![image](https://user-images.githubusercontent.com/112344508/192005663-4aaa47ae-aec4-46f0-ad41-f2a16dc93fe3.png)

**Setup Information**
Version 30220906_0

**Comment by Squinkerdoodle** [comment]
Also just a reminder that Dynamis is still dropping BLU / COR / PUP / DNC / SCH AF2 pieces, I know it was already mentioned they will be removed at some point before launch.

**Comment by Frankie-hz** [comment]
Multiple NM are spawning from what it seems to be random statues as well
![image](https://user-images.githubusercontent.com/105882754/192065850-3ac0401d-44b2-4c27-84b1-5f06b46615ec.png)

**Comment by Frankie-hz** [comment]
A statue that is supposed to spawn only 2 mobs spawned 6 even though the lua file is set to 2.
![image](https://user-images.githubusercontent.com/105882754/192066284-0f9d4e7a-5f82-44bc-b276-7625ce947c48.png)

![image](https://user-images.githubusercontent.com/105882754/192066252-579f8c70-40c9-4408-8fee-d6cdb597e33f.png)

**Comment by Frankie-hz** [comment]
waves are respawning instantly - causing the entire zone to aggro
![image](https://user-images.githubusercontent.com/105882754/192066412-0c6a3639-5dba-44a8-88e0-5ced62f7bf49.png)

**Comment by Squinkerdoodle** [comment]
Restested after recent fixes were implemented. New github submitted with current issues.
