### ISSUE TITLE
🐛[BUG][NPC] Only one spawn for Ten of Coins

### ISSUE THREAD

**Issue by bdahlinghaus** [HorizonFFXI/HorizonXI-Issues#1317]
**What does this bug affect?**
Ten of * spawns in (J-8) in Dahlia tower of Outer Horutoto Ruins
only a single mob in the spawn set can be up

**Expected behavior**
Actual era behavior from classic ffxi wiki "There are three spawn points in the room that spawn a different Ten cardian."

**Comment by Clonegoat** [comment]
Just wanted to tag in that this is still the case, makes trying to get the 2 different ten cards needed for quests even more difficult than needed
