### ISSUE TITLE
🐛[BUG] Ballad1 + Ebony HArp +1

### ISSUE THREAD

**Issue by SinnerFreaky** [HorizonFFXI/HorizonXI-Issues#1319]
**What does this bug affect?**
When casting Ballad 1 with the above mentioned instrument, it can go beyond 18Y

**Steps to Reproduce**

**Expected behavior**
As ballad 2 with the same instrument, should be 10Y

**Screenshots**

**Setup Information**

**Additional context**

**Comment by SinnerFreaky** [comment]
um... pretty self explanatory.

**Comment by CriticalXI** [comment]
https://ffxiclopedia.fandom.com/wiki/String_Instrument_Skill

This is intended, please see the chart at the link above.
