### ISSUE TITLE
🐛[BUG][Combat] Dynamis Sandoria Issues

### ISSUE THREAD

**Issue by siknoz** [HorizonFFXI/HorizonXI-Issues#1332]
**What does this bug affect?**
Anyone doing Dyna-Sandoria(maybe other dynas)

**Steps to Reproduce**
Run Dyna Sandy

**Expected behavior**
1) -ga3 from spells were only hitting 1 party, not the entire alliance  -ga spells should hit everyone in the area, whether they have hate or not.
2) Defense boosts from Arm Block are way too high, reduced all damage including ws to 0 - Defense Boost should only be a small defense boost, not 100% reduction
3) Mobs are hitting too softly, monks were hitting for 20-30 a hit, Slam dunks were only doing ~150-200. Both of those examples were to a ninja without shadows. They should be hitting in the range of 150-200 a hit, slam dunks should be in the area of 400-500, maybe more. Need research.
4) The tent near the west ronfaure gate has a statue that only pops a hecteyes, without a beastmaster. Should pop beastmaster who summons pet.
5) The statue near the count's manor did not auto-link the popped statues. It's possible to just pull the statue + NM. They should all autolink as soon as they spawn. 

**Screenshots**
Will update this later.

**Additional context**

**Comment by TracentEden** [comment]
@siknoz 
1. Yep, this will be fixed.
2. Increases def by 25% outside of dyna but decreases physical damage by 90% in dyna, this is probably wrong but might need some retail testing to find correct value for inside dyna (which frank says is diff from outside).
3. Still checking into this
4. I was not able to find the statue that only pops a hecteyes.
5. This is not the case on other p-servers, did you have retail testing?

**Comment by siknoz** [comment]
For point 5 there is no videos (that i've found anyways) to support it, it's inferred based off of dynamisbums\enedin maps which indicate statues are popped from aggro'ing another statue, because there are very few of these and because most are within very close proximity it's a good guess that they aggro on pop\link. 

![image](https://user-images.githubusercontent.com/78240569/232897836-fab80b59-2730-4fab-a268-b23ed5a386b0.png)

For sando the manor is the only statue where they pop far enough away that they don't automatically aggro, so it's not a far leap to say that they should link\aggro on spawn. It's not an overly difficult pull anyways.
