### ISSUE TITLE
🐛[BUG][NPC//Combat/] Jailer of Temperences' Optic Induration hits too hard I think

### ISSUE THREAD

**Issue by TristtHXI** [HorizonFFXI/HorizonXI-Issues#1335]
**What does this bug affect?**
Induration is hitting for around 1k, im not sure it should, worth checking out i guess
https://cdn.discordapp.com/attachments/1057343365663957063/1090510447750414346/image.png

**Comment by CriticalXI** [comment]
Have video evidence of Optic Induration absolutely destroying people from retail. 1.5k+ damage. Feel free to re-open if you have evidence otherwise.
