### ISSUE TITLE
🐛[BUG][NPC/Combat] Euvhi forms do not function correctly

### ISSUE THREAD

**Issue by zuultek** [HorizonFFXI/HorizonXI-Issues#1337]
Aw'Euvhi forms seen on the screen do not correspond to its actual damage resistance and damage output - it starts taking double damage w/o changing forms, and changes form w/o any change to damage resistance. Besides, it doesnt seem to change forms as often as it should - most of the time during a ~5 min long fight it stays in closed form in terms of damage resistance and is seen as open on the screen.

**Setup Information**

30221103_1

**Additional context**

Only tested it on aw'euvhis in Ru'hmet garden

**Comment by TracentEden** [comment]
This will be fixed by two incoming PRs https://github.com/AirSkyBoat/AirSkyBoat/pull/2902 and https://github.com/AirSkyBoat/AirSkyBoat/pull/2917
Thanks for reporting
