### ISSUE TITLE
🐛[BUG][Item]Juggernaut +30 attack not applied

### ISSUE THREAD

**Issue by KushertonCapn** [HorizonFFXI/HorizonXI-Issues#1338]
**What does this bug affect?**
Juggernaut axe is not getting the +30 attack on the weapon

**Screenshots**
![Capnk_2023 03 30_133041](https://user-images.githubusercontent.com/125845530/228917900-ad2b9f8d-d952-4bcc-a565-e78e8971eb6e.png)
![Capnk_2023 03 30_133048](https://user-images.githubusercontent.com/125845530/228917936-7561b7b1-a923-480b-9d9b-c7dd64ee25f9.png)

**Comment by TracentEden** [comment]
@KushertonCapn There is a known issue with attack display in the menu. Use /checkparam <me> to see attack and it should reflect the +30 attack.
