### ISSUE TITLE
Central Tenemos floors 2 and 3 have improper loot tables and mobs taking improper damage

### ISSUE THREAD

**Issue by Cdelka** [HorizonFFXI/HorizonXI-Issues#1339]
**What does this bug affect?**
Central Temenos 2nd and 3rd floors. Enemy drop tables are incorrect and are dropping Tavnazian Sheep Livers and Miseraux Garlic instead of Ancient Beast Coins. As well, the elementals on floor 2 are taking 0 damage from melee attacks while the elementals on floor 3 are taking obscene amounts of damage from them.

**Steps to Reproduce**
Kill enemies on the floors.

**Expected behavior**
The wiki says that the elementals on floor 2 should only take 25% less damage, not 100% and that the elementals on floor 3 should take more damage but it definitely feels like they're taking way too much.  As for the drop tables, they should be dropping Ancient Beast Coins but instead none dropped outside of the chest.

![image2](https://user-images.githubusercontent.com/129469051/228998719-9b538043-533a-4197-885e-2a7355f85c54.png)
![image](https://user-images.githubusercontent.com/129469051/228998738-0f480092-9a83-4fe8-8242-93f62f6be082.png)

**Comment by hookstar** [comment]
https://github.com/LandSandBoat/server/pull/3717
