### ISSUE TITLE
🐛[BUG][Combat] Knight crabs @ KA can be zoned and depopped to instantly pop KA

### ISSUE THREAD

**Issue by Crotchbat** [HorizonFFXI/HorizonXI-Issues#1342]
**What does this bug affect?**
 You can aggro the Knight Crabs at KA and zone them. They will depop and count as killing them.

**Steps to Reproduce**
aggro and zone Knight Crabs 

**Expected behavior**
 Walking back to their spawn location after zoning

**Comment by TracentEden** [comment]
This should be fixed now.
