### ISSUE TITLE
🐛[BUG][System] Misareaux logging points are still bugged

### ISSUE THREAD

**Issue by bobthevicious** [HorizonFFXI/HorizonXI-Issues#1351]
I haven't seen it mentioned in the patch notes since the first attempted fix of the logging nodes when there was only four functioning nodes, so I'll presume they're still bugged.
The bottom rightmost set of logging points only has one functioning point, making logging in the zone very tedious.
Specifically the set in and around I-11.

**Comment by CriticalXI** [comment]
Working as intended, points are gathered directly from retail
