### ISSUE TITLE
🐛[BUG][System CRASH Zone by level syncing while having charmed pet]

### ISSUE THREAD

**Issue by SarithLekit** [HorizonFFXI/HorizonXI-Issues#1352]
Was watching Lynxaria's Twitch stream on April 1'st and she mentioned the zoned crashed when they level synced with a pet TWICE.  I went into zone, charmed a pet and level synced and zone immediately crashed so i verified it!!!

If you want to see proof watch Lynaxria's stream on April 1st around 2:10 ish mark.

**Comment by TracentEden** [comment]
This should now be fixed, thanks for reporting!
