### ISSUE TITLE
🐛[BUG][Mission] Snoll Tzar incorrect ability type

### ISSUE THREAD

**Issue by andeluvian** [HorizonFFXI/HorizonXI-Issues#1358]
**What does this bug affect?**
During chains of promathia 5-3 Ulmias path, we are supposed to fight the Snoll Tzar. The nm has a move called Hiemal Storm. This is supposed to be a breath attack with a frontal **CONE** , however this seems to be a regular AOE attack. This impacts the mission in a negative way because when a party stands behind the NM they can get 1 shot by this ability.

**Steps to Reproduce**
Go into the BCNM with the snoll tzar, set pets and summons or a paladin to attack and keep aggro.
Rest of the part can stand 10 - 15 yalms away **behind** the NM
When the NM does Hiemal Storm everyone standing behind the NM will also get hit by this move.

**Expected behavior**
This is a frontal cone attack so everything in front of the NM facing direction should take damage, standing behind the NM should not take damage.

**Screenshots**
![image](https://user-images.githubusercontent.com/13761269/229699748-45796051-eae0-41c6-8ac4-af9de4cbf531.png)
![image](https://user-images.githubusercontent.com/13761269/229699782-93362f3a-d265-4b0d-90a8-dc7c6d83bd34.png)
![image](https://user-images.githubusercontent.com/13761269/229699857-ab551d30-f6d5-43b0-b86e-96820ab9dbd9.png)

**Additional context**
If the NM does not use this ability the fight is winnable, however if this ability is an AOE the fight is near impossible to win because the AOE can kill anyone throwing salt at the NM.

**Comment by andeluvian** [comment]
If needed I have recordings of all attempts we made including the last attempt where the NM did not use the ability at all and resulted in a victory.

**Comment by SpaggiG** [comment]
https://www.youtube.com/watch?v=qOQSjoUe28M
A video here where it shows a drk pull hate, and is the only one getting hit with heimal storm in '06

**Comment by HorizonPotato** [comment]
This is still happening.  Just did the fight today, nearly caused a full wipe.   It did ~1k damage to everyone in an large AoE Radius.   Its brutal :\
