### ISSUE TITLE
Charm Bypasses Claimshield 

### ISSUE THREAD

**Issue by ahenry30** [HorizonFFXI/HorizonXI-Issues#1362]
Charming an NM with Claimshield appears to bypass the shield mechanic entirely.
All casts are interrupted and claim is immediately given to the charmer.
Also no message about your group winning or losing the claim

Example screenshot:
![image](https://user-images.githubusercontent.com/54108454/229912749-50fb9d14-c882-4e37-becb-3f1b084238c8.png)

**Comment by TracentEden** [comment]
@ahenry30 Who were the players in your group? What was the first action and when did it spawn? If the claim shield lottery ends before your cast lands it will be interrupted.

**Comment by ahenry30** [comment]
Hello @TracentEden,
Thanks for the Claim Shield explanation I think I was misunderstanding it.
NM actually spawned at 15:49:39  so the shield must have elapsed before the casts completed.

I dont have the logs to show first action, however Edicius was in my alliance (different pt)
I was generally confused because he got a message about losing the lottery, but I didn't get a message at all (I think due to being in a different party?)

But I do believe you've cleared up why the casts were interrupted, we were too slow!
