### ISSUE TITLE
🐛[BUG][/Combat] Day/Weather Magic Accuracy Bonuses Not Implemented

### ISSUE THREAD

**Issue by RenaviOnEden** [HorizonFFXI/HorizonXI-Issues#1363]
**What does this bug affect?**
Day/Weather bonuses for Magic Accuracy

**Steps to Reproduce**
Could test by casting on a monster with known values and expected resist rates without and then with Obi on correct day/weather.  Should see relevant boost in magic accuracy.  

**Expected behavior**
Day is +5 MACC
Weather is +5 MACC
Weather x2 would be +10 MACC

**Screenshots**
None unfortunately

**Setup Information**
30221103_1

**Additional context**
https://luteff11.livedoor.blog/archives/42385969.html - Day/Weather/Obi MACC Testing from JP source.

More info from Jimmayus when it was originally found:

**Jimmayus — 12/07/2022 10:47 AM
https://luteff11.livedoor.blog/archives/42385969.html
FF11赤ソロ小冊子
戯言シリーズ5　～天候とか虚誘とか発生率とか～ : FF11赤ソロ小冊子
こんにちは(･ω･)ノ戯言4では魔命特化の学とスキル特化の黒でウォーの門のミミズLV124にウォータ連打しました。結果は魔命特化の学に軍配が上がりました。今回はその時の結果をベースに、学者ならではの補足を行いました。■補足部分・天候有り（豪雨の陣&水輪の帯)でのウォ
戯言シリーズ5　～天候とか虚誘とか発生率とか～ : FF11赤ソロ小冊子
weather and day effects have a magic accuracy associated bonus
basically +5 for each, so double weather + day is +15 total
Casey — 12/07/2022 10:56 AM
is it always active?
Jimmayus — 12/07/2022 11:05 AM
apparently same proc rate as damage
Casey — 12/07/2022 11:08 AM
proc independent of the damage or at the same time?
Jimmayus — 12/07/2022 8:14 PM
independent apparently

**Comment by Frankie-hz** [comment]
The day/weather bonuses for palyers vs mob is indeed working correctly as shown by local prints. There was however an issue with mobs which was fixed here: https://github.com/AirSkyBoat/AirSkyBoat/pull/3252
