### ISSUE TITLE
[CRAFTING]Pirate's Gun recipe not enabled

### ISSUE THREAD

**Issue by Eskaer1** [HorizonFFXI/HorizonXI-Issues#1365]
item required for relic upgrade

Pirate's Gun:
Yield: Pirate's Gun x 1
    HQ 1: [Pirate's Gun +1] x 1
    [Fire Crystal]

        1 x [Steel Ingot]
        1 x [Darksteel Ingot]
        1 x [Turtle Shell]

**Comment by dallano** [comment]
I believe this is a ToAU synth recipe. Thank you for the report!
