### ISSUE TITLE
🐛[BUG] Dynamis - Beaucedine Issues

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#137]
**What does this bug affect?**
SMN's pet issues from other dynas present here. Using wrong astral flow moves and using carbuncle's rage / ward blood pacts (regardless of what avatar it is) when the SMN mob uses a TP move.

SMN & BST mobs can get stuck in the summoning animation and it does not summon a pet. When this happens the mob does not attack or use any spells and just stands there. Seems to happen more commonly when the SMN / BST mob starts to summon and then runs for whatever reason before the summoning is completed.

V.Mason uses the Yagudo Feather Shot animation instead of Ore Toss when it uses Eagle Eye Shot.

DRG NM D. Scalecrust from statue 40 used 2hr Call Wyvern, but no pet was summoned and the log stated he took 0 dmg from the ability. This seems to be possible on all DRG mobs.
![image](https://user-images.githubusercontent.com/112344508/192104559-9f6c2678-77fa-4647-8ed6-75a3b069256a.png)

Mega Boss - Angra Manyu: When it does it's warp mechanic to go to a different spot in it's "arena" it gets stuck in the warp animation becoming barely visible for a moment and then moving to a different area repeatedly. Unable to target / engage again after this happens.

**In the entries below AF is referring to the Relic AF**
These issues are in the top Vanguard area: Note when the mobs were summoned in the wrong gear they had no attack animations, but the attacks showed in the log.
Eye 107 summoned 2 H. Monks (which were Ahriman instead of Fomor) which used Manafont instead of Hundred Fist, and also casted BLM spells.
Eye 118 summoned a H. Thief which used Hundred Fist instead of Perfect Dodge.
H. Black Mage from eye 117 was wearing SMN AF instead of BLM AF.
Eye 116 summoned a H. Paladin which was in WHM AF instead of PLD AF. Also summoned H. Dragoon which was invisible and had the same Call Wyvern issue as described for Scalecrust above.
Eye 115 summoned a H.Ranger in WHM AF and a H.Warrior in SMN AF.
Eye 119 summoned a H.Red Mage in SMN AF and a H.Samurai in WHM AF.
Eye 113 summoned a H.Dark Knight in SMN AF.
Eye 108 summoned 2 H.Monk (which were Ahriman instead of Fomor) which used Manafont instead of Hundred Fist, and also casted BLM spells.
Eye 109 summoned a H.Thief in SMN AF, also used Hundred Fist instead of Perfect Dodge.
Eye 111 summoned a H.Beastmaster in SMN AF.
Eye 112 summoned a H.Warrior in RDM AF.
Eye 120 summoned a H.White Mage in SMN AF and a H.Summoner in BST AF.
Eye 121 summoned a H.Dragoon in RDM AF and had the same Call Wyvern issue as described for Scalecrust above.
**Eye 122 summoned a H. Black mage which gave a 15 min time ext when killed.**
**Eye 123 summoned a H.Dark Knight in BLM AF which gave a 15 min time ext when killed.**
**Eye 124 gave a 15 min time ext when killed, and summoned a H.Paladin in BLM AF.**
Eye 125 summoned a H.Bard in RDM AF.
**Eye 126 summoned a H.White Mage which gave a 15 min time ext when killed.**
Eye 127 summoned a H.Beastmaster in WAR (or DRK?) AF.
**Eye 128 summoned a H.Summoner in RDM AF (and a H.Paladin that was in correct gear) which gave a 15 min time ext when killed.**
**Eye 129 summoned a H.Bard in PLD gear which gave a 15 min time ext when killed**
**Eye 130 summoned a H.Ranger in PLD gear which gave a 15 min time ext when killed**
**Eye 131 summoned a H.Black Mage in PLD gear which gave a 15 min time ext when killed, and a H.Ninja in WAR gear.**
**Eye 133 summoned a H.Red Mage in PLD gear which gave a 15 min time ext when killed.**
Eye 134 summoned a H.Samurai in WAR gear.
**Eye 135 summoned a H.Dark Knight in PLD gear which gave a 15 min time ext when killed.**
**Eye 132 summoned 2 H.Monk (which were Ahriman instead of Fomor) which used Manafont instead of Hundred Fist, and also casted BLM spells. Also gave a 15 min time ext when killed.**
**Eye 137 summoned 2 H.Monk (which were Ahriman instead of Fomor) which used Manafont instead of Hundred Fist, and also casted BLM spells. Also gave a 15 min time ext when killed.**
**Eye 136 summoned a H.Thief which used Hundred Fist instead of Perfect dodge and gave a 15 min time ext when killed. Also summoned a H.Dragoon which had the same Call Wyvern issue as described for Scalecrust above.**
**Eye 138 summoned a H.Beastmaster in THF gear which gave a 15 min time ext when killed.**
**Eye 140 summoned a H.Black Mage in THF gear which gave a 15 min time ext when killed.**
**Eye 141 summoned a H. Summoner in THF gear which gave a 15 min time ext when killed.**
**Eye 142 summoned a H.Dragoon in THF gear (Call Wyvern actually worked for this one) which gave a 15 min time ext when killed.**
**Eye 143 summoned a H.Samurai in THF gear which gave a 15 min time ext when killed.**
**Eye 144 summoned a H.Ranger in THF gear which gave a 15 min time ext when killed.**
**Eye 145 summoned a H.Paladin in THF gear which gave a 15 min time ext when killed.**
**Eye 147 summoned a H.Red Mage which gave a 15 min time ext when killed (this was in addition to the 15 min time ext that the eye itself gave) and a H.Thief in WAR gear that used Hundred Fist instead of Perfect Dodge.**
**Eye 148 summoned a H.Bard in WAR gear and a H.Paladin in RDM AF which gave a 15 min time ext when killed.**
**Eye 149 summoned a H.Dragoon in RDM AF (call wyvern worked) which gave a 15 min time ext when killed.**
Eye 150 summoned a H.Bard in RDM AF.
**Eye 151 summoned a H.Black Mage in RDM AF which gave a 15 min time ext when killed.**
**Eye 152 summoned a H.Ninja in RDM AF which gave a 15 min time ext when killed.**
Eye 153 had no summons, not sure if intentional or not.
**Eye 154 summoned a H.Beastmaster in RDM AF which gave a 15 min time ext when killed.**
Eye 155 summoned a H.Summoner in RDM AF 
**Eye 156 summoned 2 H.Monk (which were Ahriman instead of Fomor) which used Manafont instead of Hundred Fist, and also casted BLM spells. Also gave a 15 min time ext when killed.**
Eye 157 summoned a H.Thief in DRG AF which used Hundred Fist instead of Perfect Dodge, a H.Red Mage in RNG AF, a H.White Mage in RDM AF, and a H.Ninja which was invisible. (H. Samurai was in SAM AF)

Attestation NMs:
Quiebitial: !getstats showed NM only had 5000 HP and 0 MP. NM used Soul Voice, but sang no songs. Only casted spells during Manafont. Did not use Benediction. (may have killed it too quickly)
Summoned 2 H.White Mage - one in RDM AF and the other in RNG AF, 2 H.Black Mage - one in SAM AF and the other in DRG AF, and 2 H.Bard, both of which had vermy cloak and brd pants, but one was missing their weapon.

Dagourmarche: !getstats showed NM only had 5000 HP and 0 MP. Used Call Wyvern and Astral Flow, but no BST pet / Familiar. (may have killed it too quickly) - Did not charm when any 2hr was used.
Summoned 2 H.Beastmaster - one in RDM AF the other in RNG AF, 2 H.Summoner - both in Vermy cloak / brd pants, and 2 H.Dragoon - one in DRG AF the other in SAM AF.

Goublefaupe: !getstats showed NM only had 5000 HP and 0 MP. NM used Invincible and Mighty Strikes and Chainspell.
Summoned 2 H.Warrior, 2 H.Red Mage, and 2 H.Paladin - all were in correct gear!

Mildauneguex: !getstats showed NM only had 5000 HP and 0 MP. Used Hundred Fist / Perfect Dodge / Mijin Gakure.
Only summoned a H.Monk, which was an ahriman instead of a Fomor and used BLM spells / Manafont. When the NM was killed, it summoned another H.Monk with the same model issue.

Velosareon: !getstats showed NM only had 5000 HP and 0 MP. Used Meikyo Shisui / Blood Weapon / Eagle Eye Shot.
Summoned 2 H.Ranger, 2 H.Samurai, and 2 H.Dark Knight - all in correct gear.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/192107966-d80bb98a-b19b-4065-8082-1d91eb9b3894.png)

**Setup Information**
Version 30220906_0

**Comment by Frankie-hz** [comment]
> Eyes 138 / 139 / 140 were up prior to eye 147 being killed.
I believe we have it correct. In order to spawn 147, 138-140 need to be killed.
![image](https://user-images.githubusercontent.com/105882754/192116169-1e15eedf-a451-4ec8-ad6c-5a21f86f2c4c.png)

**Comment by Squinkerdoodle** [comment]
Yea, i see it now -.- I had a brain fart and read it backwards

**Comment by Squinkerdoodle** [comment]
Retested recent fixes. New github submitted.
