### ISSUE TITLE
🐛[BUG][NPC]

### ISSUE THREAD

**Issue by hienlongli** [HorizonFFXI/HorizonXI-Issues#1370]
**What does this bug affect?**
Dynamis-Bastok has not dropped an Ito in the last two runs that we've full cleared. I have reached out to a few other linkshells and they have also mentioned not seeing an Ito. 

**Steps to Reproduce**
-Enter Dynamis-Bastok
-Treasure Hunt Mobs
-Kill Mobs
-See if Ito drops

**Expected behavior**
I believe an Ito should've dropped by now even with the variable RNG as we've seen 15+ of every other relic weapon in Dynamis-Bastok between our two full clears.

**Screenshots**
N/A

**Setup Information**
V1.1.4

**Comment by setsuk0** [comment]
forgot to add a title to your bug report!

**Comment by TracentEden** [comment]
Fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2979
