### ISSUE TITLE
Combat Bug - Utsusemi w/ Slow

### ISSUE THREAD

**Issue by cubbypanda** [HorizonFFXI/HorizonXI-Issues#1375]
**What does this bug affect?**

Whenever a ninja or ninja subjob is afflicted with slow, the recast timer actually shortens. For example, Utsusemi: Ichi has a recast of 45 seconds when not slowed. When slowed, it's 43 seconds. I believe the slow timer is based off of the original recast time of 30 seconds instead of the 45 that is on the Horizon Server.
**Steps to Reproduce**

Get affected with slow and then cast Utsusemi and look at recast timer.
**Expected behavior**

Recast should be higher than the original recast timer after being slowed.
**Screenshots**

**Setup Information**

**Additional context**

**Comment by Shayemz** [comment]
I did not have this experience. I was slowed by a Bark Spider in The Boyahda Tree and even with some Haste gear, my recast timer went to 1:02. 

Perhaps you had a weak slow on you with enough haste gear?

**Comment by CriticalXI** [comment]
Cannot reproduce this. Doesn't appear to be an issue.
