### ISSUE TITLE
🐛[BUG][Crafting] Rainbow Cape desynth

### ISSUE THREAD

**Issue by WarAurochs** [HorizonFFXI/HorizonXI-Issues#1391]
**What does this bug affect?**
When performing a desynthesis on Rainbow Capes, the quantity of Rainbow Thread returned is not correct.  

**Steps to Reproduce**
Successfully desynth a Rainbow Cape

**Expected behavior**
Results per current era should be as follows:

Result: 3x Rainbow Thread
HQ #1: 4x Rainbow Thread
HQ #2: 5x Rainbow Thread
HQ #3: 6x Rainbow Thread

What I received assuming my one HQ result was only tier 1:

Result: 2x Rainbow Thread
HQ #1: 3x Rainbow Thread
HQ #2: ???
HQ #3: ???

**Screenshots**
![image](https://user-images.githubusercontent.com/130323304/230803717-0f3dd57b-625b-4e45-a5bd-fe829fde3316.png)

**Setup Information**
30221103_1

Earliest notation of this on wiki: https://ffxiclopedia.fandom.com/wiki/Rainbow_Cape?direction=next&oldid=88872

**Comment by dallano** [comment]
era desynth rates are as follows: https://ffxiclopedia.fandom.com/wiki/Rainbow_Cape?oldid=322205
It seems in 2009 it was increased. But thank you for the report all the same!
