### ISSUE TITLE
🐛[BUG][NPC]Ancient Goobbue spawning outside map

### ISSUE THREAD

**Issue by benvaun** [HorizonFFXI/HorizonXI-Issues#1394]
**What does this bug affect?**
Ancient Goobbue, an NM in The Boyahda Tree, is not spawning in his proper location, and is instead spawning outside the map.

**Steps to Reproduce**
N/A

**Expected behavior**
His expected spawn should be around [E-10]., but he is spawning far to the east of that location

**Comment by TracentEden** [comment]
This was fixed in an update a while ago
