### ISSUE TITLE
🐛[BUG][System] Mog Wardrobe Not Unlocking

### ISSUE THREAD

**Issue by JilboBenkins** [HorizonFFXI/HorizonXI-Issues#1395]
**What does this bug affect?**

Its a bug with the inventory system I think in which the Wardrobe option that lets you store armor and weapons did not expand after reaching certain milestones
**Steps to Reproduce**

I think it had something to do with me sending items maybe? It's the only event I remember bugging out before hand
 - Sent items from main to new alt character (specifically a Centurion's Axe)
 - Main character had the Wardrobe slots unlocked
 - Never received item for alt character
 - Before sending item, I had 5 slots from doing subjob quests, afterwards I couldn't receive any more Wardrobe slots
 Though I also installed the game on a different drive then my C drive if that makes a difference
**Expected behavior**

I was told in linkshell I was supposed to get up to 15 slots from doing both "Acquire Advanced Job" and "Complete Rank 3 Mission for your nation" but I didn't get neither
**Screenshots**

**Setup Information**

I'm running the current patch I believe, the March 17th one, Version 1
**Additional context**

![Fordtough_2023 04 10_180705](https://user-images.githubusercontent.com/130409671/231010297-ec1b0eed-d716-425a-8843-c0d750916250.png)
![Fordtough_2023 04 10_181255](https://user-images.githubusercontent.com/130409671/231010304-18ece144-e70b-406e-8a95-0e98bb7ba24f.png)

**Comment by CriticalXI** [comment]
Should be working properly now but please feel free to re-open if still experiencing this.
