### ISSUE TITLE
🐛[BUG][NPC/Combat] Dynamis Xarcabard various issues

### ISSUE THREAD

**Issue by setsuk0** [HorizonFFXI/HorizonXI-Issues#1398]
I apologize for the clutter. I did not want to make a bunch of different bug reports for these. My LS ran Xarc Saturday and I noted the following issues:

Dynamis Xarc bugs
1.	382, 233, 454 TEs are missing (known issue by GMs)
2.	358 seems to be missing or possibly in a different location. It was not there at all during our run. 
3.	Marquis Orias is currently able to be silenced. Old crap quality dyna xarc videos show Orias not being silenced, but I am not sure if this was due to gear or not. NMs overall may need possible audit on abilities/resists.
4.	Nebiros avatar is sleepable on Horizon. It should not be able to be slept. 
5.	NM eyes do not link on Horizon. Specifically, I’m referring to the eyes that spawn the demon NMs. Since they do not link, it is possible to simply pull one at a time without fear of getting the other eyes and demon NMs. I’m guessing this is similar to my Beaucedine bug report where I noted that all of the eyes near the Hydra will not link at all even if they path in front of other eyes. 
6.	Vanguard dragons are sleepable and should not be.
7.	Vanguard dragons do not drop anything. These should have a high drop rate on necropsyches and a small chance to drop a hundred piece. We killed most in the zone and saw zero drops. This could have been bad luck, but I have never seen vanguard dragons killed without at least the necropsyches dropping.
8.	Ying/Yang will deaggro while being pulled and will start pathing back to their spot.
9.	Ying/Yang can be slept. They should not be sleepable.
10.	Ying/Yang are sleepable on the DL fight. Not sure if intended here either.

I have a full video if this is helpful at all, can dm me and request certain parts to clip if this is needed. 

I am referencing the following map for the statue numbers--
![dyna xarc](https://user-images.githubusercontent.com/48462732/231096274-968b6bee-5da9-4878-bd57-bcef0d131c02.jpg)

**Comment by bliven-was-taken** [comment]
Point 4 is incorrect. 
https://youtu.be/lLbNh-0p0_E?t=456
This video shows horde having no effect on the avatar because the avatar is already asleep.
