### ISSUE TITLE
🐛[BUG][System/Combat] Killing Nightmare Fly in Dynamis-Valkurm Causes Zone Crash + Final Boss Has Wrong Model

### ISSUE THREAD

**Issue by KiplingFFXI** [HorizonFFXI/HorizonXI-Issues#1405]
**What does this bug affect?**

When you kill a nightmare fly in Dynamis-Valkurm it seems to crash the zone.

**Steps to Reproduce**

1. Enter Dynamis-Valkurm
2. Kill Nightmare Fly to unlock subjobs
3. The zone crashes

1. Final Boss has an Orc Model instead of a Marlboro

**Expected behavior**

The zone should not be crashing and the boss should look like a Marlboro and not an orc.

**Screenshots**

N/A

**Setup Information**

N/A

**Additional context**

N/A

**Comment by TracentEden** [comment]
I think the zone crash issue might be due to invalid cleanup that was recently fixed. The boss model should be fixed now by the linked PR.
