### ISSUE TITLE
🐛[BUG][NPC/] King Behemoth doesnt drop Behemoth Horn

### ISSUE THREAD

**Issue by TristtHXI** [HorizonFFXI/HorizonXI-Issues#1408]
Seems the item doesnt appear in kbs loot pool on ASB, fairly sure it hasnt been added on HXI either.

pls gib horn

**Comment by TracentEden** [comment]
This was fixed in a recent PR.

**Comment by TristtHXI** [comment]
> This was fixed in a recent PR.

Any word on this been pushed to live soon?
