### ISSUE TITLE
🐛[BUG][NPC] Loot tables for Gigas Upper Defaulks tower

### ISSUE THREAD

**Issue by PrinceOfParallax** [HorizonFFXI/HorizonXI-Issues#1411]
**What does this bug affect?**
I think their tables is empty based on what i am seeing and have tested.

**Steps to Reproduce**

**Expected behavior**
Loot tables should be populated.

**Screenshots**

**Setup Information**

**Additional context**

**Comment by hookstar** [comment]
Could you provide some more amplifying info, such as which ones? Is it all of them?

**Comment by PrinceOfParallax** [comment]
I believe its just the Gigas that are not NMs, 
example
Gigas Stonemason isn't dropping Gigas necklace or Gigas socks.

**Comment by hookstar** [comment]
Ok I'll take a look but I think it's just a really low drop rate the tables look correct -
