### ISSUE TITLE
🐛[BUG][Combat] Gravity not working properly again

### ISSUE THREAD

**Issue by heresyourpizza** [HorizonFFXI/HorizonXI-Issues#1415]
**What does this bug affect?**

Gravity is no longer working again. Monsters with the weight debuff applied move at or at most a couple percent slower than player movement speed.
**Steps to Reproduce**

Cast Gravity on any monster with normal movement speed and attempt to kite it.
**Expected behavior**

Should be a 26% movement speed slow, I believe this is already known though as it was working properly prior to April 7th as reported by Emeric on the discord.
**Screenshots**

**Setup Information**

**Additional context**

**Comment by TracentEden** [comment]
This was fixed by a recent PR.
