### ISSUE TITLE
🐛[BUG][Quest] A Squire's Test is bugged and won't accept revival root (post 1.1 patch)

### ISSUE THREAD

**Issue by DuskLove** [HorizonFFXI/HorizonXI-Issues#1417]
**What does this bug affect?**

A Squire's Test is bugged, npc doesn't accept the revival tree root.
**Steps to Reproduce**

accept the quest from Balasiel

**Expected behavior**

accept my damn root so i can eventually unlock PLD ;(

**Screenshots**

**Setup Information**

**Additional context**

waited for several ig days, zoned, nada.

**Comment by DuskLove** [comment]
also forgot to mention meeting multiple people also unable to complete the quest by the npc.

**Comment by xtremenerdrage** [comment]
Also having this issue - Tried zoning and logging and he will not accept the trade for the root.

**Comment by hookstar** [comment]
Found and updated both issues. Please reach out to a GM and let them know if you are on A squires test and they will run the command I provided them to get you back on path. Sorry for any inconvenience!
