### ISSUE TITLE
Albatross Ring buff removing whenever boats dock/ zoning (7 minute boat ride)

### ISSUE THREAD

**Issue by Wookienip** [HorizonFFXI/HorizonXI-Issues#1423]
**What does this bug affect?**
 It makes the Albatross Ring useless in trying to assist with fishing the types of fish it was created for (Gugrusaurus) because you have to wait 30 seconds after the boat ride starts to be able to use it, and 6.5 minutes later the buff disappears when we dock at the next stop on the 'Islands Tour'.  You then have a 13+minute CD to use it again because the ring's buff is supposed to last you 20 minutes and persist through zoning.

**Steps to Reproduce**
 Use Albatross Ring, change zones/stay on boat until it docks somewhere.  Use ring before boat takes off, once cutscene ends, buff gone. 

**Expected behavior**
  The buff should persist for 20 straight minutes.

**Screenshots**
![ring1](https://user-images.githubusercontent.com/130799718/232229526-85c4dce9-c46a-4364-81f8-22101aa9ac67.PNG)
![ring2](https://user-images.githubusercontent.com/130799718/232229528-2a43b21a-5b15-47e6-9960-0b496f503c8f.PNG)
![ring3](https://user-images.githubusercontent.com/130799718/232229530-27328009-ff49-4766-8aea-0a5828d5f06a.PNG)
![ring4](https://user-images.githubusercontent.com/130799718/232229532-74822d90-c177-45bb-a0af-0aa08029d32f.PNG)

**Additional context**
 The albatross ring was working as normal until the 1.1 Patch.

**Comment by TracentEden** [comment]
@Wookienip Are you sure it is suppose to last through zoning? Wiki for example says it does not https://ffxiclopedia.fandom.com/wiki/Albatross_Ring

**Comment by TracentEden** [comment]
@Wookienip I think SE original intent was to be used on the selbina ferry which is about 20 mins. If you are suggesting an era+ change so it does not wear when zoning you can post in the suggestions section of the discord.
