### ISSUE TITLE
🐛[BUG][Mission] San d'Oria Mission 9-2 First Half is Overtuned - Trash Orcs HP is Far too High

### ISSUE THREAD

**Issue by Shayemz** [HorizonFFXI/HorizonXI-Issues#1432]
**What does this bug affect?**
San d'Oria Misison 9-2 The Heir to the Light trash orcs HPs are far too high. They have as much HP as the NMs in the BCNM making this first half incredibly difficult to manage and complete.

![image](https://user-images.githubusercontent.com/120886485/232338762-c70e43ab-d2c2-4096-9420-b52c29abf274.png)
^These guys are the ones with their HP being set far too high, and who I am referencing as the trash orcs.

**Steps to Reproduce**
Enter the BCNM for Sandy's 9-2 Mission and attempt to kill the trash orcs and see how high their HP is. They take the whole pt to kill each and makes the volume of mobs very difficult to manage without skilled players. The volume of mobs is as high as they are due to how easily these guys were supposed to die.

**Expected behavior**
These orcs should be dying very quickly, easily to 1 WS where 1 person can each solo one quickly. 

**Screenshots**
None available.

**Setup Information**
30221103_1

**Additional context**
Please see this video of 75s easily destroying the trash orcs: https://www.youtube.com/watch?v=V61SD07VrGg

**Comment by dallano** [comment]
linked video might not be sufficient. it was taken in 2010 which is from abyssea area iirc.

**Comment by Shayemz** [comment]
The video is from 2009. Abyssea released in September of 2010.

![image](https://user-images.githubusercontent.com/120886485/233214363-51f805d8-1327-4526-a9b3-4e336f97c67f.png)

**Comment by dallano** [comment]
Either way, Horizon is currently CoP era (2006). I will keep an eye out for earlier captures for some heavy evidence.
