### ISSUE TITLE
Bonecrafting synthesis recipe is not producing a pearl

### ISSUE THREAD

**Issue by Tanaleeff** [HorizonFFXI/HorizonXI-Issues#1440]
Synthesys
**What does this bug affect?**
Cost of the synthsis materials vs the item produced

**Steps to Reproduce**
Wind Crystal and a Shell Shall 

**Expected behavior**
Pearl

**Screenshots**

**Setup Information**

**Additional context**

**Comment by Tanaleeff** [comment]
I am using a Shell Shall and a wind crystal and it is producing a pebble instead of a pearl.  I am trying to skill up and the cost of the shell shall is expensive.  To produce a pebble instead of getting my skill up is not acceptable

**Comment by CriticalXI** [comment]
We are using the in-era recipe as listd here: https://ffxiclopedia.fandom.com/wiki/Pearl?oldid=144833
