### ISSUE TITLE
🐛[BUG]Crafting (Missing Desynth)

### ISSUE THREAD

**Issue by drixel** [HorizonFFXI/HorizonXI-Issues#1448]
**What does this bug affect?**
Unable to desynth Bracers

**Steps to Reproduce**
lightning crystal + bracers

**Expected behavior**
[Clothcraft](https://ffxiclopedia.fandom.com/wiki/Category:Clothcraft) (25[/36](https://ffxiclopedia.fandom.com/wiki/Crafting_Skill_Ups))

Yield: [Saruta Cotton](https://ffxiclopedia.fandom.com/wiki/Saruta_Cotton) x 2
HQ 1: [Linen Thread](https://ffxiclopedia.fandom.com/wiki/Linen_Thread) x 5
HQ 2: [Linen Thread](https://ffxiclopedia.fandom.com/wiki/Linen_Thread) x 6
HQ 3: [Linen Thread](https://ffxiclopedia.fandom.com/wiki/Linen_Thread) x 7

**Comment by dallano** [comment]
According to ffxiclopedia, I can only find history of a desynthesis recipe until 2014. Nothing prior. Are you able to find anywhere with evidence of this recipe existing in era?

**Comment by drixel** [comment]
that's my bad then, didn't realize those low crafts didn't all come with the desynth recipe at the same time. ty for your time. i really do appreciate all the work you guys are doing

**Comment by dallano** [comment]
Of course! And I always appreciate bug reports. Whether they turn out truly as bugs or not. It's always great to have people doing their best to help Horizon be as healthy as possible!
