### ISSUE TITLE
🐛[BUG][NPC/Quest/Mission/System/Combat/Launcher/]

### ISSUE THREAD

**Issue by whateverW3** [HorizonFFXI/HorizonXI-Issues#1456]
Launcher
**What does this bug affect?**

When logging into new characters after the deletion of previous mules, receiving error POL-0001 on the two new characters. 
**Steps to Reproduce**

1. Delete two Character(s)
2. Create two new mules with same names as deleted characters. 
3. Send items/money to new mule from main account.
4. Attempt to log in on the new character.
5. ERROR POL-0001

**Expected behavior**

Logging in to character.

**Screenshots**

**Setup Information**
w
Windows 10

**Additional context**

I’ve done this before the only difference this time is i sent items to one of the mules before ever attempting to log in to it… don’t know why that’d matter though.

**Comment by CriticalXI** [comment]
There is a solution for this issue in the announcements on Discord. Please check there for the fix.
