### ISSUE TITLE
🐛[BUG][Combat] Winds Thrown at Gods not Working anymore since new patch

### ISSUE THREAD

**Issue by BrisketXI** [HorizonFFXI/HorizonXI-Issues#1457]
When Throwing Winds at Gods no longer permanently Dispels their EN effects, this has been a issue since the newest patch that came out. Possibly having to do with the fix to Mother Globe as well.

**Comment by Butsuon** [comment]
I can confirm this bug is still active at the time of this comment. The thrown weapons do nothing.
