### ISSUE TITLE
🐛[BUG] Dynamis - Buburimu Issues

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#147]
**What does this bug affect?**
Able to sleep dragon NMs (including the mega boss Apoc. Beast) easily with sleep magic, not sure if they should be immune or highly resistant or not.

Dragon NM Koschei does not use it's TP move Thornsong, even when fed 3000 TP and only follows you around until you kill it.
Dragon NM Stollenwurm does not use it's TP move Lodesong, even when fed 3000 TP and only follows you around until you kill it.
Dragon NM Aitvaras does not use it's TP move Voidsong, even when fed 3000 TP and only follows you around until you kill it.

Orc RNG NM (Lyncean Juwgneg) missing from statue 011.
Goblin RDM NM (Gosspix Blabberlips) missing from statue 015.

If you engage the Apoc. Beast before killing any dragon NMs or beastman NMs it does not use any 2hrs or TP moves. It should be using the 2hrs of any unkilled beastmant NMs and the TP moves of any unkilled dragon NMs.

**Setup Information**
Version 30220906_0

**Additional context**
On my full clear test run the Apoc beast did not use any TP moves with all dragon NMs killed, or use any 2hrs of the beastmen NMs that were killed (even the RNG / RDM 2hrs from the missing NMs).
On my second run I entered and ran right to the Apoc Beast to test it, and without killing any other NM in the zone it would still not use any 2hr or TP move and would only auto attack until killed.

**Comment by Frankie-hz** [comment]
RNG and RDM NMs fixed with: https://github.com/AirSkyBoat/AirSkyBoat/pull/444

**Comment by OpheliaXI** [comment]
Sleep issue is due to a bug with onSpawn at the moment, will be fixed as soon as the bug is fixed.
