### ISSUE TITLE
🐛[BUG] Omega Pod Ejection

### ISSUE THREAD

**Issue by shinjiku2008** [HorizonFFXI/HorizonXI-Issues#1471]
**What does this bug affect?**
Omega will still not eject a pod if the person with hate is out of range.

**Steps to Reproduce**
Pod ejection is every 5min. Step out of range during that time.

**Expected behavior**
Omega should target himself during this time so he will always spawn a pod.

`https://pasteboard.co/fOY9wx2MRpdj.png`

**Comment by TracentEden** [comment]
Fixed in recent PR.
