### ISSUE TITLE
Error code POL 0001

### ISSUE THREAD

**Issue by inquirer101** [HorizonFFXI/HorizonXI-Issues#1473]
i am unable to get the hash tag Unknown link on hotizonx1 discord and i need access to read notes on how to solve error code pol 0001 so that i can log my third toon.

**Comment by Tybohurley** [comment]
I have the same issue.

**Comment by BristolMD** [comment]
I also have this issue. Newly installed client and my first character.

**Comment by Lockepick** [comment]
Same issue, pol-0001, cannot log in. New character to Horizon.
FFXI was installed and updated before installing horizon loader if that helps pinpoint any issues.
Have been playing on NS through Ashita.

**Comment by BristolMD** [comment]
> Same issue, pol-0001, cannot log in. New character to Horizon. FFXI was installed and updated before installing horizon loader if that helps pinpoint any issues. Have been playing on NS through Ashita.

Got it working. Just need to drag and drop a new bootloader into the install directory:

1. Go to the HorizonXI discord channel and accept the rules to unlock the chats.
2. Sear for POL-0001 in the 'announcementa' channel and click the link which Aarec has provided.
3. Follow the fix instructions from there.

Hope it works for you!

**Comment by SublimeLEV** [comment]
Has anyone had issues with party member list after correcting this issue?

**Comment by Oxiide** [comment]
> 

Yes, party member list not working as well as level sync

**Comment by CriticalXI** [comment]
Party list has been fixed with today's patch

**Comment by Gokusanchez** [comment]
Can anyone post the link to the instructions on a potential fix for this? in checking the official discord, the link was removed and supposedly patched. Not sure if something messed up in the install? im getting this error even after deleting and doing a fresh install. Haven't played before.
