### ISSUE TITLE
🐛[BUG][Combat]Vouivre has incorrect Gil drop values / Mug Values

### ISSUE THREAD

**Issue by HorizonPotato** [HorizonFFXI/HorizonXI-Issues#1476]
**What does this bug affect?**
The Notorious Monster, "Viouvre", in Ifrit's Cauldron. 

**Steps to Reproduce**
1) Mug/Kill NM
2) Mug for ~12 gil.  Drops ~70 gil.

**Expected behavior**
Vouivre drops 18,000 Gil without Gilfinder. 
Mug should be around 1k~3k but that information is less reliable due to the nature of mug.

**Screenshots**
I did not take a Screenshot of my kill this time, sorry, but should be easy to view on a test environment. 
However here is a Video from 2009 which shows 9,000 gil with 2 people, neither have Gilfinder -- https://www.youtube.com/watch?v=sUH5REKLJ-w

**Setup Information**
Current

**Additional context**
There are several NMs who have incorrect gil Values in Horizon, for both drop and mug, I'm just trying to document as many as I can... because frankly mug is already the most useless ability in the game, it should at least properly work on the few NMs it has value on. 

I know 2009 isn't the era we are in, but I've checked every patch note from 2006 to 2010 on the Official FFXI website and there are no mentions of any NMs getting their gil values increased.  18,000 Gil for Vouivre should be era-accurate.

**Comment by dallano** [comment]
I've seen this crop up in multiple areas. Many NMs (until WoTG) dropped very little if no gil at all. However in 2009 there is a multitude of NMs that begin reporting thousands in gil. As this issue and gil drop report repeatedly crops up in 2009, it can only be deduced that some patch in 2009 introduced gil drops to NMs.

Your report is greatly appreciated, and I encourage you to continue reporting anything you think to be a bug.

**Comment by HorizonPotato** [comment]
https://ffxi.allakhazam.com/db/bestiary.html?fmob=1628&p=2#comments

Theres a post a the bottom of this page from July 2004 labeled "Free Money" that mentiones Viouvre's Mug value. As Mug values are related to Gil drop from NMs and this is something we have documented, its strongly believe the lack of information on Gil Drops and mug values of these NMs is more likely a result of simply poor record keeping and data on Old wikis, and not that the gil pool was unused until some point in the future. 

You don't have to take my word for it, but after you mentioned this I've personally dug through every single patch note between 2006 and 2010(BG Wiki Patch Note history links to Official notes on their website) and there is no information or evidence that any Notorious monsters had their drop pools adjusted, gil or otherwise, aside from a mention in 2007 of Siren's Hair being removed from some, and a few peeps about Besieged NMs.

**Comment by dallano** [comment]
So I have definitely been in the same boat as you. Where there is evidence there that these values to be correct in that they should be era, but we as developers have to maintain a high level of quality of proof. Simple comments from blogs (which I've tried to use as evidence myself in the past) aren't strong enough to make permanent game changing effects to the server.

The best evidence, time and time again, is video evidence of killing the mob in era. If you can find a youtube video of someone killing it in CoP era with logs showing gil dropping, then it's sure fire evidence we can use to put this in the game!

**Comment by HorizonPotato** [comment]
I appreciate that you can understand where I'm coming from here.  I personally feel silly arguing over about 20k gil and putting this much time into researching it, but I know I'm right, and I'd like Era-Accurate to actually be Accurate.  But yah, I couldn't find a video, and I REALLY tried.  As previously stated the oldest video I could find of Vouivre was from ~2009. 

I found a video of Guivre from 2006 but thats the wrong Wyvern.  Side note, Guivre drops a large sum of gil.  If I ever kill him and find him dropping 70 gil you'll bet your butt I'll be posting that video I dug up from 2006 here :P

I know I'm a broken record right now, but dang, when you take in all the evidence we have now, being "No official records of change from Square Enix FFXI Patch notes in ~23 years", "sporadic and incomplete records from early days", "Multiple gil-dropping NMs having their gil added to their records at random times in XI's history on non-official sources", and further "Video Evidence showing Gil drops not corroborated with era-record keeping",  it just seems like we have enough evidence to conclude "They drop gil until we're proven otherwise".

Theres a fine line between healthy, necessary skepticism to ensure accurate information and "Ignore the mountain of evidence in front of me leading to one very obvious conclusion.".  But at the end of the day I understand these are your standards and theres probably nothing I can say to get you guys to put in a buttload of man-hours to change values that amount to not much more than "consolation prizes" lol.

I would like to point out there are several NMs I've fought who do in fact have their correct gil drop values, It'd be less jarring to find inaccurate ones if I didn't know at least someone out there is ensuring accuracy on a few of them :|
