### ISSUE TITLE
🐛[BUG][System/Combat/]

### ISSUE THREAD

**Issue by Hwaorong** [HorizonFFXI/HorizonXI-Issues#1479]
**What does this bug affect?**

The respawn of Zircon Quadav in Beadeux F-11. This is the place holder for Zo'Khu Blackcloud. The Quadavs respawn timer seems to be out of sync or sometimes just doesnt respawn for 40 minutes. I checked around the zone to make sure the NM hadnt spawned yet somewhere else and couldnt find it. It makes it very hard to figure out if its on cooldown or just acting up

**Steps to Reproduce**

I only have to kill the place holder a couple of times in a row before it seems to happen again
**Expected behavior**

around a 17 minute respawn timer on the Zircon Quadav and if this is the true PH then eventually the Notorious Monster should spawn
**Screenshots**

**Setup Information**

latest version is 1.1 
**Additional context**

**Comment by dallano** [comment]
Thank you for your report! I'll look into this.

**Comment by dallano** [comment]
Unfortunately I'm unable to reproduce. Mobs respawned in 17 minutes. We'll leave this open if the issue persists
