### ISSUE TITLE
🐛[BUG][NPC] Storms of Fate battlefield entry issue

### ISSUE THREAD

**Issue by ThoseWhoFight** [HorizonFFXI/HorizonXI-Issues#1481]
**What does this bug affect?**
Unable to enter battlefield despite every member having access to fight, we all get battlefield status properly but it just spits out a generic "this is a portal" dialogue. We circumvented this and were able to enter by having everyone preload/open the "enter fight: Storms of Fate" menu box and having one person enter, so everyone gets battlefield status and then everyone can select to enter afterward.

**Comment by TracentEden** [comment]
I was not able to replicate this issue, can reopen if it happen again, thanks for reporting!
