### ISSUE TITLE
🐛[BUG][Quu Domi the Gallant spawn time]

### ISSUE THREAD

**Issue by BigDaveRitchie** [HorizonFFXI/HorizonXI-Issues#1485]
**What does this bug affect?**

I've seen way too many time this NM take 9-10 hours to spawn for it to be just a coincidence. Mee Deggi usually spawn several times before Quu does. He seems to get locked on very long spawns much more than Mee Deggi.

**Steps to Reproduce**

Impossible to reproduce. Only empirical tests and hunch.

**Expected behavior**

He should have similar spawn times as Mee Deggi the Punisher

**Screenshots**

**Setup Information**

**Additional context**

I've had people tell me this before I started camping it. I brushed it off at first, because I thought it was just RNG. But I've just had 2x 10 hours spawn time week-end, which should be very unlikely. I've talked to more regular campers and I'm not alone there seems to be an issue with this NM. Could it be looked into to see if the parameters are right?

Thank you

**Comment by dallano** [comment]
Thank you for the formal bug report. I'll try and see what's going on

**Comment by dallano** [comment]
The code seems to be identical to other NMs that have similar behaviors and working as intended.
 
I'm never one to chalk it out to "bad luck sorry", so I'm happy to leave this ticket open for any further feedback from the community.

**Comment by BigDaveRitchie** [comment]
hmm..., thank you for checking it out!
