### ISSUE TITLE
🐛[BUG][Combat]

### ISSUE THREAD

**Issue by Sundrix** [HorizonFFXI/HorizonXI-Issues#1487]
**What does this bug affect?**
Diabolos' Blood Pact: Rage Nether Blast is (presumably) being treated as a spell, and is subject to getting half and quarter resisted. This blood pact is a special snowflake ability and is supposed to deal a fixed amount of damage (although there are corner cases that can change that fixed amount of dmg, like magic burst, MAB bonus, and the target having MDB bonus)

**Steps to Reproduce**
Activate Rage: Nether Blast on stuff of appropriate level, is particularly trivial to see this happening on higher level mobs (like Ground King HNMs, Sky Gods, Grand Wyrms etc.)

**Expected behavior**
Nether Blast is supposed to deal a fixed amount of damage (although there are corner cases that can change that fixed amount of dmg, like magic burst, MAB bonus, and the target having MDB bonus)

**Screenshots**
https://cdn.discordapp.com/attachments/1061420232465469530/1100087661856837663/image.png
https://cdn.discordapp.com/attachments/1061420232465469530/1100087684417998928/image.png

**Setup Information**
we playing on the horizon FFXI video game box

**Additional context**
this bug makes me sad inside

**Comment by CriticalXI** [comment]
Fixed in today's patch
