### ISSUE TITLE
🐛[BUG][Mission] Sandy 9-2 "The Heir To The Light" Phase 2 Trion Army

### ISSUE THREAD

**Issue by Shugsucks** [HorizonFFXI/HorizonXI-Issues#1490]
We were assisted by 4 additional copies of Prince Trion during phase 2 of this fight. They all spawned in stacked on top of each other and chose random targets.

**What does this bug affect?**
The 2nd half of this mission is incredibly easy because of this.
**Steps to Reproduce**
Just repeat the Sandy 9-2 Fei'yin fight.
**Expected behavior**
You're supposed to be assisted by Prince Trion, not an entire army of Prince Trion.

**Comment by dallano** [comment]
Did there happen to also be 4 of you doing this fight? I think it might be calling once for each player.

**Comment by Shugsucks** [comment]
We actually had a full party.

**Comment by Shugsucks** [comment]
There may have even been 6 to be honest between all the sheep and orcs and trions running around I'm not sure.

**Comment by Shayemz** [comment]
This also happened to us, I believe we had 3? I have a screenshot on #398 - We also had a full party when we did this mission.

**Comment by dallano** [comment]
yeah I saw your bug report just now @Shayemz. I'll try and figure out what's going on
