### ISSUE TITLE
🐛[BUG][Combat] A l'Outrance additional effect issues

### ISSUE THREAD

**Issue by brianschroeder1** [HorizonFFXI/HorizonXI-Issues#1491]
**What does this bug affect?**
A l'Outrance is intended to have an additional effect of extra dark damage against Beast-type enemies with a 100% occurrence. However, after testing this against multiple beast types (Coeurl, Dhalmels, Manticores, Rabbits, Tigers), this effect appears to have a lower proc rate. If this is intended, it's a significant nerf to a relatively niche Scythe.  Based on early testing I would estimate it's currently ~10% (or lower) proc rate.

**Steps to Reproduce**
Equip scythe, auto attack beasts.

**Expected behavior**
100% proc

**Screenshots**
![image](https://user-images.githubusercontent.com/23159460/234110762-006d6fcd-f344-48ad-8cdd-329ffe021157.png)

**Setup Information**
most recent as of 24APR2023

**Additional context**

**Comment by dallano** [comment]
Hey, bud! If you're able to help us find ample evidence of this scythe being 100% proc rate against beasts, I'll be happy to make the change. The wiki's "always active against beasts" feels a little vague - especially when making definitive changes based from this. 
It could always be active against beasts, but have even a 50% proc rate.

**Comment by brianschroeder1** [comment]
Hello,

This is outlined from user experience shown in the alakazham wiki comments.
https://ffxi.allakhazam.com/db/item.html?fitem=3733


User: __DEL__1591816499577 on may 2005 stated:


Sage
[image: *][image: *][image: *]
1,192 posts
I was mostly getting this to have a Rare/Ex scythe my level, and in case I
ever took my Bst to these heights. I'm a lvl 65 Drk, with a TON of Acc+
equips (Woodsman Rings, Life Belt, Assault Earring, etc..) And I didn't
think I would use this over my Vassago's, but after equipping it and trying
it out I might be wrong. In Xp parties I tend to sub Samurai (of course I
have thf sub if they request it...) so a 480 delay is very nice because
overall I will hit more often and accumulate TP faster. The interesting
thing I noticed is that my Dmg vs. XP mobs is nearly identical to the dmg I
was doing with Vassago's despite the Dmg on this weapon being 9 less. Now,
going in to the level range where I get to xp off the Catoblepas this could
be nifty. Since the added effect kicks in 100% Vs. Beasts and so far it's
done right around 40 extra dmg every time, That's a signifigant increase in
dmg per hit. Don't get me wrong, I'm not throwing out my Vassago's, but so
far this scythe is definetly not just ideal for Bst.

**Comment by dallano** [comment]
This is a step in the right direction. Ideally if we find 2-3 more sources that claim the same information we could move forward on the changes. Although a video of someone using the scythe is sure-fire evidence and will get implemented immediately (if we can find it)

**Comment by brianschroeder1** [comment]
As a follow up: additional comments by users continue to confirm the 100% hit rate on beasts is accurate with additional darkness damage of approx~ 40 per hit. I hope this helps :)On Apr 24, 2023 11:20 p.m., Brian Schroeder ***@***.***> wrote:Hello,This is outlined from user experience shown in the alakazham wiki comments. https://ffxi.allakhazam.com/db/item.html?fitem=3733User: __DEL__1591816499577 on may 2005 stated:Sage1,192 postsI was mostly getting this to have a Rare/Ex scythe my level, and in case I ever took my Bst to these heights. I'm a lvl 65 Drk, with a TON of Acc+ equips (Woodsman Rings, Life Belt, Assault Earring, etc..) And I didn't think I would use this over my Vassago's, but after equipping it and trying it out I might be wrong. In Xp parties I tend to sub Samurai (of course I have thf sub if they request it...) so a 480 delay is very nice because overall I will hit more often and accumulate TP faster. The interesting thing I noticed is that my Dmg vs. XP mobs is nearly identical to the dmg I was doing with Vassago's despite the Dmg on this weapon being 9 less. Now, going in to the level range where I get to xp off the Catoblepas this could be nifty. Since the added effect kicks in 100% Vs. Beasts and so far it's done right around 40 extra dmg every time, That's a signifigant increase in dmg per hit. Don't get me wrong, I'm not throwing out my Vassago's, but so far this scythe is definetly not just ideal for Bst.On Mon, Apr 24, 2023, 11:05 p.m. Abdiah ***@***.***> wrote:
Hey, bud! If you're able to help us find ample evidence of this scythe being 100% proc rate against beasts, I'll be happy to make the change. The wiki's "always active against beasts" feels a little vague - especially when making definitive changes based from this.
It could always be active against beasts, but have even a 50% proc rate.

**Comment by dallano** [comment]
oh you know what? Don't even worry about it anymore! It looks like someone tried fixing this, but it never went through. I'll get on it right now. 

Thank you for your collaboration and hard work! :)

**Comment by brianschroeder1** [comment]
https://www.ffxiah.com/item/18041/a-loutrance

Comments on ffxiah are also claiming the same. If there's any additional
info, I'll provide it. But looks like I'm running out of ffxi sites. :P
