### ISSUE TITLE
🐛[BUG][System] Bugard in the Cloud ENM Issues

### ISSUE THREAD

**Issue by Shayemz** [HorizonFFXI/HorizonXI-Issues#1495]
**What does this bug affect?**
Bugard in the Cloud ENM Fight

- No Enstone
- It seemed as though Invincible never wore off

**Steps to Reproduce**
- Fight Bougard in the Clouds ENM
- Watch him Invincible and never see it wear off in chat

- Get hit and see no Enstone

**Expected behavior**
- Invincible should wear after 30 seconds
- Should have Enstone on all hits

**Screenshots**
![image](https://user-images.githubusercontent.com/120886485/234160099-afc8f94b-567e-40e3-aea6-b559918fa0e5.png)
![image](https://user-images.githubusercontent.com/120886485/234160235-b7f764b6-1057-4c10-8e8b-9cb14d692d4e.png)

![image](https://user-images.githubusercontent.com/120886485/234160377-7f855cb2-4f9c-4c34-93a4-188a39d50338.png)

**Setup Information**
30221103_1

**Additional context**
I understand the Bougard can be immune to both RAs and Melee at the same time, but from the chat logs it more appears that his Invincible just never wore off. When he used Mighty Strikes you can see it wear in the chat, but Invincible never did. Ever since the Invincible he was immune to both RAs and Melee.

**Comment by dallano** [comment]
This unfortunately seems to be working as intended. In the live captures I used to implement this quest, his invincible lasted 15 minutes - sometimes never wearing off for the rest of the battlefield. Moreover, his enstone never began until he reached below ~30% HP, nor was it a 100% proc rate. So I believe this is working as intended. But I welcome you to discuss further should you feel inclined! <3

**Comment by Shayemz** [comment]
Oh wow, really? I never did this ENM in retail, I was going off information I found online, so if you have recordings then I don't have much to refute it with lol! Just curious though, isn't he supposed to be able to be magic immune as well? If his invincible doesn't wear, and he becomes magic immune, wouldn't you be unable to do any damage to him making the ENM impossible to complete?

**Comment by dallano** [comment]
I believe invincible only works against physical. Ranged damage should still work no problem! But I will double check that.

**Comment by dallano** [comment]
Sorry for such a late response btw lol

**Comment by dallano** [comment]
https://www.youtube.com/watch?v=2i0qb0q-weM
https://rumble.com/vbt5hx-enm-50-bugard-in-the-clouds-w-pld-rdm-smn.html

In the above videos you can see he only uses invincible. Unfortunately there's no evidence that he does any kind of ability or shows behavior of immunity to damage other than physical.

**Comment by Shayemz** [comment]
I gotcha, no worries on the delayed response! Thanks for getting back to me, but yeah the invincible makes him immune to RA too, which is what threw us off initially. Just our misunderstanding or poor documentation in the source we were using to prepare for the fight. Thanks again!
