### ISSUE TITLE
🐛[BUG][NPC/Quest] - Unbridled Passion

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#15]
**What does this bug affect?**
Koenigstiger did not cast Graviga. Only received 1 Ice Arrow instead of the 99 it should have given.

**Steps to Reproduce**
Spawn NM and fight it while monitoring abilities / spell used. Complete quest and check reward given.

**Expected behavior**
Koenigstiger should cast Graviga in addition to using tiget TP moves. Only received 1 Ice Arrow instead of the 99 it should have given.

**Screenshots**
https://drive.google.com/file/d/19o0R60_yNzWZXot6eBwHFUoKmRfjrqH-/view

**Setup Information**
Game version: 30220802_3

**Additional context**
N/A

**Comment by CriticalXI** [comment]
Fixed in https://github.com/AirSkyBoat/AirSkyBoat/pull/370
