### ISSUE TITLE
🐛[BUG][ Combat] Tiny Mandragora swinging twice

### ISSUE THREAD

**Issue by ProtomanEXE** [HorizonFFXI/HorizonXI-Issues#150]
**What does this bug affect?**
The "Tiny Mandragoras" ( lvl 1) right outside the gate of West Sarutabaruta are double attacking. They should be attacking once per swing. Yes they are labeled mnks but at this lvl the monster should not

**Steps to Reproduce**
 Go out to West Sarutabaruta  ( I-10 personally) and fight one 

**Expected behavior**
  Change the "Tiny Mandragora" to single attack per swing.

**Screenshots**
screenshot via Gyazo https://gyazo.com/16c70364cfa400f47400747b93e8a0db  

**Setup Information**
Please choose to add at least one of the following, game version (/version), browser, or operating system. 

**Additional context**
 v 30220609_0.

**Comment by dallano** [comment]
It appears this was fixed! But this bug wasn't linked or clsoed.
https://github.com/AirSkyBoat/AirSkyBoat/pull/446
