### ISSUE TITLE
🐛[BUG][System] Sickles not breaking in West Sarutabaruta

### ISSUE THREAD

**Issue by drixel** [HorizonFFXI/HorizonXI-Issues#1502]
**What does this bug affect?**
harvesting and sickles not breaking

**Steps to Reproduce**
buy sickle trade to a harvest point

**Expected behavior**
sickles should break at some point. hopefully not as often as they did but they shouldn't never break

**Screenshots**

**Setup Information**

**Additional context**

**Comment by hwangje** [comment]
Information was not given on the latest patch. A sickle will not break when you have three of the harvesting bonus field gears equipped. It is a feature of sorts.

**Comment by drixel** [comment]
oh ok ty

**Comment by TracentEden** [comment]
Yep
