### ISSUE TITLE
🐛[BUG][System/Combat] Level Sync not working and not showing member list in party

### ISSUE THREAD

**Issue by Oxiide** [HorizonFFXI/HorizonXI-Issues#1505]
**What does this bug affect?**
Level sync shows no applicable entries

**Steps to Reproduce**
Create a party

**Expected behavior**
Shows no applicable entries in level sync menu... Also noticed member list in party selection show no applicable entries even though it shows us all in the party frames.

**Setup Information**
Newest version --- New character as of 4/23

**Comment by Oxiide** [comment]
doing a search in discord it looks like multiple new characters are having this issue after the POL-0001 fix

**Comment by jynkies** [comment]
I am also having this issue. Party Member list is showing no applicable entries as well as level sync. I also had to update my bootloader because of the POL-0001 error when creating a new character.

**Comment by CriticalXI** [comment]
Fixed in today's patch
