### ISSUE TITLE
🐛[BUG][NPC/Quest] Pepperoni guild point item not able to be crafted

### ISSUE THREAD

**Issue by drixel** [HorizonFFXI/HorizonXI-Issues#1507]
**What does this bug affect?**
my gil after buying the ingredients and not being able to craft the requested guild point item
and not being able to get guild points today

**Steps to Reproduce**
buy 
[Fire Crystal]
1 x [Black Pepper]
1 x [Buffalo Meat]
1 x [Giant Sheep Meat]
1 x [Kazham Peppers]
1 x [Oak Log]
1 x [Rock Salt]
1 x [Sage]

**Expected behavior**
making 12 pepperoni's to turn in for guild point item. if it's out of era then npc shouldn't be asking for it

**Screenshots**
![pepperoni](https://user-images.githubusercontent.com/42727605/234934094-4848d695-83fa-452b-9cd3-9b2c299f95ee.png)

**Setup Information**

**Additional context**

**Comment by TracentEden** [comment]
This should now be fixed.
