### ISSUE TITLE
🐛[BUG] Spells  Tonko: Ichi Incorrect casting time.

### ISSUE THREAD

**Issue by Lil-Rena-Foxcat** [HorizonFFXI/HorizonXI-Issues#1510]
Spells 
**What does this bug affect?**

Tonko:Ichi Cast Time

**Steps to Reproduce**

Casting the spell reports an incorrect cast bar in both game client and HXUI  implying that the timer for some reason is out of sync with the actual cast time.

**Expected behavior**

Expected spell to complete on conclusion of cast bar.  Spell does not and becomes interrupted when i try  and move or prevents me fro mbeing able to act until its finished.

**Screenshots**

**Setup Information**

Current

**Additional context**

**Comment by CriticalXI** [comment]
Already fixed, needs DAT updates which will be sent out soon
