### ISSUE TITLE
🐛[BUG] Checkered scarf gives -12 hp instead of +12 :(

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#1511]
**What does this bug affect?**

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/78566333/235011029-2e8cea21-d265-41a2-832d-ec98854263f8.png) Scarf equipped.
![image](https://user-images.githubusercontent.com/78566333/235011089-3fefa996-6ae0-4169-965c-e98c39ba3138.png)
Scarf unequipped.

**Setup Information**

**Additional context**

**Comment by HorizonPotato** [comment]
If I recall from last time this came through, Its intentional to give -12HP.   The equipment itself is incorrectly displaying a + instead of -.

**Comment by dallano** [comment]
Fixed in https://github.com/HorizonFFXI/HorizonDats/pull/1
