### ISSUE TITLE
🐛[BUG][Combat] Items mislabeled

### ISSUE THREAD

**Issue by Riutou** [HorizonFFXI/HorizonXI-Issues#1513]
I have noticed that a few items in game are incorrect on what they give the character. The two I noticed this with, and have photo's of are the Shepherd's Bonnet amd Checkered Scarf. One item made just for this game, and another edited, or "buffed."

-The Checkered Scarf says it give DEF:4 and HP+12, when in fact it gives no DEF amd HP-12...

-And the Shepherd's Bonnet also states it gives DEF:7 when it doesn't seem to do that. 

I am not sure if it's either the item is identified wrong or they are missing the stats they are suppose to have, so some clarity on these would be great. If I notice any other items doing this, I will also bring it to your attention.

I primarily play on the Steam Deck but noticed that this was the same on my laptop as well. Also asked other people to see if they were having the same issue just to verify it wasn't me.

![16827153930664665458586462292835](https://user-images.githubusercontent.com/132103827/235252932-e933457b-1ed3-4c3a-9e52-476534679ff6.jpg)
![16827154751893481241005116928627](https://user-images.githubusercontent.com/132103827/235253036-7bf5e27a-c6f2-488f-ab88-476926012c41.jpg)
![16827155560096248343472063012224](https://user-images.githubusercontent.com/132103827/235253266-e27a5ac0-64a9-49b0-959d-1f1b2db96469.jpg)

As you can see above, my DEF stays at 105 whether these items are equipped or not, and my hp goes up when I unequip my Scarf.

Thank you for your time, and I appreciate all the hard work you guys put into this game.

**Comment by clanofartisans** [comment]
The DEF:4 on the Checkered Scarf has been fixed in this PR: https://github.com/HorizonFFXI/HorizonXI/pull/1248
The HP-12 has actually since been updated in the DAT and should be correct.

**Comment by clanofartisans** [comment]
The Shepherd's Bonnet missing DEF is fixed in this PR: https://github.com/HorizonFFXI/HorizonXI/pull/1249
