### ISSUE TITLE
🐛[BUG][Combat] Like The Wind ENM - Race Runner Possibly Too Resistant to Elemental Magic

### ISSUE THREAD

**Issue by RenaviOnEden** [HorizonFFXI/HorizonXI-Issues#1516]
**What does this bug affect?**
The boss NM in the ENM "Like The Wind" is possibly too resistant to elemental magic.  All of my elemental spells do maximum around 150-160 dmg as RDM.   

**Steps to Reproduce**
Cast elemental magic on aforementioned boss and note damage values/resist rates of the spells.

**Expected behavior**
While the boss is more resistant, it should still be possible to land full damage elemental magic with enough gear.   

**Screenshots**

https://i.imgur.com/i2CeyGX.jpeg
https://i.imgur.com/hQnI4gA.jpeg

**Setup Information**
/ver 30221103_1

**Additional context**
My stats when I was casting was INT65+40 for 105 total INT.  Elemental Magic Skill was 289. (Was on Iceday so I had Ice Ring active).  I was only using Blizzard/Ice spells in order to take advantage of Ice Staff as well.   I did try a different element once just to see.  This is the first time I've taken pictures, but it's been the case everytime I've done the ENM as well.  

Video linked below shows a RDM soloing it with what looks like just ToAU/CoP/RoTZ gear.  Not saying it should be possible yet, but seems unlikely to never see a half resist or no resist on this mob.

**Comment by TracentEden** [comment]
The NM has inherent magic damage reduction of 40% (for example see some of the nukes in this [capture](https://www.youtube.com/watch?v=l4dF94Wnr2E&ab_channel=Jimmayus)), thus you are not being resisted but just the damage is naturally cut. Thanks for reporting!
