### ISSUE TITLE
🐛[BUG] Waking the Beast

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#152]
**What does this bug affect?**
Getting message "You cannot enter the battlefield at present. Please wait a little longer" when trying to enter the battlefield "Waking the Beast" at the elemental protocrystals in the avatar's cloisters. Getting the same unable to enter message at Full Moon Fountain while in possession of the 6 "Eye of ...." key items. 
Only Titan worked and I was able to fight it. During the Titan fight his Earth Elementals used Slow 2 instead of normal Slow 1. Titan did not use it's level 75 merit BP Geocrush once during the fight. Additionally Titan only used his 2hr move Earthen Fury once, instead of multiple times. Occasionally when titan uses Rock Throw it will use it repeatedly until a different move is used.
![image](https://user-images.githubusercontent.com/112344508/192669274-c5423a28-b509-45a5-8837-f6cf2991188a.png)

**Steps to Reproduce**
Try to enter Waking the Beast at the protocrystal in each avatar's cloister.

**Expected behavior**
Entry should be allowed. Earth elementals in the Titan fight should use Slow 1 instead of Slow 2. Titan should be able to use it's AF Earthen Fury multiple times during the fight.

**Setup Information**
Version 30220906_0

**Additional context**
Titan now correctly uses Earthen Fury instead of Inferno. I was able to get the eye of tremors key item from the titan fight. I gave myself the other 5 "Eye of ..." key items and tried to enter the fight at the Full Moon Fountain and received the same "You cannot enter the battlefield at present. Please wait a little longer" message.

**Comment by dallano** [comment]
Fixes incoming!
