### ISSUE TITLE
🐛[BUG][NPC/Quest/Mission/System/Combat/Launcher/Website]?

### ISSUE THREAD

**Issue by KrystSakes** [HorizonFFXI/HorizonXI-Issues#1521]
**What does this bug affect?**
Can not play on the HorizonXI FFXI server

**Steps to Reproduce**
1.run HorizonXI-Launcher shortcut on my desktop to start game launcher.
2.once the launcher loads I click play game button.
3.It then does it's cmd promt looking stuff and then I get the Error.

**Expected behavior**
I should be joining their server and starting to play the game.

**Screenshots**
https://ibb.co/WkQDsr4

**Setup Information**
Windows 10

**Additional context**

![Capture](https://user-images.githubusercontent.com/14958327/235345400-133d6f81-6159-481e-a3fa-679c48cbda78.PNG)

**Comment by Bleu07** [comment]
Any result here? I got the same problem

**Comment by TracentEden** [comment]
This is a tech support issue and can be posted and asked in the tech support section of the Horizon discord, thanks!
