### ISSUE TITLE
[BUG][System][Combat] All NMs seem to have Bind/Gravity resist buildup.

### ISSUE THREAD

**Issue by Drop-Horizon** [HorizonFFXI/HorizonXI-Issues#1522]
Bind durations were always 30/45/60s if they landed depending on 50%/25%/0% resist.

NMs that built Bind resist did not build resistance to the duration but to the enfeeble itself. The system that is currently implemented doesn't even tell if your Bind resists or not after casting. Zip and all other sky NMs should not build resistance to Bind if going for era-accurate gameplay.

It seems some sky NMs do build Gravity resist but not Bind according to wiki and BGforums. The broken(imo) catch-up mechanic forces me to use Gravity on fights I would be fine with just Bind.

![image](https://user-images.githubusercontent.com/132195059/235344817-908ed969-ba56-4839-9559-5c2d3f6158d4.png)

**Comment by TracentEden** [comment]
This was fixed in https://github.com/AirSkyBoat/AirSkyBoat/pull/3629.
