### ISSUE TITLE
🐛[BUG][Combat] Flash Magic accuracy is too low + duration/efficacy not accurate

### ISSUE THREAD

**Issue by setsuk0** [HorizonFFXI/HorizonXI-Issues#1525]
Currently Flash is being resisted back to back to back quite frequently on HNMs and even lower level mobs, even by paladins with capped skills. On retail, Flash already had a high base mag acc. You can reference old videos to check out resists, which never actually even happen in anything I can find. 

I can try to find more era videos, but at a quick glance: https://youtu.be/cRZO3zUtZcI   at least 12 flashes on fafnir, 0 resists

Shit quality but does show no flash resists on Tiamat as far as I can tell: https://youtu.be/j76tFDZfZY0

This one shows at least 4 flashes on Faf that I can tell, still shit quality, might be more but 0 resists :https://youtu.be/dTEzoFiE-2o

I count at least 7 flashes on this tiamat with 0 resists: https://youtu.be/Om82pUnZAII

Note that you will need to slow down the video to watch and count the flashes, as sometimes the chat log scrolls too fast. I tried my best to count with each video, and noted absolutely 0 resists. Flash always landed on HNMs. We are currently seeing resists even on normal mobs and lower level mobs than ourselves. The magic accuracy on this is way too low. Flash shouldn't really be resisted, just more so have varying duration, as flash currently lasts full duration if not resisted. It is also not blinding the mobs enough, as they will still oftentimes land hits even while flashed.

**Comment by ZellithS** [comment]
I cant speak for flash _accuracy_ against HNMs, but I certainly feel that the _potency_ is too low when I fight against regular enemies.  It hardly ever stops you taking damage.  Chances are you flash and you wont even negate any damage.  Flash used to be a much more useful tool.

**Comment by setsuk0** [comment]
That has been my experience in anything from exp parties to gods and HNMs as well.

**Comment by Frankie-hz** [comment]
This was fixed in a previous PR
