### ISSUE TITLE
🐛[BUG][System] Character freeze

### ISSUE THREAD

**Issue by MPAbsorb** [HorizonFFXI/HorizonXI-Issues#1528]
**What does this bug affect?**
<Character freezes and cannot move, cannot move cursor. Still able to navigate to menu.>

**Steps to Reproduce**
<1.) Occurred when clicking on treasure chest to collect rewards in BCNM 50, 2.) Occred when selecting Digaga in Lower Jueno.>

**Expected behavior**
<Opening chest and collecting loot, Opening menu for delivery>

**Screenshots**
<I took a video with OBS>

**Setup Information**
<Horizon 1.1, Windows 10>

**Additional context**
<Twice now cursor highlighted an object, confirm selected, and character froze. The game continued to run, however the character could not move, and cursor would only highlight myself. Navigating through menu to shut down "Broke" the freeze and I was able to continue playing. I took a video in OBS>

**Comment by TracentEden** [comment]
I was not able to replicate, maybe a transient issue, can reopen if it happens again, thanks for reporting.
