### ISSUE TITLE
🐛[BUG] Tango with a Tracker (Fight)

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#153]
**What does this bug affect?**
Able to easily sleep all 3 repeatedly as a naked 75 red mage, wiki states sleep should only land with elemental seal and capture shows at least the rabbit is immune to the sleep. Additionally no reward was given upon fight completion.

**Steps to Reproduce**
Try to sleep the NMs repeatedly without elemental seal to see if if lands.

**Expected behavior**
The capture showed at least the pet rabbit completely resistant to sleep. Wiki suggests the 2 mithra NMs are highly resistant to sleep, only landing it with elemental seal. Completing the fight (which completes the quest in the tracker) should award 10k gil.

**Setup Information**
Version 30220906_0

**Comment by dallano** [comment]
Fixes incoming!
