### ISSUE TITLE
🐛[BUG][Combat]Xzomit TP move "Siphon Discharge", is acting like an AoE move, not a Conal.

### ISSUE THREAD

**Issue by HorizonPotato** [HorizonFFXI/HorizonXI-Issues#1530]
**What does this bug affect?**
All Xzomit mobs in Sea, specifically their move "Siphon Discharge"

**Steps to Reproduce**
Get the mob to use the TP move, it'll hit everyone in a moderate AoE range.

**Expected behavior**
A Cone shaped "Breath" attack.

**Screenshots**

**Setup Information**

**Additional context**
Was fighting mobs for Organs and noticed it use this TP move with a very "This is a conal breath attack" Animation, but was hitting everyone in range.   I went and looked it up to see it was indeed suppose to be conal.

**Comment by TracentEden** [comment]
Fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/3467
