### ISSUE TITLE
🐛[BUG][NPC/Conquest] Cannot purchase Warp ring(500 cp)

### ISSUE THREAD

**Issue by WiseKodama** [HorizonFFXI/HorizonXI-Issues#1534]
**What does this bug affect?**
* I have 3000+ conquest points, Warp ring is listed under common items for 500 conquest points. 
Upon trying to purchase it says I do not have enough points.

**Steps to Reproduce**
* Have more than 500 conquest points
* Talk to conquest NPC
* Try purchasing Warp ring from Common items for 500 conquest points

**Expected behavior**
* I should be able to purchase the ring due to the cost being lower than my balance

**Comment by TracentEden** [comment]
Yeah this item is out of era (cannot remove as an option from NPC at the moment due to limitations with dat editing).
