### ISSUE TITLE
🐛[BUG][System] OOE Butterpear obtainable through logging. 

### ISSUE THREAD

**Issue by Kyne09** [HorizonFFXI/HorizonXI-Issues#1535]
**What does this bug affect?**
Yhoator Jungle logging points can award Butterpear, which were added in 2011.

**Steps to Reproduce**
Get a hatchet and log away. You'll see a Butterpear eventually.

**Expected behavior**
Should not be obtainable until later expansions.

**Additional context**
https://ffxiclopedia.fandom.com/wiki/Butterpear?action=history

https://www.bg-wiki.com/index.php?title=Butterpear&action=history

**Comment by TracentEden** [comment]
This should be fixed.
