### ISSUE TITLE
🐛[BUG][Combat] Temenos 4 Proto Ultima Loot Tables Strange

### ISSUE THREAD

**Issue by Lv99Entei** [HorizonFFXI/HorizonXI-Issues#1537]
**What does this bug affect?**
Proto Ultima from Temenos 4th floor loot crate did not drop the proper items according to wiki and ASB code.

**Steps to Reproduce**
Kill Ultima and pop the box.

**Expected behavior**
Box should give 7 ABC, 1 piece (not body), 1 piece (not body), and a chance for body.

**Screenshots**
![image](https://user-images.githubusercontent.com/118329357/236084497-819f6dbb-6b02-43eb-ab5e-e4eedd4ed51f.png)
![image](https://user-images.githubusercontent.com/118329357/236084523-0687ea20-397e-48b6-9b94-eb72308a4106.png)
![image](https://user-images.githubusercontent.com/118329357/236084594-7c57a822-bc58-41fb-a83d-ecf6de54b41c.png)
![image](https://user-images.githubusercontent.com/118329357/236084602-5e58d2b9-488e-466a-9200-314b45d1fca5.png)

**Setup Information**
![image](https://user-images.githubusercontent.com/118329357/236084633-7bbce621-7c4e-49b5-93cc-c397e8ac2dab.png)

**Additional context**
Link to the page I found loot tables
https://github.com/AirSkyBoat/AirSkyBoat/blob/staging/scripts/battlefields/Temenos/central_temenos_4th_floor.lua

**Comment by Lv99Entei** [comment]
![image](https://user-images.githubusercontent.com/118329357/236461249-f1c46ba7-6f77-439a-b5aa-15ecacc10390.png)
GM tested and also had a buggy pool. Got the 3 items but missing the guaranteed chip for era+ buff.

**Comment by Gunosaguki** [comment]
chipping in but it does seem that the item pool is deleting random items
