### ISSUE TITLE
🐛[BUG][Combat]"Lock of Siren's Hair" Should drop from Various Sahagin NMs. 

### ISSUE THREAD

**Issue by HorizonPotato** [HorizonFFXI/HorizonXI-Issues#1538]
**What does this bug affect?**
Voll the Sharkfinned/Zuug the Shoreleaper/Pahh the Gullcaller/Worr the Clawfisted/
Novv the Whitehearted

**Steps to Reproduce**
Kill these NMs.  Siren's Hair not in pool. 

**Expected behavior**
They should have a chance to drop Siren's Hair until well into ToAU Era.

**Screenshots**
None

**Setup Information**
Current

**Additional context**
http://www.playonline.com/pcd/update/ff11us/20070308c2bbd1/detail.html
From the March, 2007 Version update ->
"- The “Lock of Siren's Hair” will be removed from the treasure dropped by the following Notorious Monsters.

Voll the Sharkfinned/Zuug the Shoreleaper/Pahh the Gullcaller/Worr the Clawfisted/
Novv the Whitehearted
*In accordance with this change, the drop rate of this item from monsters other than the four mentioned above will be increased."

So if we're in 2006 pre-ToAU Release, these mobs should still drop Sirens Hair in that era.

**Comment by TracentEden** [comment]
This was fixed.
