### ISSUE TITLE
🐛[BUG] Requiem of Sin (Fight)

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#154]
**What does this bug affect?**
Able to sleep all easily / repeatedly as naked 75 rdm without elemental seal.

**Steps to Reproduce**
Able to sleep all easily / repeatedly as naked 75 rdm without elemental seal.

**Expected behavior**
Not sure if the mithras should be immune to sleep or not, but the rabbit and wyvern should be.

**Setup Information**
Version 30220906_0

**Comment by dallano** [comment]
Fixes incoming!
