### ISSUE TITLE
🐛[BUG] ENM - Beloved of the Atlantes

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#155]
**What does this bug affect?**
The Guard Hippogryph does not seem to have strongly linked hate with the Watch Hippogryph. Tested with BST pet, able to provoke the Watch Hippo off of the pet, but the Guard Hippo stayed on the pet (The Bst pet was attacking the watch hippo, and the guard hippo had been untouched).

If the first guard hippo is not killed, the watch hippo will not summon a second one at 50%. However if the first guard hippo is killed after the watch hippo is under 50% the 2nd guard hippo will be summoned.

Correctly summons a Guard Hippo at 75% and 50% health, but does not summon the third one at 25%.

**Expected behavior**
The Watch Hippo should summon a Guard Hippo at 75% / 50% / 25% health for 3 total.
The Guard Hippos should have strongly linked hate with the Watch Hippo.
The Watch Hippo should be able to summon multiple Guard Hippos instead of only having a max of 1 up at a time.

**Setup Information**
Version 30220906_0

**Additional context**
The only capture vid on the discord is a loss right after the first is summoned, so had to use information from the wiki for the rest of the fight.

**Comment by dallano** [comment]
So when I originally went through, I noted that the hippogryph would skip spawning phases if players kept the hippogryph alive throughout when it should be spawned again.
ex. If guard was spawned and killed at 24% it wouldn't spawn again. I'll reexamine captures to double check this.

I also didn't notice any hate sharing. but again I'll double check before proceeding.

**Comment by dallano** [comment]
2:30 you can see no shared hate
https://www.youtube.com/watch?v=4jlRFHbmqMg&ab_channel=aliveend

**Comment by Squinkerdoodle** [comment]
I'm surprised you could see anything with that capture lol

**Comment by dallano** [comment]
oooh but watching through I did notice that the guard hippogryph died when the watch did. I'll make sure to add that in

**Comment by Squinkerdoodle** [comment]
Gotchya, and yea I see no shared hate in that vid either.
