### ISSUE TITLE
Bug in Dawn Promathia Fight after completion

### ISSUE THREAD

**Issue by cbjames2** [HorizonFFXI/HorizonXI-Issues#1552]
**What does this bug affect?**
when you beat promathia, you're supposed to get 2k EXP upon the completion of the fight.

**Steps to Reproduce**
kill promathia

**Expected behavior**
you get 2k xp for winning the fight(once a day)

**Screenshots**
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/55806796/4a8dc9af-43fd-4e78-b872-6f1bf73bb578)
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/55806796/9d5e1adb-b127-4acd-a31e-77793481a29f)

**Setup Information**
Windows 11

**Additional context**
Nothing more to add really.  We beat the fight, and nobody got the 2k exp.

**Comment by TracentEden** [comment]
This is out of era and was added in ToAU (see http://www.playonline.com/pcd/update/ff11us/20070606TsVPr1/detail.html)
