### ISSUE TITLE
🐛[BUG][Launcher] - Error Code: POL-0001

### ISSUE THREAD

**Issue by Gokusanchez** [HorizonFFXI/HorizonXI-Issues#1556]
Launcher

Launcher fails to connect to server once character is selected. Error Code: POL-0001 was given. 

Steps to Reproduce
1) Launch Horizon launcher
2) Log into account
3) Click "Play Horizonxi"
4) Main menu loads and connects to account
5) Click accept on terms and conditions
6) Click select character
7) Asked to login with named character
8) clicks yes
9) Error code: POL-0001 is presented

**Expected behavior**
Login to server with character

**Screenshots**
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/133169680/aa6e8743-17a5-4082-936b-faf86e4bcd63)

**Setup Information**
Windows 11, Ashita command line injector version 4.0.0.2, horizonxi launcher version 1.1.4

**Additional context**
Character was created on the official website May 9th. issue persists into May 10th. I checked the official discord and it said this was patched and the old instructions can't be found anymore. I also tried using the bootloader patch and still didn't fix the issue. I also tried deleting and doing a fresh install.

**Comment by DoBetterDom** [comment]
I have been experiencing the exact same issue! I've looked everywhere and tried everything I could find, still nothing. Was thinking just give it a couple days, but im not sure at this point. Leave a comment if you find a resolution for this! Thanks!

**Comment by Gokusanchez** [comment]
> I have been experiencing the exact same issue! I've looked everywhere and tried everything I could find, still nothing. Was thinking just give it a couple days, but im not sure at this point. Leave a comment if you find a resolution for this! Thanks!

Did you also have a newly created account and character? I haven't been able to get in for even a minute of play time.

**Comment by ZellithS** [comment]
The instructions for fixing this issue are able to be found by using the search function on the horizon discord and looking for "pol 0001" or even typing it in horizon chat somewhere (there is a bot that points people in the right direction).

This is a link to the instructions on how to resolve the pol-0001 problem which is in the tech-support-faq section.

https://discord.com/channels/933423693848260678/1048426076608680006/1100203297966665809

**Comment by Gokusanchez** [comment]
You're the best! i think my problem last time was i didn't realize i didn't fully accept all the rules in the server (silly me). I managed to follow the instructions and replace the boot loader with the provided in the faq section.
