### ISSUE TITLE
🐛[BUG][Combat]Tiamat Resistance's Build not Resetting

### ISSUE THREAD

**Issue by sarca571ca** [HorizonFFXI/HorizonXI-Issues#1557]
**What does this bug affect?**
Tiamat in this instance but it might apply to all NM's.

**Steps to Reproduce**
Cast any SPELL that applies slow and requires MACC. Eventually all forms of SLOW (except abilities that apply slow) will be completely resisted no matter how long you wait. 

**Expected behavior**
This is where I'm a bit unsure. I believe if a resistance is built, it should have a timer on that resistance built up and once it has expired the "resbuild" should reset. 

**Additional context**
If this is completely intended, then maybe a bit of clarification should be posted. Even something vague would be good. Otherwise, we don't really know if something is intended or a bug.

**Comment by TracentEden** [comment]
@sarca571ca I know tiamat has silence resist building that does not reset but I think other resist building should wear after 20 seconds of not casting spells of that element. I will ask a magic expert to take a look.

**Comment by sarca571ca** [comment]
@TracentEden Cheers thanks mate.

**Comment by TracentEden** [comment]
@sarca571ca What are your total MND (with full gear as you would cast slow), enfeebling magic (with full gear as you would cast slow), and do you use an earth or terra staff?

**Comment by sarca571ca** [comment]
There is a lot of stacking info for this so I'll detail it all. 

75Bard/37Whm casting Carnage Elegy.
w/ Earth Staff and Horn +1
CHR = 113 (123 w/ Etude)
SINGING SKILL = 243
WIND SKILL = 225

Tiamat was rebuffed with Earth Threnody using Piccolo +1 and the above stats.

Early in the fight elegy's would randomly land, sometimes with full durations and others with half durations. I would land elegy at times when another more geared bard couldn't.

**Comment by Frankie-hz** [comment]
This is verified as working as intended
