### ISSUE TITLE
🐛[BUG] ENM - Automaton Assault

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#156]
**What does this bug affect?**
*All 5 automatons were present during my testing, instead of only 4 which should be the other races besides the group's race (minus the automaton of your own race which for my tests should have been the Hume).
*When the automatons use the WS Freezebite it is not causing a sleep effect.
*If the Elvaan, Galka, or Mithra Automaton is engaged first the other automatons will also aggro (instead of going 1 by 1), as pictured below. The same is true for the Hume Automaton, I tested it even though it's not supposed to be present since my character is a Hume.
*When the Taru automaton is engaged first and then killed, the Mithran / Galkan / Elvaan automatons will then aggro one by one in about a 1 second interval, instead of waiting until the following automaton's low HP trigger.

**Expected behavior**
There should only be one automaton active when you attack the first automaton. Once you get it to low HP the next automaton should activate and start fighting. This behavior should repeat until all four are active and defeated. (There should not be more than 2 active theoretically)

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/192862661-10c2c845-a22a-4d59-a415-460c6b5cf955.png)
![image](https://user-images.githubusercontent.com/112344508/192862730-ebb1b8b7-7fbb-4653-9822-61565171effd.png)

**Setup Information**
Version 30220906_0

**Additional context**
I tested this multiple times to be able to see what happens when each automaton is pulled initially. The automaton's individual weaknesses / strengths seem correct to me.

**Comment by dallano** [comment]
Fixes incoming!
