### ISSUE TITLE
🐛[BUG] [QUEST] Reap What You Sow

### ISSUE THREAD

**Issue by Clonegoat** [HorizonFFXI/HorizonXI-Issues#1560]
**What does this bug affect?**
Quest "Reap What You Sow" is still unable to be completed via Deathball

**Steps to Reproduce**
Mashuu-Ajuu does not seem to accept any trades, only repeats the same dialogue
"Tsk. Don't tell me another adventurer has wandered into our class with eyes wide open in wonder..."
"I know our school is liberal and open to all and all that, but I don't see why that means any ill-mannered trespasser can walk in and disturb our studies."

**Expected behavior**
Should accept the trade of Sobbing Fungus and Deathball, the former rewarding 500g and Stationary Set, and the later 700g, the Stationary Set, and completing the quest.

**Screenshots**
![Screenshot 2023-05-12 144553](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/80860333/b31d6936-5166-4b4e-8d46-ba95b9ab45ca)
^ trade results in zero dialogue, no reward, quest still in log

**Setup Information**
/ver 30221103_1

**Additional context**
This has been written off as resolved/closed multiple times, but yet has never been fixed. I know it's just a silly little quest, but I can't just walk away from it.. or this Deathball that's been in my moghouse for months now.

**Comment by dallano** [comment]
Bug has been fixed and is coming soon! Please watch the patch notes for the fix.
