### ISSUE TITLE
🐛[BUG][NPC]Mis speller Mob name - OrcishCursemak

### ISSUE THREAD

**Issue by PrinceOfParallax** [HorizonFFXI/HorizonXI-Issues#1564]
**What does this bug affect?**

Name is Cursemaker

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/38820735/881280b6-a815-4756-8ea0-90a3ea21047c)

**Setup Information**

**Additional context**

**Comment by PublicXI** [comment]
To be fixed on launcher update. Thanks!
