### ISSUE TITLE
🐛[BUG] ENM - Bionic Bug

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#157]
**What does this bug affect?**
NM does not use third Mighty Strikes at 25%. I did not witness the NM doing increased damage as the fight went on. Per the wiki and captures the NM is able to do more max damage on auto attacks and TP moves the lower it's health gets.

**Expected behavior**
NM should use 3 Mighty Strikes total, at 75% / 50% / 25% HP. NM should do increased damage as the fight goes on, causing it to do more damage with auto attacks / TP moves.

**Setup Information**
Version 30220906_0

**Additional context**
It was hard to tell if he was taking increased magic damage during the mighty strikes due to how magic resist and buildup works, but on the un-resisted spells he did seem to take more max damage from the spells so from what I can tell that mechanic is working as intended.

**Comment by dallano** [comment]
https://github.com/AirSkyBoat/AirSkyBoat/pull/284

So when I was reviewing captures I didn't notice any kind of increased damage whatsoever. But it appeared as though he gained counterstance as well as increased damage taken from magic.

I was able to fix the mob not using 2hr below 25%. Used a capital G in the wrong spot...

**Comment by Squinkerdoodle** [comment]
Maybe I was mistaken while watching the capture and his TP move like Mighty Whisk or whatever it's called just wasn't hitting for full max amount often.
