### ISSUE TITLE
Heliodromos Island Jumping

### ISSUE THREAD

**Issue by Tagriel01** [HorizonFFXI/HorizonXI-Issues#1570]
Engaged the three Heliodromos NM's in Riverne-A01. Left spawn island when another party member died, left through stable displacement like normal. The NM followed, jumped to new island (from M-11 to L-10) and laid waste to a very nice Elvaan fellow. Despawned shortly thereafter. Discord and In game: Tagriel

**Comment by ThoseWhoFight** [comment]
https://github.com/HorizonFFXI/HorizonXI-Issues/issues/1321

in case it's related in any way
