### ISSUE TITLE
🐛[BUG][System] HELM Activities Still Generating Eggs

### ISSUE THREAD

**Issue by clanofartisans** [HorizonFFXI/HorizonXI-Issues#1574]
**What does this bug affect?**
HELM activities are still generating lettered eggs from the egg hunt event.

**Steps to Reproduce**
Perform HELM activities.

**Expected behavior**
No eggs should be generated.

**Additional context**
Have been receiving reports from multiple players that this is still going on as of 2023-05-19.

**Comment by TracentEden** [comment]
This should be fixed now, can reopen if still happening, thanks for reporting!
