### ISSUE TITLE
ENM40 Bad Seed: Phalanx not removing after game indicates its removed

### ISSUE THREAD

**Issue by MynniQuinn** [HorizonFFXI/HorizonXI-Issues#1576]
We are doing this ENM (I did it last week easily) and the mob is not removing Phalanx even after the game indicates it did. It is also not Blaze Spikeing itself. Phalanx never removes no matter how many times we dispel it. Is this a known issue? I've heard about it before but I'm not sure what to do. We are stuck in ENM, can we get the fight reset or see if there is an issue?

**Comment by MynniQuinn** [comment]
It finally removed Phalanx and started its rotation like normal at 1min left. We got removed. Got it down 30% hp in under a min. So it's not damage issue.

**Comment by MynniQuinn** [comment]
I cant go back to the first 15min of fight when we had all charges and removed phalax multiple times but i did find 2 instances in the logs up till 5min remaining, posting to show it was always up
![Mynni_2023 05 20_214747](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/134179621/5c291d94-c6b0-4565-8ce9-e98b590c4812)
![Mynni_2023 05 20_214841](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/134179621/a50e719c-13c2-410b-8979-807d3256344f)

**Comment by MynniQuinn** [comment]
When we had full pet charges we were moving it like 2-4x back to back within a few seconds, but my logs didn't go all the way up to show beginning of fight. We would just like to be able to fight it and not lose our weekly key :/ we have TP'd out and are doing our second ENM while we wait for response.

**Comment by dallano** [comment]
So the way this fight works, is the effects on Hamadryad are only dispelled by using certain elemental damage on it. As you see once you begin using geist wall it begins to remove the effect. Each effect is dispelled by a random element each time, and can sometimes be the same as another.

It can reapply these effects as quick as 10 seconds as seen in captures done on retail. This might give the illusion that it's not wearing off.

**Comment by dallano** [comment]
Here is my initial PR when I first implemented this fight. Feel free to look over anything to see if I missed it or did anything improperly.

https://github.com/dallano/server/commit/b39a3a99a23010b0ef1ed98f9dd21e680537203b
