### ISSUE TITLE
WHM AF Feet Quest

### ISSUE THREAD

**Issue by DrDoakHead** [HorizonFFXI/HorizonXI-Issues#1577]
I was doing the quest Prelude of Black and White which requires Moccasins and and Yagudo Holy Water.  Following the guide on BG-wiki, I went to Castle Oztroja and farmed Yagudo Abbots to get the holy water.  I bought the moccasins from the AH.  I traded both items to Narcheral and nothing happened.  Trying to figure something out, I decided to trade just the moccasins and it worked.

I was able to finish the WHM AF feet quest by just trading the moccasins.

**Comment by dallano** [comment]
This issue was resolved by a commit that can be found at: https://github.com/dallano/server/commit/50b3aaca39dfc42711dd5b13cdc56941092011f0
