### ISSUE TITLE
🐛[BUG] 5 mog wardrobe spots not unlocking after having first advance job 

### ISSUE THREAD

**Issue by traven89** [HorizonFFXI/HorizonXI-Issues#1578]
**What does this bug affect?**

 mog wardrobe unlock not unlocking after getting first advanced job 
**Steps to Reproduce**

no clue
**Expected behavior**

having 5  mog wardrobe slots 
**Screenshots**

![Screenshot 2023-05-21 151942](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/75099034/3f8c7c5a-7cb3-415e-b4e9-9b05d22b2d4c)

**Setup Information**

**Additional context**

**Comment by traven89** [comment]
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/75099034/8a2bfd87-5a22-43f2-842d-eac9973e8cfc)

**Comment by traven89** [comment]
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/75099034/93bd0f03-ffa0-4bd2-ac86-0eaf37458c99)

**Comment by TracentEden** [comment]
@traven89 If you still have any issues you can put in a GM ticket as GMs have a command to check and correct issues with mog wardrobe spots (which can sometimes get bugged out). Thanks for reporting!
