### ISSUE TITLE
🐛[BUG][NPC] Dynamis-Valkrum Loot Tables Incorrect

### ISSUE THREAD

**Issue by Jeauxzuf** [HorizonFFXI/HorizonXI-Issues#1579]
**What does this bug affect?**
The loot tables of mobs in Dynamis-Valk.

We cleared a significant number of the hippos and cactars only got single bronze pieces off these mob types, no more no less, no AF related items.

Sheep and Manticore were dropping items at a rate that is reasonable but they were also dropping Dynamis-Quifm gear as well.

**Steps to Reproduce**
Kill Cactus and Hippos.
Did not kill enough beastmen to confirm incorrect currency quantity/type or AF off these.
Kill Sheep and Manticore.

Audit the tables for Dynamis-Valk

**Expected behavior**
Mobs to be dropping Dynmis-Valk gear. 
Mobs to drop more than 1 bronze piece.

**Comment by TracentEden** [comment]
@Jeauxzuf Cactus and Hippos are dropping gear and multiple coins from my testing on the test server. Also what specific Dynamis-Quifm gear do you mean?

**Comment by Jeauxzuf** [comment]
@TracentEden If possible I'd ask to test on live then. We cleared almost the entirety of the valkrum emperor location up to the lizzard xp camps where there are more hippos and cactar. Also a note of it was either hippos or cactar near the lizard camps were spawning different mobs. such as attack a cactar and 2 manticore pop out of them. 

as far as quifm gear we were getting scout socks -1, ninja feet -1, ranger af head and so on. The same mobs dropping this gear also dropped valk dunes gear, but the hippos and cactar only dropped the 1 coin. we had 0 instances of the 1-4 coins mob, 0 gear. We gave up killing on that 1/2 of the map went back to the sheep and manticore and it was night and day.

**Comment by TracentEden** [comment]
@Jeauxzuf I found an issue with a hippo that spawns a manticore and I also found an issue that could cause the two qufim AF-1 drops (from quadav mobs), do you remember what mob dropped the ranger head AF? Thanks!

**Comment by Jeauxzuf** [comment]
Unfortunately I do not. I asked my team to give input or screen shots and parses but i dont think anyone was really recording that day. All I could say is all the drops we got came from the oasis side of the map down over to highlands zone.
