### ISSUE TITLE
🐛[BUG] KSNM - Royale Ramble

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#158]
**What does this bug affect?**
King of Swords's initial placement is incorrect and facing the wrong direction. (Pictured below)
King / Queen of Cups no longer cast Dia / Banish / Diaga / Banishga spells of any tier.
King of Coins used Diaga III.

**Expected behavior**
Capture has all 4 in a straight line facing the arena entrance for initial starting position. Capture shows the mobs casting Dia 2 / Diaga 2 / Baishga 2, with the King & Queen of Cups using Banish 3

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/193106296-f19e17c1-5461-436d-9313-1bfa47b8daa6.png)

**Setup Information**
Version 30220906_0

**Additional context**
The issue with the queen's staying dead after the first clear has been resolved and they now spawn on each new attempt.

**Comment by dallano** [comment]
Fixes incoming!
