### ISSUE TITLE
🐛[BUG][Mission] Bastok Mission 1-3 Doesn't Grant Rank 2

### ISSUE THREAD

**Issue by ryuu9187** [HorizonFFXI/HorizonXI-Issues#1593]
**What does this bug affect?**
Prevents characters from being able to achieve Rank 2 in main story missions for Bastok under certain conditions.

**Steps to Reproduce**
- As a Bastokan, complete missions 1-1 and 1-2
- Get mission 1-3, Fetichism.
- With a full inventory, trade the 4 required Fetich body parts for this mission to a Bastokan gate guard.
- The guard will say to come back once your inventory has space. Note, your character still loses the traded items.
- Ensure you now have at least one open inventory space and complete the mission again by trading the 4 Fetich body parts to a Bastokan guard.
- The guard will simply say you've completed the mission.

**Expected behavior**
The guard should grant the character Rank 2 and give the Bastokan Ring as a reward.

**Setup Information**
Windows 10

**Additional context**
I don't remember what my rank points looked like before encountering the issue, but afterwards, I noticed they were back to 0. I tried completing Fetichism another 2 times, including zoning/logging out, but to no avail. Rank points move up slightly each time.

**Comment by Biskmatar** [comment]
It's July 4 currently and it's still an issue. I didn't even know my inventory was full or that this would somehow be such a big issue.

**Comment by TracentEden** [comment]
This has been fixed
