### ISSUE TITLE
🐛[BUG][Quest/Combat] Waking the Beast battlefield, Ramuh Prime elementals drop out of era polearm

### ISSUE THREAD

**Issue by RetroPrez** [HorizonFFXI/HorizonXI-Issues#1596]
**What does this bug affect?**
Thunder Elemental in battlefield dropping out of era WotG polearm

**Steps to Reproduce**
Waking the Beast, Ramuh fight, one of the four thunder elementals dropped a polearm.

**Expected behavior**
Unsure if they should be dropping anything at all in the battlefield

**Screenshots**

![Retro_2023 05 28_234048](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/112651690/490aa197-1663-42eb-95ca-df5e5f9cc9ec)

**Comment by TiberonKalkaz** [comment]
DropID 3000 is the only place I see Pike (itemId 19305)

_ALL_ elementals in WtB pre-reqs have drop ID 3000
