### ISSUE TITLE
🐛[BUG][Quest] Waking the Beast Hard Crash

### ISSUE THREAD

**Issue by 9001-Sols** [HorizonFFXI/HorizonXI-Issues#1598]
**What does this bug affect?**
`Waking the Beast` battlefield

**Steps to Reproduce**
* Enter waking the beast
* Get Carbuncle to 75%, he spawns 1 avatar
* Kill the elemental
* Carbuncle respawns, get it to 50%
* 3 elementals spawn (only 2 should spawn)
* Kill the 3 elementals
* 5 Carbuncles spawn (this is incorrect, 1 Carbuncle should spawn with 50% HP)
* Get 1 of the 5 Carbuncles to 25%
* The zone freezes and nobody can log in

**Expected behavior**
Carbuncle shouldn't crash the zone

**Screenshots**
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/43099213/45578b82-5ff4-42f9-a14c-6adbd4c387eb)

**Additional context**
We think the hard crash occurs because the cloned Carbuncle attempts to summon avatars, but at this point the cloned Carbuncle should not exist

**Comment by dallano** [comment]
There seems to be an issue with the incrementing of variables used to control the battlefield. Where he's spawning 3 avatars instead of 2 seems to be the beginning of the issue. I'll take a look into this.

**Comment by dallano** [comment]
So the issue seemed to be occurring when players dealt killing blows at the same time. This would cause the battlefield to skip a phase and therefore throw off logic. Thank you for the report!
