### ISSUE TITLE
🐛[BUG] Combat, Carbuncle's Pole

### ISSUE THREAD

**Issue by Minasojo** [HorizonFFXI/HorizonXI-Issues#1599]
**What does this bug affect?**

The weapon "Carbuncle's Pole" has listed bonuses:

CHR+4, TP Bonus
Latent Effect: Light Damage
Enchantment: Recover HP

The latent, which should be active when Carbuncle is summoned by the player (or a party member) does not appear to be functioning.

From BG Wiki ( https://www.bg-wiki.com/ffxi/Carbuncle%27s_Pole ) this appears to have a high proc rate when active, yet I haven't been able to see any successful procs. 

**Steps to Reproduce**
1) Equip to main: "Carbuncle's Pole" 
2) Summon Carbuncle (or have a Party member summon Carbuncle).
3) Auto-Attack a mob in melee with the Carbuncle's Pole 

**Expected behavior**
Additional Light damage should be getting dealt with the auto-attacks from the weapon at a high rate.

**Screenshots**
I took screenshots of me solo fighting Flamingo mobs with Carbuncle summoned and using the weapon, where you can see despite many many attacks, there were no additional Light Damage Procs. 

![Minasojo_2023 05 23_011430](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/123211340/66280f1c-04da-4d9a-8611-df302d6d532c)
![Minasojo_2023 05 23_010800](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/123211340/bb2a393c-c3a6-4b03-a502-6e292db3fb07)
![Minasojo_2023 05 23_010730](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/123211340/d3077e16-3de9-4803-83e6-a4937060182c)
![Minasojo_2023 05 23_010742](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/123211340/f9a2daa7-0f63-4505-b289-8c220e7d34b8)
![Minasojo_2023 05 23_010750](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/123211340/3381c97a-edf7-4236-8967-1f4873b9a818)
![Minasojo_2023 05 23_010752](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/123211340/083158d1-a439-4755-b0ab-fd5ce37263b5)
![Minasojo_2023 05 23_010757](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/123211340/5d5c2a6c-c545-49c4-9b16-73e11e295c0d)

**Comment by dallano** [comment]
Fix will be in ASAP

**Comment by dallano** [comment]
Players will see fixes on live Horizon most likely this friday
