### ISSUE TITLE
🐛[BUG][Digging]

### ISSUE THREAD

**Issue by piihub** [HorizonFFXI/HorizonXI-Issues#160]
**What does this bug affect?**
Player Dialog

**Steps to Reproduce**
Digging anywhere, failing to dig up an item

**Expected behavior**
Player sees the text:
"You dig and dig, but find nothing, dialog (forgot the exact text)
Instead, player sees:
"Your rod breaks"

**Comment by Squinkerdoodle** [comment]
@OpheliaXI did https://github.com/AirSkyBoat/AirSkyBoat/pull/480 fix this issue too?

**Comment by dallano** [comment]
@Squinkerdoodle Testing now, and it seems to have been fixed.

**Comment by Squinkerdoodle** [comment]
@piihub @dallano guess this one can be closed then
