### ISSUE TITLE
🐛[BUG][System]Chaos Sollerets +1 era+ accuracy not working.

### ISSUE THREAD

**Issue by Its-Just-Jam** [HorizonFFXI/HorizonXI-Issues#1604]
**What does this bug affect?**
DRK AF feet were era+'d to have +3 accuracy, after upgrading them to HQ the +3 accuracy no longer works.

**Steps to Reproduce**
Equip AF+1 boots on DRK.

**Expected behavior**
Should be adding +3 accuracy.

**Screenshots**
![afboots](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/135197096/96881659-5b9e-4225-89ea-097a569d349b)

**Additional context**
Screenshot is /checkparam before and after equipping them, ATK is increased by the STR+5 but Accuracy does not increase as it should.

**Comment by clanofartisans** [comment]
Fixed: https://github.com/HorizonFFXI/HorizonXI/pull/1237
