### ISSUE TITLE
🐛[BUG][System/Combat] DRK AF "Chaos flanchard" missing +2 DEX

### ISSUE THREAD

**Issue by EndofRivers** [HorizonFFXI/HorizonXI-Issues#1609]
**What does this bug affect?**
This effects the DRK AF "Chaos flanchard"

**Steps to Reproduce**
Equip DRK AF "Chaos flanchard" and see that there is no DEX bonus

**Expected behavior**
DRK AF "Chaos flanchard" should be giving +2 DEX.

**Screenshots**
Wearing DRK AF "Chaos flanchard"
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/44332924/46ad5e86-3ee0-4ab4-a07d-e75c36c42caf)
Naked
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/44332924/78e8450e-51ae-4ec8-8018-01ca7c961ec0)
checkparam before and after unequiping
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/44332924/bb5bad2c-3322-47f1-8396-b5a7f1d11075)

**Comment by clanofartisans** [comment]
Should be fixed in this PR: https://github.com/HorizonFFXI/HorizonXI/pull/1247
