### ISSUE TITLE
🐛[BUG] - Wild Card (Quest)

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#161]
**What does this bug affect?**
Unable to receive the Joker Card from the Toraimarai Canal treasure coffer after opening it twice while on the quest. Received gil both times.

**Steps to Reproduce**
Be on the quest and after the step where you go to the House of the Hero and speak to either Joker or Apururu go to Toraimarai Canal and open a treasure coffer to see what you get.

**Expected behavior**
After speaking with Joker at the House of the Hero in Windurst Walls you are then sent to the Toraimarai Canal to open a coffer and get the Joker Card from within.

**Setup Information**
Version 30220906_0

**Comment by dallano** [comment]
fix incoming
