### ISSUE TITLE
[BUG] Bahamut V2 - Vrtra bugged spams charm back to back constantly.

### ISSUE THREAD

**Issue by ExodusDave** [HorizonFFXI/HorizonXI-Issues#1610]
**What does this bug affect?**

Bahamut V2 Fight, Vrtra charm rate is extremely high he uses it back to back on everyone in the alliance untill all 18 people are charmed, there seems to be no internal cooldown on the ability, it legit just spams charm.

**Steps to Reproduce**

Take mulltiple people into Bahamut V2 and wait for Vrtra to spawn and it will spam charm constantly.
**Expected behavior**

Vrtra should not spam charm, but use it in intervals instead. The exact intervals I do not know, but I imagine 5mins? or something between each charm.
**Screenshots**

![dddxddd](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/18454776/27ca072c-9486-4a52-8dee-1281f3dc34ba)

**Setup Information**

Windows 10 - Ashita V4 generic Horizon installation.
**Additional context**

**Comment by Gunosaguki** [comment]
in retail it could rapid fire charm, but not non-stop as its only attack. it would still do other things, which is what was happening here.

**Comment by TracentEden** [comment]
@ExodusDave @Gunosaguki Yeah there is an issue as it is using it too fast, should be about every 5 seconds, I will put in a fix. Thanks for reporting!

**Comment by TracentEden** [comment]
I'm going to close this issue, can reopen if further input
