### ISSUE TITLE
🐛Windshear Hat Not Rewarded for quest Hat in Hand

### ISSUE THREAD

**Issue by Gaugeforever** [HorizonFFXI/HorizonXI-Issues#1616]
**What does this bug affect?**
The ability to get the windshear hat.

**Steps to Reproduce**
1.  Accept the quest Hat in Hand in Windurst Waters.
2. Talk to literally every NPC in the entire zone (1 and 2), do not leave Windurst Waters or the quest loses track.
3. Go back to the quest giver.
4. See that you can never be rewarded with the 200 gil and Hat, you can only ever get 150gil and no hat.

**Expected behavior**
The hat is rewarded along with the proper amount of gil (although I don't think anyone cares about the gil).

**Additional context**
I did a discord search on Horizon XI's discord and this has been encountered by a great many individuals.

**Comment by dallano** [comment]
I was able to complete this as expected. Will leave this ticket open for others to contribute

**Comment by Gaugeforever** [comment]
Can I ask, did you talk to the guy looking for a hat in the shop before or after you talked to everyone else in the zone?
