### ISSUE TITLE
🐛[BUG] Cosmo Cleanse Issue

### ISSUE THREAD

**Issue by Jibblesenbits** [HorizonFFXI/HorizonXI-Issues#1619]
**What does this bug affect?**

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**
<!Version 30221103_1. -->

**Additional context**

**Comment by Jibblesenbits** [comment]
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/63336723/b086d48b-00f9-43fc-9fa7-d8af0d1aa874)

Apparently I filled the above wrong. Limbus soap is not refreshing on the 71 hr mark from pickup, but on the 71 hour from leaving the Limbus zone. My group previously ran Limbus on Tuesday at 1pm my time, but this is the 2nd time that I was not able to receive the soap.

**Comment by dallano** [comment]
Was your group able to get soap at the expected time? Just not yourself?

**Comment by Jibblesenbits** [comment]
My entire group was able to, I was the only one who wasn't. This has happened before, I just skipped the last time it happened.

**Comment by dallano** [comment]
I'm terribly sorry for the inconvenience. And I'm perplexed as to why only yourself is effected. I'll keep looking into this

**Comment by dallano** [comment]
When you are able to buy the soap again, do so and then talk to her again immediately after and let's see what she says.
