### ISSUE TITLE
🐛[BUG][NPC/Mission]Harith not trading Animas for Recollections

### ISSUE THREAD

**Issue by Ryeshosho** [HorizonFFXI/HorizonXI-Issues#1622]
What does this bug affect?
I am unable to trade Recollection of Fear or Pain for Hysteroanima/Psychoanima

Steps to Reproduce
I went to Promy-Mea, sealed my memories, entered the Hall of Transference then used the large apparatus to enter.  I received the cutscene and entered Promy-Mea.  Then used the device to exit the promy and the device to exit the Hall of Transference.  Warped back to Jeuno and went to Harith.  Talked to him 4 times and nothing.  Traded the Recollection of Fear and 2k; nothing.  Traded the Recollection of Pain and 2k; nothing.  I even tried just the recollection and nothing. I have no animas currently on my account nor have I ever traded before. Every member of my party (5 others) are having the same issue as well as many others standing around trying.

Expected behavior
I should be able to trade a recollection and 2k gil and receive the appropriate anima based on the recollection that I trade.

Screenshots
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/136195982/d6eb47de-507f-463e-807e-67a92b28c604)
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/136195982/645b7bea-eea9-4703-8bcf-19993414b9a5)

Setup Information
Windows 10

**Additional context**

**Comment by dallano** [comment]
This issue should be solved on live horizon

**Comment by Ryeshosho** [comment]
I did this just today and I had no luck.  I traded the recollection of fear and 2,000 gil.  Is that wrong for era?

**Comment by dallano** [comment]
it was just fixed about an hour ago. You should be good to go now my guy!

**Comment by Ryeshosho** [comment]
so sorry.  I just tried again.  started all over again.  got the cutscene went to Harith and traded items and nothing.
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/136195982/5322d85f-2b69-4ddb-afb4-ba1acb8c25ac)
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/136195982/1693842f-deb0-405f-8539-4667a1f18c4d)
![Ryeshosho_2023 06 11_142713](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/136195982/37db3527-083b-4abc-8659-ed5528ce1ec6)
![Ryeshosho_2023 06 11_142728](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/136195982/2607b62c-c6b2-4896-b007-04f069a24c74)

**Comment by dallano** [comment]
Hey don't be sorry my guy. I think the zone restarted after the hot-fix was put in. Which caused the code to reset. We're going to put in a PR to make sure it doesn't get undone again like this. 

I apologize for making you run through all of this again.
