### ISSUE TITLE
🐛[BUG]Glass Sheet Out of Era Dropping from SE Apollyon

### ISSUE THREAD

**Issue by Gunosaguki** [HorizonFFXI/HorizonXI-Issues#1623]
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/8631923/ee07b2e6-fd84-4bec-945b-8ed8dfc0adb4)

Simple enough, was from the third floor chest

**Comment by sarca571ca** [comment]
xi.items.SHELL_POWDER has an item ID of 1887 which is the same ID of xi.items.GLASS_SHEET. xi.items.SHELL_POWDER should be 1883. Making the adjustment and making a pull request to ASB.
