### ISSUE TITLE
🐛[BUG][Quest] BRD AF2 quest (The Requiem) not allowing trade of Holy Water to NPC

### ISSUE THREAD

**Issue by Baradri** [HorizonFFXI/HorizonXI-Issues#1625]
**What does this bug affect?**

BRD AF2 quest "The Requiem" does not allow trading of Holy Water to Bki Tbujhja to continue the quest. NPC does not react to trading of water and therefore does not make the Eldieme NMs available to fight.

**Steps to Reproduce**

1. Start quest on BRD
2. Buy Holy Water and attempt to trade it to Bki Tbujhja to continue the quest

**Expected behavior**

Bki Tbujhja should accept the trade, make a comment about going to Eldieme and allow you to spawn the NMs at the sarcophagus there.

**Screenshots**

Nothing to show.

**Setup Information**
Ver. 30221103_1
Windows 11

**Additional context**

Tested by three players, same issue on all.

**Comment by dallano** [comment]
This will be fixed in the upcoming patch
