### ISSUE TITLE
🐛[BUG][Quest] The NPC Harith in "Empty Memories" is unresponsive

### ISSUE THREAD

**Issue by ElleHarribel3** [HorizonFFXI/HorizonXI-Issues#1626]
**What does this bug affect?**
I cannot trade the recollections + gil to him to create psychoanimas etc. He only repeats the same Emptiness.... hmmm... Message that he defaults to at the start of the quest and doesn't give the quest he is supposed to after the player finishes cutscenes and enters a promy.

**Steps to Reproduce**
Get done with Promathia 1-2 doing the cutscenes necessary, enter a promy and try to talk to harith.  seems like a few others are having the issue as well as per a search on the discord.

My mission log rn: lists 1-2 as both completed and my current mission, in case that matters.

**Expected behavior**
Harith should allow you to synthesize anima's based on your memory of entering a promy

**Screenshots**

**Setup Information**
Windows 10. Default latest version of the horizonxi launcher (v1.16?)

**Additional context**
It has been probably a few months since I started the first steps of this mission, and I only recently continued it to get all the cutscenes. But an hour ago or so I went into Promy Mea and got the cutscenes I expected, so everything seems to have worked up to that point.
I also talked to the GM staff on the discord prior to making this report.

**Comment by ElleHarribel3** [comment]
[[](url)](https://cdn.discordapp.com/attachments/1117444051139035236/1118999023152541706/Elle_2023.06.15_222217.png)

Just did this and it worked.

**Comment by dallano** [comment]
Was fixed here. https://github.com/AirSkyBoat/AirSkyBoat/pull/3185
Should be permanently fixed in the next patch update this friday
