### ISSUE TITLE
🐛[BUG][NPC] Missing ingredient: Koma not available for purchase

### ISSUE THREAD

**Issue by Dadrice** [HorizonFFXI/HorizonXI-Issues#1628]
**What does this bug affect?**
The firework "Meifu Goma" cannot be crafted, due to a missing ingredient.

**Steps to Reproduce**
Go to Amalasanda in Lower Jeuno's Tenshodo HQ, check her stock across multiple days.

**Expected behavior**
Koma should be available for purchase, for approximately 220g.

 **Additional Context**
The recipe for [Meifu Goma](https://ffxiclopedia.fandom.com/wiki/Meifu_Goma?oldid=15412) as well as the ingredient [Koma](https://ffxiclopedia.fandom.com/wiki/Koma?oldid=20823) were available at least as early as May and August 2005, respectively, going by the wiki's history.

**Comment by dallano** [comment]
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/62350957/5082ef20-d289-412d-8a79-8093f7bc6204)

**Comment by kylefrischman** [comment]
This is not on Horizon server.

**Comment by Dayyman** [comment]
This is not available on Horizon XI Private server currently.
