### ISSUE TITLE
🐛[BUG][System][Crafting] Little Comet Cannot be Synthesized

### ISSUE THREAD

**Issue by Dadrice** [HorizonFFXI/HorizonXI-Issues#1629]
**What does this bug affect?**

Unable to craft the firework "Little Comet".
Result is the system message: "Synthesis canceled. That combination of materials cannot be synthesized."

**Steps to Reproduce**

Attempt to craft Little Comets as Alch92. (Per the wiki, requirement should be Alch35)
Used ingredients: Rain Lily x1 Firesand x1, Bast Parchment x2 with an Earth Crystal.

**Expected behavior**

Should produce Little Comet x33, x66, or x99 depending on HQ result.

**Additional context**

In-era justification:
[Patch notes from July 2005](http://www.playonline.com/pcd/update/ff11us/20050715Pm01B1/detail.html) show that Little Comet was originally named "Comet". To pair with this, [a gardening guide last edited in April 2004](https://gamefaqs.gamespot.com/pc/555735-final-fantasy-xi/faqs/30052) shows that Rain Lily was an ingredient, even during this time when it was still called Comet.

**Comment by dallano** [comment]
I cannot replicate this issue. I believe it was corrected by pulling from upstream LSB. Please try again! <3
