### ISSUE TITLE
🐛[BUG][System] Air Rider Cannot be Synthesized

### ISSUE THREAD

**Issue by Dadrice** [HorizonFFXI/HorizonXI-Issues#1631]
**What does this bug affect?**

Unable to craft the firework "Air Rider". 
Result is the system message: *"Synthesis canceled. That combination of materials cannot be synthesized."*

**Steps to Reproduce**

Attempt to craft Air Riders as Alch92, Wood49. (Per the wiki, requirement should be Alch78, Wood45)  
Used ingredients: Lauan Lumber x1, Firesand x2, Bast Parchment x1, Goblin Doll x1, Twinkle Powder x1 with an Earth Crystal.

**Expected behavior**

Should produce Air Rider x33, x66, or x99 depending on HQ result.

**Additional context**

Evidence of this recipe goes back as far as [December, 2004](https://web.archive.org/web/20050107063949/http://ffxi.allakhazam.com:80/db/item.html?fitem=3488), according to an archive of Allakhazam's comment thread.

**Comment by dallano** [comment]
Correcting. It's currently set to use a fire crystal if you want to craft it. Fix will most likely be in next patch
