### ISSUE TITLE
🐛[BUG][Combat] Carmine Dobsonflies followed through displacement

### ISSUE THREAD

**Issue by NicholasDodd** [HorizonFFXI/HorizonXI-Issues#1633]
**What does this bug affect?**
<Carmine Dobsonflis followed us through the displacement -->

**Steps to Reproduce**
!We engaged with a charmed hawker, killed 6, got our sallets and decided to leave the rest there for someone else to kill we entered the displacement and they folowed us to the other zone

**Expected behavior**
<! they should remain on the other side of the displ,acement? -->

**Screenshots**
<!-[-SS](https://drive.google.com/file/d/1LXoClkvUoRntgHgpo8YDK6eLTCe_bo4i/view). -->

**Setup Information**
<! windows 10. -->

**Additional context**
<!we were in an alliance if that matters and one of our members was dead on the other side spawn side of the displacement. -->

**Comment by NicholasDodd** [comment]
![Anko_2023 06 14_082419](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/99947348/fd448891-7e68-4ba9-b7d8-2e164ff53c20)
in case that link didn't work

**Comment by dallano** [comment]
This is bizarre.. I'm unable to replicate this solo, so it must have something to do with the body you guys left behind, or the charming of the fly. It could be that the flies linked the hawker after it uncharmed? Or if it didn't uncharm, it didn't wipe hate on the pet. Which is what I'm guessing happened.
