### ISSUE TITLE
🐛[BUG][Mission] San d'Oria Mission 8-1 unable to be finished

### ISSUE THREAD

**Issue by JoshueG** [HorizonFFXI/HorizonXI-Issues#1634]
**What does this bug affect?**
The last cutscene from mission 8-1 "Coming of Age" after delivering Key item "Drops of Amnio" to Halver, a cutscene should appear after leaving Chateau d'Oraguille and entering North San d'Oria, But the cutscene never appears even after zoning. Therefore, the gate guard still thinks I'm doing 8-1, and doesn't allow me to get mission 8-2. 

**Steps to Reproduce**
1. Deliver Key item "Drops of Amnio" to Halver at Chateau d'Oraguille 
2. Log out/Exit game
3. Log in/Enter HorizonXI
4. Leave Chateau d'Oraguille
5.  A cutscene should appear (normal behavior) but it does not appear. 

**Screenshots**

![Nobu_2023 06 14_203813](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/120850091/e67c9a70-02cc-445c-a91a-832efadf3614)
![Nobu_2023 06 14_204829](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/120850091/79ce6e6c-7817-4ce1-a506-1196636cdde1)

I finished mission 8-1 "Coming of Age", and after delivering Key item "Drops of Amnio" to Halver, I logged out of the game, and then I logged in, and went to North San d'Oria and I didn't get the cutscene, therefore I can't get the mission 8-2.

**Comment by sarca571ca** [comment]
In era you had to wait until JP midnight to get the cutscene

**Comment by dallano** [comment]
Can confirm that this is a midnight wait.
