### ISSUE TITLE
🐛[BUG][Combat] Harajnite NM on Manaclipper has no loot pool

### ISSUE THREAD

**Issue by Sup3rlfy** [HorizonFFXI/HorizonXI-Issues#1636]
**What does this bug affect?**

a) On manaclipper theHarajnite NM does not drop any loot. We have killed it 16x in the last 3 weeks. it never drops a regular crystal, nor an urugnite shell nor its Harajnite shell. no loot at all except gil.

(i may be mistaken since the drop rates are not great, but it seems unlikely. It seems way more likely its bugged or intentionally disabled at some point and forgotten to reinstate)

b) Monsters on mana clipper will only bite +/- 12 hours after maintainance. This cannot be intentional!

**Steps to Reproduce**

a) pop the nm - kill it 100x

b) try fishing during the week

**Expected behavior**

a) 5-12% drop rate?

b)  some formula of decreasing likelyhood of havin monsters bite a few times? - resets with ingame day, or RL day.

**Screenshots**

**Setup Information**

win11
**Additional context**

if prooven right, plz have a GM kill it for me 16 times and let me have my loot retroactively.
![Soulfly_2023 06 16_184704](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/64333638/9456d81d-7e66-497d-b7ee-3ad5d9ffabff)
![Soulfly_2023 06 16_185933](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/64333638/d8ad988c-9c98-4ce4-ad6f-0b6549071024)
![Soulfly_2023 06 16_192112](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/64333638/9b88fcbf-3e00-4cd1-8904-ea26826e2f7c)

**Comment by dallano** [comment]
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/62350957/7ad069a6-497e-432d-a91e-29e7aa6abce0)
He appears to have one. I'll kill him a few dozen times on local to see if it's working as intended.

**Comment by dallano** [comment]
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/62350957/fe468faf-c23e-40dc-af0b-a3f2d1ad213b)
Seems to be working. Keep up the hardwork! And I wish you the best

**Comment by Sup3rlfy** [comment]
well thx. i was sure he was bugged >.<
