### ISSUE TITLE
[BUG][System] Cant Change Title at bard even with unlock or gil 

### ISSUE THREAD

**Issue by traven89** [HorizonFFXI/HorizonXI-Issues#1637]
i completed under oath and wanted to change my title to paragon of paladin excellence but it wont let me im even at the correct bard but he always tells me i dont have the gil  in game name is Traven this goes for all Titles 
![image (20)](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/75099034/c47ae787-b180-44e5-8ee8-1b72820253cb)

**Comment by siknoz** [comment]
So this bard is actually the cutscene replayer. The one you're looking for is the "traveling minstrel". Can look up this list to find those ones to change title, there are specific npcs for specific titles as well - 

https://ffxiclopedia.fandom.com/wiki/Traveling_Bard

As for the cutscene replayers, none of those are coded as far as I know. I'll work on getting captures for those so we can implement.
