### ISSUE TITLE
🐛[BUG][System] Logging results Yhoator Jungle updated to old state

### ISSUE THREAD

**Issue by Sup3rlfy** [HorizonFFXI/HorizonXI-Issues#1638]
**What does this bug affect?**

Logging in Yhoator Jungle was updated a few weeks ago to drop (amongst others) Ebony Lumber, and ButterPears and Arrowwood Lumber (and possibly otehrs) were removed from its lootpool.
Just recently someone changed lootpool back to include Butterpears and Arrowwood and ebony is gone from its pool, effectively making logging worthless.

Maybe this happend because they tried to remove easter eggs from the lootpool?

**Steps to Reproduce**

go logging in Yhoator Jungle
**Expected behavior**

drop ebony and 0 Butterpears and 0 arrowwood
**Screenshots**

**Setup Information**

win11
**Additional context**

![Soulfly_2023 06 20_014149](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/64333638/6273d6ff-4d86-4064-82de-2d35536c2ad7)

**Comment by TracentEden** [comment]
This should now be fixed, thanks for reporting!
