### ISSUE TITLE
🐛[BUG] Ranged Attack Weaponskills Broken

### ISSUE THREAD

**Issue by Skold177** [HorizonFFXI/HorizonXI-Issues#164]
**What does this bug affect?**
Ranged attack weaponskill currently do no damage and do not show up in the combat log.
**Steps to Reproduce**
Perform any ranged attack weaponskill on any monster.
**Expected behavior**
Ranged attack weaponskill does damage and shows up in the combat log.
**Screenshots**

**Setup Information**

**Additional context**

**Comment by Squinkerdoodle** [comment]
Also just wanted to include Eagle Eye Shot in this since it was doing 0 damage each time too. (As found by Skold)

**Comment by OpheliaXI** [comment]
This has been fixed in the most recent patch.
