### ISSUE TITLE
🐛[BUG][Quest]Inside the Belly

### ISSUE THREAD

**Issue by Elderlycrawfish** [HorizonFFXI/HorizonXI-Issues#1640]
**What does this bug affect?**

Tried to confirm this the best I could through observation and discussion with other players. Inside the Belly quest appears to be bugged with Opal Silk drop rate from Liks. I'm over 0/600 and I know of 14 other people currently turning in Liks without any success for at least 2 weeks. 

**Steps to Reproduce**

When was the last Opal Silk the server gave out? That should be the best way to prove/reproduce issue.

**Expected behavior**

0.5% droprate, or 1 in 200 turn-ins should result in an Opal Silk.

**Screenshots**

Just Zaldon saying his signature "Better luck next time!" 

**Setup Information**

Current version 

**Additional context**

**Comment by dallano** [comment]
Unfortunately with 0.5% drop rate you can go 1/5 or you can 1/1000. Players have received ebisu rods in the past, and the code hasn't been touched for 9 months.

**Comment by MarkWaldron** [comment]
Go here: https://randomwordgenerator.com/number.php - set it to random number between 1 to 200. Guess a number, and then click "Generate random numbers". If you guessed correctly, you get the Opal Silk. If you guessed incorrectly, you go again. This is the lotto, you aren't guaranteed to win after a certain number of plays.

**Comment by MarkWaldron** [comment]
I've been fishing on this server since day one. I've sold Lik to multiple people this week who have received their silk. It's working

**Comment by TracentEden** [comment]
Ok, thanks everyone, GL with your fishing!
