### ISSUE TITLE
🐛[BUG][System/item]

### ISSUE THREAD

**Issue by Satedatv** [HorizonFFXI/HorizonXI-Issues#1644]
**What does this bug affect?**

I am using the Royal Squire's Robe +1 in an area controlled by my nation and I am not receiving the +3 int.  I am only receiving the base +1 int.
This comes and goes in many areas.  yesterday it worked in the are I'm in today it does not.

**Steps to Reproduce**

Anytime I enter a zone that is under my nations control

**Expected behavior**

in Areas controlled by my nation I should receive +3 int.
**Screenshots**

![Sateda_2023 06 22_165558](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/104714111/7e68ec76-6207-4aa0-b18c-c21a3251e577)
![Sateda_2023 06 22_165602](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/104714111/377a82e0-c5de-4e43-9379-889d6dc58c3e)
![Sateda_2023 06 22_165811](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/104714111/70753e7f-6c64-4f41-b601-553950f2256a)
**Setup Information**

30221103_1

**Additional context**

**Comment by PublicXI** [comment]
Apologies that this is confusing, but the [original mechanic itself is confusing](https://ffxiclopedia.fandom.com/wiki/In_areas_under_own_nation%27s_control):
> Note that in order to obtain the benefits, you must have either Signet or Sanction active.

Can confirm this works as expected when Signet is active.
