### ISSUE TITLE
🐛[BUG] [Quest] Unbridled Passion Koh Lebanlalako

### ISSUE THREAD

**Issue by ElleHarribel3** [HorizonFFXI/HorizonXI-Issues#1647]
**What does this bug affect?**
I am on the quest Unbridled Passion and it appears in quest log, I cannot advance past the NPC Koh Lebanlalako and thus cannot get my AF boots

**Steps to Reproduce**
Ideally just completing RNG quests up to the point of unbridled passion, where Koh will not let you talk to her for cutscenes or trade the gold earring.

The potential spanner in the works is that I started AF over a month ago, and I hadn't tried to complete it until now.

**Expected behavior**
I should get a cutscene where she talks to me and tells me she won't say more until I trade her a golden earring. After I trade this, she speaks some more and asks me to bring an envelope (key item) to xarcabard. (where I also click on a thing and get a cutscene)

**Screenshots**
https://imgur.com/a/Q4D22c5

**Setup Information**
Latest HorizonXI client, windows 10

**Additional context**

It has been a little while since I started the quest, and I completed borghertz hands in the meantime, so perhaps that matters for some reason; like patches changing how this is handled or something.
I've also had similar issues with other quests, like the anima production quest was hanging for me until it was fixed via GM ticket and bug reports.

**Comment by dallano** [comment]
We recently updated this quest on our end, unfortunately changing variable conventions. You will have to reach out to a GM in order to get this fixed.
