### ISSUE TITLE
🐛[BUG] Apocalypse Nigh

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#165]
**What does this bug affect?**
Unable to trigger the cutscene at the palace in Ru'Lude Gardens to start the quest.

**Setup Information**
30220906_0

**Additional context**
I have finished Storms of Fate and Shadows of the Departed legitimately and it has been more than 2 days since I finished Shadows, but still unable to start the quest.

**Comment by Squinkerdoodle** [comment]
When @CriticalXI was checking that live with me she said I had all the right var / triggers for it, but it just wouldn't go off

**Comment by hookstar** [comment]
It should call !cs 32000 somewhere. Do you get a message or get locked in a cs?

**Comment by Squinkerdoodle** [comment]
I get neither when running into the palace

**Comment by hookstar** [comment]
Interesting... I cannot duplicate the issue on ASB.

**Comment by Squinkerdoodle** [comment]
Neither was Crit on the test server, and she was able to trigger the CS when she set herself for it. I did the chain though as a normal player would (Storms of Fate / Shadows of the Departed done) but could not trigger Apoc Nigh.

**Comment by hookstar** [comment]
Yea - it seems there is a disconnect between the variables in the progress. May the odds be in your favor.
