### ISSUE TITLE
🐛[BUG][NPC/Quest/Mission/System/Combat/Launcher/Website] Dragon Cuisses +1

### ISSUE THREAD

**Issue by KaiseiWings** [HorizonFFXI/HorizonXI-Issues#1651]
**What does this bug affect?**

Dragon Cuisses +1 npc'ing for wrong amount
**Steps to Reproduce**

https://ffxiclopedia.fandom.com/wiki/Dragon_Cuisses_%2B1?oldid=688493
**Expected behavior**

As posted in the link its suppose to npc for 9.9k, here they NPC for 7.5k
**Screenshots**

**Setup Information**

**Additional context**

**Comment by dallano** [comment]
We reduced the prices intentionally in order to prevent currency inflation
