### ISSUE TITLE
🐛[BUG] Missing synth recipe for Epee

### ISSUE THREAD

**Issue by Diminished9th** [HorizonFFXI/HorizonXI-Issues#1663]
**What does this bug affect?**

Epee was requested as the Guild Point item today for the Goldsmithing Guild Artisan level. The item is not able to be synthesized following the recipe listed on the multiple wikis
**Steps to Reproduce**

Try crafting the Epee (x1 of each: Angelstone, Steel Ingot, Mythril Ingot, Gold Ingot, Platinum Ingot, Mercury)
**Expected behavior**

Either Epee should be craftable, or it should not be requested as a GP item
**Screenshots**

**Setup Information**

7/4/2023
**Additional context**

**Comment by sarca571ca** [comment]
Checking a few Wiki's the sword would fall into the current era. The recipe was commented out in the ASB code so im going to uncomment it and do a PR for this.
