### ISSUE TITLE
🐛[BUG][Quest] Waking the Beast - Carbuncle Prime moves/Key Items lost on death

### ISSUE THREAD

**Issue by CondorL** [HorizonFFXI/HorizonXI-Issues#1665]
**What does this bug affect?**

Carbuncle Prime has access to Healing Ruby II - https://ffxiclopedia.fandom.com/wiki/Waking_the_Beast/Strategies (only guide I could find that lists BP's - only the High Tier battlefield mentions use of all bloodpacts)

Key items should only consume on win - https://www.bg-wiki.com/ffxi/Waking_the_Beast

**Steps to Reproduce**

Enter and lose for the key items

for healing ruby ii get it to 25% and let them gain tp they should healing ruby 2 healing all the primes for over 6k hp

**Expected behavior**

key items shouldn't be lost on a loss

prime should have access to a limited number of BPs

**Screenshots**

https://clips.twitch.tv/SteamyDeafEelCopyThis-KI6fdAT5au8W8fOi

**Setup Information**

30221103_1

**Additional context**

**Comment by The-Aerec** [comment]
Waking the beast is currently working as intended on Horizon.
