### ISSUE TITLE
🐛[No Prompt for door to Monastic cavern]/Whence Blows the Wind/LBQuest 

### ISSUE THREAD

**Issue by Richnarf** [HorizonFFXI/HorizonXI-Issues#1666]
Unable to receive prompt for door to Monastic Cavern after receiving orb attempted multiple times including after logging.   I died due to this please fix..

**Comment by sarca571ca** [comment]
Did you complete the orb quest and receive the Key Item [Crimson Orb](https://www.bg-wiki.com/ffxi/Crimson_orb)? You won't get the dialog if you don't have the key item.
