### ISSUE TITLE
digging zones need adjustments

### ISSUE THREAD

**Issue by leelightfoot25** [HorizonFFXI/HorizonXI-Issues#1667]
The zones don't offer enough items for chocobo diggers. they get dug up too quick. 
There are clearly zones that all diggers end up in because they offer the best rewards. e.g. Western/Eastern Altepa  These zones get completely dug out each day by 02:00 game time. I don't know what the quantity of items is for a zone i know each player can dig 120 items.   Sauraumong Champaign gets cleared out in about the same amount of time 2-3 minutes.  

Options:
1. spread out good items to multiple zones so that there aren't highly contested zones.  (i dont recommend this option, because zones target items that logically make sense for that zone (bones in a desert, logs in a forest, gems in mountains)
3. significantly increase the amount of items for the hot zones (recommended) (maybe this number scales with the amount of chocobo digers on a server or palyers?

**Comment by TracentEden** [comment]
This is more of a suggestion then a bug report, please post in the suggestions section of Horizon discord as far more people will see it there, thanks!
