### ISSUE TITLE
🐛[BUG][Quest] To Cure a Cough missing dialog found

### ISSUE THREAD

**Issue by ProtomanEXE** [HorizonFFXI/HorizonXI-Issues#167]
**What does this bug affect?**
I found a youtube capture of "To Cure a Cough". This should help with the missing dialog for WHILE on the quest. I yet to have found the dialog for while not on the quest.

**Screenshots**
youtube link of a capture of said quest https://www.youtube.com/watch?v=lg1nvRvKPTo

**Comment by Squinkerdoodle** [comment]
https://github.com/HorizonFFXI/HorizonXI-Issues/issues/236 also submitted for To Cure a Cough, just posting so devs can see both easier.
