### ISSUE TITLE
🐛[BUG][NPC/Quest] Eco- Warrior San d'Oria reward is not given by NPC 

### ISSUE THREAD

**Issue by JoshueG** [HorizonFFXI/HorizonXI-Issues#1673]
**What does this bug affect?**
The Eco- Warrior San d'Oria NM quest was killed but NPC does not give the reward. 

**_Please note that the Eco-Warrior NM quest was killed, but I try to get the reward 2 weeks after the NM was killed._** 

**Screenshots**
Screenshot of the Key item obtained by NM killed
![Nobu_2023 07 10_112434](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/120850091/e188fe55-00f7-4a80-bd40-332d72340eeb)

Quest name
![Nobu_2023 07 10_112422](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/120850091/0d239416-0c86-4194-9ea2-55cfd1e8ba31)

**Additional context**
Also note that NPC does not give a new quest due to the current one is not being finished.

**Comment by JoshueG** [comment]
Mark as fixed. 

Went back to the NPC that gives the lvl cap and it gave me the dialogue needed to complete the quest with Norejaie

**Comment by sarca571ca** [comment]
Yea its a requirement to talk to the lvl cap npc after killing the NM.
