### ISSUE TITLE
🐛[BUG][System] Carbuncle's Pole not a useable item

### ISSUE THREAD

**Issue by klostrophobik** [HorizonFFXI/HorizonXI-Issues#1677]
**What does this bug affect?**
Carbuncle's Pole (reward for Waking the Beast) not a usable item.

**Steps to Reproduce**
Equip pole, wait for cooldown, attempt to use item, receive error "Unable to use item."

**Expected behavior**
Should give HP (~160) when used.

**Screenshots**
![Screenshot 2023-07-13 203930](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/1709958/403e27e4-e8bc-4746-8055-fbc489b8e7bf)

**Setup Information**
30221103_1

**Additional context**
Yes, I did try to do it while having less than 100% HP.

**Comment by siknoz** [comment]
Whoever ends up working this one, the restore should be random 160-170 based on testing - https://youtu.be/-tegdZT1FYc
