### ISSUE TITLE
🐛[BUG][Combat/] Leviathan's Blood Pact: Ward Slowga lands 100% of the time with full potency

### ISSUE THREAD

**Issue by TristtHXI** [HorizonFFXI/HorizonXI-Issues#1679]
**What does this bug affect?**
Currently levi's slowga doesnt get resisted at all, lasts the full duration everytime and seems to have full potency (cant be overwritten with rdm slow with full mnd set)

**Comment by Gunosaguki** [comment]
its retaila ccurate for full potency always if it lands, but probably not supposed to land always yeah
