### ISSUE TITLE
🐛[BUG][Combat]Crab ability "Bubble Curtain" not reducing magic damage properly.

### ISSUE THREAD

**Issue by ArmellXI** [HorizonFFXI/HorizonXI-Issues#1685]
**What does this bug affect?**
The monster TP skill "Bubble Curtain" from the Crab family is a reduction of 0.5% Magic Damage instead of 50%.
Affects Jugs as well so just assuming it's the ability itself as a whole.

**Steps to Reproduce**
Fight a crab and use magic when ability is up.

**Expected behavior**
Magic damage should doing half

**Screenshots**
Damage WITHOUT curtain on.
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/125695227/ce58dc66-dba1-4c60-bd42-f20260a705e5)

Damage WITH curtain on. (a .5% difference)
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/125695227/d257a59a-2320-4c14-a0fd-9584c15c0f63)

**Comment by Frankie-hz** [comment]
Fixed: https://github.com/AirSkyBoat/AirSkyBoat/pull/3264
