### ISSUE TITLE
🐛[BUG][System] Poseidon's Ring and Aqueous Orichalcum

### ISSUE THREAD

**Issue by SpaggiG** [HorizonFFXI/HorizonXI-Issues#1697]
**What does this bug affect?**

The Aqueous orichalcum ingot does not require 'Gold Ensorcellment' Key item like it should
The Ring itself is currently un-usable
The vendor price is also incorrect at 4,069 instead of 45,795~46,939 gil (this entire synth line is about 15k per orichalcum ingot)
The HQ orichalcum ring 'Triton Ring' also has an incorrect resale price of 4k, instead of ~32,079 gil (NQ orichalcum ring sells for about 30k)
**Steps to Reproduce**

Try to synth aqueous ingot without necessary KI, synth will succeed. Then ring will have no function and incorrect npc price
**Expected behavior**

You should be unable to synth the aqueous ingot without KI. after final synth the ring should be usable to summon a water spirit. And ring should vendor for around 46k
**Screenshots**

**Setup Information**

**Additional context**

**Comment by 0x05010705** [comment]
This seems to break down into a couple of issues:
1 - Aqueous Orichalcum Ingot Recipe is not requiring the Gold Ensorcellment
2 - The vendor price of Poseidon's Ring is wrong (4069 vs 45795)
3 - The vendor price Orichalcum Ring +1 (Triton Ring) is wrong (4000 vs 37079)
4 - Poseidon's Ring is unusable

Working on these...
