### ISSUE TITLE
🐛[BUG][Combat] Guivre pathing in Kuftal Tunnel

### ISSUE THREAD

**Issue by Scarifi3dXI** [HorizonFFXI/HorizonXI-Issues#17]
**What does this bug affect?**
Mob design, pathing, zone mechanics

**Steps to Reproduce**
N/A, can observe when NM is up.

**Expected behavior**
Guivre repeats positions around Amemet, walking to northern wall and then returning to spawn point around { X 106.57, Y 0.62, Z 2.21 }. He does not roam to Sabotender Mariachi and then back as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/112238268/187599858-2935b71b-59cf-49cc-af97-092460d9d672.png)
_"Spawn point I-9*_
![image](https://user-images.githubusercontent.com/112238268/187600078-13cd5ebf-30f8-4274-baf0-d34455c9a091.png)
_*Path end point where Guivre turns around and heads back to spawn*_

**Setup Information**
ver.30220802_3 Up to date with retail client (active retail player), no other private servers installed besides local. Ashenbubs, XIPivot. 

**Additional context**
Upon getting aggro and zoning, Guivre will disappear and pop up at Mariachi spawn area, and then walk the expected path back to Amemet indicating that pathing works but seems to glitch out after returning to Amemet area. Will attempt to solve on local as a personal learning experience with the codebase but providing context here as I doubt I'll have a solve initially! :)

**Comment by CriticalXI** [comment]
Assigned to you since I know you've been working on this

**Comment by Scarifi3dXI** [comment]
PR submitted!

**Comment by CriticalXI** [comment]
Fixed in AirSkyBoat/AirSkyBoat/#419
