### ISSUE TITLE
🐛[BUG][System] Out of Era item harvested

### ISSUE THREAD

**Issue by clanofartisans** [HorizonFFXI/HorizonXI-Issues#1702]
**What does this bug affect?**
It's been reported that harvesting in Giddeus is yielding Dyer's Woad which is out of era.

**Steps to Reproduce**
Use sickles to harvest in Giddeus for a while. Find Dyer's Woad. Be sad.

**Expected behavior**
Harvesting shouldn't yield any Dyer's Woad.

**Comment by 0x05010705** [comment]
There is actually a Quest in Windurst specifically for these Dyers Woad (even though they are out of era).
https://horizonffxi.wiki/Dyer%27s_Woad_Quest

**Comment by clanofartisans** [comment]
It was brought up in our staff Discord and we decided to keep this OOE item in-game because of the quest for it. Thanks for the report!
