### ISSUE TITLE
🐛[BUG][Combat] Earthen Warden (Titan BP) shouldn't overwrite a mages stoneskin (i think)

### ISSUE THREAD

**Issue by TristtHXI** [HorizonFFXI/HorizonXI-Issues#1704]
**What does this bug affect?**
Currently smns can ruin your good stoneskin with their terrible titan one, fairly sure you arent suppose to be able to overwrite stoneskin with titan (unless it was titans stoneskin).

Kinda hard to find concrete evidence for this, but Was able to find a few testimonials googling, so retail testing may be needed;

'EW will not overwrite SS but it will overwrite itself'
'Earthen Ward will overwrite itself, but not white magic Stoneskin (which can't overwrite itself either)'
'There was a brief time when Earthen Ward wouldn't overwrite itself, but its fixed now.
Earthen Ward still won't overwrite Stoneskin, but it will refresh itself, at least.'
'Also, Earthern Ward no longer overwrites itself or Stoneskin. I'm pretty sure if somebody has a Stoneskin on with 1 HP left, and you try to use Earthern Ward on them it gives a "no effect" message. This was patched a while ago'

'Stoneskin will overwrite Metallic Body Stoneskin effect.
Stoneskin will overwrite Diamondhide Stoneskin effect.
Stoneskin will overwrite Earthen Ward Stoneskin effect.
Metallic Body will not overwrite Stoneskin and gives a "has no effect" error.
Diamondhide will not overwrite Stoneskin and gives a "has no effect" error.
Earthen Ward will not overwrite Stoneskin and gives a "has no effect" error.
Stoneskin will not overwrite Stoneskin and gives a "has no effect" error.'

shitty sources; 
https://www.bluegartr.com/threads/39495-SMN-buff-formula(s)
https://www.ffxionline.com/forum/ffxi-game-related/ffxi-frequently-asked-questions/68963-does-blink-stack-with-utsusemi
https://ffxi.gamerescape.com/wiki/Stoneskin

please save my good stoneskin devs pls

**Comment by siknoz** [comment]
So testing on retail - https://youtu.be/C5w6JS-WuMo

Yes, Earthen ward does not overwrite Stoneskin. Can check video for the rest, the only one I wasn't able to test was Diamondhide vs Earthen Ward and vice versa.
