### ISSUE TITLE
🐛[BUG][NPC] Alkyoneus only has one spawn point

### ISSUE THREAD

**Issue by TristtHXI** [HorizonFFXI/HorizonXI-Issues#1718]
**What does this bug affect?**
Alkyoneus currently only has one spawn point, he should have much than one... :)

**Comment by 0x05010705** [comment]
This is likely due to the Pop NM system that was introduced on Mar 8, 2007.
When the NM is popped, it should only have one spawn point as it would pop right next the ??? where the item is traded.

Without the pop system, this should probably have multiple pop points -- This means this is a Horizon specific fix so I can't really put in a PR on ASB for this I would think.

I'll still generate new pop points though for someone to implement on Horizon's side.

**Comment by 0x05010705** [comment]
In `nm_spawnpoints.sql` near line 4575
```sql
INSERT INTO `nm_spawn_points` VALUES (17424480,0,-300,-175,22); -- Alkyoneus
INSERT INTO `nm_spawn_points` VALUES (17424480,1,-277,-175,30);
INSERT INTO `nm_spawn_points` VALUES (17424480,2,-282,-175,39);
INSERT INTO `nm_spawn_points` VALUES (17424480,3,-295,-175,46);
INSERT INTO `nm_spawn_points` VALUES (17424480,4,-302,-175,49);
INSERT INTO `nm_spawn_points` VALUES (17424480,5,-314,-175,42);
INSERT INTO `nm_spawn_points` VALUES (17424480,6,-323,-175,33);
INSERT INTO `nm_spawn_points` VALUES (17424480,7,-327,-175,22);
INSERT INTO `nm_spawn_points` VALUES (17424480,8,-325,-175,11);
INSERT INTO `nm_spawn_points` VALUES (17424480,9,-319,-175,-1);
INSERT INTO `nm_spawn_points` VALUES (17424480,10,-304,-175,-8);
INSERT INTO `nm_spawn_points` VALUES (17424480,11,-292,-175,-8);
INSERT INTO `nm_spawn_points` VALUES (17424480,12,-281,-175,-2);
INSERT INTO `nm_spawn_points` VALUES (17424480,13,-274,-175,5);
INSERT INTO `nm_spawn_points` VALUES (17424480,14,-271,-175,20);
INSERT INTO `nm_spawn_points` VALUES (17424480,15,-272,-175,29);
INSERT INTO `nm_spawn_points` VALUES (17424480,16,-281,-175,32);
INSERT INTO `nm_spawn_points` VALUES (17424480,17,-287,-175,39);
INSERT INTO `nm_spawn_points` VALUES (17424480,18,-299,-175,40);
INSERT INTO `nm_spawn_points` VALUES (17424480,19,-307,-175,36);
INSERT INTO `nm_spawn_points` VALUES (17424480,20,-318,-175,31);
INSERT INTO `nm_spawn_points` VALUES (17424480,21,-322,-175,23);
INSERT INTO `nm_spawn_points` VALUES (17424480,22,-316,-175,11);
INSERT INTO `nm_spawn_points` VALUES (17424480,23,-307,-175,3);
INSERT INTO `nm_spawn_points` VALUES (17424480,24,-298,-175,3);
INSERT INTO `nm_spawn_points` VALUES (17424480,25,-283,-175,9);
INSERT INTO `nm_spawn_points` VALUES (17424480,26,-281,-175,20);
INSERT INTO `nm_spawn_points` VALUES (17424480,27,-288,-175,27);
INSERT INTO `nm_spawn_points` VALUES (17424480,28,-292,-175,31);
INSERT INTO `nm_spawn_points` VALUES (17424480,29,-298,-175,37);
INSERT INTO `nm_spawn_points` VALUES (17424480,30,-309,-175,27);
INSERT INTO `nm_spawn_points` VALUES (17424480,31,-308,-175,19);
INSERT INTO `nm_spawn_points` VALUES (17424480,32,-299,-175,12);
INSERT INTO `nm_spawn_points` VALUES (17424480,33,-291,-175,19);
INSERT INTO `nm_spawn_points` VALUES (17424480,34,-277,-175,-8);
INSERT INTO `nm_spawn_points` VALUES (17424480,35,-295,-175,17);
INSERT INTO `nm_spawn_points` VALUES (17424480,36,-336,-175,15);
INSERT INTO `nm_spawn_points` VALUES (17424480,37,-313,-175,53);
INSERT INTO `nm_spawn_points` VALUES (17424480,38,-291,-175,54);
INSERT INTO `nm_spawn_points` VALUES (17424480,39,-283,-175,-13);
INSERT INTO `nm_spawn_points` VALUES (17424480,40,-312,-175,-14);
INSERT INTO `nm_spawn_points` VALUES (17424480,41,-335,-175,8);
INSERT INTO `nm_spawn_points` VALUES (17424480,42,-276,-175,19);
INSERT INTO `nm_spawn_points` VALUES (17424480,43,-327,-175,44);
INSERT INTO `nm_spawn_points` VALUES (17424480,44,-285,-175,-7);
INSERT INTO `nm_spawn_points` VALUES (17424480,45,-269,-175,43);
INSERT INTO `nm_spawn_points` VALUES (17424480,46,-295,-175,28);
INSERT INTO `nm_spawn_points` VALUES (17424480,47,-290,-175,54);
INSERT INTO `nm_spawn_points` VALUES (17424480,48,-335,-175,20);
INSERT INTO `nm_spawn_points` VALUES (17424480,49,-326,-175,-3);
```

**Comment by TracentEden** [comment]
> In `nm_spawnpoints.sql` near line 4575
> 
> ```sql
> INSERT INTO `nm_spawn_points` VALUES (17424480,0,-300,-175,22); -- Alkyoneus
> INSERT INTO `nm_spawn_points` VALUES (17424480,1,-277,-175,30);
> INSERT INTO `nm_spawn_points` VALUES (17424480,2,-282,-175,39);
> INSERT INTO `nm_spawn_points` VALUES (17424480,3,-295,-175,46);
> INSERT INTO `nm_spawn_points` VALUES (17424480,4,-302,-175,49);
> INSERT INTO `nm_spawn_points` VALUES (17424480,5,-314,-175,42);
> INSERT INTO `nm_spawn_points` VALUES (17424480,6,-323,-175,33);
> INSERT INTO `nm_spawn_points` VALUES (17424480,7,-327,-175,22);
> INSERT INTO `nm_spawn_points` VALUES (17424480,8,-325,-175,11);
> INSERT INTO `nm_spawn_points` VALUES (17424480,9,-319,-175,-1);
> INSERT INTO `nm_spawn_points` VALUES (17424480,10,-304,-175,-8);
> INSERT INTO `nm_spawn_points` VALUES (17424480,11,-292,-175,-8);
> INSERT INTO `nm_spawn_points` VALUES (17424480,12,-281,-175,-2);
> INSERT INTO `nm_spawn_points` VALUES (17424480,13,-274,-175,5);
> INSERT INTO `nm_spawn_points` VALUES (17424480,14,-271,-175,20);
> INSERT INTO `nm_spawn_points` VALUES (17424480,15,-272,-175,29);
> INSERT INTO `nm_spawn_points` VALUES (17424480,16,-281,-175,32);
> INSERT INTO `nm_spawn_points` VALUES (17424480,17,-287,-175,39);
> INSERT INTO `nm_spawn_points` VALUES (17424480,18,-299,-175,40);
> INSERT INTO `nm_spawn_points` VALUES (17424480,19,-307,-175,36);
> INSERT INTO `nm_spawn_points` VALUES (17424480,20,-318,-175,31);
> INSERT INTO `nm_spawn_points` VALUES (17424480,21,-322,-175,23);
> INSERT INTO `nm_spawn_points` VALUES (17424480,22,-316,-175,11);
> INSERT INTO `nm_spawn_points` VALUES (17424480,23,-307,-175,3);
> INSERT INTO `nm_spawn_points` VALUES (17424480,24,-298,-175,3);
> INSERT INTO `nm_spawn_points` VALUES (17424480,25,-283,-175,9);
> INSERT INTO `nm_spawn_points` VALUES (17424480,26,-281,-175,20);
> INSERT INTO `nm_spawn_points` VALUES (17424480,27,-288,-175,27);
> INSERT INTO `nm_spawn_points` VALUES (17424480,28,-292,-175,31);
> INSERT INTO `nm_spawn_points` VALUES (17424480,29,-298,-175,37);
> INSERT INTO `nm_spawn_points` VALUES (17424480,30,-309,-175,27);
> INSERT INTO `nm_spawn_points` VALUES (17424480,31,-308,-175,19);
> INSERT INTO `nm_spawn_points` VALUES (17424480,32,-299,-175,12);
> INSERT INTO `nm_spawn_points` VALUES (17424480,33,-291,-175,19);
> INSERT INTO `nm_spawn_points` VALUES (17424480,34,-277,-175,-8);
> INSERT INTO `nm_spawn_points` VALUES (17424480,35,-295,-175,17);
> INSERT INTO `nm_spawn_points` VALUES (17424480,36,-336,-175,15);
> INSERT INTO `nm_spawn_points` VALUES (17424480,37,-313,-175,53);
> INSERT INTO `nm_spawn_points` VALUES (17424480,38,-291,-175,54);
> INSERT INTO `nm_spawn_points` VALUES (17424480,39,-283,-175,-13);
> INSERT INTO `nm_spawn_points` VALUES (17424480,40,-312,-175,-14);
> INSERT INTO `nm_spawn_points` VALUES (17424480,41,-335,-175,8);
> INSERT INTO `nm_spawn_points` VALUES (17424480,42,-276,-175,19);
> INSERT INTO `nm_spawn_points` VALUES (17424480,43,-327,-175,44);
> INSERT INTO `nm_spawn_points` VALUES (17424480,44,-285,-175,-7);
> INSERT INTO `nm_spawn_points` VALUES (17424480,45,-269,-175,43);
> INSERT INTO `nm_spawn_points` VALUES (17424480,46,-295,-175,28);
> INSERT INTO `nm_spawn_points` VALUES (17424480,47,-290,-175,54);
> INSERT INTO `nm_spawn_points` VALUES (17424480,48,-335,-175,20);
> INSERT INTO `nm_spawn_points` VALUES (17424480,49,-326,-175,-3);
> ```

Wondering how these were generated, most spawn points have more precision (like I think are taken from a player moving around and querying with !pos to make sure there are no spawn points inside object or too close to the ground or such). Thanks for your work so far!

**Comment by TristtHXI** [comment]
I imagine Pallas has the same issue as well? cant think of any other nm that has this issue

**Comment by 0x05010705** [comment]
Tracent - Yea, I quick generated these based on character placement and truncated my coords.
I can take some time to actually do this with more precision if that is what is needed (and double checking it doesn't spawn into walls/floors).

I can also do this for Pallas too.  This is another one where it has a fixed spawn point in ASB because of the ??? trade that happens and it needing that fixed pos.

**Comment by TracentEden** [comment]
> @TracentEden - Yea, I quick generated these based on character placement and truncated my coords. I can take some time to actually do this with more precision if that is what is needed (and double checking it doesn't spawn into walls/floors).
> 
> I can also do this for Pallas too. That is another one where it has a fixed spawn point in ASB because of the ??? trade that happens and it needing that fixed pos.

Yep, if you could use more precise coordinates and check to make sure not spawning into walls and floors. Also doing for Pallas would be great! I will add your name to the Horizon PR.

**Comment by TracentEden** [comment]
@0x05010705 Bump
