### ISSUE TITLE
🐛[BUG][Quest] - Even More Gullible's Travels

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#173]
**What does this bug affect?**
When speaking with Magriffon to start the quest the cutscene will get stuck at the part pictured below. I tried in both 30 fps cap and 60 fps cap, and I even tried pressing F12 during the cutscene to see if that might get it going again but nothing worked.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/194402866-3907cd42-48e0-4d35-8f64-cbe24b875aa1.png)

**Setup Information**
Version 30220906_0

**Comment by dallano** [comment]
was the cutscene started in 60 fps? I've also heard that "print screen" can sometimes bypass this

**Comment by Squinkerdoodle** [comment]
It was started in 30 fps, I didn't try print screen

**Comment by dallano** [comment]
I'll check this quest in debug and see if I can't get any errors that are coming up preventing this quest from progressing. It might need an onEventUpdate that's not being declared or something

**Comment by Squinkerdoodle** [comment]
I just checked and print screen did not bypass it. @dallano

**Comment by dallano** [comment]
alright :) I'll check it out sometime soon here!

**Comment by dallano** [comment]
oo I think there's a problem with the NPCs not rendering in. I also had problems with this in another quest where there weren't any actors, but it still worked fine.

**Comment by CriticalXI** [comment]
I agree, watching a video of the quest Magriffon is supposed to be walking through the cutscene. I assume the npc_list entry for the Magriffon that appears in the cutscene is not put in correctly so the cutscene gets stuck. This requires a capture of the quest on retail.
