### ISSUE TITLE
🐛[BUG][System] Freezes up fishing with goldfish basket only

### ISSUE THREAD

**Issue by drixel** [HorizonFFXI/HorizonXI-Issues#1733]
**What does this bug affect?**

character gets locked in position and can't do anything. have to kill out game and relog in
**Steps to Reproduce**

put goldfish basket in ranged slot. **don't** equip the super scooper. then go to water and /fish. you will lock in position and not be able to move. you can still do the macro sets. you can still change gear with equipsets. but can't /fish anymore. can't move period. had to kill game and relog

**Expected behavior**

expected behavior should be something along the line about saying can't fish without bait or whatever
**Screenshots**

**Setup Information**

**Additional context**

**Comment by dallano** [comment]
Fixed here: https://github.com/AirSkyBoat/AirSkyBoat/pull/3408
