### ISSUE TITLE
🐛[BUG]Last TE in Dyna-Xarc did not pop upon beating the 6 Vanguard Eyes on Hill

### ISSUE THREAD

**Issue by ShadowFox85** [HorizonFFXI/HorizonXI-Issues#1737]
**What does this bug affect?**
Dynamis-Xarcabard time extension

**Steps to Reproduce**
We killed the 6 eyes on the hill after clearing all the NMs.

**Expected behavior**
 The Statue Prototype should have popped on the hill but didn't. Had to have GM pop it for us.

**Screenshots**
TE150 on the map below for reference
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/32938187/1cc7eb71-ce3b-4923-a842-36752f505674)

**Comment by 0x05010705** [comment]
I am not 100% sure if this is accurate, but I did some testing and it seems you need to kill 142 + 143 in addition to 144-149 to spawn 150.

Not killing 142 was enough to prevent 150 TE from spawning.

**Comment by TracentEden** [comment]
Yep you can see in the code the requirement to spawn 150 is currently `{"142_killed", "143_killed", "144_killed", "145_killed", "146_killed", "147_killed", "148_killed", "149_killed"},    -- Spawns 150` so need to kill 142-149, so yeah needs a fix.
`
