### ISSUE TITLE
🐛[BUG][Quest] - A Discerning Eye (Sandy)

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#174]
**What does this bug affect?**
Unable to fully start quest. Speaking with the NPC will prompt the quest start where they ask you to find the owner of a drop item and shows you what the NPC looks like, however after that it will state that the airship has already left and they'll leave the item with the authorities. This happens even if the airship is currently docked at port Sandy (before it takes off to Jeuno).

Since the quest audit sheet shows "A Discerning Eye" marked as missing / incomplete for all cities I suspect this issue is the same or at least similar across all 3 nations.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/194629845-be45ed3d-ebdd-448e-baf2-8114d19e7e5b.png)

**Setup Information**
Version 30220906_0

**Comment by The-Aerec** [comment]
I wouldn't call this p0 while it is still an issue, its impossible to code atm since there is no quest data for these perticular quests. (No captures.) TLDR: Its impossible to code atm until we go on retail and capture it a few dozen times.

**Comment by siknoz** [comment]
Did some captures of this, placing here for ease of use for Devs, also posted in capture discord.

https://youtu.be/WIsnTtcyXWs
https://youtu.be/mjjJtmU1Pew
https://youtu.be/zgEqGWx1ZEE
https://youtu.be/6Lb2gN9k73o
https://youtu.be/FRRDYU92XFo
https://youtu.be/Juqc0_hpckw
https://youtu.be/vjWg2ju5YJg
https://youtu.be/lbE3c21-wrc
https://youtu.be/BAa4uCKMF8g
https://youtu.be/BPayFa-iwLw
https://youtu.be/QI4-vsjK9_A
https://youtu.be/qvR7tvOT9I8
https://youtu.be/QRAYwFjlSb8
https://youtu.be/xEcViPd2Cv0
https://youtu.be/5rWFQYFLMlA
https://youtu.be/4MmgR7hyf1U
https://youtu.be/WIsnTtcyXWs

[A Discerning Eye.zip](https://github.com/HorizonFFXI/HorizonXI-Issues/files/10848032/A.Discerning.Eye.zip)

**Comment by siknoz** [comment]
I posted several more in the capture discord as well. Should cover all races and genders except for Hume F. I will try to get that later. But confident that there's enough captures to at least build out a good amount of the quest. I'm working on a spreadsheet of all the different equipment being used in the quest to help as well. Will post that back here when I get it done.
