### ISSUE TITLE
🐛[BUG][DAT ISSUE]Galka face5B using incorrect model

### ISSUE THREAD

**Issue by TaodR** [HorizonFFXI/HorizonXI-Issues#1743]
**What does this bug affect?**
Galka face 5B is using the custom 5C model

**Steps to Reproduce**
look at a galka with the 5B model

**Expected behavior**
black hair, is grey hair instead

**Screenshots**

**Setup Information**

**Additional context**
wrong model

**Comment by TracentEden** [comment]
This has been fixed.
