### ISSUE TITLE
🐛[BUG][NPC] Elshimo P. Fruit missing from Kazham merchant

### ISSUE THREAD

**Issue by RedricThered** [HorizonFFXI/HorizonXI-Issues#1747]
**What does this bug affect?**

The NPC merchant on the Kazham arrival dock “Ghemi Sinterilo” seems to be no longer selling Elshimo Pachira Fruits. This issue only started after the last Friday maintenance. The NPC otherwise has been selling this fruit since the start of the server and according to wiki, this fruit is in-era.
**Steps to Reproduce**

Check the NPC Ghemi Sinterilo at any given time of the day, you will see the merchandise is an incomplete list missing the Pachira Fruit.
**Expected behavior**

The NPC should carry a full stock of this item at all times. According to wiki.
**Screenshots**

**Setup Information**

**Additional context**

**Comment by TristtHXI** [comment]
They aint era lol, they came out in late 2009, 2 years after WOTG came out.

**Comment by TracentEden** [comment]
Yep, out of era
