### ISSUE TITLE
🐛[BUG] - Airship error **Unrelated to Job for the Consortium Quest**

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#175]
**What does this bug affect?**
After accepting the quest I took the airship from Sandy to Jeuno which I got stuck on and had to use !zone port jeuno command which put me at the sandy airship dock in jeuno instead of the mog house. After going through customs I went to the tenshodo shop in lower jeuno to speak with Yin Pocanakhu to give her the key item, however she only gave her normal dialogue instead of the quest dialogue. After checking my key items I then found that the Brugaire Goods key item was not in my log. After going back to the quest giver he would not talk at all when interacting with him. I even deleted the quest from my log and was unable to restart or talk to the NPC further.

Note: After deleting the quest from my log and unable to start the quest again I checked the airship to see if it happened again in that state and it worked normally for the Sandy > Jeuno and Jeuno > Sandy route.

![image](https://user-images.githubusercontent.com/112344508/194639228-8b59a799-b572-440d-9e49-e1144fa8fc47.png)

In this bugged state it was skipping stops. The picture below was when I boarded from Sandy originally and it skipped the Jeuno stop then headed back to Sandy and skipped the Sandy stop.
![image](https://user-images.githubusercontent.com/112344508/194639244-b26db5a5-be2d-4c9d-829c-6d8321c1d479.png)

**Setup Information**
Version 30220906_0

**Comment by dallano** [comment]
I cannot replicate this unfortunately. Just made a new char and ran this through and it worked perfectly.

**Comment by dallano** [comment]
I believe these errors are unrelated to the quest.

**Comment by Squinkerdoodle** [comment]
Possibly for the airship part, but I wasn't able to complete the quest itself, or pick it up again after deleting it

**Comment by dallano** [comment]
you can't get the quest until JP midnight if the quest was failed in any shape or form. I fixed his dialogue not saying anything in the meantime though. 
But give this quest another shot after JP midnight

**Comment by Squinkerdoodle** [comment]
So it counted it as a failed quest somehow? I didn't get stopped by the customs or anything. I'll give it another try tomorrow.

**Comment by dallano** [comment]
Let's relabel this. It's a bug for sure. just not from this quest.

**Comment by Ystial** [comment]
I have had this happen in-game, the only thing I did differently the one time it has happened was trying to flag Discerning Eye, while the NPC told me "the airship has already left" no matter whether the airship was arriving or boarding.
