### ISSUE TITLE
🐛[BUG] Oscar's Scarf Enchantment Does Not Work

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#1750]
**What does this bug affect?**
Oscar Scarf's enchantment: "Slightly Bad Breath" does not work when you try to use the item on a monster (both in and out of combat).

**Steps to Reproduce**
Equip an Oscar Scarf and try to use the enchantment on a mob.

**Expected behavior**
https://ffxiclopedia.fandom.com/wiki/Slightly_Bad_Breath

**Screenshots**
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/112344508/fcdf0d32-8904-4bca-b2e6-b5e698531c17)

**Comment by Frankie-hz** [comment]
There is already an issue for this: https://github.com/HorizonFFXI/HorizonXI-Issues/issues/1204
