### ISSUE TITLE
🐛[BUG][System] Harlequin's Horn Mazurka Effect

### ISSUE THREAD

**Issue by KCKBlack** [HorizonFFXI/HorizonXI-Issues#1756]
System Bug
**What does this bug affect?**
The Harlequin's Horn (Mazurka +2) does nothing to the effect of Mazurka.

**Steps to Reproduce**
/equip Range "Harlequin's Horn"
/ma "Chocobo Mazurka" <me>

**Expected behavior**
Increase duration of Chocobo Mazurka by 20 seconds (to 140 seconds total)

**Screenshots**

**Setup Information**
HorizonXI Version 1.2

**Additional context**
[](https://github.com/AirSkyBoat/AirSkyBoat/pull/3437)
Possible fix being attempted.

**Comment by nixyyyy** [comment]
This seems to work on ASB. Could be wrong though, been wrong before.

**Comment by KCKBlack** [comment]
Sorry I guess I don't understand what that means.  It definitely does not
work in game.

**Comment by nixyyyy** [comment]
https://github.com/AirSkyBoat/AirSkyBoat/pull/3437

The fix is in the upstream repository and will make it in the game soon.
