### ISSUE TITLE
🐛[BUG][NPC]Mashii-Ajuu[Quest]Reap What You Sow

### ISSUE THREAD

**Issue by jcp3alex** [HorizonFFXI/HorizonXI-Issues#1757]
[BUG][NPC]Mashii-Ajuu[Quest]Reap What You Sow

**What does this bug affect?**
Unable to flag quest

**Steps to Reproduce**
I was rank 9 when I attempted to begin this quest. According to the wiki, he will not give you the quest at or above rank 4, unless you complete 'Let Sleeping Dogs Lie'. I tried talking to Mashii-Ajuu before flagging 'Let Sleeping Dogs Lie', but he would not give it to me. So I completed 'Let Sleeping Dogs Lie', but he would still not give me the quest. I tried zoning and logging out, nothing has worked.

**Expected behavior**
I should have been able to flag 'Reap What You Sow'.

**Setup Information**
V1.1.1 (update #3)

**Additional context**
This is what he says when you try talking to him:

Mashii-Ajuu: Pakuu-Nakku's attitde to learning is so bad. He's always half-asleep in class lately.
Mashii-Ajuu: His consistent yawning gets on my nerves. If only there was some spell to stop yawning, I'd soon fix him!
---------------------------‐--‐----------------------------------
Mashii-Ajuu: Tsk. Don't tell me another adventurer has wandered into our class with eyes wide open in wonder...
Mashii-Ajuu: I know our school is liberal and open to all and all that, but I don't see why that means any ill-manered trespasser can walk in and disturb our studies.

**Comment by nixyyyy** [comment]
```lua
check = function(player, status, vars)
            return status == QUEST_AVAILABLE and
            (player:getFameLevel(xi.quest.fame_area.WINDURST) < 4 or
            player:hasCompletedQuest(xi.quest.log_id.WINDURST, xi.quest.id.windurst.LET_SLEEPING_DOGS_LIE))
        end,
```

I do not know if this is in the game or not but it has been on ASB for 5 months now.
