### ISSUE TITLE
🐛[BUG][System]Dragon Fruit Obtainable - Out of Era

### ISSUE THREAD

**Issue by AyameCat** [HorizonFFXI/HorizonXI-Issues#1763]
**What does this bug affect?**
Logging in the Jungles may yield Dragon Fruit - https://ffxiclopedia.fandom.com/wiki/Dragon_Fruit

**Steps to Reproduce**
I have logged Dragon Fruit a few months ago, and I logged some yesterday (9/26/2023). 

**Expected behavior**
Dragon Fruit should not be obtainable during this era - fandom wiki shows first history of November 2007. 

**Screenshots**
![dragonfruit](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/146265289/1bca7a86-94c3-4cbe-8877-05ed1200db8a)

**Setup Information**

**Additional context**
Even though this is an out of era item, it could be Era+'d into the game and have the Dragon Fruit au Lait recipe added. There is currently no Auction House history of this item (Dragon Fruit au Lait).

**Comment by clanofartisans** [comment]
This item only has one synth and it is flagged as `ABYSSEA` in the Horizon repo right now:
[HorizonXI/modules/era/sql/synth_recipes_era.sql ~ Line 2142](https://github.com/HorizonFFXI/HorizonXI/blob/a73b412328ce2c203f78518d637445cf87050cc7/modules/era/sql/synth_recipes_era.sql#L2142C1-L2142C108)

It appears, though, that both the item and the corresponding synth should both have been flagged as Wings. Will talk to balance or someone to see if they want to add the synth or remove the item.
