### ISSUE TITLE
[BUG] Combat - Death Scythe HP drain 6x larger than Death Scythe +1

### ISSUE THREAD

**Issue by Hinxter** [HorizonFFXI/HorizonXI-Issues#1765]
I have tested the Death Scythe and Death Scythe +1, and the HP drain on the NQ weapon is on average 30-60 hp, whereas on the Death Scythe +1 it is 5-10 hp.

This was tested using both weapons on the Aura Statues in Ullikimi room.

I would expect the HP drain to be the same for both weapons - I have tested this on other mobs too with the same effect.

I assume that the NQ HP drain was buffed for Horizon, but perhaps the same buff wasn't applied to the +1 weapon.

I have attached 2 Screenshots of HP drain AE with the HQ weapon and 2 with the NQ weapon on the Aura Statues. The first two Screenshots are with the HQ scythe, and the second two with the NQ one.

![Kamazu_2023 09 27_144017 HQ](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/146362112/d4d6a5e0-f5d3-4f98-9566-e633dbb1eaf5)

![Kamazu_2023 09 27_144117 HQ](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/146362112/4f3f5b65-36a9-44dc-ae5f-9b178e2593de)

![Kamazu_2023 09 27_145447 NQ](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/146362112/18d8c001-6fdd-4b4c-bcf8-8feb0b8e78a7)

![Kamazu_2023 09 27_145746 NQ](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/146362112/68d4c331-3600-43da-abe9-bf11ac156222)

**Comment by nixyyyy** [comment]
```-- Death Scythe
INSERT INTO `item_mods` VALUES (16777,431,5);  -- ITEM_ADDEFFECT_TYPE: 5
INSERT INTO `item_mods` VALUES (16777,499,21); -- ITEM_SUBEFFECT: 21
INSERT INTO `item_mods` VALUES (16777,500,60); -- ITEM_ADDEFFECT_DMG: 60
INSERT INTO `item_mods` VALUES (16777,501,10); -- ITEM_ADDEFFECT_CHANCE: 10
INSERT INTO `item_mods` VALUES (16777,950,8);  -- ITEM_ADDEFFECT_ELEMENT: 8```

```-- Death Scythe +1
INSERT INTO `item_mods` VALUES (16791,431,5);  -- ITEM_ADDEFFECT_TYPE: 5
INSERT INTO `item_mods` VALUES (16791,499,21); -- ITEM_SUBEFFECT: 21
INSERT INTO `item_mods` VALUES (16791,500,10); -- ITEM_ADDEFFECT_DMG: 10
INSERT INTO `item_mods` VALUES (16791,501,10); -- ITEM_ADDEFFECT_CHANCE: 10
INSERT INTO `item_mods` VALUES (16791,950,8);  -- ITEM_ADDEFFECT_ELEMENT: 8```

this is a one line change, only I am not sure which value is correct

**Comment by Hinxter** [comment]
Has this change been released yet? My DS+1 is still draining for 10
