### ISSUE TITLE
🐛[BUG][Combat] WHM job ability 'Devotion' missing 5%

### ISSUE THREAD

**Issue by SpaggiG** [HorizonFFXI/HorizonXI-Issues#1767]
**What does this bug affect?**

Currently on horizon, white mage learn devotion while leveling, in the code where it checks for merit categories it sees 0. this incurs an unintended -5% mp efficiency on use.

**Steps to Reproduce**

Have 1000 hp, use devotion, lose 250 hp, target only gains 200 mp

**Expected behavior**

Have 1000 hp, use devotion, lose 250 hp, target only gains 250 mp

**Additional context**

![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/118819208/d34e78ef-89e5-4594-b20d-23c40e0fbdb0)

**Comment by nixyyyy** [comment]
I am not sure how to test this but looking at the code I assume this should be changed to ```player:getMerit(xi.merit.DEVOTION) * 5```
