### ISSUE TITLE
🐛[BUG][Quest] - A Timely Visit

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#177]
**What does this bug affect?**
When on the step where you click on the ??? at F-5 in Jugner Forest it is not spawning the 2 NMs for the quest. It gives no dialogue when clicking the ??? or any interaction.

**Expected behavior**
When you go through King Ranperre's Tomb and get to the Jugner Forest section behind it (King Arthro's area) and click on the ??? at F-5 during nighttime (18:00 - 6:00) it should spawn the 2 NMs: 
Giollemitte B Feroun (paladin fomor https://ffxiclopedia.fandom.com/wiki/Giollemitte_B_Feroun )
Skeleton Esquire (Dark Knight skele https://ffxiclopedia.fandom.com/wiki/Skeleton_Esquire )

**Setup Information**
Version 30220906_0

**Additional context**
I tried clicking multiple times during the night from 18:00 to 6:00 the next day.

**Comment by dallano** [comment]
Fix incoming
