### ISSUE TITLE
🐛[BUG][System] Gold Earring Desynth Recipe Does Not Exist

### ISSUE THREAD

**Issue by CarmineCarnage** [HorizonFFXI/HorizonXI-Issues#1770]
**What does this bug affect?**
Gold Earring desynth

**Steps to Reproduce**
Use a Lightning Crystal on a Gold Earring

**Expected behavior**
Gold Earring should be  able  to be  desynthesized  into  1-2 Gold Ingots since 2005 era  or  earlier

**Comment by nixyyyy** [comment]
https://github.com/AirSkyBoat/AirSkyBoat/pull/3506
