### ISSUE TITLE
🐛[BUG][ITEM/SYSTEM] Carbuncle's Cuffs cast time reduction "added" but not working

### ISSUE THREAD

**Issue by Clonegoat** [HorizonFFXI/HorizonXI-Issues#1771]
**What does this bug affect?**
Carbuncle's Cuffs were patched today (10/6/23) to receive both of the listed effects. The cast time reduction is not working. Cast times are still the same as without the gloves equip

**Steps to Reproduce**
Casted carbuncle without gloves, took roughly 7.25 seconds 0-100% and roughly one second less to get the "completion" of spell at 80%
Casted carbuncle with gloves, same time as above on both 0-100% and 80%

**Expected behavior**
I'm not sure what -1 exactly equates to, but I would assume it to mean one second faster

**Screenshots**
NA

**Setup Information**
/version is not working today, so it's the fresh (10/6/23) patch on Windows 11

**Additional context**
The Shining Ruby half of the gloves is working as intended though

**Comment by nixyyyy** [comment]
https://github.com/LandSandBoat/server/pull/4589

**Comment by Clonegoat** [comment]
> [LandSandBoat/server#4589](https://github.com/LandSandBoat/server/pull/4589)
> 
> I misunderstood the mod based on the description in a comment and it currently has avatar recast reduction -1 second.

Understandable! I've just been excited for these to function so when the patch went out and they still weren't, I was bummed and had to come report it quickly was all. Appreciate your work!
