### ISSUE TITLE
🐛[BUG][Combat] Ancient Goobbue does not have claim shield

### ISSUE THREAD

**Issue by amille14** [HorizonFFXI/HorizonXI-Issues#1773]
**What does this bug affect?**
The NM Ancient Goobbue was recently added to the game but does not have claim shield.

**Steps to Reproduce**
Claim Ancient Goobbue and it immediately goes claimed.

**Expected behavior**
Should have claim shield.

**Comment by TracentEden** [comment]
Yep, we see that it is quite popular and we will add a shield, watch patch notes for when the shield is introduced. Thanks for reporting!
