### ISSUE TITLE
🐛[BUG][Item] Evoker's Boots (era+) Hidden Effect?

### ISSUE THREAD

**Issue by Clonegoat** [HorizonFFXI/HorizonXI-Issues#1777]
**What does this bug affect?**
I've been made to believe that the Lv71 Evoker's Boots that drop from Prehistoric Pigeons (DEF:11 MP+20 MND+2 Enm-2) were era+d to have an hidden effect of "Avatar Cast Time -#" to them.

**Steps to Reproduce**
 After much testing of off(vs)on, compared to the recently fixed Carbuncles Cuffs (cast time-1) and tested with the cuffs, I can conclude there is no such effect present. 

**Expected behavior**
If the hidden effect is truly era+d in, I believe they were meant to have the same effect as Carby Cuffs of Avatar Cast Time -1 to them

**Screenshots**
![1123123](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/80860333/a6d2de90-00cb-4bca-b1b6-170e638bf3ab)

**Setup Information**
/ver or /version no longer provide version number instead only /ver states "version psfiles date[0:0:0]"

**Additional context**
On Discord where discussion of the Carbuncle's Cuffs (at the time, broken) effect, it was made apparent "it seems we don't have a mod for summoning magic cast time..." which leads me to believe the era+ effect was indeed intended, but also improperly implemented as it was with the cuffs.

**Comment by nixyyyy** [comment]
They do have the effect. I missed it because ASB does not have the mod for it. We should probably update Evoker's Boots to use the mod I pushed to LSB though. Thanks for bringing this up!
