### ISSUE TITLE
🐛[BUG][Combat] The Wasps are Morbols!

### ISSUE THREAD

**Issue by SulreverRaz** [HorizonFFXI/HorizonXI-Issues#1779]
**What does this bug affect?**
The Canyon Wasps in Tahrongi Canyon have Morbol TP moves, Including Impale, Vampiric Lash, Sweet Breath, and Bad Breath. Not only is it kind of scary but it also sometimes causes the whole game to crash, though the crash is inconsistent.
**Steps to Reproduce**

Engage with the the Canyon Wasp and feed TP until it uses a skill. Every TP skill it used was that of the Morbol class.
**Expected behavior**

**Setup Information**

Both game and launcher versions are current and up to date. Operating system is Windows 10.
**Additional context**

It seems to only be the Canyon Wasps specifically. The Killer Bees retain their movesets. The Canyon Wasps don't seem to have any other Morbol characteristics. They are charmable, non aggressive, and drop the right loot.
![Razaell 10_16_2023 2_07_51 PM](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/148138766/eb5ad326-2d94-49fb-b9af-391437dd2f88)
![Razaell 10_16_2023 2_08_55 PM](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/148138766/50fa3638-617e-415a-b4ab-251151f12704)
![Razaell 10_16_2023 2_14_55 PM](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/148138766/c81c5c07-b4c4-40fd-90a6-8482306e7805)

**Comment by nixyyyy** [comment]
I have an open PR on the hxi repository that fixes this.
