### ISSUE TITLE
🐛[BUG][Quest] - Spice Gals

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#178]
**What does this bug affect?**
Unable to start quest. When speaking with the quest giver she only gives the below dialogue and gives nothing about a quest, nor does it show up in the quest log.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/194668922-f5c72065-ad49-4b97-8869-4dfd14da54f7.png)

**Setup Information**
Version 30220906_0

**Comment by dallano** [comment]
What COP mission are you on?

**Comment by Squinkerdoodle** [comment]
At the moment, completed Dawn. (I was able to start Storms of Fate / Shadows of the Departed)

**Comment by dallano** [comment]
ope. found the issue. Dumb mistake. Fix incoming lol
