### ISSUE TITLE
[BUG][Combat] Automaton Assault ENM has wrong enemy model and behavior

### ISSUE THREAD

**Issue by rmrmrmrmr** [HorizonFFXI/HorizonXI-Issues#1781]
**What does this bug affect?**
The Tarutaru Automaton in the Automaton Assault ENM appears as a second Hume, having the correct damage resistance and traits for Tarutaru (Fast Cast, weak to physical), but using the Hume's model and spell list of -aga II spells.

**Steps to Reproduce**
Be a Mithra in a solo party.
!zone 13
!addkeyitem shaft_gate_operating_dial
Enter Automaton Assault ENM.

**Expected behavior**
Tarutaru Automaton should be a Tarutaru and cast only ancient magic.

**Screenshots**
![automato](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/118459286/8b8a47db-6d6d-425b-bf6b-8029fc6ff633)
![humetaru](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/118459286/0f89be80-4e61-4ceb-8ff4-44997e094989)

**Comment by nixyyyy** [comment]
is this an issue on live or your local server?

**Comment by nixyyyy** [comment]
Interesting, I guess the module was loaded for some reason. I'll see if anyone knows more about it.
