### ISSUE TITLE
🐛[BUG][System] Bottom option for the Summoner category merits does nothing (not for elemental spirits either).

### ISSUE THREAD

**Issue by catcatwaffleiron** [HorizonFFXI/HorizonXI-Issues#1782]
In Summoner category of merit points, the bottom option doesn't work.

It doesn't lower summoning magic cast time like the text says.
But also it doesn't lower elemental spirits perpetuation cost like it should do in era.
It should do something.

**Comment by nixyyyy** [comment]
This was my fault and happened when I created a mod for Carbuncle's Cuffs on LSB not knowing we already had it on Horizon. I have a PR open that updates all the references to the old mod. Sorry about this.
