### ISSUE TITLE
🐛[BUG] Beastmaster Charmed Pet Death

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#179]
**What does this bug affect?**
When a Beastmaster dies with a charmed mob the charmed mob will despawn as if it was a jug pet (Call Beast)

**Steps to Reproduce**
As a Beastmaster, die when you have a charmed pet.

**Expected behavior**
When a beastmaster dies with a charmed mob the charmed mob should stay alive and go back to it's unclaimed state.

![image](https://user-images.githubusercontent.com/112344508/194687204-16dbd31f-aa0f-4157-8424-97229909bb45.png)
![image](https://user-images.githubusercontent.com/112344508/194687208-1efc8c60-c3f5-42e0-8548-6d2ca233c6a5.png)

**Setup Information**
Version 30220906_0

**Comment by OpheliaXI** [comment]
Resolved with a previous change.

**Comment by Frankie-hz** [comment]
still happening

**Comment by Squinkerdoodle** [comment]
Still having the same issue reported above as of 10/28

**Comment by OpheliaXI** [comment]
Closed by https://github.com/AirSkyBoat/AirSkyBoat/pull/606
