### ISSUE TITLE
🐛[BUG][Combat] Groundskeeper Sight Aggro 

### ISSUE THREAD

**Issue by Scarifi3dXI** [HorizonFFXI/HorizonXI-Issues#18]
**What does this bug affect?**
Zone mechanics, mob mechanics

**Steps to Reproduce**
N/A Can be observed by traveling to Ru'Aun and attempting to aggro by not staying in the middle of path around Despot spawn. 

**Expected behavior**
Stationary Groundskeepers in the portal spawn areas should sight aggro if you stray too far from the middle of the alley to Ru'Avitau starting at H-10. 

**Screenshots**
![image](https://user-images.githubusercontent.com/112238268/187603368-b11c5627-2815-4f3d-9f02-daa5ca11fe2a.png)
**_Well within aggro range, yet safe._**
![image](https://user-images.githubusercontent.com/112238268/187603633-b2c4aa23-e69f-430f-ab18-236fc91305c2.png)
**_Wallhack flag on and dead Groundskeeper after successful aggro as noted below_**

**Setup Information**
ver.30220802_3 Up to date with retail client (active retail player)

**Additional context**
If you enable wallhack and zone into the step one of the Groundskeeper portals, this will aggro it. Possible mob height/aggro mechanics issue.

**Comment by CriticalXI** [comment]
This is a navmesh issue which I already poked Aerec about a bit ago. Hoping to fix this before launch.

**Comment by The-Aerec** [comment]
I think the proper solution is to make a mod that allows mobs to aggro +/- y an amount

**Comment by The-Aerec** [comment]
Closed with latest ASB MR
