### ISSUE TITLE
🐛[BUG][NPC] Era+ Scowlenkos Uleguerand Range Missing

### ISSUE THREAD

**Issue by scoobwrx** [HorizonFFXI/HorizonXI-Issues#1800]
**What does this bug affect?**
Attempted to party last night on the era+ eyes but they were not up in their location, GM said to open a bug report. Unsure how long they have been missing as we just went up last night assuming they were functioning as expected.

**Steps to Reproduce**
Mobs are missing at location in title.

**Expected behavior**
Era+ eyes spawn at G7 in Uleguerand Range

**Screenshots**

**Setup Information**

**Additional context**
Contacted GM and they instructed to open a bug.

**Comment by KiplingFFXI** [comment]
This is not a bug. These were replaced intentionally with another mob family per the patch 1.2 patch notes.
