### ISSUE TITLE
🐛[BUG][System] Mog Wardrobe 8 Some event items not storing

### ISSUE THREAD

**Issue by RedBaren** [HorizonFFXI/HorizonXI-Issues#1805]
**What does this bug affect?**

A lot of the Cosmetic/event items are not able to be placed into Mog Wardrobe 8. I checked with multiple people having same results on Linkshells. None of the Easter items, half of the Christmas Santa +1 gear, the Summer Event hammer, and half of the Halloween staffs.

**Steps to Reproduce**

Tried moving items from Inventory into Mog Wardrobe 8. They're not greyed out and show they can be moved but will not transfer

**Expected behavior**

Event Items able to be stored in Mog Wardrobe 8. 

**Setup Information**

Version 1.2

**Comment by klostrophobik** [comment]
Pitchfork +1 and the Trick Staff II are the only 2 staffs from Halloween not storing.  Aern Axe is also not storing in Wardrobe 8.

**Comment by RedBaren** [comment]
All items seem to have been fixed that are worth saving not as a doubles item like NQ when there's a HQ
