### ISSUE TITLE
🐛[BUG][System/Combat] Aw'euvhi Drop Tables

### ISSUE THREAD

**Issue by Mystique-FFXI** [HorizonFFXI/HorizonXI-Issues#1808]
**What does this bug affect?**

Spent 2 hours in The Garden of Ru'Hmet fighting Aw'euvhi with no drops other than 2 seals. We had TH4. I know it is relatively a low drop rate on organs, but to get absolutely nothing from their drop table after 20+ kills seems wrong. An LS mate went 0/40+ when he was out there previously which made me think the drop table might be bugged.

**Steps to Reproduce**

Conversely, we were in Grand Palace of Hu'Xzoi and killed only a few Eo'euvhi before getting a couple of euvhi orgains. A MUCH lower drop rate on those.

**Expected behavior**

Drop rates for Aw'euhvi are at 7% for organ, HQ organ, and tissue. We saw nothing drop from them.

**Screenshots**

**Setup Information**

Game v1.2.0 (update #6)

**Additional context**

Thinking that maybe since the Aw'euvhi in Al'Taieu have nothing in their drop table that the two versions are somehow linked or swapped.

**Comment by TracentEden** [comment]
This should now be fixed.
