### ISSUE TITLE
🐛[BUG] Fomor pets not despawning with master in Lufaise

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#181]
**What does this bug affect?**
Fomor pets (SMN / BST / maybe DRG?) are not despawning when their master despawns at dawn. I witnessed this in Lufaise Meadows but may be happening in other zones as well.

**Expected behavior**
Fomor pets should despawn alongside their master when they despawn at dawn.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/194730971-5b54f1f1-7749-4a48-ae08-c1852ce68743.png)

**Setup Information**
Version 30220906_0

**Comment by dallano** [comment]
nice catch, mang <3
