### ISSUE TITLE
🐛[BUG][Combat] Bully and sneak attack damage

### ISSUE THREAD

**Issue by catcatwaffleiron** [HorizonFFXI/HorizonXI-Issues#1812]
**What does this bug affect?**
Sneak attack does increased damage from any direction when used on a monster with bully effect on.

**Steps to Reproduce**
Use bully on an enemy, use sneak attack, hit enemy from front. It won't be critical hit like normal sneak attack but it does increased damage.

**Expected behavior**
Patch notes made it sound like bully shouldn't affect sneak attack at all.

**Comment by TracentEden** [comment]
Will be fixed by https://github.com/HorizonFFXI/HorizonXI/pull/1569
