### ISSUE TITLE
🐛[BUG][System] HQ Rates

### ISSUE THREAD

**Issue by Traguwu** [HorizonFFXI/HorizonXI-Issues#1822]
System
**What does this bug affect?**
HQ Crafting

**Steps to Reproduce**
Unkown, unsure what caused

**Expected behavior**
Given the odds atleast one HQ across all my crafts would be guaranteed.

**Screenshots**

![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/154031962/5d392650-f8b9-459e-b125-4fe1dafbfb53)
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/154031962/c7d688f4-14f0-40ed-90a1-4dff5b091683)

**Setup Information**
game version v1.2.1

**Additional context**
Crafting after the recent Update 16/12/23. unable to HQ any item to impossible odds. HQ2 at 25% chance over 20 crafts equates to a 99.683% chance of atleast one HQ. yet none occured. This also extended to other materials (ebony logs) that were also not HQ's but not caught on a screenshot. Correct Synth Support, Apron, Gloves and Mogenhancement were used.

**Comment by The-Aerec** [comment]
I've checked and everything seems fine with crafting and our rng seed. Thanks for the report.

**Comment by Traguwu** [comment]
> I've checked and everything seems fine with crafting and our rng seed. Thanks for the report.
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/154031962/e8e0400e-42db-4aee-a686-b5e4a5f48044)
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/154031962/6020ce6a-b93f-47d1-8e2b-7774eac7e866)

Appreciate your quick response but .... that aint right
