### ISSUE TITLE
🐛[BUG][Quest] - A Chocobo's Tale

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#183]
**What does this bug affect?**
Unable to start quest, even at rank 9 fame in Jeuno and having completed the CoP mission A Vessel Without A Captain (PM3-2). NPC Nevela only gives the dialogue in the picture below and quest does not show up in the quest log.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/194731040-9bd46ba7-f970-49e7-bddc-7d756611fcf0.png)

**Setup Information**
Version 30220906_0

**Comment by dallano** [comment]
Can't replicate. I just tested and works perfectly fine for me. I'll try on horizon box rn

**Comment by dallano** [comment]
oh derp
it isn't on horizon box yet. sorry!

**Comment by CriticalXI** [comment]
Implemented in AirSkyBoat/AirSkyBoat#435

Could use a review to ensure it is functioning correctly
