### ISSUE TITLE
🐛[BUG][Quest] Regression on Aroma Fly in Gusgen Mines - RSE sachet drop rate seems to be broken again

### ISSUE THREAD

**Issue by RoseMokka** [HorizonFFXI/HorizonXI-Issues#1830]
**What does this bug affect?**
For many weeks now, I haven’t been able to drop the RSE sachet from the Aroma Fly in Gusgen Mines.
I’ve killed the monster 51 times, including 6 times with TH4, 2 times with TH2 and the rest with TH1.
I’ve asked on the discord about it and the returns were unanimously the same: some have been 0/65 lately, others went to other NMs in Shakhrami or Ordelles and got their RSE sachet there.

That NM appeared to have received a fix some months ago. Maybe a regression in the fix has occurred, leading all of us to waste our time trying, thinking about a bad rng, but it’s obviously not the case.

**Steps to Reproduce**
- Be on your RSE week IG;
- Check the ??? That appears in Gusgen Mines ;
- Fight and kill the Aroma Fly for a representative number of times to correlate with the supposed drop rate (~15%).

**Expected behavior**
According to current and previous wiki pages, the drop rate is between 13,7 and 15%.
0/51, or 0/65 is not bad RNG…

Thank you!

**Comment by TracentEden** [comment]
This has now been fixed.
