### ISSUE TITLE
🐛[BUG] Fast Cast I/II/III Job trait not providing recast bonus

### ISSUE THREAD

**Issue by post32015** [HorizonFFXI/HorizonXI-Issues#1831]
**What does this bug affect?**
Fast Cast I/II/III Job Trait.

**Steps to Reproduce**
Stoneskin has a default 30s Recast.
Gravity has a default 60s Recast.

While casting these spells wearing no gear as 75RDM , I would expect to have a recast time of 27s for Stoneskin and 54s for Gravity.  This is not the case.  I still get the standard 30s/60s recast.

I went outside and cast Gravity and got the same results as the Stoneskin test.

I equipped RDM AF Hat and RDM Relic Body which should give a 20% Fastcast and 10% Reduction. and my recast indeed reduced to 27s/54s as expected with a 10% reduction.
Equipping gear with Fast Cast gave me the expected reduction in Recast.

**Expected behavior**
Per the Horizon Wiki, this is the expected behavior.
Fast Cast I:  10% Fast Cast.  5% Recast reduction.
Fast Cast II:  15% Fast Cast.  7.5% Recast reduction.
Fast Cast III:  20% Fast Cast.  10% Recast reduction.

**Screenshots**

**Setup Information**
HorizonXI v1.2.1 (update #7)
**Additional context**

**Comment by TracentEden** [comment]
This should be era+ values of 2.5%, 1.25%, and 1.25% recast reduction, will be fixed.
