### ISSUE TITLE
🐛[BUG][Combat] Gungnir 2.5x damage proc is only 2x.

### ISSUE THREAD

**Issue by VellhartWasTaken** [HorizonFFXI/HorizonXI-Issues#1832]
**What does this bug affect?**

The 2.5x damage proc from Gungnir doesn't seem to be working correctly.

**Steps to Reproduce**

Hit some Lv1 enemies in a starter zone and multiply your damage by 2.5x and see that it's higher than any number achieved with a proc. Multiplying by 2x shows the correct number.

**Expected behavior**

Proc should be 2.5x damage instead of 2x.

**Screenshots**

https://imgur.com/a/YqHeHBY

**Setup Information**

**Additional context**

**Comment by TracentEden** [comment]
@VellhartWasTaken The 2x value is probably from the [JP wiki site for Gungnir](https://wiki.ffo.jp/html/2398.html), as this is generally more accurate than other wikis). If you have any data supporting 2.5x value can post as would be helpful.

**Comment by VellhartWasTaken** [comment]
There's no way I could ever provide any further data. I was just going by all the other wikis that have it at 2.5x. I don't have a Lv75 retail Gungnir and any pictures I could find wouldn't be enough proof that it was a retail account with the base weapon.

**Comment by TracentEden** [comment]
> There's no way I could ever provide any further data. I was just going by all the other wikis that have it at 2.5x. I don't have a Lv75 retail Gungnir and any pictures I could find wouldn't be enough proof that it was a retail account with the base weapon.

I mean data like any era forum or blog postings describing testing, does not have to be your actual testing.

**Comment by VellhartWasTaken** [comment]
I'll see what I can dig up. It's hard to get good information from that time, as I'm sure you're aware, with most links to pictures being dead. (on top of Gungnir not being a largely desired weapon compared to others to begin with)

**Comment by TracentEden2** [comment]
We have someone on retail doing testing so will be able to determine if 2.0 or 2.5 and thus can fix it it is incorrect.

**Comment by TracentEden** [comment]
We have someone on retail doing testing so will be able to determine if 2.0 or 2.5 and thus can fix it it is incorrect.

**Comment by TracentEden** [comment]
> I'll see what I can dig up. It's hard to get good information from that time, as I'm sure you're aware, with most links to pictures being dead. (on top of Gungnir not being a largely desired weapon compared to others to begin with)

The results of retail gungnir testing shows that out of 400 normal hits the ratio between of average of high damage hits to average of low damage hits is 2.0048, thus confirming the 2.0 value. As mentioned if there are any era data available that shows an different value then feel free to reopen the issue.
