### ISSUE TITLE
🐛[BUG][BRD song stacking]

### ISSUE THREAD

**Issue by amawnkey** [HorizonFFXI/HorizonXI-Issues#1836]
**What does this bug affect?**
BRD can effectively stack as many songs as they can cast before having to restart their rotation

**Steps to Reproduce**
The process we know of right now is:
1) Set one character up as BRD main job
2) Set another character up as BRD sub job in the same party
3) Have the BRD sub sing any group song such Mage's Ballad or Army's Paeon
4) Before the BRD sub's song expires, have the BRD main play the exact same song
5) The BRD sub is now free to cast another song, and the BRD main can keep every song the sub sings going limited only by how fast they can cast and how long a duration they can apply to each song

The strength of songs depends on the BRD main's stats and *is* affected by Soul Voice

**Expected behavior**
BRD mains should only be able to put up two songs each, BRD subs should only be able to put up one

**Screenshots**
48BRD/NIN and 48DRK/BRD with 9 songs running
![nine-songs-brd-drk](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/155277297/f3bb5ae0-a66a-43a2-8d52-f9f4281b4a08)

**Setup Information**
Game version 1.2.1

**Additional context**

**Comment by overefined** [comment]
this is already fixed upstream
