### ISSUE TITLE
🐛[BUG][System] Accidentally duped shihei

### ISSUE THREAD

**Issue by RedricThered** [HorizonFFXI/HorizonXI-Issues#1837]
**What does this bug affect?**

I would like to report a possible dupe that I encountered. Here is what happened:
1) I had 3 tool bags of shihei left in my inventory. And 0 shihei.
2) Before heading to camp, I purchased a new stack of 12 shihei toolbags from the AH. 
3) When I arrived at camp, realizing I had 0 shihei,  so I used all 3 tool bags that I previously had. 
4)  I looked back at my inventory I found 10 extra shihei tool bags had appeared, in addition to the 12 I just purchased.

See screenshot.

**Steps to Reproduce**

As above
**Expected behavior**

Perhaps this is a one off-bug? maybe it cannot be reproduced, not sure.
**Screenshots**

![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/143734821/f2d3e73c-e279-48cb-8357-d9ccb483e9a1)
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/143734821/e73f6b67-6f55-4437-8f26-c16c46151df1)
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/143734821/ebb1dc48-aa08-40a4-845a-924a7d283157)

**Setup Information**

**Additional context**

**Comment by Flam9** [comment]
No reproducible steps. Possibly had the extra 10 from before and didnt notice.
