### ISSUE TITLE
🐛[BUG]Mithra Model changed after first login

### ISSUE THREAD

**Issue by nubbi** [HorizonFFXI/HorizonXI-Issues#1838]
**What does this bug affect?**
Appearance of player model (Mithra 6C) changed (to Mithra 3B) on second login

**Steps to Reproduce**
Mithra model 6C was created, loaded properly on first login, on second login Mithra model 3B appeared on character selection screen and in game

**Expected behavior**
Mithra model 6C should be loaded properly

**Screenshots**
-

**Setup Information**
Microsoft Windows 10 Enterprise
Game v1.2.1 (update #7)
Launcher v1.2.4

**Additional context**
HorizonXI Launcher and website do show the correct model image

**Comment by nubbi** [comment]
Model just switched back for whatever reason. I had logged in for many times with the wrong model and just like that it switched back..

**Comment by Flam9** [comment]
You probably used a different install without the custom models for a while, or used an addon that changed your look.

Nothing changes the model seection server side and the fact it recovered points to a client issue
