### ISSUE TITLE
🐛[BUG][Combat] Claim Shield being bypassed

### ISSUE THREAD

**Issue by HydroMerano** [HorizonFFXI/HorizonXI-Issues#1839]
**What does this bug affect?**
It affects the Notorious Monster Claim Shield

**Steps to Reproduce**
Utilize a status effect the monster is immune to, such as:
Applying Charm/Stun to a monster immune to it
Bypass Claim Shield

**Expected behavior**
Claim Shield should activate and allow for a window where others can attempt to 'tag' the NM and perform a lottery roll for who gets the actual claim.

**Screenshots**
See Attached Image
![Claim Shield bypass](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/155566626/1ee958a1-91d9-4849-9eb7-f19ca5b45008)

**Setup Information**
N/A

**Additional context**
It appears that any status effect that touches a NM that its immune to, grants the claim immediately to the person afflicting the status.

**Comment by Flam9** [comment]
The described behavior isn’t happening on retail. Not a bug
