### ISSUE TITLE
🐛[BUG][Combat] Monk Kick Attack does full damage.

### ISSUE THREAD

**Issue by Skold177** [HorizonFFXI/HorizonXI-Issues#184]
Monk kick attack currently does full damage like a normal hit and seems to be getting the bonus from your H2H Weapon

Kick attack damage should be equal to your H2H damage without a weapon equipped, currently it does equal damage to a normal hit.

**Comment by Skold177** [comment]
Kung-Fu Shoes seem to not be applying extra damage either - will retest once kick attack formula is fixed.

**Comment by OpheliaXI** [comment]
Closed with https://github.com/AirSkyBoat/AirSkyBoat/pull/478
