### ISSUE TITLE
🐛[BUG][Quest - Jueno "Save my Sister"]

### ISSUE THREAD

**Issue by RunisPrime** [HorizonFFXI/HorizonXI-Issues#1848]
Unable to light all 4 Braziers > turn in the quest for completion
Upon lighting 1 Brazier, the other 3 don't react. Baudin does not accept quest as complete.
EDIT:
Update, GM changed values to re-flag quest. It is now working as intended.
RESOLVED.

**Comment by jamesbradleym** [comment]
Unable to reproduce - upon interacting with each Brazier in order the lantern lights as expected. Interacting with the Braziers out of order extinguished the flame as expect. When interacting with a Brazier out of sequence the Brazier no longer interacts with the lantern.

Do you have any other details/notes to help track this down?

**Comment by RunisPrime** [comment]
GM changed values to re-flag quest. It is now working as intended.
