### ISSUE TITLE
🐛[BUG][Quest] - A Bitter Past

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#186]
**What does this bug affect?**
When obtaining the key item after fighting the 2 orc NMs, the key item name is missing from the chat log entry pictured below (Though it does still show up properly in your Temp Key Items log). Additionally when turning in the key item the NPC does not give a cutscene and only gives a brief dialogue with the reward at the end, and the extra optional cutscene with Equette is not playing when talking to her after completing the quest.

**Expected behavior**
Key item name should show in the chat log entry when obtaining it. Turning in the key item should trigger a cutscene as seen in the video, and you should be able to get an additional optional cutscene when talking with Equette after completing the quest (starting around timestamp 2:46): https://youtu.be/X0G6GdA0r-A?t=166  
Currently Equette gives a different cutscene about a monster hiding a linkshell.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/194917684-68f84b55-008c-4334-bd25-15e6d07ea473.png)
![image](https://user-images.githubusercontent.com/112344508/194917541-8c2323d9-e7fa-448b-a974-a445e01ac0f0.png)

**Setup Information**
Version 30220906_0

**Additional context**
No capture available on the discord, had to go off of one I found on youtube from 2015, but should be fine for the cutscene issue. After these issues are fixed this should be fine to be set to "Exists" on the audit sheet as the rest of the quest works fine.

**Comment by dallano** [comment]
Fix incoming here: https://github.com/AirSkyBoat/AirSkyBoat/pull/463/files
