### ISSUE TITLE
🐛[BUG][Quest] - The Call of the Sea

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#187]
**What does this bug affect?**
After killing the crab NM and clicking the ??? it gives a dialogue with the Whispering Conch key item name missing, though it does show properly in your KI list.

**Expected behavior**
Dialogue should say "Obtained key item: Whispering Conch"

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/194921131-cd33a1ff-f732-49a7-b63d-04e4eb989940.png)
![image](https://user-images.githubusercontent.com/112344508/194921158-44480bea-5775-4bf6-8a50-35a7ac218c45.png)

**Setup Information**
Version 30220906_0

**Additional context**
Outside of this issue the quest worked fine and can be set to "Exists" on the audit sheet once this is fixed.

**Comment by dallano** [comment]
Fix coming from: https://github.com/AirSkyBoat/AirSkyBoat/pull/463
