### ISSUE TITLE
🐛[BUG][Combat] Gae Assail (Stage 4 Polearm) Geirskogul aftermath not healing wyvern

### ISSUE THREAD

**Issue by ThoseWhoFight** [HorizonFFXI/HorizonXI-Issues#1871]
**What does this bug affect?**
Geirskogul aftermath currently only appears to be granting the legacy shock spikes effect and doesn't seem to have the wyvern heal effect, when stage 4 weapon skills should all be granting same aftermath effects that stage 5 has.

**Comment by TracentEden** [comment]
This should now be fixed.
