### ISSUE TITLE
🐛[BUG][Combat] Metatron Torment Defense Down effect

### ISSUE THREAD

**Issue by Swundler** [HorizonFFXI/HorizonXI-Issues#1875]
**What does this bug affect?**
Def down on metatron is based on TP; should be flat 1min duration.  Also not sure when def down is applied (should be at readies ws not at ws dmg)

**Steps to Reproduce**
use metatron, see def down wear based on TP

**Expected behavior**
should last 1 min - https://ffxiclopedia.fandom.com/wiki/Metatron_Torment

**Screenshots**
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/131523980/54d6d2c1-f7cf-424e-aa8c-6bcf645b56ca)

**Setup Information**
current live horizon v

**Additional context**
https://www.bluegartr.com/threads/83513-Metatron-Torment-Aftermath

**Comment by TracentEden** [comment]
This should now be fixed.
