### ISSUE TITLE
🐛[BUG][NPC/Combat] Chlevnik (Ks99 behe) can be slept with Lullabies.

### ISSUE THREAD

**Issue by TristtHXI** [HorizonFFXI/HorizonXI-Issues#1877]
**What does this bug affect?**
As title says you can sleep the mob and interrupt any meteor casts he does, making the fight way to easy.

**Comment by TracentEden** [comment]
Yep, I will try to fix this soon, as Lapislosh has PR already for it.

**Comment by TracentEden** [comment]
This should now be fixed.
