### ISSUE TITLE
🐛[BUG][Quest] - Petals for Parelbriaux

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#188]
**What does this bug affect?**
Able to click on the ??? and spawn the flytrap NM Baumesel at any time, instead of only in fog weather during the morning from 2:00-7:00. When clicking the ??? it did give the dialogue of "There is nothing out of the ordinary here." but the NM still spawned afterwards. Note: Even though it spawned at the wrong time and weather, the ??? still gave the key item & cutscene after killing the NM.

**Expected behavior**
The flytrap NM should only be spawnable in the morning from 2:00 to 7:00 during fog weather.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/194925037-5512c0d1-68d5-4b24-922b-69bca9b0fef6.png)

**Setup Information**
Version 30220906_0

**Additional context**
Outside of this spawn issue the rest of the quest worked and this can be set to "Exists" on the audit sheet once corrected.

**Comment by dallano** [comment]
foggy weather in lufaise can occur at anytime. Wiki only suggests that foggy weather most often occures between those hours. So I imagine upon the time of testing, it was foggy, but not between those hours.
I have a fix incoming for the messaging issue though.

**Comment by Squinkerdoodle** [comment]
@dallano maybe I'm interpreting it wrong then, based on the wiki entry I took it as it can happen any time during the morning hours only. "Fog shows up sporadically, during the morning from 2:00-7:00. It can only show when there is no weather icon up." I haven't been able to find anything other than the wiki entry though to base that on.

**Comment by dallano** [comment]
https://ffxiclopedia.fandom.com/wiki/Petals_for_Parelbriaux#:~:text=Go%20to%20Lufaise%20Meadows%20to%20the%20%3F%3F%3F%20at%20G%2D6%3B%20it%20needs%20to%20be%20selected%20during%20fog%20weather

https://ffxiclopedia.fandom.com/wiki/Category:Weather#:~:text=Fog%20Weather%20normally%20occurs%20during%202%3A00%2D7%3A00%20game%20time.

It definitely is only foggy weather, not just the time. But I did fix this bug nonetheless! There was a bug that definitely caused it to pop no matter the weather though. So nice catch!
