### ISSUE TITLE
🐛[BUG][Quest] - In Search of the Truth

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#189]
**What does this bug affect?**
Tressia does not give any dialogue / cutscene when returning to her after getting the 4 witness accounts from Raminey, Fouagine, Zadant, and Noam. When clicking on Tressia she gives no interaction.

**Expected behavior**
After getting the 4 witness accounts from Raminey, Fouagine, Zadant, and Noam and returning to Tressia, she should give the next quest step with dialogue / cutscene.

**Setup Information**
Version 30220906_0

**Comment by dallano** [comment]
Fix incoming!
