### ISSUE TITLE
🐛[BUG][System] - Can't discard items from inventory

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#19]
**What does this bug affect?**
Dropping items from inventory

**Steps to Reproduce**
Attempt to drop items from inventory. Items not showing in recycling bin after dropping and upon zoning the items are still there in the inventory.

**Expected behavior**
Items should be removed from inventory after dropping them.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3 using AshitaV3

**Additional context**
Attempted as a normal player (no godmode / and not flagged as gm) and still had the same results.

**Comment by CriticalXI** [comment]
This was an issue with a LSB merge that has since been fixed.
