### ISSUE TITLE
🐛[BUG][Quest] - For the Birds

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#190]
**What does this bug affect?**
Unable to start the quest. I completed the previous quest more than a day ago, and have zoned multiple times since then. Koblakiq will only give the same dialogue, but won't start this quest.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/194934954-20300e44-9274-4ff8-9ae7-5b7d3bb56034.png)

**Setup Information**
Version 30220906_0

**Comment by dallano** [comment]
https://github.com/AirSkyBoat/AirSkyBoat/pull/462
Still a PR into ASB at the moment.
