### ISSUE TITLE
🐛[BUG] - Gravity Spell

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#191]
**What does this bug affect?**
After casting gravity on a mob it will not move as if under the Bind spell. Additionally, if nothing else is casted on the mob the mob will de-aggro from the player. Also if a mob aggros the player and the player then casts gravity on it, it will also do the above where it won't move and will de-aggro from the player. The above is true even if the mob has a dot effect on them such as poison or bio while gravitied.

**Setup Information**
Version 30220906_0

**Additional context**
Ping me on discord and I can share my screen to show you exactly what happens if needed.

**Comment by dallano** [comment]
Fix coming from: https://github.com/AirSkyBoat/AirSkyBoat/pull/488
