### ISSUE TITLE
🐛[BUG][NPC]Eeko-Weeko's dialog contains a grammatical error

### ISSUE THREAD

**Issue by AzrielltheWise** [HorizonFFXI/HorizonXI-Issues#1910]
NPC Bug

**What does this bug affect?**

The new Eco-War checker Eeko-Weeko in Ru'lude Gardens contains a grammatical error.  She refers to San d'Oria as "San D'Oria" (capitalized D).  The D is never capitalized in any official game text.  (I hope this "bug report" is not taken as nitpicking.  That is not my intention.)

**Steps to Reproduce**

Talk to Eeko-Weeko when San d'Oria is available in your Eco-War rotation.

**Expected behavior**

It should be written as "San d'Oria"

**Screenshots**

![image](https://github.com/user-attachments/assets/cabd8ba3-c708-437a-a355-39b7c3e3a772)
![image](https://github.com/user-attachments/assets/b8c152cc-06fd-461f-8f13-a1ee88230dab)
![image](https://github.com/user-attachments/assets/5e972579-4bbe-499e-9c34-03ce6ba4c600)

**Setup Information**

/version isn't working for me for some reason.  As far as I know I am running the standard Horizon version.  
**Additional context**

**Comment by 0x05010705** [comment]
Thanks for catching this.  Since there are some other fixes coming in soon™ for Eeko, I'll add this to them.

**Comment by 0x05010705** [comment]
This should now be resolved.
