### ISSUE TITLE
🐛[BUG] BCNM - Crustacean Conundrum

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#192]
**What does this bug affect?**
The crabs in this fight will take 0 damage until a dot (Poison / Bio / Dia all confirmed) or en spell (only tried en-thunder) is used on them, after which it seems every hit always does 1 dmg.

**Expected Behavior**
Crabs will take 0-2 damage from any damage source without having to use a dot / en spell first.

**Setup Information**
Version 30220906_0

**Additional context**
Tested different ways over 3-4 runs and crabs would always take 0 damage until a dot / en spell was used on them, even with godmode.

**Comment by dallano** [comment]
Fixed here: https://github.com/AirSkyBoat/AirSkyBoat/pull/490/files

**Comment by Squinkerdoodle** [comment]
What was the issue exactly? @dallano

**Comment by dallano** [comment]
@Squinkerdoodle It seems that physical, ranged, and magic damage relied on the mob being previously damaged as that damage was then being stored to reflect the new damage output. Rather than the other way around.
