### ISSUE TITLE
🐛[BUG] BCNM - Celery

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#196]
**What does this bug affect?**
The NMs aggro you and the fight starts when you get close to them. When this happens the ghost that aggrod the player(s) will begin casting and the other 3 despawn. (Essentially / potentially screwing you if the wrong one aggrod for your group setup)

**Expected behavior**
https://youtu.be/x9LC8oxH0rU?t=202 - per the capture the ghosts do not aggro and will wait until you pick which one you want to fight and engage it, after which the other 3 disappear (which they are correctly despawning currently)

**Setup Information**
Version 30220906_0

**Comment by dallano** [comment]
Fix incoming
