### ISSUE TITLE
🐛[BUG] Die by the Sword

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#20]
**What does this bug affect?**

The weapons immunities dont seem to take effect until after they swap their weapons for the first time which is incorrect. They also seem to swap weaknesses mutliple times after a weaponskill occasionally. 
**Steps to Reproduce**

**Expected behavior**

The weapons should be immune to the weapons not above their head at the start of the fight.
**Screenshots**

**Setup Information**

**Additional context**

**Comment by dallano** [comment]
Fix should be pushed
