### ISSUE TITLE
🐛[BUG][Digging] Fatigue not working 

### ISSUE THREAD

**Issue by piihub** [HorizonFFXI/HorizonXI-Issues#200]
**What does this bug affect?**
The intended functionality is to be able to dig 100 items per earth day. Currently this limit is not working.

**Steps to Reproduce**
Dig more than 100 items in the same 24 hour span

**Expected behavior**
Should not be able to dig more than 100 items until next JP Midnight

**Comment by OpheliaXI** [comment]
This only needs to be fixed on Horizon.
