### ISSUE TITLE
🐛[BUG] KSNM - Royale Ramble

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#202]
**What does this bug affect?**
King / Queen of Cups no longer cast Dia / Banish / Diaga / Banishga spells of any tier.
King of Coins used Diaga III.

**Expected behavior**
Capture shows the mobs casting Dia 2 / Diaga 2 / Baishga 2, with the King & Queen of Cups using Banish 3.
King of Coins should be using Dia instead of Diaga (I think), NM is a Red Mage.

**Setup Information**
Version 30220906_0

**Additional context**
Mob's starting position is now correct.

**Comment by dallano** [comment]
Using diaga as high as diaga II as a RDM or WHM mob is accurate. Players don't have access to it, but mobs should do.
https://ffxiclopedia.fandom.com/wiki/Diaga_II#:~:text=The%20spell%20%22Diaga%20II%22%20is%20not%20available%20for%20players%20to%20learn%20within%20the%20FFXI%20world%2C%20even%20though%20almost%20all%20high%20level%20RDM%20or%20WHM%20mobs/NPCs%20(generally%20level%20~55%20and%20above)%20are%20able%20to%20cast%20it.

Fix for the latter incoming!
As for the queen and king of cups not casting those spells, they definitely have access to the proper spell list along with ~50 spells. Only spells that were removed were from the last bug fix: banishga 3, diaga 3, banish 4, and dia 3.
What spells were they casting instead? Anything unexpected?

**Comment by dallano** [comment]
oh diaga 3 was definitely removed. But I'm shocked to hear they not casting ANY of the other lower tiers

**Comment by Squinkerdoodle** [comment]
The queen did do Holy though for what it's worth
