### ISSUE TITLE
🐛[BUG][BCNM] Automaton Assault: Mithra weakness may not be correct

### ISSUE THREAD

**Issue by piihub** [HorizonFFXI/HorizonXI-Issues#203]
**What does this bug affect?**
In this BCNM, each automaton is supposed to have a weakness to a certain type of dmg.
The Mithra does not seem to have a specific weakness to ranged attacks as wiki tells us.
Ranged attacks were hitting for 100 tops as rng 60 with crossbow 60 and scorpion arrows.

**Steps to Reproduce**
Enter automaton assault as any race but mithra. Ranged attack mithra.

**Expected behavior**
Mithra should be taking increased damage from ranged attacks.

**Comment by Squinkerdoodle** [comment]
@dallano just wanted to add onto this one, when pii and giga checked (2 taru) they only had the 4 correct automatons in the fight. However when I went in solo I had all 5 still, similar to the report in https://github.com/HorizonFFXI/HorizonXI-Issues/issues/156

**Comment by dallano** [comment]
What race did you test with @Squinkerdoodle ?
I'll double check the resistances. Mithran's resistances are set to take 75% less physical and 75% more ranged damage in the lua. I'll test. May be damage formulas out of whack, could be the mob mod, or could have been testing scenariors.

**Comment by Squinkerdoodle** [comment]
@dallano Hume

**Comment by dallano** [comment]
> @dallano Hume

such a sad bug. But I'm happy you found it. I typo'd HUME as HUNE.
So easy to miss lol

**Comment by dallano** [comment]
@piihub Personal testing has determined mithra to be taking more damage from ranged compared to the other automatons
