### ISSUE TITLE
🐛[BUG]Combat Enhancing and Healing spells - can't self target to cast

### ISSUE THREAD

**Issue by FFXIGigametz** [HorizonFFXI/HorizonXI-Issues#206]
**What does this bug affect?**

 Ability to cast healing and enhancing spells on yourself. Sneak, Invisible, Deodorize,  Curaga (I II III, IV) Regen (  I II III),  Message received You can not attack this target.   
**Steps to Reproduce**

Change job to 75 WHM cast any of the spell mentioned above. 
**Expected behavior**

Message received You can not attack this target. 
**Screenshots**

VER 30220906_0 Windows 10 x64 
**Additional context**

**Comment by Squinkerdoodle** [comment]
@FFXIGigametz you should be good to close this ticket now, everything seems to be working properly after the recent maintenance.

**Comment by Frankie-hz** [comment]
Fixed in https://github.com/AirSkyBoat/AirSkyBoat/pull/500
