### ISSUE TITLE
🐛[BUG] BCNM - Idol Thoughts

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#210]
**What does this bug affect?**
Mob initial spawn point incorrect. Golems not using TP moves in unison, and also using Crystal Shield & Heavy Strike. Additionally Golems are using the wrong element for Crystal Weapon instead of their own. I.E. Fire Golem using a fire damage Crystal Weapon, Water Golem using a water damage Crystal Weapon, Earth Golem using an earth damage Crystal Weapon, and Wind Golem using a wind damage Crystal Weapon.

**Expected behavior**
These golems should only use the Ice / Thunder Break, Crystal Rain, and Crystal Weapon TP moves, which they use in unison per the capture vid https://www.youtube.com/watch?v=0IzsGf_r7UQ .

As seen in the capture and stated on the vid comments: "All golems will use the same line of TP moves at the same time. Whenever Crystal Weapon is used the element of the move will match the golem i.e. Fire Golem will have a fire damage Crystal Weapon. Also for the break line of TP moves Ice Break & Thunder Break, Wind & Earth Golem will only use Thunder Break while Water & Fire Golem will only use Ice Break."

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/195677369-9def5270-6754-45fb-a0c4-9bf913aa981f.png)

**Setup Information**
Version 30220906_0

**Comment by dallano** [comment]
I don't think this BCNM has even been touched once yet. I believe it was marked as "working" when I made my first pass through the BCNMs, so I never bothered looking at it.
I'll have to work on this from the ground up soon.

**Comment by Squinkerdoodle** [comment]
Yea I think this was one from when I was going off of wiki still before I had the capture discord access. :( When I went back through it this time I based everything off the vid from the capture discord.
