### ISSUE TITLE
🐛[BUG] BCNM - Grimshell Shocktroopers

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#212]
**What does this bug affect?** 
(Note: Sleep issue was determined to be a general issue not specific to this BCNM)
If you start the fight out by sleeping the NMs and the sleep lands, the others will not link and start fighting. Note: Starting with any other spell does correctly link the other NMs. I was able to sleep each NM individually without the other awake NMs linking, until all 6 were slept.

BCNM is giving Dream Platter as a reward which is incorrect.

**Expected behavior**
The other NMs should link if sleep is landed on any of the NMs.

![image](https://user-images.githubusercontent.com/112344508/195767688-f56f46db-dce5-4c35-96bd-f00f46a9f2a6.png)

**Setup Information**
Version 30220906_0

**Comment by dallano** [comment]
incoming PR only fixing loot drop. Overall bug is moved to: https://github.com/AirSkyBoat/AirSkyBoat/issues/494
