### ISSUE TITLE
🐛[BUG][Combat] Goblin Leecher at lvl 11 Lizzy camp

### ISSUE THREAD

**Issue by piihub** [HorizonFFXI/HorizonXI-Issues#215]
**What does this bug affect?**
At level 11 lizzard camp in dunes, there is a goblin that wanders through the usual pull spots for lizzards.

**Steps to Reproduce**
Go to the camp and observe the wanderer

**Expected behavior**
The gobs tended to stay closer to the walls and away from the main lizzard pull spots

**Comment by montijin** [comment]
The actual max roam radiuses are significantly higher  compared to what people are used to from private servers. 

This is a screenshot from retail when I was capturing dunes. 
![image](https://user-images.githubusercontent.com/2160211/196310907-97c7fffc-bbed-44bf-9e57-d2fbd675853a.png)
