### ISSUE TITLE
🐛[BUG][Combat] Goblin Bounty Hunters at Valkurm Dunes beach

### ISSUE THREAD

**Issue by piihub** [HorizonFFXI/HorizonXI-Issues#216]
**What does this bug affect?**
When exping at level 16+ camps in the dunes beaches, there are goblin bounty hunters wandering around.
Unsure if this is intentional

**Steps to Reproduce**
Go to either beach camp in dunes (unsure about secret beach)
Observe

**Expected behavior**
No goblin bounty hunters

**Comment by CriticalXI** [comment]
Goblins are at all fishing spots to deter fish bots
