### ISSUE TITLE
🐛[BUG] Qufim islan mob not spawning. 

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#217]
**What does this bug affect?**

Gigas hunters arent spawning after several rounds of killing gigas.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by Squinkerdoodle** [comment]
I'll kill some gigas around delkfutt in a bit to see if any spawn, but this could be like the issue with Ten of Cups I reported in https://github.com/HorizonFFXI/HorizonXI-Issues/issues/180

**Comment by Frankie-hz** [comment]
Fixed in last update
