### ISSUE TITLE
🐛[BUG][Combat] Mobs use OoE spells and spells from jobs other than their own

### ISSUE THREAD

**Issue by TracentEden** [HorizonFFXI/HorizonXI-Issues#218]
**What does this bug affect?**
Aura Pots in The Shrine of Ru'Avitau use OoE spells such as Stone V and Bio III (see https://github.com/EdenServer/community/issues/5123 for equivalent bug that impacted Eden and era proof)

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by TracentEden** [comment]
To generalize on this other BLM mobs (such as steam cleaner) also cast OoE spells (such as Water V), according to Era wiki pages (such as https://ffxiclopedia.fandom.com/wiki/Stone_V?oldid=724119) only a few select mobs could cast T5 spells:

Specifically these included:
Stone V: Kirin and Nightmare Worm (https://ffxiclopedia.fandom.com/wiki/Stone_V?oldid=724119)
Water V: none (no era page)
Aero V: Absolute Virtue (https://ffxiclopedia.fandom.com/wiki/Aero_V?oldid=724123)
Fire V: Bahamut in Storms of Fate (https://ffxiclopedia.fandom.com/wiki/Fire_V?oldid=724126)
Blizzard V: none (no era page)
Thunder V: NPC Azima (https://ffxiclopedia.fandom.com/wiki/Thunder_V?oldid=724121)

ASB shows the other mobs that have access (see https://github.com/AirSkyBoat/AirSkyBoat/blob/staging/sql/mob_spell_lists.sql) including beastmen BLM, magic pots, worms, etc.

For T4 -GA spells the only potential issue seems to be that Nightmare Worm is missing Stonega IV and Animated Staff has Stonega IV when maybe should not (https://ffxiclopedia.fandom.com/wiki/Stonega_IV?oldid=724118)

**Comment by TracentEden** [comment]
Additional Spells that should probably be limited to only a few mobs:

Holy II: Alexander,
 Proto-Ultima
, Razfahd (https://ffxiclopedia.fandom.com/wiki/Holy_II?oldid=724138)
Cure VI: none (no era page)
Regen IV: none (no era page)
Aspir II: none (no era page)
Foe Requiem VII: none (no era page)
Horde Lullaby II: none (no era page)
Army's Paeon VI: none (no era page)

I am less familiar with the ninja and blu spells and they may be less likely to have era pages even if certain mobs did use them in era.

**Comment by Frankie-hz** [comment]
Current Draft PR: https://github.com/AirSkyBoat/AirSkyBoat/pull/510

Can comment on that if you see anything wrong - can finish it up tomorrow @TracentEden
