### ISSUE TITLE
🐛[BUG]Combat: Rapid Shot merit do not work

### ISSUE THREAD

**Issue by ccl085** [HorizonFFXI/HorizonXI-Issues#226]
**What does this bug affect?**

Rapid shot merit don't seems to work

**Steps to Reproduce**

!getmod RAPID_SHOT without merit = 25
!getmod RAPID_SHOT with merit = 25 (should be 30, each merit add 1%-
!getmod RAPID_SHOT with scout jerkin = 30 (5% from the body do work and show 30)

**Expected behavior**

!GET_MOD RAPID_SHOT with merit should show 30
**Screenshots**

**Setup Information**

**Additional context**

**Comment by OpheliaXI** [comment]
Rapid shot merits are OOE, the current retail client shows something completely different in merit groups, thus this is unfixable. Closing.

**Comment by The-Aerec** [comment]
This entire calculation is done in core and is currently working:

![image](https://user-images.githubusercontent.com/6257062/196593530-76a49eef-db5d-499f-8e0d-c6b37a6e6160.png)
