### ISSUE TITLE
🐛[BUG] BCNM / KSNM / ENM entry

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#229]
**What does this bug affect?**
Unable to enter any fights inside a BC or avatar fights at Protocrystals, or any BCNM / KSNM / ENM. When clicking to enter the fight it does nothing, same when trying to trade an orb to the BC. This happens both with and without the gm toggle. No list of the available fights shows up when clicking as a GM.

**Steps to Reproduce**
Try to enter arena fights both the normal way and while flagged as a GM.

**Expected behavior**
Should be able to enter the fight as normal.

**Setup Information**
Version 30221004_0

**Comment by dallano** [comment]
oh lord

**Comment by dallano** [comment]
@jmcmorris I have yet to see the server after the merge. But do you know what's going on off the top of your head?

**Comment by Squinkerdoodle** [comment]
I think Ophelia may have been working on it yesterday evening too

**Comment by Squinkerdoodle** [comment]
Issue resolved with prev maintenance
