### ISSUE TITLE
🐛[BUG][NPC/Combat] Kirin & 4 Sky Gods damage taken by SMN pets

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#23]
**What does this bug affect?**
Summoner's pet damage on Kirin and the 4 sky gods

**Steps to Reproduce**
Spawn Kirin and the 4 individual sky god fights and try the BPs on them, while looking at the log for the damage entry.

**Expected behavior**
SMN pets should do damage to the sky gods, especially with the level 70 BPs.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
Summoner avatars BPs do 0 damage to kirin and the 4 sky gods. Magic BPs (the tier 2 and 4 spells) do seem to go through though with little damage done, but all other BPs do 0 damage.

**Comment by CriticalXI** [comment]
This was an issue with all Summoner avatar physical BPs doing zero damage across the board. I believe this is already corrected.
