### ISSUE TITLE
🐛[BUG][Quest] San d'Oria - The Vicasque's Sermon - Incorrect Dialogue - Flagging Incorrectly

### ISSUE THREAD

**Issue by Nukuchan** [HorizonFFXI/HorizonXI-Issues#230]
**What does this bug affect?**
Immersion and questline. Waters of the Cheval should be the first quest of the line however it wont flag but The Vicasque's Sermon does flag. 

**Steps to Reproduce**
Speaking with Miageau should flag the quest Waters of the Cheval however he just gives his basic dialogue instead. Speaking with Abioleget however will flag The Vicasque's Sermon. Additionally when speaking with the NPC Andelain for the quest his dialogue is incorrect saying "There is a hollow here in the shape of ." and "The lycopodium is entranced by a sparkling light..." this occurs whether he is spoken to before during or after the quest. Lastly when traded the blue peas he states in emote font "Your memory is engraved with an image of your surroundings and the fragrance of flowers..." the quest works and can be otherwise completed

**Expected behavior**
Player should have to flag and complete Waters of the Cheval before they can flag The Vicasque's Sermon. When speaking to Andelain his dialogue should read "During this time, I may eat only three pods of blue peas a day for nourishment. No more, no less. And no other food may i eat." and when you trade him the blue peas he should say "Thanks be to the Goddess in her benevolence!" followed by "May the Gates of Paradise open for all..." 

**Screenshots**
![Nuku_2022 10 17_124137](https://user-images.githubusercontent.com/116027994/196268270-6bd8dff3-7625-4deb-961e-05ff5750e1cf.png)

![Nuku_2022 10 17_124151](https://user-images.githubusercontent.com/116027994/196268247-990741c4-380c-4176-beb3-b038a3b90fd5.png)

**Setup Information**
30221004_0

**Additional context**
Ran into this and a couple other issues I'll be making reports for after the big merge/update on 10/16/22

**Comment by Nukuchan** [comment]
Waters of the Cheval seems to be flagging correctly again now however Andelain's dialogue is still incorrect. not a high priority but notable

**Comment by dallano** [comment]
Fixes incoming! Nice catch :)
