### ISSUE TITLE
🐛[BUG][Combat] OFFHAND hit from weaponskill use main hand weapon.

### ISSUE THREAD

**Issue by ccl085** [HorizonFFXI/HorizonXI-Issues#231]
**What does this bug affect?**

Weaponskill when dual wield use main hand calculation for the off hand hit

**Steps to Reproduce**

1- Cap skill on Main hand
2- get 10 skill on Offhand weapon
3- Observe full tp return on WS and 0 Skill up from the offhand weapon from using  a 1 hit ws 
4- Swap weapon (10 skill main hand / capped skill offhand
5- Observe full miss on weaponskill / double skill up on 1 hit weapon skill when it land 

**Expected behavior**

Offhand should get it's own accuracy check and it's own skillup check instead of being based on Main Hand

**Screenshots**

**Setup Information**

**Additional context**

**Comment by montijin** [comment]
The TP return on offhand hits is also currently bugged.
