### ISSUE TITLE
🐛[BUG][Combat] Magical Weaponskill Can Miss

### ISSUE THREAD

**Issue by ccl085** [HorizonFFXI/HorizonXI-Issues#232]
**What does this bug affect?**

Magical weaponskill can miss on Horizon
**Steps to Reproduce**

1: Nin 75 !capskill katana
2: fight something evasive such as Fafnir/Tiamat
3: Spam Blade: EI
4: Observe Miss
**Expected behavior**

Magical weaponskill cannot miss on FFXI -> https://www.bg-wiki.com/ffxi/Category:Elemental_Weapon_Skill#:~:text=Magical%20Weapon%20Skills%20never%20miss,physical%20and%20magical%20attack%20modifiers.

"Magical Weapon Skills never miss, but are subject to magical resist states. On Magical Weapon Skills, abilities such as [Warcry](https://www.bg-wiki.com/ffxi/Warcry) and [Sneak Attack](https://www.bg-wiki.com/ffxi/Sneak_Attack) have no effect. Hybrid Weapon Skills, however, are affected by [Sneak Attack](https://www.bg-wiki.com/ffxi/Sneak_Attack), as well as both general physical and magical attack modifiers."

**Screenshots**

**Setup Information**

**Additional context**

**Comment by OpheliaXI** [comment]
Closing this, will dm reason.
