### ISSUE TITLE
🐛[BUG][System] - !getfame desktop crash

### ISSUE THREAD

**Issue by BayaniTenzen** [HorizonFFXI/HorizonXI-Issues#234]
**What does this bug affect?**
desktop game crash following !getfame command

**Steps to Reproduce**
use GM Command - !getfame (name) then expand chat - resulted in crash to Desktop 

**Expected behavior**
should be able to expand chat and see a full list of current Fame Status

**Comment by Squinkerdoodle** [comment]
@BayaniTenzen try it again and see if it's still happening. The command is working fine for me with no crashing.
