### ISSUE TITLE
🐛[BUG][Quest] To Cure a Cough and Over the Hills and Far Away POTENTIALLY NEW INFORMATION

### ISSUE THREAD

**Issue by Nukuchan** [HorizonFFXI/HorizonXI-Issues#236]
**What does this bug affect?**
The quest audit list says these two quests are missing dialogue that the diary wont show pages 3 and 4 needed for them.

**Steps to Reproduce**
By interacting with the diary after completing The Trader in the Forest but BEFORE flagging The Medicine Woman I was able to get pages 3 and 4 to show up. This allowed me to be able to complete Over the Hills and Far Away but NPC Amaura still wont ask for the thyme moss despite page 3 being acessable for me. 

**Expected behavior**
after speaking with Nenne and reading page 3 of the diary Amaura is supposed to ask for thyme moss however she just continues her bit about brewing a powerful potion. 

**Screenshots**

**Setup Information**
30221004_0

**Additional context**
Maybe this little workaround will help someone smarter than me to look in the right place

**Comment by Nukuchan** [comment]
More developments: The above was done on one character. on another that was stuck unable to see pages 3 or 4 i deleted the The Medicine Woman quest using !delquest after having completed it and the page appeared. re did the medicine woman and was able to get amaura to ask for the moss after completing it again!

**Comment by Squinkerdoodle** [comment]
https://github.com/HorizonFFXI/HorizonXI-Issues/issues/167 also submitted for To Cure a Cough, just posting so devs can see both easier.

**Comment by hookstar** [comment]
To Cure a Cough fix #548
