### ISSUE TITLE
🐛[BUG][Combat] Stun MACC is too low

### ISSUE THREAD

**Issue by ccl085** [HorizonFFXI/HorizonXI-Issues#237]
**What does this bug affect?**

nin/drk tank was huge for  endgame on COP/TOAU era,  but stun from /drk is being resisted on Sky god, making this combo less effective
**Steps to Reproduce**

1. NIN/DRK and cap skills
2. pop Seiryu
3. /ma stun <t>
4. observe resist

**Expected behavior**

Stun from nin/drk should land on stunable HNMs mob level (should work on mob up to Tiamat at least)

**Screenshots**

![Ccldd_2022 10 18_140738](https://user-images.githubusercontent.com/48790940/196426168-9a01d4cb-090d-45de-a8bf-210205cf9673.png)

**Setup Information**

**Additional context**

BGwiki -> : "The relatively high [Magic Hit Rate](https://www.bg-wiki.com/ffxi/Magic_Hit_Rate) of this spell's Stun effect is thought to be caused by multiple (perhaps three) resist sub-states." There might be a 3rd resist sub-state only for the stun effect ?

**Comment by Frankie-hz** [comment]
Something might be wrong with resistances in general or just stun itself. He doesn't seem to have any real resistance or sdt applied to him for stun/dark and his INT seems to be normal. Needs a deeper test

**Comment by ccl085** [comment]
I believe it is a Stun issue, this is an error on most if not every private server, either stun has an "hidden" huge magic accuracy bonus that was never coded on private server, or there is a "special resist sub stat check.
