### ISSUE TITLE
🐛[BUG][Quest] - Escort for Hire (Bastok)

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#24]
**What does this bug affect?**
Unable to start quest.

**Steps to Reproduce**
Try to start quest by speaking with quest giver with fame lvl 6 or higher.

**Expected behavior**
Quest should be given with fame lvl 6.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
Spoke with NPC to try to get the quest at Bastok rep lvl 6, and then increased rep lvl by one until lvl 9 and still unable to start quest.

**Comment by hookstar** [comment]
Quest needs to be written.

**Comment by JVMasterforce** [comment]
I'm trying to start Escort for hire Bastok as a non citizen but can't seem to get it to work it like the only method is to be a citizen of Bastok they need to address this damn issue asap!
