### ISSUE TITLE
🐛[BUG] Meteorite is incorrectly dropping from all Crawlers in West Saruta

### ISSUE THREAD

**Issue by Cyr-test** [HorizonFFXI/HorizonXI-Issues#240]
**What does this bug affect?**
Incorrect item drop pool

**Steps to Reproduce**
Kill lots of crawlers in West Saruta (away from Starfall Hill).  The level 3 Crawlers by the Windy zonelines are dropping it. 

**Expected behavior**
Should only drop from the higher-level crawlers near Starfall Hill (East of the Outpost)

**Comment by panicstevenson** [comment]
PR open on ASB 🎉
