### ISSUE TITLE
🐛[BUG][System] Cannot have "sau" in character name

### ISSUE THREAD

**Issue by nickandwolf** [HorizonFFXI/HorizonXI-Issues#242]
**What does this bug affect?**
Naming restrictions are weird. Some names cannot contain "sau".

**Steps to Reproduce**
When making a new character, try the following names:
Sauless -> does not work
Anarsau -> does not work
Dissauron -> does not work

**Expected behavior**
To have "sau" in a name.

**Screenshots**
![image](https://user-images.githubusercontent.com/42407735/196550199-face5671-381e-4d12-8e8c-5925b0cd3369.png)

**Setup Information**
Game Ver.30221004_0
Windows 11 Version 10.0.22621 Build 22621

**Additional context**
I started with "Sauless" and then whittled it down to only "Sau" being wrong. Then played around with that and couldn't resolve it.

**Comment by The-Aerec** [comment]
This won't matter anyways as we will be doing character creation through the website, I don't believe the server has a name block list on server side so this is a client rejection. (From first look)
