### ISSUE TITLE
🐛[BUG][NPC]Shami (BC/KS NPC) displays Out of Era text.

### ISSUE THREAD

**Issue by AzrielltheWise** [HorizonFFXI/HorizonXI-Issues#243]
**What does this bug affect?**

Shami  displays OoE text.  He talks about Kindred Crests and High Kindred Crests.

**Steps to Reproduce**

Talk to Shami in Port Jeuno.

**Expected behavior**

He should not talk about High/Kindred Crests.

**Screenshots**

![image](https://user-images.githubusercontent.com/90195635/196570167-3482c51a-d316-4714-be89-8fb0ba7532a1.png)

**Setup Information**

/ver 30221004_0

**Additional context**

**Comment by dallano** [comment]
Not sure if it's in era, but I was able to shorten his dialogue to no longer go on about the new crests and what not. Here's the full dialogue when triggering him. Can't find era accurate dialogue elsewhere.
![image](https://user-images.githubusercontent.com/62350957/196575000-112ec219-a1fe-43e4-808a-ec140d74aaa2.png)
