### ISSUE TITLE
🐛[BUG][Combat Ability] Improper Status Effect Icons

### ISSUE THREAD

**Issue by BayaniTenzen** [HorizonFFXI/HorizonXI-Issues#244]
**What does this bug affect?**
"Majesty" (OOE) and "Rampart" both have BCNM style icons on the UI

**Steps to Reproduce**
Cast Job Ability "Majesty" or "Rampart"

**Expected behavior**
Should display an accurate Icon - for both Abilities

**Screenshots**
https://cdn.discordapp.com/attachments/993636667791523931/1032095562620739614/unknown.png
https://cdn.discordapp.com/attachments/993636667791523931/1032107676240445480/unknown.png

**Comment by dallano** [comment]
Hmm I don't seem to be able to recreate this. Were there any specific conditions you were in when this happened?

**Comment by Squinkerdoodle** [comment]
Are you sure you're not using an addon that changes the icons? Your icons look different from mine and I'm using no addons:

![image](https://user-images.githubusercontent.com/112344508/197114107-6dfa2d0b-57ec-49da-901d-bf5023570784.png)

**Comment by BayaniTenzen** [comment]
Yeah.... Majesty has been removed now as an OOE ability - turned off and on visual addons 
Rampart only bugged in Ashenbubs so not a base Horizon Issue - I'll report it to the Mod Maker
