### ISSUE TITLE
🐛[BUG][Item] The Scarlet King BCNM Drops Claymore/Pole Grip

### ISSUE THREAD

**Issue by panicstevenson** [HorizonFFXI/HorizonXI-Issues#245]
**What does this bug affect?**
The Scarlet King BCNM drops Claymore Grip/Pole Grip/Spear Strap/etc which are out of era.

**Steps to Reproduce**
Finish The Scarlet King BCNM and get drops from the Armoury Crate.

**Expected behavior**
Out of era items should not drop.

**Screenshots**
![image](https://user-images.githubusercontent.com/8849608/196586362-d7fc99e7-ead9-4621-9444-c6f3e1497032.png)
![image](https://user-images.githubusercontent.com/8849608/196586739-dd7af87b-d862-4b17-9741-8becfa2b4efe.png)
EDIT: Another one
![image](https://user-images.githubusercontent.com/8849608/196588414-615145d5-bce4-4c05-b96b-0ec10678be03.png)

**Setup Information**
version 30221004_0

**Additional context**

**Comment by dallano** [comment]
What's the basis of these items being out of era?

**Comment by dallano** [comment]
That's the oldest date I've also been coming up with. 
Hmm. I'll bring this to the balance team!

**Comment by hookstar** [comment]
I can only find AUG 2007 mentions as well.

**Comment by CriticalXI** [comment]
Grips 100% were a TOAU item and should not be included at Horizon launch

**Comment by dallano** [comment]
All the needs to be done is enter 0 for their values in items.lua on horizon database and it'll take them all out. I set it up on ASB to handle it for all battlefields. @CriticalXI 
Just forgot to do it before I left for vacation!
