### ISSUE TITLE
🐛[BUG][System] Mazurka Useable in Dungeons

### ISSUE THREAD

**Issue by RobustPancakes** [HorizonFFXI/HorizonXI-Issues#246]
**What does this bug affect?**
Able to use Mazurka inside dungeon zones

**Steps to Reproduce**
1. Enter Dungeon
2. Cast Mazurka
3. Feet go brrrrrrrrrrrr

**Expected behavior**
Mazurka should only be able to be cast in "Outside" zones

**Comment by dallano** [comment]
Appreciate the bug report <3 Let's just rename this bug report to be a bit more informative as to what's going wrong

**Comment by dallano** [comment]
Fix made and incoming
