### ISSUE TITLE
🐛[BUG][System/Combat] Charm/Engage Issue

### ISSUE THREAD

**Issue by BayaniTenzen** [HorizonFFXI/HorizonXI-Issues#247]
**What does this bug affect?**
Stuck engaged to a Target and unable to use Camera probably after being Charmed

**Steps to Reproduce**

Using PLD in KSNM "Copy Cat" - engaged an avatar made after a SMN party member was charmed - had weapon drawn and was Charmed by NM - slept by BRD (unsure if important) - after Charm ended I was stuck "engaged"; couldn't disengage even without a Target - my right hand side "Camera Controls" were stuck rotating options in the Battle Menu - so my Camera was locked at an awkward angle - problem didn't disappear even after being Charmed twice more. Eventually Boss was defeated and even in the post fight zone with no target my Character was still stuck "Engaged" - couldn't disengage or close out of the option. Eventually being teleported to another player removed the "engaged" state from me.

be Engaged with Weapon drawn during a fight and get Charmed by an Enemy
might be more widespread than just "Copy Cat" KSNM - not sure where to test further

**Expected behavior**
Should be able to disengage after leaving the charmed state

**Comment by dallano** [comment]
Did this issue arise with any other players during the KSNM? I appreciate all the detail by the way. Every last bit helps when trying to track down what's causing the bug

**Comment by BayaniTenzen** [comment]
Yeah we were a Full 6 Man party with a GM observer present - PLD/RDM/BRD/SMN/SMN/RNG

I've not been able to test it anywhere else because it's hard to find mobs that just wanna "Charm" you

Maybe engaging Xolotl in Attowha Chasm and after being charmed; 
an observer could !hp 0 him - that could re-create it outside a BCNM

**Comment by BayaniTenzen** [comment]
Myself and the RNG present both experienced the issue; - none of the mages were "engaged" prior to being charmed

I believe we were both engaged/weapon drawn/auto attacking with a Target other than the NM when we were charmed

I was specifically hitting the Carbuncle Avatar summoned by the NM when he charmed a SMN

**Comment by RetroPrez** [comment]
I was the RNG. I only witnessed it persist to the room after the BCNM ended. I got charmed, but didn't get the issue.

I can add that I've seen a vaguely similar thing happen before (on controller without the camera issues) while playing BST in ASB. I've gotten stuck engaged like this I believe until my pet kills the mob or dies and then it finally disengages you. Probably unrelated and I don't know how to recreate it, but maybe it helps.

**Comment by BayaniTenzen** [comment]
After further testing we have confirmed that "Sleeping" or "Stunning" the Charmed Player is the trigger which results in the Player being unable to return to the "Disengage" state. Multiple players were charmed, slept, stunned or left just charmed whilst engaged with the NM "Xototl" and only players Slept or Stunned became "Bugged" in the engaged state.

**Comment by OpheliaXI** [comment]
@dallano any luck on this?

**Comment by dallano** [comment]
oh I thought this was fixed when I was away on reading week lol. I'll look into it again
