### ISSUE TITLE
🐛[BUG][System] Fafnir and Nidhoog up at the same time

### ISSUE THREAD

**Issue by ccl085** [HorizonFFXI/HorizonXI-Issues#250]
**What does this bug affect?**

Looks like Faf and nid can both pop if HQ is due 
**Steps to Reproduce**

I did log off in DA, nothing was up, I did log on later during the day and they both were up, suspecting if Nid is due, faf can pop too ?
**Expected behavior**

Only one or the other can pop
**Screenshots**

![Ccldd_2022 10 19_175244](https://user-images.githubusercontent.com/48790940/196743013-caa67e8d-55ca-4db5-a502-56be60fc2e80.png)

**Setup Information**

**Additional context**

**Comment by OpheliaXI** [comment]
I believe this only needs to be fixed on Horizon.
