### ISSUE TITLE
🐛[BUG] - KSNM Horns of War

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#252]
**What does this bug affect?**
NM is doing it's final meteor attack after reaching 0% HP instead of sitting at 1% HP and doing it, then falling to the ground and dying afterwards. Additionally the armor crate is spawning when he hits 0% HP / before the final meteor attack goes off, though the final attack does go off and do damage whether you open the crate or not.

**Expected behavior**
Copying from wiki because I'm lazy:
Chlevnik cannot be directly defeated by depleting its HP. When Chlevnik is out of HP (its HP bar stays at 1% and it still takes damage from attacks) and has finished performing any TP move or Meteor cast it was attempting (if any), it immediately uses an ability named Meteor as a "final attack". It is similar to the spell Meteor, but is more damaging and cannot be prevented. This move deals high damage to anyone within 40.0 units from [Chlevnik](https://ffxiclopedia.fandom.com/wiki/Chlevnik). Following this attack's long animation, Chlevnik "falls to the ground" and dies.
Even if the entire party perishes from the final Meteor, the fight is still a win if at least one party member can Reraise.

**Setup Information**
Version 30221004_0

**Additional context**
This was working properly prior to the recent LSB big update / merge.

**Comment by dallano** [comment]
Fix incoming!
