### ISSUE TITLE
🐛[BUG] - KSNM The Hills Are Alive Loot Issue

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#253]
**What does this bug affect?**
Armoury Crate from this KSNM is giving 2 Blue Pondweeds instead of just 1 on each clear.

**Steps to Reproduce**
Go in and clear the fight and check the loot reward.

**Expected behavior**
Should only allow 1 Blue Pondweedmax.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/196775677-334336cd-88ff-4b00-98ea-15e164041ffc.png)

**Setup Information**
Version 30221004_0

**Comment by Twispn8** [comment]
Still a current bug blue pondweed drop x2
