### ISSUE TITLE
🐛[BUG][Combat/Graphical] Ghost Avatar Persisting after battlefield

### ISSUE THREAD

**Issue by alessa89** [HorizonFFXI/HorizonXI-Issues#255]
**What does this bug affect?**
This is just a minor graphical bug, however as a summoner after clearing a battlefield and being dumped into the next area, the avatar is still spawned in and visible. it doesn't move/respond to commands, doesn't cost MP, and blood pact menus show as if there is no pet out. summoning a new pet will replace the "ghost" thats just hanging out. other people in the zone confirmed they saw as well.

**Steps to Reproduce**
go into a battlefield as a summoner, call out an avatar, beat the battlefield and advance to the next area

**Expected behavior**
should load into the next area without any pet

**Screenshots**
![image](https://user-images.githubusercontent.com/115948656/196792581-2f6bfceb-feff-497a-8718-c542c129efca.png)

**Setup Information**
ver 30221004_0

**Additional context**
this doesn't happen with bst pets

**Comment by jmcmorris** [comment]
I tried to reproduce this and the avatar is unsummoned when doing a level capped bcnm. When doing an uncapped ksnm it'll leave the avatar up and fully functional. Can you please supply exact steps to reproduce this issue?

**Comment by alessa89** [comment]
We noticed it was still there after doing Apollyon NW as well. It doesn't happen with all BCNMs, but I was just able to get it to happen with Maat fights (tested SMN, and BLM as a summoner just in case it was SMN maat specifically and it happened), tested as well in contaminated colosseum and it happened.

As for steps, its just go into the bcnm/ksnm and have an  avatar out and beat it, either !hp0 or legit. you can see it if you do shattering stars SMN

<img width="1082" alt="gh1" src="https://user-images.githubusercontent.com/115948656/197557874-b6d496d2-3111-4845-9b1b-e9a805b2097a.png">
<img width="1029" alt="gh2" src="https://user-images.githubusercontent.com/115948656/197557887-dbd09a5e-c019-4c33-81ba-d316bd47e6fb.png">

**Comment by jmcmorris** [comment]
I was able to reproduce this in Contaminated Colosseum. I looked at a retail capture and saw that the avatar (and I believe all pets) should stick around after being ejected even in a level synced battlefield.
https://www.youtube.com/watch?v=RCXi88dkqZk

**Comment by jmcmorris** [comment]
Thinking about this more I believe a despawn packet for the avatar is just not being sent to the client properly. However, I'm going to look at fixing the real issue here which is that pets shouldn't despawn at all when leaving a battlefield.
