### ISSUE TITLE
🐛[BUG][COMBAT]Fenrir Prime

### ISSUE THREAD

**Issue by 0Fox2Give** [HorizonFFXI/HorizonXI-Issues#258]
**What does this bug affect?**
Not trying to target me and dispel buffs with Lunar Roar.  Not using 2 hour ability Howling Moon at 50%.  Fight is significantly easier

**Steps to Reproduce**
Fought him 4 times so far and I stood next to him with Garuda attacking.

**Expected behavior**

Should be able to dispel buffs from (random?) target(s)? Looks to be AOE Lunar Roar in the video.  He is not using Howling Moon at all.
**Screenshots**

**Setup Information**
Windows 10 Ashita 3

**Additional context**
[](https://www.youtube.com/watch?v=BKcEdX0oLbM) here is a link where you can see Fenrir using most of his abilities.

**Comment by TracentEden** [comment]
The howling moon issue was fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/3496 , Lunar Roar is already AoE.
