### ISSUE TITLE
🐛[BUG][Quest] - Beadeaux Smog

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#26]
**What does this bug affect?**
Unable to obtain key item in Beadeaux.

**Steps to Reproduce**
Accept quest and click on the ??? near the base of the smokestacks at G-9 or H-9 in Beadeaux during rain weather.

**Expected behavior**
When clicking on the ??? during rain weather it should give you the key item [Corrupted Dirt](https://ffxiclopedia.fandom.com/wiki/Corrupted_Dirt)

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
The ??? were also up during the lightning weather that proceeded the rain weather, per the wiki the ??? should only pop up during rain weather.

**Comment by CriticalXI** [comment]
Tested this myself and this looks to be good now.
