### ISSUE TITLE
🐛[BUG][Quest] A Knight's Test - Incorrect quest event order

### ISSUE THREAD

**Issue by Nukuchan** [HorizonFFXI/HorizonXI-Issues#261]
**What does this bug affect?**
era accuracy

**Steps to Reproduce**
after getting the book of tasks from Balasiel you can get the books of the west and east out of order.

**Expected behavior**
the riddle in the book of tasks says to go east to know the west 

**Screenshots**
![Nuku_2022 10 19_203839](https://user-images.githubusercontent.com/116027994/196843312-f00a80be-c41e-4b41-b100-1d185f8f8e8c.png)

**Setup Information**
30221004_0

**Additional context**

**Comment by Squinkerdoodle** [comment]
Can't you get these books in either order? At least on the wiki entry it has you getting West and then East, with the book of task entry being more of a hint.

**Comment by Nukuchan** [comment]
I could be mistaken, I remember it being order specific but either way not a big deal just reportin anything i find on my quest review ^.^
