### ISSUE TITLE
🐛[BUG][Combat] Ix'aern (Dark Knight) Issues

### ISSUE THREAD

**Issue by TracentEden** [HorizonFFXI/HorizonXI-Issues#264]
**What does this bug affect?**
The sea NM Ix'aern (Dark Knight) has a few issues:
- Ix'aern (Dark Knight) 2hr shows a log message of Refulgant Arrow instead of Blood Weapon and the 2hr animation is missing. However the ability seems to actually be blood weapon (HP is drained by hits) and the wears off message is correct. See the screenshot below.

**Steps to Reproduce**
Pop Ix'aern (Dark Knight) and nuke down until it uses 2hr

**Expected behavior**
- The log should say Blood Weapon and should have the 2hr animation

**Screenshots**
![Trace_2022 10 20_193257](https://user-images.githubusercontent.com/92269743/197009492-944b6b34-d5ba-47bb-86a3-92383c80f67c.png)

**Setup Information**

**Additional context**

**Comment by hookstar** [comment]
![image](https://user-images.githubusercontent.com/16403542/199102821-777a02d5-a8ae-4558-8e0d-127032fd8c95.png)

![image](https://user-images.githubusercontent.com/16403542/199102967-c8b6beb5-c376-4644-b85a-c9837b354cc4.png)

ASB build is able to recreate above. Although from the first SS, it appears its specific to IX_DRK and not all mobs.

**Comment by hookstar** [comment]
submitted PR https://github.com/AirSkyBoat/AirSkyBoat/pull/594
