### ISSUE TITLE
🐛[BUG] KSNM - Infernal Swarm Loot Issue

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#266]
**What does this bug affect?**
KSNM reward chest is dropping grips which are out of era. I had pole grip and spear strap drop, but suspect the staff strap & claymore grip can drop too.

**Expected behavior**
Reward chest loot pool does not have grips / straps.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/197117153-02afcc3d-3961-4fb6-aa53-b9fff5b85f1f.png)
![image](https://user-images.githubusercontent.com/112344508/197117981-2b2d3557-b61e-434e-a41b-e488949c538a.png)

**Setup Information**
Version 30221004_0

**Comment by Squinkerdoodle** [comment]
@hookstar yea that would need to be done on all arenas, not just Qu'Bai. @dallano said that there was a fix to remove all the grips / straps that would be directly on Horizon since this doesn't need to happen on LSB / ASB.

**Comment by hookstar** [comment]
So can these be closed?

**Comment by Squinkerdoodle** [comment]
Possibly, just waiting for confirmation from @dallano (who has been busy with school stuffs)

**Comment by dallano** [comment]
Yeah haven't gotten around to it yet. 😬 been unbelievably busy.

**Comment by Squinkerdoodle** [comment]
I'll leave it alone til you say otherwise then. And yea I remember you saying you had a lot on your plate for now, hope everything is going well for you!
