### ISSUE TITLE
🐛[BUG][Quest] - Escort for Hire (Windurst)

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#27]
**What does this bug affect?**
Unable to start quest with required rank 6 rep in Windurst, with no other Escort For Hire quest started or completed in the same conquest tally period.

**Steps to Reproduce**
Speak with NPC with rank 6 Windurst rep or higher, with no other Escort For Hire quest started or completed in the same conquest tally period.

**Expected behavior**
Should be able to start the quest when meeting the requirements.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
N/A

**Comment by dallano** [comment]
Quest partially complete. All that remains is modifying the behavior of the NPC to be attacked by mobs.
