### ISSUE TITLE
🐛[BUG][Combat] Weaponskill being learnt a 5 skil is OOE

### ISSUE THREAD

**Issue by ccl085** [HorizonFFXI/HorizonXI-Issues#272]
**What does this bug affect?**

Currently 1st weaponskill is learnt at 5 skill on Horizon at least on staff and club
**Steps to Reproduce**

Skill up to level 5 on a low level job or !capskill and !changejob level 1
**Expected behavior**

On era first WS is learnt at 10. source -> https://ffxiclopedia.fandom.com/wiki/Heavy_Swing?oldid=383090
**Screenshots**

**Setup Information**

**Additional context**

**Comment by OpheliaXI** [comment]
This only needs to be fixed on Horizon.
