### ISSUE TITLE
🐛[BUG][Combat] Aerns do not reraise if killed with single spell

### ISSUE THREAD

**Issue by TracentEden** [HorizonFFXI/HorizonXI-Issues#273]
**What does this bug affect?**
Aerns (e.g., Aw'aerns) do not reraise if killed with single spell. (They do reraise at a normal rate if engaged or killed with two spells)

**Steps to Reproduce**
Go to The Garden of Ru'Hmet and enable godmode then start killing Aw'aerns with Thundaga III

**Expected behavior**

The Aerns should reraise about 40% of the time even if killed with single spell.  Maybe this issue has to do with the aern family mixin and the DEATH listener, still unclear.

**Screenshots**

**Setup Information**

**Additional context**

**Comment by Squinkerdoodle** [comment]
Just want to comment that I had no issue with aerns reraising if killed by one spell yesterday. I killed a few with both thunder 4 and thundaga III (one shot with godmode enabled) and had reraises go off.
