### ISSUE TITLE
🐛[BUG][Combat] Ix'aern (Monk) Issues

### ISSUE THREAD

**Issue by TracentEden** [HorizonFFXI/HorizonXI-Issues#274]
**What does this bug affect?**
The sea NM Ix'aern (Monk) has a few issues:
- Ix'aern (Monk) paths directly through the columns that players typically kite around
- Ix'aern (Monk) has a crazy high attack speed (4-6 attacks per second, attacks so fast the animation cannot keep up and stutters) when first popped (before 2hr and without bracers). During 2hr seems to have correct 2hr attack speed and after 2hr (with bracers) seems to also have correct attack speed based on videos (like https://www.youtube.com/watch?v=k413vn8SbrU)
- Ix'aern (Monk) ??? has a 5 min repop time

**Steps to Reproduce**
Pop Ix'aern (Monk) and let it hit you and then also kite around pillars, also kill and check the repop time of ???

**Expected behavior**
- Ix'aern (Monk) should go around the columns that players typically kite around
- Ix'aern (Monk) should have a much slower attack speed (before 2hr and without bracers), I think this might be because the mob delay is accidentally set to 0 on line 71 Ixaern_MNK.lua in ASB (i.e., mob:setDelay(0))
- Ix'aern (Monk) ??? should have a 15 min repop time in CoP era

**Screenshots**

**Setup Information**

**Additional context**

**Comment by panicstevenson** [comment]
Fixed
