### ISSUE TITLE
🐛[BUG][Mission] CoP 4-2 The Savage - Ouryu missing Stoneskin, maybe Typhoon Wing also

### ISSUE THREAD

**Issue by RetroPrez** [HorizonFFXI/HorizonXI-Issues#276]
**What does this bug affect?**
Ouryu should have Stoneskin in his spell rotation. Seems to do everything else listed on wiki/seen in videos except Typhoon Wing also. I still need to learn how to look at the mob spell lists and skills/abilities, but Ouryu certainly isn't doing Stoneskin at all like he should in the fight.

**Comment by dallano** [comment]
Ouryu should be using typhoon wing. Squinks and I thought we fixed the bug not too long ago. I'll look into it nonetheless
