### ISSUE TITLE
🐛[BUG] KSNM - E-vase-ive Action

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#278]
**What does this bug affect?**
Pots aggro to magic when they should not aggro at all via proximity or magic until you attack one, at which point the other 5 despawn (currently despawning correctly).
Reward crate is rewarding grips and straps which are out of era.
Reward crate is dropping lvl 50 rings instead of the level 70 earrings (pictured below)

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/197314286-8feab0b8-505f-4b47-afc7-2c6055e53ccd.png)
![image](https://user-images.githubusercontent.com/112344508/197314779-e278675e-0b72-48c8-9b0e-8507fb5f5aa8.png)
![image](https://user-images.githubusercontent.com/112344508/197316340-ad294e69-f086-4509-907e-e56532193ed5.png)

**Setup Information**
Version 30221004_0

**Comment by dallano** [comment]
Fixes for the grips will go to horizon directly and not onto ASB <3 But a fix is incoming
