### ISSUE TITLE
🐛[BUG][Mission] Missing optional text for PM4-4, ZM12 and ZM17(partial)

### ISSUE THREAD

**Issue by RetroPrez** [HorizonFFXI/HorizonXI-Issues#279]
Some missing optional text.
Attempting to format this post with sources.
---------------
**1) PM4-4 - There's two lines of optional text missing from Sueleen after the airship departs and PM4-5 starts:**

>Sueleen : The airship carrying Prishe and Ulmia just left for San d'Oria.<7F31>
>Sueleen : Someday maybe I'll be lucky enough to ride an airship off the island... Someday...<7F31>

-    Video reference:
    https://youtu.be/qtstjlh6dUw?t=903
-    Text source (lines 7632, 7633):
    https://bitblt.org/elevyn/Sep2022/Zones/Sealion's%20Den/Dialog%20(EN).txt
---------------
**2) ZM12 - There's two lines of optional text missing after you receive the "Cerulean Crystal" key item from Maryoh Comyujah:**

>Gilgamesh : Arrrg, so that be the <01053382808080> that we've been searchin' fer. It looks like you had a hell of a time tryin' t'get yer hands on it.<7F31>
>Gilgamesh : But the real hell is yet t'come, {player}. Crystal Warriors...floating islands... It may all seem crazy, but don't let that get in yer way. Yer Vana'diel's only hope.<7F31>

-    Video reference:
    https://youtu.be/sasNW6ZWT_g?t=763
-    Text source (lines 10739, 10740):
    https://bitblt.org/elevyn/Sep2022/Zones/Norg/Dialog%20(EN).txt

---------------
**3) ZM17 optional dialogue is missing for Aldo and 3 other NPCs after the final two cutscenes.**

>Aldo : A lot has happened in the past few months... I don't know how long the news of the archduke and his brother is going to stay a secret, but that has nothing to do with me or the Tenshodo.<7F31>
>Aldo : What to do now? Maybe I'll get myself a boat and sail around Vana'diel...\x07Good luck on your journeys, {player}, and may fortune smile upon you always!<7F31>

-    Aldo video reference only, missing Garnev, Yin Pocanakhu and Sattal-Mansal.:
    https://youtu.be/t3XJv-1FQU0?t=3940
-    Text source (lines 8492, 8493):
    https://bitblt.org/elevyn/Sep2022/Zones/Lower%20Jeuno/Dialog%20(EN).txt

**Comment by CriticalXI** [comment]
Sueleen portion has been fixed.
