### ISSUE TITLE
🐛[BUG][Quest] - Water Way to Go (repeat)

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#28]
**What does this bug affect?**
Unable to repeat quest Water Way to Go after initial completion.

**Steps to Reproduce**
Complete quest and then try to accept quest again.

**Expected behavior**
Should be able to repeat quest after initial completion.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
Just to be clear the quest worked fine the first time and was able to complete it and continue the quest chain. I was not on quest [Curses, Foiled A-Golem!?](https://ffxiclopedia.fandom.com/wiki/Curses,_Foiled_A-Golem!%3F) and already completed Tuning In & Tuning Out so I should be able to repeat the quest.

*********************
I noticed this after submitted the bug, but the canteen of giddeus water stayed in my inventory after trading it to the NPC to complete the quest.

**Comment by CriticalXI** [comment]
Fixed in https://github.com/AirSkyBoat/AirSkyBoat/pull/370
