### ISSUE TITLE
🐛[BUG] KSNM - Moa Constrictors Loot Issue

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#280]
**What does this bug affect?**
*Note: The fight itself worked fine, only issue found was with the loot pool.*
Reward crate giving out of era grip. May possibly also drop Spear Strap and Claymore Grip as these are in the wiki's loot pool, didn't continue to check after the first drop.

**Expected behavior**
Reward crate does not give OOE grips / strap.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/197316207-5ba694f0-580c-40eb-9916-b0563a16360f.png)

**Setup Information**
Version 30221004_0

**Comment by dallano** [comment]
mad you got a pole grip?? lol
again fixes will come directly into horizon for this.

**Comment by Squinkerdoodle** [comment]
@dallano Gotchya, since we won't see this fix on the test server and it's directly on Horizon would you like for me to close these reports where it's only an issue with the grip / strap dropping and mark it as testedx2 on the BCNM sheet?
