### ISSUE TITLE
🐛[BUG][Combat]Ranged Attack does not complete if the mob moves out of 25' during the wind-up

### ISSUE THREAD

**Issue by Cyr-test** [HorizonFFXI/HorizonXI-Issues#281]
**What does this bug affect?**
Hopefully my recollection is correct: but I believe era was set to have ranged attacks complete if the mobs moved out of 25' range after you began your /ra animation.

**Steps to Reproduce**
/ra near max distance & have mob move away

**Comment by dallano** [comment]
I believe we determined this to not be the cast. I believe it was @Frankie-hz and Monti that figured it out.

**Comment by Squinkerdoodle** [comment]
Correct, in era if a mob moves out of range while you're aiming the shot / before it goes off it will interrupt the ranged attack. This can be closed I'm pretty sure.

**Comment by Cyr-test** [comment]
mystery solved!
