### ISSUE TITLE
🐛[BUG][Combat] OoE cure V CE/VE values

### ISSUE THREAD

**Issue by TracentEden** [HorizonFFXI/HorizonXI-Issues#282]
**What does this bug affect?**
- The enmity for Cure V is different in spell_list.sql (VE: 700 CE:400, era values) compared to enmity_container.cc (VE: 600 CE:300, current retail values)

**Steps to Reproduce**

**Expected behavior**
- The enmity for Cure V should be VE: 700, CE:400 (era values) in both files

**Screenshots**

**Setup Information**

**Additional context**

**Comment by The-Aerec** [comment]
Cure V is 400 ce 700 ve: See era_spell_list.sql
