### ISSUE TITLE
🐛[BUG] Limbus battlefield buff bug.

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#287]
**What does this bug affect?**

The battlefield buff wasn't removed from some of us properly after we timed out in limbus. 
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by jmcmorris** [comment]
Fixed with https://github.com/LandSandBoat/server/pull/3022
