### ISSUE TITLE
🐛[BUG] SW Apollyon Issues

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#288]
**What does this bug affect?**
When trying to enter some alliance members were able to get in and others weren't. Those who were unable to enter consisted of people both with and without the COP 8-1 done / activated.

All members were unable to interact with the time/item armory crates, making it impossible to get time extensions.

Once the limbus timer ran out and we were removed from SW Apollyon the battlefield buff was not removed properly from everyone in the alliance, and had a mix of people that still had the BC buff and those that didn't. Though we were able to get it to wear off by using !goto on ourselves.

**Setup Information**
30221004_0

**Comment by jmcmorris** [comment]
Should be fixed with the following PRs
https://github.com/LandSandBoat/server/pull/2996
https://github.com/LandSandBoat/server/pull/3022
