### ISSUE TITLE
🐛[BUG] NW Apollyon Issues

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#289]
**What does this bug affect?**
When trying to enter some alliance members were able to get in and others weren't. Those who were unable to enter consisted of people both with and without the COP 8-1 done / activated.

We were able to open the time / item armory crates in this zone, although they would respawn afterwards. After they respawned we were unable to interact with them and some of them did not have a visible model, though we were able to run into it's hitbox and target it even though it was invisible.

Kaiser Behemoth did not cast meteor at all. Checking the !getstats command showed it has 0 MP. (Also fed it TP just in case and still no meteor)

**Setup Information**
Version 30221004_0

**Comment by jmcmorris** [comment]
The following PRs fix the mentioned issues
https://github.com/LandSandBoat/server/pull/2996
https://github.com/LandSandBoat/server/pull/3021
https://github.com/LandSandBoat/server/pull/3023
