### ISSUE TITLE
🐛[BUG][Quest] - Wild Card (Quest)

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#29]
**What does this bug affect?**
Unable to complete quest "Wild Card (Quest)" due to the [House of the Hero](https://ffxiclopedia.fandom.com/wiki/House_of_the_Hero) in [Windurst Walls](https://ffxiclopedia.fandom.com/wiki/Windurst_Walls) not giving the cutscene with either Joker or Apururu when interacted with. The Hero House only gives the dialogue "The doors are firmly sealed shut."

**Steps to Reproduce**
Accept quest and speak with the 2 NPCs before the House of the Hero step.

**Expected behavior**
When interacting with House of the Hero door at this step in the quest it should give a cutscene with either Joker or Apururu and allow you to proceed with the quest.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
N/A

**Comment by dallano** [comment]
Found a fix! Will be PR'ing soon
