### ISSUE TITLE
🐛[BUG][System] Tracking NPC's with Wide Scan will r0 home nation

### ISSUE THREAD

**Issue by RetroPrez** [HorizonFFXI/HorizonXI-Issues#290]
**What does this bug affect?**
Disconnects yourself and anyone in the home nation by r0. Also seemed to r0 someone logged into Bastok from Windurst Woods. 
Wide Scan tracking <ins>does</ins> currently work in outdoor zones.

**Steps to Reproduce**
Use Wide Scan and Track an NPC in home nation.

**Expected behavior**
Target name should show up beside compass on HUD.

**Screenshots**
![widescanNPC](https://user-images.githubusercontent.com/112651690/197371671-1b6f1aaa-f9b5-4841-81cd-14ffb3b3423f.png)

**Comment by RetroPrez** [comment]
![Retro_2022 10 22_234113](https://user-images.githubusercontent.com/112651690/197372532-eeefa9f8-1ab3-4c34-ad55-f72fb9f99acc.png)

**Comment by OpheliaXI** [comment]
This only needs to be fixed on Horizon.
