### ISSUE TITLE
🐛[BUG][Apollyon] NE Item chest dropped SCH af1+1 item

### ISSUE THREAD

**Issue by piihub** [HorizonFFXI/HorizonXI-Issues#291]
**What does this bug affect?**
Should not be getting out of era af1+1 items

**Steps to Reproduce**
Open item chests in apollyon. Should eventually get SCH (potentially other OOE jobs) af1+1 item

**Expected behavior**
Should not drop SCH or DNC items

**Comment by piihub** [comment]
Just got DNC item as well from chest

**Comment by jmcmorris** [comment]
Horizon will need an override for these. I am planning on reworking the Apollyon drop tables soon so let's hold off on that for the time being.

**Comment by jmcmorris** [comment]
This is no longer an issue as it was fixed just before launch.
