### ISSUE TITLE
🐛[BUG][Apollyon]Logging off before timer ends, then logging back after timer has ended, does not kick you out of the instance

### ISSUE THREAD

**Issue by piihub** [HorizonFFXI/HorizonXI-Issues#292]
**What does this bug affect?**
A player is able to stay inside the apollyon battle area (whatever they entered) even after they have been timed out

**Steps to Reproduce**
Start a run. Log off immediately. Wait beyond the remaining time on limbus.
Log back in.

**Expected behavior**
Should be kicked out of limbus

**Comment by piihub** [comment]
I'm unsure if this is a dupe of https://github.com/HorizonFFXI/HorizonXI-Issues/issues/287 since that seems to not have specific steps to repro

**Comment by Squinkerdoodle** [comment]
Yea that does seem like a barebones report D:

**Comment by jmcmorris** [comment]
I believe this has been fixed with https://github.com/LandSandBoat/server/pull/3022

**Comment by jmcmorris** [comment]
I'm going to test it myself real quick.

**Comment by jmcmorris** [comment]
It still persists. Thanks for reporting!

**Comment by jmcmorris** [comment]
Fixed in https://github.com/LandSandBoat/server/pull/3025
