### ISSUE TITLE
🐛[BUG][Apollyon] Armoury Crates remain (although invisible and not interactable) after opening them

### ISSUE THREAD

**Issue by piihub** [HorizonFFXI/HorizonXI-Issues#294]
**What does this bug affect?**
Just a visual bug. Players see the invisible armoury crate after opening it. Players cannot interact with the invisible crate.

**Steps to Reproduce**
Enter apollyon NE (have not tried other zones yet). Open a crate.

**Expected behavior**
Crate should disappear

**Screenshots**
![armoury crate](https://user-images.githubusercontent.com/112743840/197379287-ca34928b-9e8f-47dd-95bb-5aeaffddcffa.PNG)

Note that it's not shown in the screenshot, but the targeted name says "Armoury Crate"

**Comment by Squinkerdoodle** [comment]
Seems the same as the loot box issue reported on https://github.com/HorizonFFXI/HorizonXI-Issues/issues/289

**Comment by jmcmorris** [comment]
Fixed in https://github.com/LandSandBoat/server/pull/3021
