### ISSUE TITLE
🐛[BUG][Apollyon] Apollyon NE Floor 2 Issues 

### ISSUE THREAD

**Issue by piihub** [HorizonFFXI/HorizonXI-Issues#295]
**What does this bug affect?**
In floor 2 of apollyon NE, a set of small issues were found (that are not listed in other separate tickets):

- Big birds (Bialozar / Thiazi) are sleepable. They should be immune to sleep
- Big birds do not aggro when getting close to the chest. They should.
- Cornu (The brown small birds) aggro when getting close to the chest. They shouldn't.

**Steps to Reproduce**
Get to apollyon NE floor 2.
Open a chest from behind the birds. You will see none aggro (if opening a chest with sirnus on it, the pink birds), or
the small birds aggro (if opening a chest with pink birds)

**Expected behavior**
Only big birds should aggro when getting close (even when from behind) their chest.
Big birds should not be sleepable.

**Comment by jmcmorris** [comment]
Thanks for the report!

The little birds do aggro by sound as can be seen in this capture video:
https://youtu.be/CNJNBhTBse8?t=701
https://youtu.be/CNJNBhTBse8?t=795
