### ISSUE TITLE
🐛[BUG][NPC/System]Moblin Maze Mongers content/NPCs are out of era.

### ISSUE THREAD

**Issue by AzrielltheWise** [HorizonFFXI/HorizonXI-Issues#296]
**What does this bug affect?**

Moblin Maze Monger NPCs are intact in Lower Jeuno.  In the Lower Jeuno Chocobo Stables there is the NPC Maze Mongers Shopfront (added in Dec 2008).  In Muckvix's Junk Shop (Lower Jeuno goblin store) there is Duplidoc (added in Apr 2009).      Maze Mongers Shopfront is used to teleport to a Moblin Maze by trading a Maze Tabula.  Duplidoc copies Maze Tabulas for a fee.
**Steps to Reproduce**

**Expected behavior**

These NPCs should not exist during the CoP era.
**Screenshots**

![image](https://user-images.githubusercontent.com/90195635/197410550-f25be540-22c3-42de-99d8-fbbaa764c2f2.png)

![image](https://user-images.githubusercontent.com/90195635/197410527-0ba447c9-0c18-476d-94f3-97a22a793342.png)

**Setup Information**

/ver 30221004_0
**Additional context**

https://ffxiclopedia.fandom.com/wiki/Maze_Mongers_Shopfront
https://ffxiclopedia.fandom.com/wiki/Duplidoc

**Comment by CriticalXI** [comment]
If this is not already, please list these NPCs in the npc-tags channel
