### ISSUE TITLE
🐛[BUG][System] Level Sync is Syncing Gear

### ISSUE THREAD

**Issue by KiplingFFXI** [HorizonFFXI/HorizonXI-Issues#3]
**What does this bug affect?**

Level sync currently is syncing gear instead of taking it off.

**Steps to Reproduce**

1. Go into a level capped BCNM or use level sync in the open world
2. Your gear doesn't get taken off but instead gets synced down

**Expected behavior**

It should take your gear off and not sync it.

**Screenshots**

![Kipling_2022 08 21_181034](https://user-images.githubusercontent.com/111715243/185820476-96e52b4d-a945-4d2c-82a5-f4177cc7305b.png)

![Kipling_2022 08 21_181814](https://user-images.githubusercontent.com/111715243/185820869-d58930c0-9242-486c-8f67-d20bbfe6910f.png)

**Setup Information**

Game version: Horizon Test server, version 30220802_3

**Additional context**

Not sure if this is a bug, I am just assuming it is because I doubt Horizon is using gear sync.

**Comment by CriticalXI** [comment]
This was fixed by disabling a server setting. Should be good now.
