### ISSUE TITLE
🐛[BUG][Quest] - Escort for Hire (San d'Oria)

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#30]
**What does this bug affect?**
Unable to start quest.

**Steps to Reproduce**
Speak with quest giver with rank 6 Sandy rep. Quest giver give beginning quest dialogue, however quest does not show up in quest log and the NPC gives the beginning quest dialogue repeatedly when spoken with. No cutscene received when zoning into Eldieme Necropolis.

**Expected behavior**
Quest should start after speaking with the quest giver and quest should show in the quest log. Player should receive cutscene after zoning into Eldieme indicating the escort can be commenced.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

N/A

**Comment by hookstar** [comment]
Quest needs to be written.

**Comment by Twispn8** [comment]
> 

same issues no quest was given after speaking w/ the npc and repeated quest dialogue.
