### ISSUE TITLE
🐛[BUG][Apollyon] NW Resistance issues

### ISSUE THREAD

**Issue by piihub** [HorizonFFXI/HorizonXI-Issues#300]
**What does this bug affect?**
Resistances seem to not match wiki in 2008/2009. I am not sure if these resistances were added to wiki from 2008 and on just because noone captured that data before that, but it seems unlikely.

- Buffalos on floor 2 can be lullabied
- Bugards on floor 3 can be lullabied

**Steps to Reproduce**
Get to floors 2 and 3 of apollyon NW and cast lullaby on the bugards and buffalos

**Expected behavior**
Mobs should fully resist lullaby

**Comment by jmcmorris** [comment]
I'm going to close this as the real issue is now being tracked here: https://github.com/LandSandBoat/server/issues/3108
