### ISSUE TITLE
🐛[BUG][Quest] Incorrect Dialogue for Waters of the Cheval

### ISSUE THREAD

**Issue by zance21** [HorizonFFXI/HorizonXI-Issues#302]
**What does this bug affect?**
When trading the waterskin to the Cheval River, the dialogue is incorrect and instead says "You find a cloth sack at the base of the signpost"

**Steps to Reproduce**
Do the quest up to where you trade the waterskin to the Cheval River and then trade it. 

**Expected behavior**
The dialogue should be "You fill your waterskin with water from the river. You now have a skin of Cheval River water."

**Screenshots**
https://i.imgur.com/JFnZZvY.png

**Additional context**
Item is still received like normal. Dialogue is the only thing messed up

**Comment by dallano** [comment]
Fix should be easy. IDs shifted recently.

**Comment by dallano** [comment]
I actually cannot replicate this. I got the correct messaging. What version are you playing on?

**Comment by zance21** [comment]
Just tried it on another character with an updated client and it was working fine. It must have just been the outdated client
