### ISSUE TITLE
🐛[BUG][Combat] Jidra (SW Apollyon) Issues

### ISSUE THREAD

**Issue by TracentEden** [HorizonFFXI/HorizonXI-Issues#303]
**What does this bug affect?**
- Jidra mobs on 2nd floor of SW Apollyon currently drop ancient beastcoins
- Mob spawned by killing a Jidra initially targets the player that was the last target of the Jidra

**Steps to Reproduce**
- Go to 2nd floor of SW Apollyon and kill a bunch of Jidra

**Expected behavior**
- Jidra should not drop ancient beastcoins, the coins should only be dropped by the mobs spawned by killing a Jidra (see videos with no coins from Jidra https://www.youtube.com/watch?v=Je5u7C1FCZU, https://www.youtube.com/watch?v=fEMacVBpoD4, https://youtu.be/v-7GrzFVQlk?t=8997 and era wiki page https://ffxiclopedia.fandom.com/wiki/SW_Apollyon?oldid=734634) 
- Mob spawned by Jidra should initially target a random player not always the last Jidra target (unclear if just in party of last Jidra target or full alli, see wiki page https://www.bg-wiki.com/ffxi/Jidra)

**Screenshots**

**Setup Information**

**Additional context**

**Comment by jmcmorris** [comment]
Huge 👍 for the reference links

**Comment by jmcmorris** [comment]
Are you sure Jidra were dropping coins? I just double checked in game and the code and I don't see how they could be.

**Comment by TracentEden** [comment]
> Are you sure Jidra were dropping coins? I just double checked in game and the code and I don't see how they could be.

I am like 90% sure as I commented on this in party chat during a run. However I do not have logs from the run, if you do not see them dropping while testing then maybe I was mistaken. Maybe close with fix for other Jidra issue and can reopen if someone sees it again.
