### ISSUE TITLE
🐛[BUG][Combat] Raise gives dead player two menu prompts with one non-functional

### ISSUE THREAD

**Issue by TracentEden** [HorizonFFXI/HorizonXI-Issues#305]
**What does this bug affect?**
- When raising someone the raise menu "allow yourself to be revived" appears twice (weather you choose yes or no), though the second one appears to be non-functional (i.e., selecting no on the first menu and then yes on the second does not raise).

**Steps to Reproduce**
- Raise someone

**Expected behavior**
- The menu should only appear once

**Screenshots**

**Setup Information**

**Additional context**

**Comment by jmcmorris** [comment]
I think this is my fault due to a recent change and I'll look into it.
