### ISSUE TITLE
🐛[BUG] SE Apollyon

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#306]
**What does this bug affect?**
1st floor slimes do not roam, and were only sitting in place. (Not sure if they should roam or not)
3rd floor skeletons were able to be slept with dark based sleep magic from a BLM.
4th floor boss physical damage resistance was normal without having to kill all the Flying Spears. Did not check magic damage, but it should be immune to magic until all Flying Spears are defeated; then it will take magic damage as normal.

**Setup Information**
Version 30221004_0

**Comment by jmcmorris** [comment]
![Siege_2022 10 26_084905](https://user-images.githubusercontent.com/1189557/198155752-9adaf4dd-b74c-4f7c-af38-1c6d176a7731.png)
You'll see the UDMGPHYS is increasing (removing resistance) and it is taking more damage.
