### ISSUE TITLE
🐛[BUG] Central Apollyon

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#307]
**What does this bug affect?**
Proto-Omega goes into bipedal form before hitting 70% hp.

GunPod did not drop any ancient beastcoins on both runs.

Proto-Omega is not using Pod Ejection frequently enough, during the test attempts it only used it once or twice per run.

Proto-Omega is using dagger WS in phase 2, and scythe WS in phase 3.
![image](https://user-images.githubusercontent.com/112344508/197923503-735f0498-0e12-49b9-b723-a12a3500a91a.png)
![image](https://user-images.githubusercontent.com/112344508/197923461-7ff9f2a2-0f82-4394-bb71-62c99c0878b1.png)

3rd form magic resistance seems to be wrong, seems to be taking full damage instead of being 50% minimum resistance to it.
![image](https://user-images.githubusercontent.com/112344508/197923952-dc0f645b-dbaa-443f-ab5d-11a230e61fb1.png)
![image](https://user-images.githubusercontent.com/112344508/197924362-14ed347f-9983-496f-9cbb-3b184f8902c7.png)

**Setup Information**
Version 30221004_0

**Comment by jmcmorris** [comment]
Proto-Omega switches modes based on time not HP%. 
Proto-Omega will only use Pod Ejection the first time switching to bipedal and then on a timer in final phase. 

https://www.youtube.com/watch?v=lJV2juzuDQQ
https://www.youtube.com/watch?v=qk-f6a1kBBg

I'll check out the wrong WS and resistances.

**Comment by jmcmorris** [comment]
Looking at the resistances it all looks like it should be right. Here are my numbers when doing Thunder IV with BLM 75 and Sorcerer's gear on:
bipedal: 91
quadruped: 350
3rd form: 229

You can use `!getmod UDMGMAGIC` to see what the current damage resistance value is at. If you can provide more information such as screenshots with the damage numbers at different stages that'd be helpful. Also if you can share your gear with me then I can try to replicate it better. Thanks!
