### ISSUE TITLE
🐛[BUG] CS Apollyon

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#308]
**What does this bug affect?**
Orc & Yagudo & Quadav NMs do not move or chase their target, though they will cast spells and melee if in range.

Quadav NM is casting rather quickly in succession, as pictured below. Believed to have started after it used Benediction, though we're not sure.

Yagudo seem to not be resistant to piercing damage.

Summoned helpers and bosses are both not dropping any ancient beastcoins. The only beastcoins we received were at the end of the run from the Armoury Crate.

NMs are not regaining their 2hr each time a new helper wave is summoned, and only used it once per NM.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/197927824-12a6c19d-5ece-4d4b-94ac-fe8d7942ad8a.png)

**Setup Information**
Version 30221004_0

**Comment by jmcmorris** [comment]
Retail verified that Yagudo are not resistant to piercing: https://youtu.be/qnEGCFWnOns
Regaining job special upon summoning support debunked here: https://www.youtube.com/watch?v=V-6PKds6oO0
ABC drops fixed here: https://github.com/LandSandBoat/server/pull/3067
Spam casting and following fixed here: https://github.com/LandSandBoat/server/pull/3073

That means all mentioned issues are now resolved or where not an issue to begin with.
