### ISSUE TITLE
🐛[BUG][NPC] Missing persistence on Taisaijin and Defoliate/Colorful Leshy

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#309]
**What does this bug affect?**

Notorious Monsters Taisaijin(17457216), Defoliate Leshy (16875763), Colorful Leshy (16875762)

**Steps to Reproduce**

After a server reset or crash the NMs will revert to 0 on their transformation timers.

**Expected behavior**

These NMs should have their transformation timers persist. 

**Additional context**

10/26/2022 Test server

**Comment by The-Aerec** [comment]
rose garden too?

**Comment by montijin** [comment]
> rose garden too?

Rose Garden/Vilma looks good from what I could tell.

**Comment by hookstar** [comment]
I believe that Argus will immediately respawn at server reset as well.. don't know if that's already been addressed or not.
