### ISSUE TITLE
🐛[BUG][Quest] - A Timely Visit

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#31]
**What does this bug affect?**
Unable to start quest A Timely Visit.

**Steps to Reproduce**
Speak with quest giver while meeting the quest requirements of: San d'Oria Reputation: 3 and rank high enough to enter Chateau d'Oraguille.

**Expected behavior**
Quest should be given so that it can be accepted and show up in the quest log.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
N/A

**Comment by dallano** [comment]
Quest recently implemented! PR: https://github.com/AirSkyBoat/AirSkyBoat/pull/405
