### ISSUE TITLE
🐛[BUG][Combat/] Byakko pop unclaimed, engaging it doesn't claim it

### ISSUE THREAD

**Issue by ccl085** [HorizonFFXI/HorizonXI-Issues#311]
Byakko pop and stay unclaimed, killing it result in no drop

![Ccldd_2022 10 27_154445](https://user-images.githubusercontent.com/48790940/198301899-f66f46d4-56c1-426c-93fb-adb99d409aee.png)

**Comment by ccl085** [comment]
More information: pop -> fight doesn't claim it but I did test: pop -> fight (no claim -> !goto ccldd -> engage again and that did claim it

**Comment by hookstar** [comment]
Could not replicate this. traded 1422 and 1423 and popped red on vanilla ASB.

**Comment by Twispn8** [comment]
Tested 3 times w/ 1422/23 spawned red each time.

**Comment by CriticalXI** [comment]
This was a problem awhile back that's been fixed for some time now.
