### ISSUE TITLE
🐛[BUG][NPC/Mission/System/] - Access to Marble Bridge Eatery, Upper Jeuno

### ISSUE THREAD

**Issue by BayaniTenzen** [HorizonFFXI/HorizonXI-Issues#314]
**What does this bug affect?**

Ability for people in an RoZ/CoP ERA server to Access the Marble Bridge Eatery

Currently it is possible for the Job Required to Access the door to include BLU/COR/PUP/DNC/SCH

**Steps to Reproduce**
Go to the Entrance of the Marble Bridge Eatery on the correct day and be asked to be present on an current unusable Job

**Expected behavior**
Shouldn't request use of BLU/COR/PUP/DNC or SCH whilst these Jobs aren't available in-game

https://ffxiclopedia.fandom.com/wiki/Marble_Bridge_Eatery?so=search

**Screenshots**
![image](https://user-images.githubusercontent.com/116040523/198404934-e2e64ef6-4c76-401c-bb53-28c75d32c508.png)

![image](https://user-images.githubusercontent.com/116040523/198405023-342d5884-c84b-460d-b320-fa341143224e.png)

**Comment by TracentEden** [comment]
See https://github.com/AirSkyBoat/AirSkyBoat/pull/2618
