### ISSUE TITLE
🐛[BUG][Combat] Limbus mobs (and potentially other non-exp yielding mobs) dropping KS

### ISSUE THREAD

**Issue by TracentEden** [HorizonFFXI/HorizonXI-Issues#315]
**What does this bug affect?**
Mobs in limbus are dropping Kindred Seals (KS). I do not think they should be, for example in the retail video (https://www.youtube.com/watch?v=Je5u7C1FCZU) no KS drops in the entire run. KS may also be dropping from other mobs that do not give exp so that general logic may need to be checked.

**Steps to Reproduce**
Go to limbus and kill mobs (in SW Apollyon for example the Fomors).

**Expected behavior**
No KS drops

**Screenshots**

**Setup Information**

**Additional context**

**Comment by The-Aerec** [comment]
Fixed via: 

https://github.com/LandSandBoat/server/pull/3059
