### ISSUE TITLE
🐛[BUG] BCNM - Idol Thoughts

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#316]
**What does this bug affect?**
Water / Earth / Wind Golems are using the wrong element for their Crystal Weapon move. Fire Golem is using fire element correctly. I tested it multiple times and with different # of golems alive and it was the same result.
Water Golem is using Earth
Earth Golem is using Wind
Wind Golem is using Water

**Expected behavior**
Golems should use the Crystal Weapon of their own element.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/198706352-85fee159-ed7a-43f1-aac6-e778ff677fd1.png)

**Setup Information**
Version 30221004_0

**Additional context**
Everything else in the fight works properly.

**Comment by hookstar** [comment]
https://github.com/AirSkyBoat/AirSkyBoat/pull/601
