### ISSUE TITLE
🐛[BUG] BCNM - Jungle Boogymen

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#317]
**What does this bug affect?**
On the first run the SMN NM's elemental had a dark elemental model but used light magic (as if it was actually a light elemental). Note that I could not replicate this issue and while making the SMN NM cycle through spirits it did summon a light elemental which worked properly, and did not summon a dark spirit again.
On the second run the SMN NM's elemental did not spawn next to the SMN NM upon initial entry, though it did not aggro to proximity / magic. Note that the SMN NM's elemental is still spawning at the location the SMN NM died in the previous run.
The third run was the same as the second run.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/198710494-af641444-8d61-41ab-91c3-7f14b5f81070.png)
![image](https://user-images.githubusercontent.com/112344508/198710308-75d157db-352b-481b-8cac-e25c090a7412.png)
![image](https://user-images.githubusercontent.com/112344508/198711676-7e2423e8-46b9-4ac0-9d69-56134b737b2f.png)

**Setup Information**
Version 30221044_0

**Additional context**
SMN NM is using Astral Flow correctly now with the avatar actually using it's move.

**Comment by Twispn8** [comment]
Same issues are present 
 - first run dark ele was out and was casting light magic, could not get dark ele to spawn again to check spells
 - second run could not get dark ele to spawn again to check spells, killed the smn nm closer to entrance 
 - third run the ele spawned where the smn nm was killed on second run. again could not get dark ele to spawn
