### ISSUE TITLE
🐛[BUG] BCNM - Dismemberment Brigade Loot Issue

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#319]
**What does this bug affect?**
Armory crate is only giving 3-4 drops instead of *up to* 6. Tested on multiple runs, all only gave 3 drops.

**Expected behavior**
Armory crate should give 6 rewards per capture vid: https://youtu.be/a-nGmqLaKiw?t=1608
Capture's 2 wins shows the following loot:
Dragvandil / zircon / peace ring / hi-reraise / mahogany log / moonstone - were their drops (hi-reraiser & mahogany log aren't listed in the wiki loot pool or in the current test server coding)
Dragvandil / flourite / peace ring / assault earring / jadeite / jadeite

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/198718204-0ea382be-f56d-4ec3-bbc8-bcd7fd078dc4.png)
![image](https://user-images.githubusercontent.com/112344508/198722729-c777211e-e98d-45d9-900d-1cd826d9bd6c.png)

**Setup Information**
Version 30221004_0

**Additional Information**
While testing the BCNM Jungle Boogymen I was getting 6 drops each run there. Just noting this in case it helps at all. 
On the BCNM Legion XI Comitatensis I had 6 drops on one run and then 4 on the other.

**Comment by Squinkerdoodle** [comment]
Yea I know that's how it's written in the code currently and it can drop multiple from some groups, however it's still missing the  hi-reraise / mahogany log that dropped in the capture vid.

**Comment by hookstar** [comment]
With that said, it looks like from the retail capture that they are broken into 

1x Weapon
1-2 Armor
0-1 rock
3 crafts
1 med (vial or reraiser from the video)

I added (for testing) an additional weapon 
![image](https://user-images.githubusercontent.com/16403542/199054653-fa4ee521-48f6-4d1d-b905-a152963ef49c.png)

**Comment by hookstar** [comment]
Aye, going to add the reraiser to the med and log to the crafts and add another slot for armor based on the video.

**Comment by hookstar** [comment]
![image](https://user-images.githubusercontent.com/16403542/199062680-0e3e1c0b-bdd4-451b-94b6-93666f787858.png)

got lucky i guess on the rock one so 6 for sure maybe 8. Is that what is expected behavior?

**Comment by hookstar** [comment]
> I need to look and see if there is ALWAYS 6 items (no more no less). If that's the case, then there will be a need to relook at the current structure. 

https://ffxiclopedia.fandom.com/wiki/Grimshell_Shocktroopers
says that "A mix of 6 out of the following".
