### ISSUE TITLE
🐛[BUG] BCNM - Demolition Squad

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#321]
**What does this bug affect?**
Nephiyl Pinnacletosser is at the arena entrance when entering.

Nephiyl Moatfiller & Keepcollapser are in the fight arena at spawn, but Nephiyl Rampartbreacher is nowhere to be seen. (seems to come from outside the arena to the West upon starting the fight)

Nephiyl Moatfiller does not use Charm as seen in capture: https://youtu.be/5wxSKHgumhM?t=219

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/198728422-e509c54a-aeb1-4f08-bb62-4830c16eb23a.png)
![image](https://user-images.githubusercontent.com/112344508/198728698-b860f489-00ee-40e5-9fe3-5069e2cb6d10.png)
![image](https://user-images.githubusercontent.com/112344508/198730160-681991ae-b4d8-4822-97a3-8b491077a94b.png)

**Setup Information**
Version 30221004_0

**Comment by hookstar** [comment]
He is watching you....
