### ISSUE TITLE
🐛[BUG][NPC/System] Housing Moogle Refusing to interact

### ISSUE THREAD

**Issue by BayaniTenzen** [HorizonFFXI/HorizonXI-Issues#325]
**What does this bug affect?**
Moogle inside Housing (Jeuno/Windurst/Bastok/Sand'Oria) all refuse to interact - clickable but immediately drop Dialogue

Using Main Menu > Page 2 > "View House" still provides Moogle Accessibility

**Steps to Reproduce**
Enter Moogle House > Talk to Moogle

**Expected behavior**

Should be able to fully access Moogle Inventory

Issue was streamed to Devs on Discord :)

**Comment by ZaksHouse** [comment]
I can agree to this one, a few of us maybe all? I target moogle, hit enter and nothing happens. Have to open up menu then go to mog house option.

**Comment by The-Aerec** [comment]
Fixed via: https://github.com/LandSandBoat/server/pull/3066
