### ISSUE TITLE
🐛[BUG][NPC] Proto-Omega Ability Issues

### ISSUE THREAD

**Issue by BayaniTenzen** [HorizonFFXI/HorizonXI-Issues#327]
**What does this bug affect?**

1# (Current) Start of the Fight - Omega instantly switches to Bi-Pedal mode and Spawns a "Gunpod" via Pod Ejection - then changes stances intermittenly - "Pod Ejection" appears to continue at 5 minute intervals regardless of HP%

1# (ERA) However Omega should remain on 4 Feet for the first 30% of the Fight; and upon reaching 70% HP switch in Bi-Pedal Mode which should cause the first cast of "Pod Ejection" spawning a "Gunpod" - then Omega would switch back and forth between forms - at specific intervals (unsure of trigger) and ALWAYS spawn a "Gunpod" on switching to Bi-Pedal Mode. Eventually when Omega reaches 30% HP it remains in Bi-Pedal Mode until killed. (Omega should take approx 50% less damage under 30% HP.)
![image](https://user-images.githubusercontent.com/116040523/198799335-7c679ffe-a8ff-4b8e-8ff2-9bbfaf934289.png)

2# Abilities that aren't working correctly:

Stun Cannon should do - 300 Conal Damage and Paralysis - but currently hits approximately 0 damage with no statuses applied
Hyper Pulse should do - 300 AoE Damage with Gravity and Bind - but currently hits approximately 0 damage with no statuses applied
Floodlight should do - 300 AoE Damage (through shadows) with Blind and SIlence - but currently hits approximately 0 damage with no statuses applied
Ion Efflux should be a Conal Attack with Paralysis - but currently doesn't apply Paralysis
Rear Lazers should be a Rear Conal Attack with Petrification - but currently hits approximately 0 damage with no statuses applied
Lazer Shower should be a Conal Attack with Defense Down with varying magic base damage - but currently hits for similar damage regardless of position.
Pile Pitch should also apply Bind with it's other effects but isn't currently
Additional Effect: Stun on Proto-Omega's Melee attacks should be around 20% chance? but feels more like 80%?

Finally Proto-Omega in Apollyon currently uses "Discharger" which is an ability from Story Mode Omega
https://ffxiclopedia.fandom.com/wiki/Discharger

**Comment by TracentEden** [comment]
> However Omega should remain on 4 Feet for the first 30% of the Fight

I do not think this is the case, see this era video https://www.youtube.com/watch?v=Usq6XZtpkcc (from June 2009) for more detail.

**Comment by Squinkerdoodle** [comment]
Adding the response I got for a similar submission: ( https://github.com/HorizonFFXI/HorizonXI-Issues/issues/307 )

Proto-Omega switches modes based on time not HP%.
Proto-Omega will only use Pod Ejection the first time switching to bipedal and then on a timer in final phase.

https://www.youtube.com/watch?v=lJV2juzuDQQ
https://www.youtube.com/watch?v=qk-f6a1kBBg

**Comment by Squinkerdoodle** [comment]
Additionally the issue with moves doing 0 dmg / not applying debuff is not specific to this fight and was an issue with the server in general which may be resolved now.

**Comment by BayaniTenzen** [comment]
I stand corrected - Arch-Omega remains on 4 Feet until at 70% HP
https://www.youtube.com/watch?v=7wiUdh4uTng

But even on the Era Videos linked - Omega is switching Forms after 2 mins and every two minutes thereafter - so his initial switch is still too soon
