### ISSUE TITLE
🐛[BUG][System]Gear Sync is still operational

### ISSUE THREAD

**Issue by Zyeriis** [HorizonFFXI/HorizonXI-Issues#33]
**What does this bug affect?**
Level syncing into a BCNM, gear above the level sync is still equipable.

**Steps to Reproduce**
Enter any level sync'd BCNM (We were doing Dropping Like Flies), have higher level gear equipped or try to equip said gear.

**Expected behavior**
Gear should be removed if above level sync and not be equipable.

**Comment by CriticalXI** [comment]
This is a server setting that was mistakenly turned off. This should be good to go now.

**Comment by CriticalXI** [comment]
Reopened because this is still a problem. I confirmed the server settings are set to disable gear sync but gear is still not being removed when level capped.

**Comment by OpheliaXI** [comment]
I have just checked and confirmed that gear scaling does disable with the setting. We can leave this issue open for another week, and if another occurrence pops up we need to check the settings file and record the findings. I have tried for the past hour with debug prints on and have yet to break it.

**Comment by OpheliaXI** [comment]
Since we haven't received any further reports of this even through all of the BCNM testing I will close out this issue. If it happens again we should reopen and investigate with known circumstances.
