### ISSUE TITLE
🐛[BUG] Apollyon CS issues.

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#333]
**What does this bug affect?**

Mobs aren't dropping anything.
Orc: 
 - Spams spells constantly even while not engaged he spams protect and shell. 
 - First wave and second wave mobs are swapped. 
 - Doesn't follow its target.
 - Orc only 2 hours 1 time. Should regain its 2 hour after it spawns a wave.
Yagudo: 
 - First wave and second wave mobs are swapped.
 - The Monk ad from the yagudo NM doesn't 2 hour
 - The Yagudo NM astral flow does crazy high damage. 2k+
 - Yagudo only 2 hours 1 time. Should regain its 2 hour after it spawns a wave.
Quadav: 
 - Spams spells constantly even while not engaged he spams protect and shell. 
 - Doesn't follow its target. 
 - Quadav only 2 hours 1 time. Should regain its 2 hour after it spawns a wave.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by Squinkerdoodle** [comment]
Linking https://github.com/HorizonFFXI/HorizonXI-Issues/issues/308 due to most issues already reported.

**Comment by jmcmorris** [comment]
The following issues are fixed in this PR https://github.com/LandSandBoat/server/pull/3073
- Doesn't follow its target.
- Spams spells constantly even while not engaged he spams protect and shell.

I will look at the remaining issues.

**Comment by jmcmorris** [comment]
Retail verified that Yagudo are not resistant to piercing: https://youtu.be/qnEGCFWnOns
Regaining job special upon summoning support debunked here: https://www.youtube.com/watch?v=V-6PKds6oO0
There isn't anything special about Astral Flow in this fight so if there is an issue with it doing too much damage I'd say that is outside of the scope of this issue.

Once the open PR is eventually merged into ASB and Horizon then this will be fully resolved. Thanks for catching these issues!
