### ISSUE TITLE
🐛[BUG][NPC/System] ASB "Bypass" for Airship/Dock has minor issue

### ISSUE THREAD

**Issue by BayaniTenzen** [HorizonFFXI/HorizonXI-Issues#334]
What does this bug affect?

Currently a Variable "player:setLocalVar('[AIRSHIP]Paid', 1)" is set to make sure people talk to the NPC and pay 200gil to access the Airship landing before interacting with the Shop NPCs:

Albinie (San d'Oria)
Uli-Pehkova (Windurst)
Denvihr/Sugandhi (Bastok)

Unfortunately there is a minor oversight in this set-up; it is possible to interact with the door which prompts the conversation with the NPC providing the "Local Variable" but this interaction doesn't provide the same LocalVar and puts the player onto the Airship landing correctly and legally but without the ability to interact with the Shop Vendors.

Steps to Reproduce
Interact with the Door to Airship Landing rather than the NPC - pay 200 gil but be unable to use the Shops on the outside Deck

Expected behavior

Interacting with Door or NPC should provide the same level of access?

**Comment by OpheliaXI** [comment]
Fixed, awaiting beta server update.
