### ISSUE TITLE
🐛[BUG][Mission]CoP5-3 Tenzen Path: Pride and Honor - Disaster Idol is immortal/1hp

### ISSUE THREAD

**Issue by RetroPrez** [HorizonFFXI/HorizonXI-Issues#336]
**What does this bug affect?**
Disaster Idol doesn't die and stays at 1hp, the name doesn't turn red while engaged either.

**Steps to Reproduce**
CoP5-3 Tenzen path: Pride and Honor - spawns from Cermet Door in Lower Delkfutt's. Using !hp 0 didn't work, and using !immortal on it twice made it killable, but didn't give a cutscene from the cermet door afterwards. I tried on different days (Fire, Earth and Water) and without !immortal on myself incase it was copying player stats, but no dice. 

I managed to kill it and receive the cutscene by leaving delkfutt's and letting it regen to full HP/reset. Zoning back in and fighting it before it despawns seems to work.

**Screenshots**
![Retroprez_2022 10 30_045103](https://user-images.githubusercontent.com/112651690/198871857-c1438ae2-ce31-4bdf-ba9f-b9e5a8c74771.png)

**Comment by hookstar** [comment]
I was able to force spawn it and kill it without any issues on current ASB build. 

![image](https://user-images.githubusercontent.com/16403542/199036187-6f5e6910-f1de-4219-8328-fd06185f04c4.png)

**Comment by CriticalXI** [comment]
I just went through this on my local and had no issues. I feel like this is a side effect of someone leaving it up with Immortal on and it despawning with it still on.

**Comment by hookstar** [comment]
Safe to say can close this one?

**Comment by CriticalXI** [comment]
Appears to be an issue with a mob shield that we added that is affecting all NMs. I'll keep this open until that is fixed.

**Comment by OpheliaXI** [comment]
Fixed in the newest PR related to MS on Horizon repo.
