### ISSUE TITLE
🐛[BUG][Mission/Combat]5-3 Ulmia Path: "Flames for the Dead" and "Head Wind" battlefield items

### ISSUE THREAD

**Issue by RetroPrez** [HorizonFFXI/HorizonXI-Issues#337]
**What does this bug affect?**
- Bearclaw Pinnacle "Flames for the Dead" Mission: 
Chunk of Shu'Meyo Salt item is consumed too fast (should take 10-12 seconds to activate) and has no effect on the Snoll Tzar despite having the working log messages. Snoll Tzar is getting bigger and using hypothermal combustion to self-destruct at the same time no matter how many shumeyo salt items are used.

- Boneyard Gully "Head Wind" Mission:
Blackened Muddy Siredon item can't be used on Shikaree X/Y/Z. Unsure if they actually have regain, but the item should work one time on each of the mithran trackers to stop their high TP gain.

**Comment by CriticalXI** [comment]
The effect on Snoll Tzar should be good to go now but I will fix the other ones. Didn't know the Siredon item existed!

**Comment by CriticalXI** [comment]
I see that the use time on Shu'Meyo Salt is actually quite quick unless this was changed in a later patch.
https://youtu.be/VRDnzJZZv88?t=537

**Comment by RetroPrez** [comment]
> I see that the use time on Shu'Meyo Salt is actually quite quick unless this was changed in a later patch. https://youtu.be/VRDnzJZZv88?t=537

Jun. 6th, 2007 - Treasures of Aht Urhgan
http://www.playonline.com/pcd/update/ff11us/20070606TsVPr1/detail.html
The following changes have been made to the Chains of Promathia missions:
5. Activation time for Shu'Meyo salt has been reduced from 10 seconds to 1 


- Video before the version update
https://youtu.be/sgkxwxsth4I?t=17 (Drax at 0:18)
Video after the version update
https://youtu.be/Xf7gMfN2wdU?t=26 (Seroph at 0:28)

**Comment by CriticalXI** [comment]
Thanks for that, adding in 10 second use time
