### ISSUE TITLE
🐛[BUG][Mission/NPC/Quest] Various OoE Issues

### ISSUE THREAD

**Issue by TracentEden** [HorizonFFXI/HorizonXI-Issues#338]
**What does this bug affect?**
The following are out of era:
- Transportation to Tu’Lia quest (added 12/2006)
- Players not losing experience points in missions (CoP, Nation, Zilart, ToAU) (added 06/2007, 03/2007)
- Goblin Bounty Hunters in Valkurm Dunes/Batallia Downs/Buburimu Peninsula/Qufim Island/Sauromogue Champaign/Korroloka Tunnel (added 03/2007, 08/2007)
- Certain teleporters (e.g., Teleporter I) located in the Shrine of Ru'Avitau send players to a fixed location (e.g., always to Kirin room) (added 05/2011)

**Steps to Reproduce**

**Expected behavior**
- No Transportation to Tu’Lia quest
- Players should loss experience points in missions
- Should not be Goblin Bounty Hunters
- Teleporter I located in the Shrine of Ru'Avitau should send players to one of the two large rooms on map 1 (one of which is Kirin) either at random or potentially based on even/odd game minutes

**Screenshots**

**Setup Information**

**Additional context**

**Comment by OpheliaXI** [comment]
Do not reopen.
