### ISSUE TITLE
🐛[BUG][NPC/System] Bibiki Bay / Purgo-Isle Skipper

### ISSUE THREAD

**Issue by BayaniTenzen** [HorizonFFXI/HorizonXI-Issues#339]
Bibiki Bay Clipper is stuck in No-Mans Land after playing leaving animation - it doesn't visually or physically travel along any of it's routes - zero Creatures spawn on the deck during the Journey - when journey is finished the Player teleport's from the Frozen vessel to the correct destination.

Steps to Reproduce

Purchase Single or Group Tickets for Bibiki Bay Clipper - get onboard - view leaving animation - Ship remains stuck at the exit of the bay - movement animations playing on the water but Ship doesn't move

Screenshots
![image](https://user-images.githubusercontent.com/116040523/198897578-25e89bef-43d0-40be-afbe-b702d33262f5.png)
![image](https://user-images.githubusercontent.com/116040523/198897492-43e7a590-6a6f-4961-855b-d19557e381dc.png)
![image](https://user-images.githubusercontent.com/116040523/198897641-aaaa92cd-afd7-4662-98b6-4e8aab108289.png)
![Rhowen_2022 10 30_185933](https://user-images.githubusercontent.com/116040523/198897703-9f327ea4-778e-476c-b1a5-50b385f9f0f4.png)
![Rhowen_2022 10 30_190335](https://user-images.githubusercontent.com/116040523/198897715-4226ca4b-a2e6-4acd-a27e-cb342e4a516b.png)
![Rhowen_2022 10 30_190539](https://user-images.githubusercontent.com/116040523/198897727-ed2cb86d-9479-4c1a-8b33-e39c7b550fb1.png)

![Rhowen_2022 10 30_190617](https://user-images.githubusercontent.com/116040523/198897736-95639753-2780-473e-8a71-c8e841df4d1f.png)
![Rhowen_2022 10 30_190626](https://user-images.githubusercontent.com/116040523/198897746-0b1b592a-fcd3-415e-a6fc-552322acc315.png)
![Rhowen_2022 10 30_190638](https://user-images.githubusercontent.com/116040523/198897751-f5eb22de-6afa-4d41-aff2-b1fd300f5e7d.png)

These last two images are the position the Skipper is stuck at after Cutscenes:

![Rhowen_2022 10 30_190655](https://user-images.githubusercontent.com/116040523/198897762-a1c06366-54a9-4722-b3e3-3fdc8aac9f6a.png)
![Rhowen_2022 10 30_190706](https://user-images.githubusercontent.com/116040523/198897764-665f4a40-1105-4757-81cc-019fba2827c8.png)

**Comment by Squinkerdoodle** [comment]
Linking https://github.com/HorizonFFXI/HorizonXI-Issues/issues/55 due to being for the same issue.

**Comment by CriticalXI** [comment]
Duplicate #55
