### ISSUE TITLE
🐛[BUG][Combat] - Diabolos Nightmare Blood Pact

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#34]
**What does this bug affect?**
Diabolos Nightmare does 0 damage and does not put mobs to sleep or deal DoT damage.

**Steps to Reproduce**
Summon Diabolos and use Nightmare BP and monitor log.

**Expected behavior**
Nightmare should put mobs to sleep and deal DoT damage.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Comment by dallano** [comment]
@paladindamarus I think I remember seeing you had worked on this recently. Was this fixed at all?

**Comment by Squinkerdoodle** [comment]
This issue is still present as of Oct. 11th.

**Comment by paladindamarus** [comment]
Got it.  I'll take a look ... This will be on my to-do.

**Comment by paladindamarus** [comment]
I remember now that I think of it that I held off on some of the BPs because there was an underlying issue with getting the right damage formulas and stuff first and I didn't want to fix the wrong problem.  I will push this one back up my list.

**Comment by Squinkerdoodle** [comment]
Closing as Nightmare is now working on test server.
