### ISSUE TITLE
🐛[BUG][System] Party forming issues

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#340]
**What does this bug affect?**

Currently when invites go out to more than 6 people, additional people can "join" the party. 
**Steps to Reproduce**

Invite more then 6 people to the party, observe when everyone hits /join that the party malfunctions.
**Expected behavior**

Any party member above the 6th will not be allowed to join. 
**Screenshots**

![image](https://user-images.githubusercontent.com/2160211/198898645-6ca095a2-ca0b-475c-b614-25961bf81ad3.png)

**Setup Information**

**Additional context**

10/30/2022 test server

**Comment by OpheliaXI** [comment]
I haven't been able to reproduce this, Monti can y'all try it again and see if you can?

**Comment by OpheliaXI** [comment]
@montijin have y'all been able to repro this?

**Comment by montijin** [comment]
> @montijin have y'all been able to repro this?

I'll try to remember to test this next time we have a group testing session.

**Comment by OpheliaXI** [comment]
Since there hasn't been any movement on this I'll close it out for now.
