### ISSUE TITLE
🐛[BUG]Groundskeeper - Ru'Aun Gardens

### ISSUE THREAD

**Issue by ZaksHouse** [HorizonFFXI/HorizonXI-Issues#341]
**What does this bug affect?**
Was testing out BST with flamingo vs Groundskeepers. The Groundskeeper finally used "meltdown ability" mob should blow up and gain experience. Health stays at whatever % it blows up. The mobs nameplate stays on screen, but mob vanishes from screen, and pet still attacks. Groundskeeper still attacks as well didn't gain experience until flamingo killed. 
Also forgot to mention meltdown does 0 damage.

**Steps to Reproduce**
Threw a pet at it until it used meltdown tried various times same result

**Expected behavior**
Blows up, and HP should go to 0% and pet should disengage and come back to me and I gain XP if it survives Meltdown that is.

**Screenshots**

![Zjinn_2022 10 30_160808](https://user-images.githubusercontent.com/46058451/198899901-c68262c8-32d5-41eb-b693-8135e5675ec3.png)
![Zjinn_2022 10 30_161804](https://user-images.githubusercontent.com/46058451/198899902-6f000dba-5a31-4a77-a841-279e9ec8f0e1.png)

**Comment by CriticalXI** [comment]
I think this is related to a bug with mob tp skills that is already fixed. It should be pushed to live soon.

**Comment by OpheliaXI** [comment]
Fixed already, closing this issue.
