### ISSUE TITLE
🐛[BUG][Combat] Blood Pacts do not have skillchain or magic burst properties

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#342]
**What does this bug affect?**

Summoners, skillchains, magic bursts
**Steps to Reproduce**

Try to make a skill chain with a blood pact or magic burst with one
**Expected behavior**

Blood pact: rage should be able to skillchain and magic burst
**Screenshots**

**Setup Information**

**Additional context**

10/30/2022 test server

**Comment by OpheliaXI** [comment]
@paladindamarus I know you removed these originally in a PR, could you add them back once you are done with fishing? Otherwise tell @Frankie-hz to do it #FuckFrank.

**Comment by CriticalXI** [comment]
BPs above a certain level do not skillchain. I would double check that. I believe its 65+ they don't have skillchain properties.

**Comment by paladindamarus** [comment]
Addressed by PR 170 on Horizon.
https://github.com/HorizonFFXI/HorizonXI/pull/170
