### ISSUE TITLE
🐛[BUG] Low damage hits not playing attack sound / visual

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#346]
**What does this bug affect?**
Low damage hits are not playing the hit animation / sound when dealing damage. Higher damage hits are playing the hit sound / visual correctly.

**Steps to Reproduce**
Witnessed as a level 1-3 warrior smacking mobs outside of Bestok.

**Expected behavior**
Any melee (non-crit) hit that does damage should have the hit animation & sound.

**Screenshots**
Low damage hits visually look like a miss:
![image](https://user-images.githubusercontent.com/112344508/199113857-bf151773-d05c-43d4-b405-e9fbf9e9644b.png)
![image](https://user-images.githubusercontent.com/112344508/199113913-8d000390-44a2-4280-b9f3-e4a939363172.png)

Instead of having a hit animation & sound like a normal hit:
![image](https://user-images.githubusercontent.com/112344508/199113952-cdc77cfb-43b4-44a3-ab5e-9bb209d3eaab.png)

**Setup Information**
Version 30221004_0

**Comment by xkoredev** [comment]
I just tried this on ASB and seems to be working fine (1 dmg hits included)
