### ISSUE TITLE
🐛[BUG][BCNM]Dropping Like Flies Hate Mechanics

### ISSUE THREAD

**Issue by Zyeriis** [HorizonFFXI/HorizonXI-Issues#35]
**What does this bug affect?**
The BCNM: Dropping Like Flies

**Steps to Reproduce**
Have some one provoke the Huntfly, then have some one autoattack it, followed up with a high enmity generating move such as invincible or sentinel. Only the target will switch targets, the rest will continue attacking whoever already had hate.

**Expected behavior**
All the enemies in the BCNM should have shared enmity (with the reduced values for non-targets).

**Comment by dallano** [comment]
Fix pushed! the hate behaviour is actually kind of cool. They agro the huntfly's target 1 by one every 2-5 seconds or so
