### ISSUE TITLE
🐛[BUG][Mission/Combat] ZM5 NM issues

### ISSUE THREAD

**Issue by TracentEden** [HorizonFFXI/HorizonXI-Issues#350]
**What does this bug affect?**
- Legendary Weapon and Ancient Weapon do not despawn
- Both Legendary Weapon and Ancient Weapon must be killed to get the fragment
- Doomed Pilgrims is always unclaimed when fighting (never red, potentially related to some widespread pop NM issue)
- Doomed Pilgrims immediately recovers to 100% HP after deaggro (player using hide for example)
- Tipha and Carthi are always unclaimed when fighting (never red) and immortal at 1% HP (again potentially related to some widespread pop NM issue)
- Both Tipha and Carthi aggro when popping with Sneak

**Steps to Reproduce**
- Pop and fight the ZM5 NMs

**Expected behavior**
- Should be able to kill only the Ancient Weapon and let Legendary Weapon despawn and still get fragment (see https://www.youtube.com/watch?v=KRgs08Kcgaw&t=307s), based on ASB code I do not think this is the case (however cannot test because of despawn issue)
- For Tipha and Carthi, when popping with Sneak only Tipha should aggro. Thus player should be able to kill Tipha first and then Carthi afterward (see https://www.youtube.com/watch?v=YS1TmzWnxoc), rather than fighting both at the same time.
- Other expected behavior for above is self explanatory

**Screenshots**

**Setup Information**

**Additional context**

**Comment by dallano** [comment]
Fix incoming for aggroing behaviors of tipha, carthi, and ancient and legendary weapon.
