### ISSUE TITLE
🐛[BUG] BCNM - Amphibian Assault

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#351]
**What does this bug affect?**
Pevv the Riverleaper's wyvern spawns at the location where the DRG NM used it's 2hr in the previous fight. Additionally the wyvern respawns as soon as it's name fades away after being killed, and keeps respawning this way until the DRG NM is killed. Lastly the wyvern despawns when the DRG NM is killed instead of persisting and having to be killed on it's own.

**Steps to Reproduce**
Go into the fight and kill the other mobs off so it's just the DRG and wyvern mobs. Move the DRG into the tunnel and make it use it's 2hr and note the location. Clear the fight and start a new run, and see where the wyvern starts out at.

For the respawning issue, kill the wyvern while the DRG is still alive and see it respawn once the wyvern's name fades away and note the location it spawns at.

**Expected behavior**
DRG NM should spawn with wyvern next to it (or use it's 2hr on pull so the wyvern is summoned). Wyvern should stay dead once killed.

**Screenshots**
Wyvern's initial spawn location (this is where DRG used it's 2hr on the previous run)
![image](https://user-images.githubusercontent.com/112344508/199147013-71c6a778-9f2b-4521-8637-54681abd3494.png)
Killed wyvern:
![image](https://user-images.githubusercontent.com/112344508/199150118-b6d69a38-a2b5-44e3-9f82-4cb92ca752da.png)
Wyvern respawns:
![image](https://user-images.githubusercontent.com/112344508/199150125-21170194-58fa-4dea-9f7a-1936f40b36f2.png)
Pulled DRG away and killed wyvern again, wyvern respawns:
![image](https://user-images.githubusercontent.com/112344508/199150133-84fc7df0-2be6-49d9-84e7-69f599e1b9f6.png)
Wyvern despawns when DRG NM is killed:
![image](https://user-images.githubusercontent.com/112344508/199150144-edbe3de8-fc9a-4a20-9bc6-ed676d2d385d.png)

**Setup Information**
Version 30221004_0

**Comment by xkoredev** [comment]
I can take this

**Comment by xkoredev** [comment]
Actually going to focus on a big task before I tackle this.
If anyone else wants to take a stab meanwhile, this may be related to the petzoning info being restored for the wyvern.
I should be able to look at it next week otherwise
