### ISSUE TITLE
🐛[BUG] Dynamis mobs not using 2hr abilities

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#352]
**What does this bug affect?**
Dynamis mobs are not using their 2hr abilities at any point.

**Expected behavior**
Dynamis mobs should be able to use their respective 2hr ability.

**Setup Information**
Version 30221004_0

**Comment by hookstar** [comment]
All the zones?

**Comment by Squinkerdoodle** [comment]
I checked Bastok / Sandy / Jeuno and it was the same, assuming the others are having the issue as well.
