### ISSUE TITLE
🐛[BUG] Waking The Beast

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#353]
**What does this bug affect?**
Avatars are only using their lowest level physical BP or Tier 2 nuke BP, and no other BPs aside from their Astral Flow move. Additionally the avatar's physical BP damage may be too high, and the avatar will repeatedly use it's physical BP move until it uses it's tier 2 nuke to break the cycle, after which it starts to auto attack again.

Elemental pets in the fights are able to use tier 2 enfeebles instead of tier 1; i.e. slow II instead of just normal slow.

**Expected behavior**
Elemental pets should only have tier 1 enfeebles. Avatars should only use 1 BP instead of being able to chain physical BPs back to back, and should use more BPs aside from their lowest physical BP and tier 2 nuke BP.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/199156067-e3a9919f-01ae-481d-85d3-8f6822c4d196.png)
I'm a naked 75 monk in the pics below, but the damage seems like it may be too high still:
![image](https://user-images.githubusercontent.com/112344508/199152006-088a4044-5de0-4909-bc6f-5c5bf38021af.png)
![image](https://user-images.githubusercontent.com/112344508/199152691-6bfb31b2-a19b-44d4-ae17-ef783a079eae.png)
![image](https://user-images.githubusercontent.com/112344508/199156220-97550b42-2d30-41ac-a2a9-c524327dc982.png)
Shiva's 2hr on lightsday:
![image](https://user-images.githubusercontent.com/112344508/199152935-246f68fa-aa0b-4f34-b342-9e6fb07881d4.png)

**Setup Information**
Version 30221004_0

**Additional context**
I did not check all the fights, but since 3 had the same issue I'm assuming the same is for the other 3 as well.

**Comment by xkoredev** [comment]
I can look into this.
The BP repetition part was fixed with https://github.com/HorizonFFXI/HorizonXI-Issues/issues/354, so the list of issues is a bit smaller at least

**Comment by xkoredev** [comment]
Ok looks to me like there are three issues. One was solved already as mentioned (the ticket linked above).
Two remain to be fixed:
- Avatar skill lists are wrong. Ifrit i.e: only has fire2 and punch
- Elementals spawned in the bcnm share the same spell list as other elementals. So they can cast slow2. I'm not even sure that elementals outside (i.e attohwa chasm) are allowed to cast slow2, but assuming they don't cause they are not high level.

The avatar skill list should be easy fix, I can get that done soon.
Elemental's would have to be spawned with a different spell list, but I don't know that system well so there could be an easy way.

**Comment by xkoredev** [comment]
Ifrit moves from capture:

Crimson Roar
Meteor Strike
Inferno
Flaming Crush

**Comment by xkoredev** [comment]
titan moves from 
https://www.youtube.com/watch?v=iaoGwZ-Y_gQ
https://youtu.be/yVAOP2VSAtM

Geocrush
Earthern Fury
Megalith Throw

I don't see Earthern ward in neither of the two captures. It's safe to assume Earthern Ward is used since it's the only defensive move under 75, and all other avatars have 1 defensive move in their list of 4 TP moves.
