### ISSUE TITLE
🐛[BUG] Behemoth Shock Wave give players sleep

### ISSUE THREAD

**Issue by ccl085** [HorizonFFXI/HorizonXI-Issues#358]
Behemoth tp move shock wave has an additionnal effect of sleep
 
 Shock wave should be  Damage and Knockback.Ignores shadows per https://www.bg-wiki.com/ffxi/Category:Behemoth

**Comment by hookstar** [comment]
https://github.com/AirSkyBoat/AirSkyBoat/pull/600

**Comment by Squinkerdoodle** [comment]
@hookstar will this affect Chlevnik in the KS99 as well? Witnessed this happening there too.

**Comment by hookstar** [comment]
It should remove all mobs that have access to shock wave from sleeping them.
