### ISSUE TITLE
🐛[BUG] Storms of Fate (fight)

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#359]
**What does this bug affect?**
When under 10% it is possible for Bahamut's ai to break to where he will no longer auto attack or use TP moves (even when given 3000 TP)

**Steps to Reproduce**
Go into the fight and fight him until 10% and then let him build / use TP moves to see if he stops auto attacking / using TP moves.

**Expected behavior**
Bahamut should have no periods where he's not auto attacking / using TP moves / casting spells.

**Setup Information**
Version 30221004_0

**Comment by panicstevenson** [comment]
[Line 48](https://github.com/AirSkyBoat/AirSkyBoat/blob/staging/scripts/zones/Riverne-Site_B01/mobs/Bahamut.lua#L48) of the Bahamut logic looks pretty suspect. Wasn't able to play around with Bahamut's local variable while we were fighting.
