### ISSUE TITLE
🐛[BUG][System/Combat] Removing Groups Level Cap in a Level Sync'd Zone

### ISSUE THREAD

**Issue by BayaniTenzen** [HorizonFFXI/HorizonXI-Issues#360]
**What does this bug affect?**
Remove the Level Cap of a whole Party/Alliance by entering and exiting a BCNM in a Level Sync'd Zone

**Steps to Reproduce**

Be part of a Party or an Alliance
Have a Member enter a BCNM - examples Cloud Evoker > Ouryu Cometh (RS #A) or Quest > Storms of Fate (RS #B)
Whole Party receives the Battlefield or BCNM buff but aren't inside the Instance
Player inside has their Level Restrictions removed
Player who enters the Battlefield/BCNM exits the BCNM with "Flee" option
Whole Party or Alliance has the Level Sync removed when the Battlefield/BCNM buff disappears
Whole Party or Alliance are now level 75 in a capped zone.

**Comment by Squinkerdoodle** [comment]
We had this happen in both Riverne A & B

![image](https://user-images.githubusercontent.com/112344508/199381909-86b90b1f-7bef-4e1c-b061-abf95c283196.png)
![image](https://user-images.githubusercontent.com/112344508/199381929-bb4223ce-d0ba-47cd-8177-da997c397e4b.png)
