### ISSUE TITLE
🐛[BUG] Ghelsba Outpost moon is bugged

### ISSUE THREAD

**Issue by RetroPrez** [HorizonFFXI/HorizonXI-Issues#362]
![Rpz_2022 11 02_070003](https://user-images.githubusercontent.com/112651690/199476219-b158e653-3645-4da0-b0a6-e41019f991ec.png)

**Comment by OpheliaXI** [comment]
Likely won't fix, leaving this open so we can remember to fix it if time is available.

**Comment by hookstar** [comment]
that's no moon..
