### ISSUE TITLE
🐛[BUG] Players Shockwave land rate is way too strong

### ISSUE THREAD

**Issue by ccl085** [HorizonFFXI/HorizonXI-Issues#364]
The Great Sword weaponskill sleep additional effect is WAY too strong/accurate, I was able to sleep nid for 3min with it at 3000 TP (should have been floored hit rate) (I was able to do it on more mob but Nid is the only one I took screenshot).

![Ccldd_2022 11 02_235502](https://user-images.githubusercontent.com/48790940/199617973-dffb7bbc-3229-454c-97da-a9518a31c18b.png)

**Comment by OpheliaXI** [comment]
Was resolved with https://github.com/AirSkyBoat/AirSkyBoat/pull/606
