### ISSUE TITLE
🐛[BUG][Combat] Blind does not affect Ranged Accuracy

### ISSUE THREAD

**Issue by ccl085** [HorizonFFXI/HorizonXI-Issues#365]
Blind does not affect ranged accuracy (it should) -> 
![Ccldd_2022 11 03_003134](https://user-images.githubusercontent.com/48790940/199621808-83e2f0e9-966d-4234-9f97-ce601bd9bcc9.png)
 
And After blind, same racc  -> 
![Ccldd_2022 11 03_003216](https://user-images.githubusercontent.com/48790940/199621875-05219198-0a87-48c9-adcf-0d3f9d8de74d.png)

**Comment by The-Aerec** [comment]
This only affects checkparam
