### ISSUE TITLE
🐛[BUG] Demon Arrow Missing Racc

### ISSUE THREAD

**Issue by ccl085** [HorizonFFXI/HorizonXI-Issues#366]
Demon Arrow does not have the +5racc bonus ingame, other arrow possibly missing too need to check.

Edit: so does Kabura looking at -> item_mods.sql

**Comment by hookstar** [comment]
added both. will leave this open however for other ones that may pop up.,

**Comment by hookstar** [comment]
https://github.com/AirSkyBoat/AirSkyBoat/pull/613
