### ISSUE TITLE
🐛[BUG][Combat] Jug pets defense, evasion, accuracy and attack overrides are incorrect

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#367]
**What does this bug affect?**

BST Jug pets
**Steps to Reproduce**

summons a jug pet, !getstats, see that it's accuracy, attack, evasion and defense are incorrect.
**Expected behavior**

The calculations for jug pet stats are the same as monsters. 

Attack = 8 + (A+ skill rank for the level) + (STR)/2 + job traits)  * any multiplier
Accuracy = (A+ skill rank for the level) + (DEX)/2) + job traits)  * any multiplier
Defense = [f(level,family defense rank) + 8 + (VIT/2) + job traits] * family multiplier
Evasion =  f(level,main job evasion skill rank) + (AGI/2) + job traits * family multiplier

**Screenshots**

Level 41 Beetle Familiar on retail:
![image](https://user-images.githubusercontent.com/2160211/199624357-f12acd93-a09e-4d03-823c-1676c130fd08.png)
Level 41 Beetle Familiar on the test server:
![image](https://user-images.githubusercontent.com/2160211/199641010-9264942c-31fd-471c-b727-6a5525ca5811.png)

You can see that the formula lines up to expected values for the retail pet. 
- Beetle Family ranks = STR-C, DEX-C ,VIT- B, AGI-E, INT-E, MND-E, CHR-E
Level 41
- PLD ranks = STR-B, DEX-E, VIT-A, AGI-G, INT-G, MND-C, CHR-C
Level 41
- STR: 22+20 = 42
- DEX: 15+20 = 35
- VIT: 25+22 =47
- AGI: 10+15 = 25
- INT: 10+15 = 25
- MND: 20+15 = 35
- CHR: 20+15 = 35

Attack = [8 + 126 {A+ skill} + (42{STR})/2) ] = 155
Accuracy = [126 {A+ skill} + (35{DEX})/2) ] = 143 

**Additional context**

11/2/2022 test server

**Comment by ccl085** [comment]
Be carefull, defense on retail is different now even for pet, so pet on retail will have more defense from their VIT than an era server -> https://www.bg-wiki.com/ffxi/Defense  2 vit = 3 def instead of 2 vit = 1 DEF
