### ISSUE TITLE
🐛[BUG] ENM - Pulling the Plug

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#370]
**What does this bug affect?**
Terroanima is not causing the [Repiner](https://ffxiclopedia.fandom.com/wiki/Repiner) / [Contemplator](https://ffxiclopedia.fandom.com/wiki/Contemplator) / or [Ingurgitator](https://ffxiclopedia.fandom.com/wiki/Ingurgitator) to flee in terror.

**Steps to Reproduce**
Kill a memory receptacle to spawn one of the mobs and use a Terroanima on it to see what happens.

**Expected behavior**
Terroanima should cause the spawned mobs to flee from whoever has the most enmity for a short duration.

**Setup Information**
Version 30221004_0

**Additional context**
The only issue found was with the Terroanima. The rest of the fight and other 2 anima worked normally.

**Comment by The-Aerec** [comment]
probably needs the mixin added to them
