### ISSUE TITLE
🐛[BUG][Combat] Incorrect access to subjob WSs

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#372]
**What does this bug affect?**

Maat fights and Pulling the Strings

**Steps to Reproduce**

Enter the BRD Maat fight or ENM 60 as a BRD/WAR and notice that you retain access to vorpal blade.

**Expected behavior**

You should not retain access to weaponskills that require a certain subjob when your subjob is disabled in a battlefield. 

**Screenshots**

![image](https://user-images.githubusercontent.com/2160211/200040766-002c6662-4700-43eb-994b-14e941b82b0a.png)

**Additional context**

11/4/2022 test server

**Comment by panicstevenson** [comment]
Fixed on ASB
