### ISSUE TITLE
🐛[BUG][Combat] Ranged Weaponskill are using wrong PDIF

### ISSUE THREAD

**Issue by ccl085** [HorizonFFXI/HorizonXI-Issues#374]
I suspect ranged weaponskill are using 1h or2h weaponskill/melee pdif calculation instead of ranged pdif:
Using Slug Shot with capped ratt and capped FSTR with annihilator
WS = (D+FSTR+WSC) * PDIF * FTP
D= Annihlator (47) + Silver Bullet = 81  = 128
Capped FSTR2 = (weapon rank+8)2 = 26
PDIF = 3.0
FTP = 5.0 (no gorget)
WSC =30% of AGI = 76 AGI 0.3 * 0.83 (alpha) = 18.9 floor = 18
Expected Damage =(128+26+18) * 3.0 * 5.0 = 2580
Horizon Damage =  1700-1900 (Ranged damage doesn't varie when you cap ratt(unless I'm uber mistaking and thinking OOE?) too so something if wrong)

**Comment by OpheliaXI** [comment]
Test server hasn't been updated yet to have this fix.

**Comment by Frankie-hz** [comment]
Wont be fixed until one more PR.
