### ISSUE TITLE
🐛[BUG][Mission] Promyvian Mea Climb and Boss Issues

### ISSUE THREAD

**Issue by TracentEden** [HorizonFFXI/HorizonXI-Issues#379]
**What does this bug affect?**
- Strays cannot be aspired (have no MP)
- Memory receptacle can be slept
- Coveter has only one spawn area (south east part of level 3)
- Buffs do not wear when going from uncapped spire to capped level 4 area
- Delver (boss) does not return to center after wipe near entrance (maybe pathing issue with stairs)
- Cut scene after defeating Delver (boss) does not start until Delver (boss) despawns

**Steps to Reproduce**

**Expected behavior**
- Strays should be aspired (at least in some situations, see https://youtu.be/fID_mhaZCQE?t=831)
- Unclear if memory receptacle should be sleepable (maybe needs retail checking)
- Coveter should have two spawn areas (see https://ffxiclopedia.fandom.com/wiki/Coveter?oldid=204063, older wiki page states just one spawn area but no mention of change to spawn areas in SE patch notes, so was likely just incomplete info)
- Unclear if buffs should wear when going from uncapped spire to capped level 4 area (not possible to check anymore on retail)
- Delver (boss) should return to center after wipe near entrance
- Cut scene after defeating Delver (boss) should start when Delver (boss) dies (note this seems to maybe be widespread issue as I have also seen in other battlefield fights such as ZM4)

**Screenshots**

**Setup Information**

**Additional context**

**Comment by hookstar** [comment]
Coveter should have two spawn areas (see https://ffxiclopedia.fandom.com/wiki/Coveter?oldid=204063, older wiki page states just one spawn area but no mention of change to spawn areas in SE patch notes, so was likely just incomplete info) 

This is due to the issue of the portals. As it stands they only take you to one island, as far as I know. A few months ago I updated LSB to change the pop location to the island that everyone is sent it only.

**Comment by dallano** [comment]
Fixes incoming for aspir'ing strays and memory receptacle sleep immunity.

Cut scene coming after mob despawns is a universal issue across all battlefields and may need to be looked at. Not sure how @jmcmorris 's new battlefield system will handle this; if it will fix it or not.

Coveter spawning should be looked at by @Frankie-hz

**Comment by TracentEden** [comment]
Yeah, I made a bug on LSB about the general battlefield delay and should be handled once all missions are converted to new system and per battlefield delays are set (see https://github.com/LandSandBoat/server/issues/3190), so probably should not block this issue

**Comment by jmcmorris** [comment]
Using the new battlesystem framework should fix both the CS delay as well as the Delver returning to the center.

**Comment by siknoz** [comment]
Taken from current retail, receptacle is sleepable. 

![image](https://user-images.githubusercontent.com/78240569/222371717-7caa9e56-4267-4fd2-a058-c6a4d1d8ae36.png)
