### ISSUE TITLE
🐛[BUG][Combat] Reraise is not dispelable

### ISSUE THREAD

**Issue by TracentEden** [HorizonFFXI/HorizonXI-Issues#380]
**What does this bug affect?**
Reraise status effect is currently not able to be dispelled (despite being dispelable in era). This also causes a secondary issue that reraise is not wiped when entering capped battlefields (when it should be in era). I think the issue was introduced in this [commit](https://github.com/AirSkyBoat/AirSkyBoat/pull/231/commits/1a7628f777a96d9e56642a112c88233e6cae7ccb) which changed the right most bit of the status effect flag from 1 to 0 (in binary) and thus made the dispelabe flag (see EFFECTFLAG_DISPELABLE) a 0 (false).

**Comment by xkoredev** [comment]
For the record, flag went from:
`0x00000020 | 0x00000008 | 0x00000001` to `0x00400000 | 0x00000020 | 0x00000008`
So flag `0x00000001` (`EFFECTFLAG_DISPELABLE`) was lost and `0x00400000` (`EFFECTFLAG_ON_JOBCHANGE`) was gained.

Adding `EFFECTFLAG_ON_JOBCHANGE` makes sense, but `EFFECTFLAG_DISPELABLE` should not have been removed. Adding this flag again should fix the issue.
