### ISSUE TITLE
🐛[BUG][Mission] San d'Oria 2-3 leftover trust dialogue if doing Windurst first

### ISSUE THREAD

**Issue by RetroPrez** [HorizonFFXI/HorizonXI-Issues#381]
San d'Oria 2-3 - Windurst path -> Bastok dragon. 
Speaking with Kupipi for the Shield Offering on this path has leftover dialogue for receiving a trust cipher.
![Retro_2022 11 06_120837](https://user-images.githubusercontent.com/112651690/200184405-189089c8-f63c-4a7f-ba2f-10f238c02e58.png)

**Comment by dallano** [comment]
fix incoming
