### ISSUE TITLE
🐛[BUG][Mission] Ranperre's Final Rest - San d'Oria 6-2 heavy stone door

### ISSUE THREAD

**Issue by RetroPrez** [HorizonFFXI/HorizonXI-Issues#382]
**What does this bug affect?**
Can't progress beyond the Heavy Stone Door at H-8 after killing the 3 NM's. 
Touching the door simply respawns them again with a "You sense something evil." message.

**Expected behavior**
Wiki states 
"After winning the fight, you will not need to fight again to enter, even after zoning out or disconnecting"

**Screenshots**
![Rpz_2022 11 06_172022](https://user-images.githubusercontent.com/112651690/200195774-f6437cad-1ad5-4557-884c-604878634cd3.png)

**Comment by hookstar** [comment]
There seems to be a X pos check, but I doubt that is the issue here. It seems that killing the mobs is not progressing your mission variable prior to touching the door. Could you re-verify that it continues to spawn mobs multiple times?

Thanks!

**Comment by hookstar** [comment]
Fix incoming. Thanks!

**Comment by hookstar** [comment]
https://github.com/AirSkyBoat/AirSkyBoat/pull/620

**Comment by hookstar** [comment]
Ok, so its cool to tag the horizon issues in ASB PR's?

**Comment by The-Aerec** [comment]
yes
