### ISSUE TITLE
🐛[BUG][Mission] PM8-1 Rubious Crystal Ru'aerns respawn infinitely halting mission progress

### ISSUE THREAD

**Issue by RetroPrez** [HorizonFFXI/HorizonXI-Issues#384]
**What does this bug affect?**
Can't progress beyond PM8-1. Ru'aerns are affected by the immortal/claim bug, but they also respawn infinitely at the Rubious Crystals preventing mission progress. 

**Steps to Reproduce**
spawn Ru'aern x3 at Rubious Crystals for 8-1, use !goto <me> or !immortal on them twice to defeat if they stay at 1hp. 
Similar to previous issue : https://github.com/HorizonFFXI/HorizonXI-Issues/issues/382

**Screenshots**

![Retroprez_2022 11 10_052725](https://user-images.githubusercontent.com/112651690/201052666-6a90a138-b41b-4bf0-88c0-b9b880721a06.png)

**Comment by CriticalXI** [comment]
Already fixed, just needs a Horizon update
