### ISSUE TITLE
🐛[BUG] Dynamis Valkurm

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#387]
**What does this bug affect?**
Job traits & abilities of subjobs not restricted upon entry. Stats from subjobs are possibly not restricted. Spells are correctly restricted. /sea still showed full lvl 37 sj instead of 0 or blank subjobs.

Nothing showing up on RNG widescan at all for the entire run.

Subjob spells were not returned after killing the 3 flies.

Mega Boss Malboro breath attacks not going through shadows. Boss also used TP moves frequently (sometimes back to back) even with all 4 NMs killed.

**Setup Information**
Version 30221004_0

**Comment by TracentEden** [comment]
Additionally Cirrate Christelle (mega boss) has the following issues:

- Cirrate Christelle should not aggro (see https://www.youtube.com/watch?v=OvI_1829tpw)
- Extremely bad breath (of Cirrate Christelle) should be AoE with range of at least 12 yalms (see 3:47 into [capture video](https://drive.google.com/open?id=1F7J6oUoITuPseiRu1kp9vf7-OI9ajTVR) of Evil Oscar (KSNM Contaminated Colosseum) who also uses the move, could not find era video of Cirrate Christelle using move but logical for it to have a range at least as large as Evil Oscar)

**Comment by OpheliaXI** [comment]
This was fixed a while ago.
