### ISSUE TITLE
🐛[BUG][System] Trade request "Soft-Locking" players in Trades

### ISSUE THREAD

**Issue by BayaniTenzen** [HorizonFFXI/HorizonXI-Issues#388]
**What does this bug affect?**

Player A is able to soft lock Player B from trading with Player C and vice versa

**Steps to Reproduce**

Player A initiates trade with Player B - neither accept immediately
Player A then gets a trade request from Player C - which they accept
Player A and Player C can now trade back and forth normally - but Player B cannot trade with either Player A or C in any way
Player D comes over and trades with Player B - this is the first trade request that goes through to Player B since Player A's initial trade

Now all Players can Trade with each other again freely...

**Comment by OpheliaXI** [comment]
Already fixed by Winter 28 days ago immediately after this bug was reported.
