### ISSUE TITLE
🐛[BUG][System/Combat] Ninjtsu Magic Burst Message

### ISSUE THREAD

**Issue by BayaniTenzen** [HorizonFFXI/HorizonXI-Issues#389]
**What does this bug affect?**

Chat Text not displayed "Magic Burst! Raiton: Ni" when using Ninjitsu to Magic Burst

**Steps to Reproduce**

Blade: Teki > Blade: Chi for Impaction with a Raiton: Ni "Magic Burst" - damage increased on Raiton
https://cdn.discordapp.com/attachments/1032745731011907604/1040752870863159296/image.png

Blade: Teki > Blade: Chi for Impaction with a Raiton: Ni "Magic Burst" - damage increased on Raiton
https://cdn.discordapp.com/attachments/1032745731011907604/1040754391424192603/image.png

Screenshot of Testing to show that Suiton: Ni was reducing Thunder MEVA from the Target
https://cdn.discordapp.com/attachments/1030220939620782180/1040755229051858995/image.png

**Comment by StyrkaGG** [comment]
still currently an issue
