### ISSUE TITLE
🐛[BUG][Combat] Dagger - Energy Drain

### ISSUE THREAD

**Issue by ChaChang-Byte** [HorizonFFXI/HorizonXI-Issues#390]
Energy Drain deals damage and does not steal MP. May affect jobs that needs mp during battle when using Daggers.

**Steps to Reproduce**

Use a job that can use Energy Drain. Use Energy Drain

**Expected behavior**

Instead of dealing damage, it should steal MP.

**Screenshots**

![Pewpewpew_2022 11 12_101131](https://user-images.githubusercontent.com/74262047/201480685-997e1a71-027a-4c12-a91a-62a6da7905f7.png)

**Setup Information**

Windows 10: on beta testing server

**Additional context**

**Comment by CriticalXI** [comment]
Do not re-open
