### ISSUE TITLE
🐛[BUG][BCNM] BCNM40 - Royal Jelly

### ISSUE THREAD

**Issue by ChaChang-Byte** [HorizonFFXI/HorizonXI-Issues#392]
BCNM40 - Royal Jelly

Princess Jelly runs to middle of the field to create Queen Jelly in like 8 seconds, faster if they don't cast a spell. It makes Royal Jelly ridiculously hard.

**Steps to Reproduce**

Enter battlefield BCNM40 Royal Jelly

**Expected behavior**

Princess Jelly should take some time to reach the middle of the field

**Screenshots**

![Pewpewpew_2022 11 06_182455](https://user-images.githubusercontent.com/74262047/201481069-0b6575bf-d8a5-4f23-af97-0292d02cb8bc.png)
![Pewpewpew_2022 11 06_182503](https://user-images.githubusercontent.com/74262047/201481073-53b1f4ff-25af-4bc4-aa45-c0405088b8ef.png)

**Setup Information**

Windows 10 : beta server

**Additional context**

**Comment by dallano** [comment]
This issue was fixed by Aerec
https://github.com/dallano/server/commit/513bcdee4e16f1de7c4d66c91926250c11cec432
