### ISSUE TITLE
🐛[BUG][Mission] San d'Oria 8-1 Coming of Age

### ISSUE THREAD

**Issue by RetroPrez** [HorizonFFXI/HorizonXI-Issues#397]
**What does this bug affect?**
The two Kraken "Honor" and "Valor" spawn in the pool and don't link, but seem to be missing sound aggro. They are typically spawned with sneak up to engage only one while the other despawns.

**Comment by dallano** [comment]
The issue doesn't lie within them not linking sound. It's the ledge that they will not link up onto.

**Comment by montijin** [comment]
Different issue but I'm unable to get the cutscene to finish this mission and progress to 8-2. 
![image](https://user-images.githubusercontent.com/2160211/206299864-34f9ad7a-a1db-4686-b803-ae8e34800fe9.png)
