### ISSUE TITLE
🐛[BUG][Mission] San d'Oria 9-2: The Heir to the Light final boss

### ISSUE THREAD

**Issue by RetroPrez** [HorizonFFXI/HorizonXI-Issues#398]
The mission final boss for San d'Oria Rank 10 is incorrectly set as Yukvok of Clandeath instead of being Warlord Rojgnoj. Prince Trion NPC was also not present during the final phase of this battlefield.

**Comment by Shayemz** [comment]
Soooo. We actrually had THREE Trions in ours. And let me tell you, they fucked shit up. One of the Trion's almost solo'd Yukvuk. Usually you're worried about Trion dying, but these Trions could have solo'd this 2nd half of the BCNM. 

![image](https://user-images.githubusercontent.com/120886485/229393514-b2e4e863-4e76-4b5a-a1d8-7bc982a21a3d.png)
