### ISSUE TITLE
🐛[BUG][System] Die Twice When /sitchair, Losing Twice as Much EXP

### ISSUE THREAD

**Issue by panicstevenson** [HorizonFFXI/HorizonXI-Issues#399]
**What does this bug affect?**
When you die with /sitchair, you die and then you start the animation to get out of the chair, and then you die again 4 seconds later when the animation finishes.

**Steps to Reproduce**
`!addeffect Reraise 1 1000`
`/sitchair`
`!hp 0`

**Expected behavior**
Should only die once.

**Screenshots**
![image](https://user-images.githubusercontent.com/8849608/201559056-895fdf0c-3875-4720-a346-a72eb3f5766c.png)

**Setup Information**
version 30221103_1

**Additional context**
Doesn't apply to /sit.

**Comment by Squinkerdoodle** [comment]
Not sure this will be a real issue since /sitchair is OOE?

**Comment by panicstevenson** [comment]
I would imagine /sitchair doesn't get removed, but I could be wrong with custom DATs. Regardless I think it's very low priority since you're not often getting killed while /sitchair, since any hit will make you stand.

**Comment by Squinkerdoodle** [comment]
It *should* be removed since it wasn't introduced until 2015. I mean they're taking the job emotes out so I don't see why not.
