### ISSUE TITLE
🐛[BUG][Mission] San d'Oria Mission 5-2 "The Shadow Lord" - Missing Cutscene

### ISSUE THREAD

**Issue by KiplingFFXI** [HorizonFFXI/HorizonXI-Issues#4]
**What does this bug affect?**

According to wiki from Jan 2006 (https://ffxiclopedia.fandom.com/wiki/The_Shadow_Lord?oldid=42038) there is supposed to be a cutscene after the Shadow Lord fight where you talk to Prince Trion in the Great Hall before talking to Halver to obtain Rank 6. However, I could not receive one. Instead I talked to Trion and he just gave me my rank 6 rewards.

Also need to add that the BCNM capped me at level 50, it should have no level cap as evidence by the BG wiki FFXI history page which discusses that players were finally able to beat Shadow Lord when the cap was raised to 55: https://www.bg-wiki.com/ffxi/The_History_of_Final_Fantasy_XI/2002 - This implies there was no level cap.

There is also an entry from December 2005 on the talk section of the Wiki page for this mission that says someone did it solo as a level 75 BST: https://ffxiclopedia.fandom.com/wiki/Talk:The_Shadow_Lord#Level_75_Cap? - Again this means it should be a non-level capped fight.

**Steps to Reproduce**

Beat Sandy mission 5-2 and try to get the cutscene with Prince Trion at the Great Hall. Going to his quarters in the chateau also does not work.

Go into fight and get level capped at 50

**Expected behavior**

There should be an additional cutscene at the great hall in the chateau with prince trion. Also the fight should not have a level cap.

**Screenshots**

![Kipling_2022 08 27_155125](https://user-images.githubusercontent.com/111715243/187050666-29f21bae-4d71-4352-b2ac-71c422512211.png)

**Setup Information**

Game version: 30220802_3

**Additional context**

I used the !admission command to start this mission, if it matters.

**Comment by CriticalXI** [comment]
I believe this is already good. I see on the wiki linked that you aren't supposed to talk to Trion until after Halver. Looking at the mission code for this, there is code for speaking with him:
```
            ['_6h0'] =
            {
                onTrigger = function(player, npc)
                    if player:getMissionStatus(mission.areaId) == 1 then
                        return mission:progressEvent(547)
                    end
                end,
            },
```

_6h0 is Trion's door.
