### ISSUE TITLE
🐛[BUG] ENM - When Hell Freezes Over

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#401]
**What does this bug affect?**
At the beginning of the fight there are 6 Snolls spawned instead of just the first wave of 1-3 (each wave should consist of 1 to 3 Snolls). If all 6 of these snolls are defeated simultaneously (via thundaga 3 or other hard hitting AOE) then that will end the fight and spawn the chest.

However, if you kill each of the first 6 snolls individually another wave will spawn consisting of 2 snolls. Once these 2 additional snolls are killed the chest then spawns.

**Expected behavior**
Copied from wiki: There will be four waves of Snow Devils that must be fought in this ENM to win. When a wave is defeated, the next wave appears. Each wave has a random number of Snow Devils ranging between 1 and 3. There are a total of 4 waves of Snow Devils. Thus, the total number of Snow Devils fought for this ENM is between 4 and 12.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/201818273-5ec3df96-a66f-4475-b449-070e5e77208e.png)

**Setup Information**
30221103_1

**Comment by dallano** [comment]
@hookstar the way this BCNM is implemented explicitly requires the old system. Would you be able to revert this to the older system until I can work out a solution?

**Comment by hookstar** [comment]
Completed with merge #2184
