### ISSUE TITLE
🐛[BUG][Quest] The Brugaire Consortium - Thierride won't accept trade

### ISSUE THREAD

**Issue by zance21** [HorizonFFXI/HorizonXI-Issues#402]
**What does this bug affect?**
Thierride won't accept the trade for the Pub Parcel

**Steps to Reproduce**
Do the quest up to giving the parcel to the pub. Trade it to Thierride

**Expected behavior**
He should comment on you being an adventurer and accept the parcel

**Screenshots**
https://i.imgur.com/OLOtov2.png
https://i.imgur.com/kRXQcaW.png

**Comment by hookstar** [comment]
This is  happening because the quest A Taste for Meat has already been converted and thus takes priority and will never get to his script. The quest will need to be rewritten to the new framework.
