### ISSUE TITLE
🐛[BUG] ENM - Follow the White Rabbit

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#403]
**What does this bug affect?**
Bearclaw Leveret are spawned on top of Bearclaw Rabbit at the start.
If all Bearclaw Leveret are killed quickly before the Rabbit is, another Leveret wave will spawn. I'm guessing this 2nd wave is actually when the Leverets are supposed to spawn during the fight because when I left the original set alive for a few minutes and then killed them this 2nd set did not spawn.

Bearclaw Leveret not using Blood Weapon at all. Based on capture vid it seems at least 1 Leveret of the group has a chance to use it. Though one of the captures showed none of the Leverets using Blood Weapon so maybe it's just a low chance for each to use it. (Unless the 1 that was able to use it died when a different Leveret was killed. Hard for me to tell on this one based off the captures.)

Leverets are missing the chat log dialogue stating it's hopping around madly / fades into the morning mist. The morning mist message is for when you kill one Leveret and others get dismissed from the fight (basically killed off) along with it. Unsure what the hopping around madly message is from.

Bearclaw Rabbit does not seem to use it's Mighty Strikes until all the Leverets have been killed, regardless of what $ of HP it's dropped to.

When a Leveret uses Wild Ginseng it is showing that it does 0 damage in the damage log. (Pictured below)

**Steps to Reproduce**
Check Leveret TP move usage

**Expected behavior**
Capture Discord vids: https://www.youtube.com/watch?v=3wvGCRA_Jzs / https://www.youtube.com/watch?v=oygCVJ9vGVg / https://www.youtube.com/watch?v=l-1lmg0O5KE
Bearclaw Rabbit should spawn in the arena by itself with the Leverets not spawned in.
Between the three capture vids I saw only 1 Leveret using Blood Weapon, so maybe it's just a slim chance for 1 (or any) of them to be able to use them, or there is 1 that is set to be able to use it each fight but that 1 is able to be killed when another Leveret dies. I'm really unsure on this one.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/201830504-2920e31d-657b-4345-a50a-afee3e204c49.png)
![image](https://user-images.githubusercontent.com/112344508/201821315-697d58ef-2b58-499a-b93f-564eab3fde76.png)

**Setup Information**
Version 30221103_1

**Comment by dallano** [comment]
@hookstar eversince the new framework, mobs that spawn in at a later time during the BCNM, they're instead all spawned in.

**Comment by hookstar** [comment]
Hit you up on discord - lets work this out one way or another. Would likely need to get @jmcmorris involved for some input as well as he is the expert.
