### ISSUE TITLE
🐛[BUG] - Kirin

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#404]
**What does this bug affect?**
Kirin spawns the first add right after trading the 4 seals and spawning Kirin.

When Kirin dies he says his death message multiple times in chat, with the number of times he says it depending on the size of the alliance that killed him. We tested this with different alliance sizes, and each time the number of messages equaled the # of people in the alliance. (Pictured below)

**Expected behavior**
There should be a delay between Kirin spawning and him spawning the first add.

Upon death Kirin should play his death message only once.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/202073304-baa44060-d589-4d5f-92c8-983d236a99b1.png)

**Setup Information**
Version 30221103_1

**Comment by dallano** [comment]
This was fixed!
