### ISSUE TITLE
🐛[BUG] - Sky Gods Additional Effect Dispel Throwable

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#405]
**What does this bug affect?**
Sky gods additional effects are not being dispelled by the throwables. 
( [Antarctic Wind](https://ffxiclopedia.fandom.com/wiki/Antarctic_Wind) / [Zephyr](https://ffxiclopedia.fandom.com/wiki/Zephyr) / [Arctic Wind](https://ffxiclopedia.fandom.com/wiki/Arctic_Wind) / [East Wind](https://ffxiclopedia.fandom.com/wiki/East_Wind) )

**Expected behavior**
The throwable items you get from killing gods should be able to dispel the additional effect (the sky god's elemental additional effects) when used on the correct god.

**Setup Information**
Version 30221103_1

**Comment by Birdy-gif** [comment]
Looks like this is still broke

**Comment by CriticalXI** [comment]
I have heard that this is working correctly on live. Feel free to re-open if that is not the case.
