### ISSUE TITLE
War job ability graning shadow or possible text error

### ISSUE THREAD

**Issue by consumelivebees** [HorizonFFXI/HorizonXI-Issues#407]
Bug

Chat log or granting the shadow/blink buff

**Steps to Reproduce**
Warrior popped warcry , defender, sentinel, rampart and the mob we were fighting absorbed a shadow from him when he was a pld/war

**Expected behavior**
no shadows should have appeared 
![shadow idk](https://user-images.githubusercontent.com/118316331/202122680-bc232b9c-5f93-4874-ad4d-c486b37a90ff.png)

**Screenshots**

**Setup Information**
current beta, windows 10

**Additional context**

**Comment by consumelivebees** [comment]
Consumelivebees and Wolf were the characters, the text showed up in both of our logs.

**Comment by panicstevenson** [comment]
Fixed now
