### ISSUE TITLE
🐛[BUG] Fafnir absolute terror hitting multiple people

### ISSUE THREAD

**Issue by consumelivebees** [HorizonFFXI/HorizonXI-Issues#408]
Bug
**What does this bug affect?**
Fighting faf at least 1 other person is targeted by the single target move. Might be more but we only had 2 people

**Steps to Reproduce**
Fight faf in a party of 2 or more and get terrored when it uses absolute terror

**Expected behavior**
Only the person at the top of the hate list should get terrored
![terror](https://user-images.githubusercontent.com/118316331/202134910-2ae591d4-a96d-48c1-a00c-b2a71f3dc491.png)

**Screenshots**

**Setup Information**
current beta, windows 10

**Additional context**

**Comment by consumelivebees** [comment]
Those involved - consumelivebees and wolf

**Comment by CriticalXI** [comment]
Fixed in AirSkyBoat/AirSkyBoat#649
