### ISSUE TITLE
🐛[BUG][System]Toadal Recall Wyvern bug

### ISSUE THREAD

**Issue by Zyeriis** [HorizonFFXI/HorizonXI-Issues#41]
**What does this bug affect?**
If a wyvern has hate and the special version of "shroom" attacks that the funguar have in this BCNM try to target it, the move fails. Followed by the funguar attempting it again, ad infinitum.

**Steps to Reproduce**
Let wyvern take hate, wait for a shroom attack on it.

**Expected behavior**
Shroom attack should finish and hit wyvern.

**Comment by dallano** [comment]
@OpheliaXI #fuckpetjobs what's going on with this?

**Comment by CriticalXI** [comment]
Closing this out as its not an issue with the BCNM itself, but a universal problem. Will be addressing this in #85
