### ISSUE TITLE
🐛[BUG][Combat] Additional effects need adjustments

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#411]
**What does this bug affect?**

Weapons and Ammo with additional effects such as enfeeblements (sleep bolt, poison bolt) or damage effects (holy bolt, ice arrow) have incorrect formulas for both proc rates as well as damage and strength of enfeeblement. 

**Steps to Reproduce**

Use holy bolts and sleep bolts on various enemies of different levels and observe that stat correlation isn't correct as well as enfeebles.

**Expected behavior**

I'll try to update this post after some extensive retail testing.

**Additional context**

11/16/2022 test server

**Comment by jonbonazza** [comment]
I haver more info to add here.

First, we only have access to ASB core code, but I did some digging into it and found that there are several issues with the additional effect logic in ASB core. I would include them here but after discussing it a bit with Shozokui in the ASB discord, it seems that the Horizon team has expanded on the additional effect/magic system substantially in their fork of the repo. 

I've seen a lot of people chime in with links to bolt additional effect logic in the open source code of other private servers such as Eden, and it should be noted that the ASB core additional effect code has been recently overhauled and works completely differently than the code that is being linked to. It's not so simple to slot in the old code into the new code.

Shozokui did some quick fixes of a few low hanging fruit in the ASB core and was able to get some better-but-not-perfect results, but ultimately, until the changes that Horizon has made are backported to ASB core. this can't really be fixed on the ASB side.

@The-Aerec @CriticalXI and other devs, are there any plans for this backport to take place? This would allow the community to assist in debugging this issue. I know I would like to actively look into it given that it effects me greatly as a player.

If there's anything at all I can do to help with this issue, please let me know.

**Comment by jonbonazza** [comment]
Also, to add even more info to this, lots of data has been collected in this issue from 2022 for the Eden server who experienced something similar.

https://github.com/EdenServer/community/issues/1191
