### ISSUE TITLE
🐛[BUG][Quest] Flyers for Regine

### ISSUE THREAD

**Issue by Nukuchan** [HorizonFFXI/HorizonXI-Issues#413]
**What does this bug affect?**
Immersion as well as chat spam. 

**Steps to Reproduce**
while handing out the flyers after trading to Guilberdrier you get the prompt "Villion looks over curiously for a moment." but it keeps prompting it repeatedly until you trade her one of the flyers. 

**Expected behavior**
should only say it once

**Screenshots**
![Nuku_2022 11 16_214145](https://user-images.githubusercontent.com/116027994/202357576-59640613-d7a2-4128-9bdf-ac4ea00bde10.png)

**Setup Information**
30221103_1

**Additional context**
The other NPC's that you're supposed to trade only do the prompt once when you get within 10 distance of them. Standing still near any of the others doesnt illicit the same spam in the chat as with Villion. With her you can be standing still and it will continually spam the message. I had thought it might have to do with the Z axis as Villion is almost directly overhead when standing near Guilberdrier however Leuveret in southern sandoria can also be stood under and he doesnt do the same spam. upon further checking Villion will spam it even if you're up on the same level with her and standing next to her. I checked all the others and Villion is the only one doing this.

**Comment by dallano** [comment]
This was fixed here: https://github.com/AirSkyBoat/AirSkyBoat/pull/295
