### ISSUE TITLE
🐛[BUG][Dynamis - Xarc issues]

### ISSUE THREAD

**Issue by StyrkaGG** [HorizonFFXI/HorizonXI-Issues#418]
**What does this bug affect?** (using dynamis bums for mob numbers)

- TE 382 does not spawn nor does the eyes spawn when you pull the eyes at the tower
- TE 233 also does not spawn after killing the eyes for it 
- TE 454 does not spawn after killing eye wall
- nothing dropped pages/stratagems
- Vanguard dragons do not drop necro or startagems 
- when you toss the hourglass it does not give any msgs about kicking you out just kicks you out after 45 seconds

**Steps to Reproduce**
just following the normal pull path for dyna will recreate these nothing special need to be done 

**Expected behavior**
after killing the eyes a TE should spawn for the first bullets 

for the other bullets eyes and dragons should drop pages/stratagems
**Screenshots**
no screenshots for these issues 

**Setup Information**
this was on the test server not beta 

**Additional context**
i did three runs of dyna xarc so far and the avg currency per run was 1342 

and the avg relic per run was 26 relics per run as well i will do more testing later

**Comment by KiplingFFXI** [comment]
This bug is still happening.
