### ISSUE TITLE
🐛[BUG] CS Apollyon Beastcoins

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#419]
**What does this bug affect?**

Beastmen aren't dropping any coins. Wiki says they should be dropping 3-6 each.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by panicstevenson** [comment]
Hopefully fixed now on next merge from ASB?
