### ISSUE TITLE
🐛[BUG]Diabolos Nightmare BP

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#42]
**What does this bug affect?**

BP says it does 0 damage. Nothing happens at all.
**Steps to Reproduce**

Summon Diabolos and use the nightmare BP on any mob. Nightmare has no effect.
**Expected behavior**

Sleep with a DOT.
**Screenshots**

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment]
Duplicate of #34
