### ISSUE TITLE
🐛[BUG] Limbus HP MP chests have limited range?

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#420]
**What does this bug affect?**

My group opened the chests in NW apollyon and the didn't restore HP MP to everyone on the same floor. It looked like it would only hit the players close to it.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment]
Need more information on what the correct behavior here is. Should it have no distance requirements?
