### ISSUE TITLE
[BUG][System/Combat] Doom Guard Staying in Casting Range

### ISSUE THREAD

**Issue by maldra** [HorizonFFXI/HorizonXI-Issues#424]
The Doom Guards in Gustav Tunnel are staying in casting range.  They should be approaching the player.

**Comment by maldra** [comment]
I checked some other DRK mobs such as Kindred Dark Knight and they seem to be okay though.  Doom Guards are the only ones I'm seeing affected by this issue.

**Comment by CriticalXI** [comment]
This is likely because they are set to be BLM mobs instead of DRK.

**Comment by maldra** [comment]
This may have even been addressed before the server launched.  I'll look to make sure its still a bug.

**Comment by maldra** [comment]
Just confirmed this bug had already been fixed.  This issue likely didn't get closed because I had mentioned it in discord at the time as well.  Closing it out now.
