### ISSUE TITLE
🐛[BUG][Quest] The Rescue

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#426]
**What does this bug affect?**

The quest in Selbina, "The Rescue"

**Steps to Reproduce**

Attempt to complete the quest and hit a wall when you try to turn it in at the last step.

**Expected behavior**

Returning to Thunder Hawk at the end of the quest should complete the quest and give you the reward of gil+map.
**Screenshots**

![image](https://user-images.githubusercontent.com/2160211/203103827-c2fc2c67-963a-47b0-a46b-d5911297a1c1.png)

**Setup Information**

11/21/2022 test server

**Additional context**

If captures are required please ping me on discord and I'll go get it.

**Comment by montijin** [comment]
In the quest lua at the end it should probably be quest:progressEvent instead of mission:progressEvent
            ['Thunder_Hawk'] =
            {
                onTrigger = function(player, npc)
                    if player:hasKeyItem(xi.ki.TRADERS_SACK) then
                        return mission:progressEvent(81)
                    else
                        return mission:event(83)
                    end
                end,

**Comment by hookstar** [comment]
This one can be closes as its been fixed. (https://github.com/AirSkyBoat/AirSkyBoat/issues/1610)
