### ISSUE TITLE
🐛[BUG][Quest] Rycharde The Chef 

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#427]
**What does this bug affect?**

The quest Rycharde The Chef
**Steps to Reproduce**

Start the quest and notice the text in the quest is missing his request for Dhalmel meat it instead read, "Bring me . ". He also  won't let you progress by trading the expected 2 Dhalmel meat.

**Expected behavior**

You should be able to progress and finish the quest. The other quests in this line should ideally be validated as well when this is fixed.

**Screenshots**

![image](https://user-images.githubusercontent.com/2160211/203117879-47c52067-2cba-42e3-abf2-a07e73eb9d05.png)

**Setup Information**

11/21/2022 test server

**Additional context**

https://ffxiclopedia.fandom.com/wiki/Rycharde_the_Chef

**Comment by montijin** [comment]
[xi.zone.MHAURA] =
        {
            ['Rycharde'] =
            {
                onTrigger = function(player, npc)
                    return quest:event(72) -- Interaction dialog.
                end,

                onTrade = function(player, npc, trade)
                    if npcUtil.tradeHasExactly(trade, { { xi.items.DHALMEL_MEAT, 2 } }) then
                        return quest:progressEvent(74) -- Quest completed dialog.
                    elseif npcUtil.tradeHasExactly(trade, { { xi.items.DHALMEL_MEAT, 1 } }) then
                        return quest:event(73) -- "That's not enough!" dialog.
                    end
                end,
            },
            
            My guess is that xi.items.DHALMEL_MEAT needs to be the item ID or slice_of_dhlamel_meat

**Comment by hookstar** [comment]
got
