### ISSUE TITLE
🐛[BUG][Quest] The Quadav's Curse

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#428]
**What does this bug affect?**

The quest "The Quadav's Curse"

**Steps to Reproduce**

Start the quest and try to progress by trading the backplate. He will not respond to trading the correct item.

**Expected behavior**

You should be able to finish the quest

**Screenshots**

![image](https://user-images.githubusercontent.com/2160211/203124034-a76d893f-5836-4285-b809-d2a565dc6da2.png)

**Setup Information**

11/21/2022 test server

**Additional context**

https://ffxiclopedia.fandom.com/wiki/The_Quadav's_Curse

**Comment by montijin** [comment]
Similar to #426 the lua for the quest is incorrectly using mission progress event call instead of quest.

[xi.zone.PORT_BASTOK] =
        {
            ['Corann'] =
            {
                onTrade = function(player, npc, trade)
                    if npcUtil.tradeHasExactly(trade, xi.items.QUADAV_BACKPLATE) then
                        return mission:progressEvent(81)
                    end
                end,
            },

**Comment by hookstar** [comment]
Will grab this one too.
