### ISSUE TITLE
🐛[BUG]Incorrect material loss rates & skillup rates on all breaksynths

### ISSUE THREAD

**Issue by Cyr-test** [HorizonFFXI/HorizonXI-Issues#429]
Incorrect material loss rates & skillup rates on all breaksynths.

Test completed: 76 attempted Death Sycthe synths (and happy to do more, but the real point is that the HXI code is OOE).  https://ffxiclopedia.fandom.com/wiki/Death_Scythe
My levels: 91 Smithing, 44 Woodworking, 44 Alchemy
Synth level caps: 93 Smithing, 20 Woodworking, 59 Alchemy.  Therefore I was 2-gap on Smithing, overleveled on WW, and 15-gap on Alchemy.

-------------------------------------

Expected era-accurate results: 
The expected Era results are pulled from multiple BG threads circa 2006/2007 after searching for the subject “breaksynthing.”  There are multiple threads by multiple users who have successfully used breaksynthing to skillup crafts, including Aurik (who I think is the basis for our crafting implementation). 
* Skillup Rates: ~36 synths (or 28% skillup rate) to skillup one full level at Veteran-tier (90+) using only breaksynthing according to Wizerd’s testing on BG.  However, there are a variety of datapoints both higher & lower.  Aurik said it was 40 synths (25% skillup rate).  
  * The testers specifically concluded that breaks have no reduced skillup rate, and these rates were the same as successful synths.
* Material Loss Rates: 50% realized materials loss rate on only failed synths.  This is with 15 gap on Alchemy sub & 2-3gap on Smithing main, for a total skill gap of 17-18 levels.  I conclude the HXI implementation should also show a 50% capped break rate.  This is from data in post 1 of this thread: https://www.bluegartr.com/threads/38803-Skilling-up-with-insufficient-subs?highlight=break+synth .  I replicated this test using the same synth and levels.  
  
--------------------------------------  

Actual results on HXI:
* 76 synths total at 17-gap.
* 3 successes, yielding a 3.95% success rate.  This seems right, as we’d expect 5%.
  * On the 3 successes: 0 skillups.  Cant draw any conclusions here, as the sample of successes was too low. 
* 73 breaks, yielding a 96.05% fail rate.
  * On those 73 breaks, I received three 0.1 skillups.  This is a 4.11% skillup rate on the breaks, whereas the expected era-accurate result would be between 18.25 to 20.5 skillups on this sample. The conclusion here is that the current build is overly punitive compared to what era was.  
  * On those 73 breaks only, I lost 145 darksteel ingots.  3 darksteel ingots are used per synth.  Therefore this is a realized materials loss rate of 66.2% on a sample of 219 rolls, vs. an expected era-accurate 50% loss rate on this test synth.   

------------------------------- 

Sources:
* https://www.bluegartr.com/threads/38803-Skilling-up-with-insufficient-subs?highlight=break+synth
  * Post # 1 is the basis for this synth test
  * Post # 2 by Aurik, line 3 for 25% skillup rate at Veteran on breaksynthing
  * Post # 6 by Gatsby separately tested & concluded 25% skillup rate on breaks.
  * Post # 9 by Wizerd is a very large sample with a conclusion of 28% skillup rate on breaks above 60.  And specially concludes: “break skilling has the same skill up rate as normal skilling, both of which are somewhere between 35-40 synths per level, averaging closer to 36, regardless of level over lv60.”
* https://www.bluegartr.com/threads/41282-Question-on-breaksynthing?p=1409364&viewfull=1#post1409364
  * Post # 12, large sample of Veteran-level breaksynths showing validity & indicates he used 1/3 to ¼ the number of materials to achieve the same skillups as success-synthing.  
* https://www.bluegartr.com/threads/57123-Before-you-ask-a-stupid-crafting-question-read-this!?p=1987222&viewfull=1#post1987222
  * Post # 1: “Item loss rate on break is approximately 50%”.  This is validated in the first source test I posted above. 
  * Also post # 1: “5 or less from cap: somewhere between 25% and 33% chance to skill-up on any synth, broken or not”.  This validates the lack of break penalty observed by other users in the source posts above.  

[Aaa_2022.11.21.log](https://github.com/HorizonFFXI/HorizonXI-Issues/files/10061498/Aaa_2022.11.21.log)
Log is attached.

**Comment by Frankie-hz** [comment]
All your links are broken and lead to different bug reports unrelated to crafting

**Comment by Cyr-test** [comment]
> All your links are broken and lead to different bug reports unrelated to crafting

Fixed, this was copy/pasted and github didnt like my formatting
