### ISSUE TITLE
🐛[BUG][NPC/Combat] - Maat WAR Fight

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#43]
**What does this bug affect?**
Maat's HP is 2300 (checked with !getstats), wiki reports it should be about 3300 for this fight.

**Steps to Reproduce**
Go in and do the fight the same way as explained in the Additional Context section.

**Expected behavior**
Per the testimonies on the wiki generally 2 Raging Rushes are used before the fight ends.

**Screenshots**
https://drive.google.com/file/d/1-ghMlRl52xEc6q-8LxqYYtnewp-ZvsHa/view
https://drive.google.com/file/d/1BTVANTqPnDsmRDgiAMGhJZCEEPasPTYp/view
https://drive.google.com/file/d/1Ch_aGed2nSJniX1o-JxGDOP8h8FwHe6R/view
https://drive.google.com/file/d/1K4ruVK8-XtCG-YgLRypaZfWU-dZcy_IT/view

**Setup Information**
Version 30220802_3

**Additional context**
Matt's HP seems to be lower than intended. I went in with the gear from the screenshots and slept to 2000 TP, used Berserk , Aggressor, Warcry, and Mighty Strikes and engaged. I hit him with 2 autos, the first for 247 dmg and the 2nd for 264 dmg, then used Raging Rush for 1435 dmg and the fight was over. Wiki testimonies state generally 2 Raging Rushes are used before the fight is over.

**Comment by dallano** [comment]
I don't think a raging rush doing 1435 isn't quite normal. I'll try and look into maat's health, but I suspect our dmg formulas to be off lol

**Comment by dallano** [comment]
so in the linked capture, the first hit deals 134 (5%) and 134 / 2500 = 5.2% I believe HP is accurate at 2500
