### ISSUE TITLE
🐛[BUG][NPC] Southern San d'Oria vendor Ashene is not functioning 

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#430]
**What does this bug affect?**

The vendor Ashene and the availability of their items.

**Steps to Reproduce**

!gotoid 17719354 
Try to interact with the NPC

**Expected behavior**

Ashene should be a vendor that sells various weapons.
https://ffxiclopedia.fandom.com/wiki/Ashene?oldid=39748

**Setup Information**

11/22/2022 test server

**Additional context**

I'm not sure if this is just a case where I need dat mods that aren't provided to us yet.

**Comment by Frankie-hz** [comment]
https://github.com/AirSkyBoat/AirSkyBoat/pull/687
