### ISSUE TITLE
🐛[BUG][NPC/Quest] The Old Monument (BRD unlock) resets progress

### ISSUE THREAD

**Issue by ZawaXI** [HorizonFFXI/HorizonXI-Issues#432]
**What does this bug affect?**
This bug effects the quest required to unlock BRD. Progress is reset if NPCs are talked to again. A BRD will go all the way out to buburimu only to not receive a cutscene and have to travel back to Jeuno to repeat talking to NPCs.

**Steps to Reproduce**
Talk to Bki Tbujhja after she tells you about the song runes then talk to Mertaire again.

**Expected behavior**
Quests should never reset progress.

**Comment by hookstar** [comment]
Ill take this one.
