### ISSUE TITLE
🐛[BUG][System] OOE Items in AH

### ISSUE THREAD

**Issue by ChaChang-Byte** [HorizonFFXI/HorizonXI-Issues#433]
**What does this bug affect?**

Does not affect gameplay. Absorb-Acc, Absorb-TP, Dread Spikes from black magic and crepe caprice, cream puff, pear crepe, crepe B. Helene, kitron macaron, and coconut rusk from sweets  are in the AH.
**Steps to Reproduce**

Food -> Meals -> Sweets
Scrolls -> Black Magic
**Expected behavior**

Should not be in AH
**Screenshots**

**Setup Information**

Windows, Ashita v3, test server
**Additional context**

**Comment by CriticalXI** [comment]
Fixed in that items no longer appear on the AH unless its been listed by a player.
