### ISSUE TITLE
🐛[BUG][Combat] Spook spawns too early in the day

### ISSUE THREAD

**Issue by TracentEden** [HorizonFFXI/HorizonXI-Issues#434]
**What does this bug affect?**
Spook first spawns at 17:00 (with all the other undead in KRT on internal horizon test server)

**Steps to Reproduce**

**Expected behavior**
Spook should first spawn at 20:00 (see [era wiki](https://ffxiclopedia.fandom.com/wiki/Spook?oldid=57008))

**Screenshots**

**Setup Information**

**Additional context**

**Comment by StyrkaGG** [comment]
spook and all undead still spawning at 17:00
