### ISSUE TITLE
🐛[BUG][BCNM OOE Items - Running List]

### ISSUE THREAD

**Issue by hookstar** [HorizonFFXI/HorizonXI-Issues#435]
**What does this bug affect?**

OOE Items in drop tables for BCNM/ENM/KSNM
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

If you find OOE item lists, please list the name of the fight and which items are OOE. Please note, all grips are already a known thing and will already be pulled out.

Thanks!

**Comment by hookstar** [comment]
------------KS Double Dragonian------------------
Darksteel Ore 
Marborol Fiber 
Source: https://ffxiclopedia.fandom.com/wiki/Double_Dragonian?oldid=42397 (One just before ToAU release) Jan 2006
------------------------------------------------------

**Comment by Eekfish** [comment]
Dropping Like Flies (BCNM 30, Horlais Peak)

Drops Emperor Hairpin (was changed sometime between August 2005 and December 2005) if that matters

https://ffxiclopedia.fandom.com/wiki/Dropping_Like_Flies?oldid=41836 I also think back then it probably didn't drop Quadav Bug Broth, however it DID drop 4000 gil (split evenly between 5 members)

https://www.youtube.com/watch?v=6BawdgJEPLU&t=0s <- this old video shows a guy getting 800 gil 

So OOE item might be Quadav Bug Broth, as I just got one here:
![image](https://user-images.githubusercontent.com/118832692/204411671-0c58f932-2cd5-4ee6-84e2-0445e4bd0389.png)

**Comment by Eekfish** [comment]
Birds of a Feather (BCNM 30, Waughroon Shrine)

It is missing its 3000 gil reward (reminder these are split between party members) which i think would be in era)

Source for 3000 gil: https://youtu.be/KmY85Rb9h2U?t=448 (vid from 2009)

![image](https://user-images.githubusercontent.com/118832692/204412668-e130f3e3-6357-4d4b-bedb-db46d27fd379.png)

Seems like no FFXIclopedia page includes this for some reason

Idk if anything else is out of era.

**Comment by Eekfish** [comment]
Creeping Doom: Missing 3000 gil reward

I am also starting to think most bcnm 30 rewarded 3000 ~ 4000 gil split amongst the party members; is this known?

https://youtu.be/Wu-3tYiuG2g?t=199

**Comment by Eekfish** [comment]
Harem Scarem (BCNM 30, Balga's Dais)

Couldn't seem to find any videos whatsoever. I am fixated on there being a gil reward for every bcnm, but with no proof for this one, I suppose I will have to manually check each one. 

This BCNM gave me 8 drops, how legit that is I have no idea: 
![image](https://user-images.githubusercontent.com/118832692/204418655-81a46ea5-871d-46b4-ba20-ce01b8b21da1.png)

**Comment by Eekfish** [comment]
Petrifying Pair (BCNM 30 Ghelsba Outpost)

Missing 3000 Gil reward

Video: https://www.youtube.com/watch?v=0c58a9kBUo0 (literally last second of the video ; ;) (August 2007)

Image: 
![image](https://user-images.githubusercontent.com/118832692/204419933-06676574-cbe7-4441-b3f1-3d05b8c9b511.png)

**Comment by Eekfish** [comment]
Toadal Recall (BCNM 30 Ghelsba Outpost)

Missing 4000 gil reward

Also missing Darksteel Ore and Tourmaline drops 

Video: https://www.youtube.com/watch?v=lOK2a4Pg5uc (7:20) (December 2006 date)

FFXIclopedia doesn't corroborate, meaning the wiki is more likely wrong/doesn't have all the information

**Comment by Eekfish** [comment]
It could be the 6 man BCNMs dropped 4000 gil and the 3 man bcnms dropped 3000 gil. Grove Guardians was also missing gil from its drop table.

**Comment by Eekfish** [comment]
Die by the Sword BCNM 30 Qu'Bia Arena

Missing: 3000 gil drop, double rusty pick can be obtained too

Videos: https://www.youtube.com/watch?v=LVHZy3kDHRk 4:08 shows drops (has 3k gil reward, rusty pick in 2 drop slots)
https://www.youtube.com/watch?v=yGsVBmfIsvE another 3000 gil vid among other stuff

**Comment by Eekfish** [comment]
Harem Scarem missing drop "Scroll of Regen" 

https://ffxiclopedia.fandom.com/wiki/Regen?oldid=54389 from this page

compared to https://ffxiclopedia.fandom.com/wiki/Harem_Scarem?oldid=40691

and https://ffxiclopedia.fandom.com/wiki/Harem_Scarem

**Comment by Eekfish** [comment]
Let Sleeping Dogs Die (BCNM 30 Qu'Bia Arena)

https://ffxiclopedia.fandom.com/wiki/Let_Sleeping_Dogs_Die

Missing drops: Mythril Ingot, Petrified Log. 4000 gil 

Source: https://www.youtube.com/watch?v=Xv-OxyLAf9s (2006 video, this channel is gold for this type of thing)

**Comment by Eekfish** [comment]
Time to sleep and i will try BCNM 40s in the morning, plus try to search for videos and other things (it's 3 am here now ; ;)

If anyone can figure out if BCNM 20s dropped gil (youtube vid or otherwise) feel free to leave more information here

**Comment by Eekfish** [comment]
....before i go to bed

BCNM 20 - all apparently drop 1500 gil

Source: https://www.youtube.com/watch?v=UunUomxDK4Y (Crustacean Conundrum around July 2007)
![image](https://user-images.githubusercontent.com/118832692/204431378-affb02cd-fd17-48fc-95e4-287a279e27d6.png)

https://www.youtube.com/watch?v=R1FUq-dHBM4 (Wings of Fury Nov. 2006)
![image](https://user-images.githubusercontent.com/118832692/204430999-92b135c8-8739-4ee5-b6ee-58daedf0b076.png)

https://www.youtube.com/watch?v=A-RgoEDu4UM Charming Trio (August 2006)
![image](https://user-images.githubusercontent.com/118832692/204431310-5c3c9dce-ae79-4c5a-9296-b6cbcda8e631.png)

https://www.youtube.com/watch?v=GOm7Vl_XkGk (August 2006)
![image](https://user-images.githubusercontent.com/118832692/204431638-2a303585-9086-46a8-9106-45fc3e2ec066.png)





okay now sleep time

**Comment by Eekfish** [comment]
Undying Promise (BCNM 40 3 man) Qu'Bia Arena

Drops 5000 Gil

https://www.youtube.com/watch?v=U1TUWnhf7yI 5:35 2009 Vid
https://cdn.discordapp.com/attachments/1041022846421438615/1047205200852680744/image.png

Didn't have gil reward

**Comment by Eekfish** [comment]
Factory Rejects (BCNM 40 6 man) Qu'Bia Arena

No old video :(

https://www.bg-wiki.com/ffxi/Factory_Rejects

Didn't have gil reward (will find this out from the other 6 man bcnms)

**Comment by Eekfish** [comment]
Under Observation (BCNM 40 3 man) Horlais Peak

Drops 5000 gil

https://www.youtube.com/watch?v=9jdsKAlpWnc 6:50 2010 vid
https://www.youtube.com/watch?v=t0UPxkrXiWc 4:36 2008 vid
https://www.youtube.com/watch?v=j7KLYetbM0k 5:43 2007 vid
<img src="https://cdn.discordapp.com/attachments/1041022846421438615/1047217213880418365/uo.png"/>
Horizon didn't have gil reward

**Comment by Eekfish** [comment]
Tails of Woe (BCNM 40 6 man) Horlais Peak

No old video

https://ffxiclopedia.fandom.com/wiki/Tails_of_Woe
https://www.bg-wiki.com/ffxi/Tails_of_Woe

Horizon didn't have gil reward (will find this out at some point)

**Comment by Eekfish** [comment]
Steamed Sprouts (BCNM 40 6 man) Balga's Dais

No old video :(

https://ffxiclopedia.fandom.com/wiki/Steamed_Sprouts
https://www.bg-wiki.com/ffxi/Steamed_Sprouts

No gil reward on Horizon (will find this out soon PLEASE someone has to have recorded a 6 man BCNM 40)

**Comment by Eekfish** [comment]
Royal Succession (BCNM 40 3 man) Balga's Dais

BCNM works fine mechanically

No videos online sadly :(

https://ffxiclopedia.fandom.com/wiki/Royal_Succession
https://www.bg-wiki.com/ffxi/Royal_Succession

Missing 5000 gil drop on Horizon

**Comment by Eekfish** [comment]
Royal Jelly (BCNM 40 3 man) Waughroon Shrine

Drops 5000 gil

https://www.youtube.com/watch?v=R_gVC7uDLso 5:22 drops (2007 vid)

Doesn't drop 5000 gil on Horizon

**Comment by Eekfish** [comment]
The Worm's Turn (BCNM 40 6 man) Waughroon Shrine

Drops 6000 gil

Video: https://youtu.be/kUODPt0WyV4?t=384 (shows drops at timestamp 6:24)
<img src="https://cdn.discordapp.com/attachments/1041022846421438615/1047262177255489546/image.png"/>https://cdn.discordapp.com/attachments/1041022846421438615/1047262177255489546/image.png

Missing 6000 gil drop on Hoirzon

This means 6 man BCNM 40s dropped 6000 gil; retroactively updating previous bcnm gil values (thank god someone did one of these)

**Comment by Eekfish** [comment]
3, 2, 1... (BCNM 50 6 man) Waughroon Shrine

No video

Missing 12000 gil reward on Horizon

**Comment by Eekfish** [comment]
The Final Bout (BCNM 50 3 man) 3 minute timer Waughroon Shrine

https://www.youtube.com/watch?v=aWN_9qp7zLY (death)

Missing gil reward on Horizon (will figure this out soon)

**Comment by Eekfish** [comment]
Hostile Herbivores (BCNM 50 6 man) Horlais Peak

https://www.youtube.com/watch?v=AXR1_6CJ-wo (4:56) (2009) (12000 gil reward)

Missing gil reward on Horizon

**Comment by Eekfish** [comment]
Up in Arms (BCNM 60 3 man) Waughroon Shrine

https://cdn.discordapp.com/attachments/1041022846421438615/1047273419047186532/image.png
https://www.youtube.com/watch?v=4HsLLpa5PaM (2007) (11:20 drops)

Drops 15000 gil  (unsure if missing on Horizon)

**Comment by Eekfish** [comment]
BCNM 50 6 man = 12000 gil

BCNM 60 3 man = 15000 gil

**Comment by Eekfish** [comment]
There are no videos of any BCNM 50 3 mans so i have no idea. If anyone has a video or can do the BCNM let me know

**Comment by Eekfish** [comment]
Eye of the Tiger (BCNM 50 3 man) Horlais Peak

No old videos found

Not sure about the amount of gil it drops still
(need someone to go in with a group and kill it on retail)

Missing gil drop on Horizon (whatever it may be)

**Comment by TheSupaBuck** [comment]
BCNM 60 Celery---- 3 man
Does not drop gil in crate. Should drop 15,000
BCNM 60  Shots in the Dark 3 man
Does not drop gil in crate. Should drop 15,000
