### ISSUE TITLE
🐛[BUG][Navmesh] Trial Size fights navmesh issues

### ISSUE THREAD

**Issue by alessa89** [HorizonFFXI/HorizonXI-Issues#437]
**What does this bug affect?**
there are some points in the zone where carbuncle will get stuck below the map and wont move/engage the avatar, or another spot where he will engage, but they will stand there looking at each other not (carby and avatar) and wont move or attack

**Steps to Reproduce**
summon carbuncle with your back up against the edge of the zone as in screenshot vs titan. the issue with them both standing there and not attacking seems to be around the bends in the path leading to the avatar as in the screenshot vs ifrit

**Screenshots**
![image](https://user-images.githubusercontent.com/115948656/204105104-213c51ec-a557-43d6-aa1c-37f37025c225.png)

![image](https://user-images.githubusercontent.com/115948656/204105086-49f4ac94-a186-4551-906d-e2bd22623b94.png)

**Additional context**
fix it rhowen

**Comment by BayaniTenzen** [comment]
added to the Shortlist for Launch

**Comment by BayaniTenzen** [comment]
All six Cloister Nav-Mesh have been updated for ASB/Horizon
