### ISSUE TITLE
🐛[BUG][System]

### ISSUE THREAD

**Issue by Zyeriis** [HorizonFFXI/HorizonXI-Issues#438]
**What does this bug affect?**
Apollyon.

**Steps to Reproduce**
Logged out while still inside Apollyon zone run. Logged back in days later, still in zone, not being kicked, no enemies or teleporters. Essentially trapped (if I didn't have gm commands anyway).

**Expected behavior**
Should be kicked out of the zone.

**Comment by panicstevenson** [comment]
Fixed on next merge from ASB
