### ISSUE TITLE
🐛[BUG][SMN summoning Fenriros, Titanlos, etc when casting sequentially after Diabolos]

### ISSUE THREAD

**Issue by Cyr-test** [HorizonFFXI/HorizonXI-Issues#439]
**What does this bug affect?**
SMN summoning Fenriros, Titanlos, etc when summoning those respective avatars sequentially after releasing Diabolos.  

**Steps to Reproduce**
Summon Diabolos, release, then summon Titan/Fenrir (probably shiva too?)

**Screenshots**
![image](https://user-images.githubusercontent.com/29617433/204115326-bd9f747b-891b-4e97-bc7e-e3be27b49c3a.png)

**Comment by panicstevenson** [comment]
Fixed now
