### ISSUE TITLE
🐛[BUG] BCNM The Worms Turn Issues.

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#44]
**What does this bug affect?**

Draw in only happens 1 time and after that doesn't seem to work. Magic damage is borked so the charm strategy listed on the wiki doesn't work cuz. Worms only do 0-9 damage on aga casts.
**Steps to Reproduce**

Cast a spell at the boss from a distance. Draw in will happen once then after that when you run nothing will happen. 
**Expected behavior**

Draw in I believe should happen always if you exit casting range.
**Screenshots**

**Setup Information**

**Additional context**

**Comment by dallano** [comment]
Works as intended
