### ISSUE TITLE
🐛[BUG] SE Apollyon Immunities and final chest bugged

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#441]
**What does this bug affect?**

Inhumers and the grave digger aren't immune to dark based sleep. Crabs and Slimes aren't immune to light based sleep. Final chest would not open at all.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by TracentEden** [comment]
The inhumers have dark sleep resist and the chest works. Just need to add immunity to the Grave Digger.
