### ISSUE TITLE
🐛[BUG]Temenos West - carbuncle pull not working

### ISSUE THREAD

**Issue by Cyr-test** [HorizonFFXI/HorizonXI-Issues#449]
**What does this bug affect?**
Wiki states that carbuncle pull should function on linked mobs.  Specifically, the 7th floor Enhanced Vultures.  However, the linked mobs did not de-agro when carbuncle despawned.  

It is possible that all carbuncle pulling isnt working, not just in Temenos.  

https://ffxiclopedia.fandom.com/wiki/Temenos_-_Western_Tower
 
**Steps to Reproduce**
Summon carbuncle, sic her on the Enhanced Vultures, and watch them not drop agro.  

**Expected behavior**
The linked mobs should drop agro and reset.

**Comment by Squinkerdoodle** [comment]
@jmcmorris

**Comment by Squinkerdoodle** [comment]
This is currently working on the live server, clearing due to old ticket / issue has since been resolved.
