### ISSUE TITLE
🐛[BUG]BCNM Undying promise

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#45]
**What does this bug affect?**

No noticeable size or melee damage increase after each death. HP doesnt decrease to 50% when it reraises to the last blm. Boss shouldn't cast immedietly on respawn.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by dallano** [comment]
Fix has been pushed!
