### ISSUE TITLE
🐛[BUG] Temenos - Eastern Tower

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#450]
**What does this bug affect?**
When entering & exiting the battlefield you get the faint hum message twice. On entry it's "You hear a faint hum.." twice and on exit it's "You can't hear a faint hum." twice.

The Earth Elementals in this tower use Slow II instead of just normal Slow.

After first entering the tower the Battlefield selection menu (the menu where you select which tower / floor to run) pops up again. We exited out of the menu, unsure if you can actually select a different zone.

The Scarlet Chip that you get at the end of the run is the rare only version instead of the in era rare/ex version.

Armory Chests are dropping loot for OOE jobs (on this run we had Filet Lace only, but assuming the other OOE jobs are there).

**Comment by Squinkerdoodle** [comment]
@jmcmorris

**Comment by xperian** [comment]
Tried this zone and got the first elemental down, popped the item chest and got 5 beastcoins but no AF+ items, this should be guaranteed to drop at least 1. Will upload the picture later.
