### ISSUE TITLE
🐛[BUG] Temenos - Western Tower

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#451]
**What does this bug affect?**
When entering & exiting the battlefield you get the faint hum message twice. On entry it's "You hear a faint hum.." twice and on exit it's "You can't hear a faint hum." twice.

The Emerald Chip that you get at the end of the run is the rare version, instead of the in era rare/ex version.

SMN pet pulling may not be working as it should be. On multiple floors we tried to Carby pull but the linked mobs still came to the party. (This may not be a Tenemos only issue, this test session is when we mainly noticed it)

We did not receive any OOE jobs loot on this run, however it may be worth double checking all Temenos zones for era accurate drops.

**Comment by Shuu-37** [comment]
We should split these into separate issues so they can be addressed @Squinkerdoodle

**Comment by Squinkerdoodle** [comment]
@jmcmorris
