### ISSUE TITLE
🐛[BUG][Combat] Dart Animation Incorrect

### ISSUE THREAD

**Issue by Scarifi3dXI** [HorizonFFXI/HorizonXI-Issues#452]
**What does this bug affect?**

Incorrect animation is used for throwing a dart. Singing animation plays.

**Steps to Reproduce**

!additem dart 99 and go kill them softly with your sweet, soulful voice

**Expected behavior**

Animation should be the same as any other thrown ranged weapon, however the singing animation plays instead.

**Screenshots**

**Setup Information**

Confirmed on closed beta server, also present on local ASB server.

**Additional context**

**Comment by The-Aerec** [comment]
This is a lockstyle bug

**Comment by Scarifi3dXI** [comment]
Did some research, indeed--is there anything we can do to address this? Looking at animations, seems to be all action packet based and not so much easily editable. This one one of the issues we had on Nasomi as well so was one that always stuck out in my memory to double-check.

**Comment by TracentEden** [comment]
Should be fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/3488 , can reopen if it is not.
