### ISSUE TITLE
🐛[BUG][Mission] Windy 2-3 Three Kingdoms cant get KI

### ISSUE THREAD

**Issue by alessa89** [HorizonFFXI/HorizonXI-Issues#454]
**What does this bug affect?**
2-3 starts fine, but early on when you go to heavens tower to talk to kupipi you're supposed to get a KI "Letter to the Consuls". Shes not giving the KI or the text she should to indicate you're starting the quest-- however the quest will still proceed if you go to the consul in the nation you choose first and is still completable (done without GM on)

just thinking you guys may be bombarded with requests on live if people dont see it added 

**Steps to Reproduce**
accept mission 2-3 windy, talk to kupipi in heavens tower

**Expected behavior**
should give you KI letter to the consuls

**Comment by panicstevenson** [comment]
She gave me one, maybe she just hates you?

![image](https://user-images.githubusercontent.com/8849608/206597266-92d445be-1fb3-4eb1-8606-358c8e275f1e.png)
