### ISSUE TITLE
🐛[BUG][Mission/Other] Cant trade crystals to conquest overseers for rank points/progress - Windurst

### ISSUE THREAD

**Issue by alessa89** [HorizonFFXI/HorizonXI-Issues#455]
**What does this bug affect?**
unable to trade crystals to any of the "W.W" conquest overseers in windy (or at the consulates in other nations), trade opens, but NPC doesn't take the items so no progress is made. this makes missions that need some rank progress unstartable - this was tested as rank 3, past the point where trading becomes available 

**Steps to Reproduce**
trade crystals to conquest overseer, dont get rank points and progress

**Expected behavior**
trade crystals to conquest overseer, get rank points and progress

**Comment by alessa89** [comment]
verified as happening with a bastok player as well

**Comment by Frankie-hz** [comment]
Can verify its working on an ASB base. Something for horizon must of caused this

**Comment by Squinkerdoodle** [comment]
Yup, verified this is happening on the test server with bastok & windy players, assuming sandy is the same. (Public also verified it's occurring.)

**Comment by Squinkerdoodle** [comment]
Issue now resolved as of 12/4.
