### ISSUE TITLE
🐛[BUG] Temenos Floors Issues ( multiple floors not implemented )

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#457]
**What does this bug affect?**
The following Temenos floors are not implemented (unable to start via chip trade or even when flagged as GM, after entering it gave the Not ready, please try again later message): *Basement / 2nd Floor / 3rd Floor / 4th Floor*

1st Floor - (Other than this issue 1st Floor seems to be working properly) May be related to the issue reported in https://github.com/HorizonFFXI/HorizonXI-Issues/issues/456 . Battlefield status doesn't get cleared if someone d/c's mid run and comes back. Additionally the person that d/c mid run was not kicked out of the zone after opening the final chest, though the rest of the group was properly ejected.

**Setup Information**
30221102_1

**Comment by Squinkerdoodle** [comment]
@jmcmorris

**Comment by jmcmorris** [comment]
I'm actively working on these remaining floors. The 2nd floor is most of the way done and I've started researching the 3rd floor.

**Comment by Squinkerdoodle** [comment]
@jmcmorris sorry to bug you about it, are there any more floors completed / merged so far for group testing tomorrow? Trying to figure out what to do.
