### ISSUE TITLE
🐛[BUG][Combat] BST pets unable to heal outside of combat

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#458]
**What does this bug affect?**

Beastmaster pets healing with an outside of combat regen and through "resting" with the pet command Stay.

**Steps to Reproduce**

Lower a pet's HP and see that it doesn't gradually regen.
Lower a pet's HP, use stay and see that it's health never recovers.

**Expected behavior**

Out of combat regen for jug pets as well as charmed ones should be 1.25% of max HP every 10 seconds.

"Stay" resting functions very similar to players resting formula. The first tick occurs after 20 seconds and then the subsequent ticks are all 10 seconds apart. The formula being used previously was correct I believe. 

**Setup Information**

12/3/2022 test server

**Additional context**

These numbers provided are from my retail testing. 

Level 33 Yuhtunga Mandragora 
Max HP = 1135
Stay
10%->14->18->24->31->39->48->58->70->82->95

Level 49 Master Coeurl
2401 HP
Stay
Healing ticks occur every 10 seconds.
22%->25->28->33->38->45->53->61->71->82->94

**Comment by panicstevenson** [comment]
I changed this in ASB. This was added in ToAU; we can put it back on for Horizon at launch. Thoughts?

**Comment by panicstevenson** [comment]
Merged
