### ISSUE TITLE
🐛[BUG]Under observation issues

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#46]
**What does this bug affect?**

Magic seems wildly inaccurate and just isnt effective for this fight. Multiple strategies mention it being possible but it just seems very inefficient.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by dallano** [comment]
This issue lies with magic damage calculation and not this battlefield. But thank you for the report!
