### ISSUE TITLE
🐛[BUG] Jailer of hope issues

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#461]
**What does this bug affect?**

Capture video shows its only possible for JoH to aerial collision up to to times in a row, but here it does it 4 or 5 time in a row sometimes. Wiki says it uses a stronger version of Tidal dive, but that didn't happen at all in the capture video.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

https://www.youtube.com/watch?v=iYBs2tzEzmo&ab_channel=BlargedyMcgee
**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment]
I believe we have purposely not given it the ability to do Tidal Dive due to limitation. It should only do Tidal Dive over deep water but we have no way for us to tell what kind of terrain JoH is on.
