### ISSUE TITLE
🐛[BUG][System/Combat] Hunter's Prelude and Archer's Prelude cannot target party members.

### ISSUE THREAD

**Issue by ZawaXI** [HorizonFFXI/HorizonXI-Issues#463]
**What does this bug affect?**
Hunter's and Archer's Prelude are BRD songs that work by targeting a party member. Currently, the BRD is unable to target a party member using the menu and must use a macro or the chat log.

**Steps to Reproduce**
Select Archer's or Hunter's Prelude from the spells list.
Attempt to target a party member.

**Expected behavior**
Party members should be targetable by Prelude.

**Comment by The-Aerec** [comment]
DAT issue. Fixed in install
