### ISSUE TITLE
🐛[BUG][System/Combat] Etudes are AoE instead of single target.

### ISSUE THREAD

**Issue by ZawaXI** [HorizonFFXI/HorizonXI-Issues#464]
**What does this bug affect?**
Etudes are stat increasing songs. In era, these were single target spells. Later, they were changed to affect the entire party. The current implementation is out of era.

**Steps to Reproduce**
Try to cast an etude.
Be unable to target others players (without using the chat log or macros).
Notice that the spell effects multiple players.

**Expected behavior**
Etudes should be single target songs.

**Comment by Squinkerdoodle** [comment]
@ZawaXI was there an issue with Preludes also or was that something else?

**Comment by Squinkerdoodle** [comment]
Commenting with another prelude / etude report: https://github.com/HorizonFFXI/HorizonXI-Issues/issues/373
