### ISSUE TITLE
🐛[BUG][Mission] Can't accept Rank 2 Missions

### ISSUE THREAD

**Issue by Kyne09** [HorizonFFXI/HorizonXI-Issues#465]
**What does this bug affect?**
Unable to accept Rank 2-1 mission.

**Steps to Reproduce**
Get Rank 2 and talk to a gate NPC, there's only the option to "Decline mission."

**Expected behavior**
Should see 2-1 in the Misison window.

**Screenshots**
![image](https://user-images.githubusercontent.com/113271225/205506816-3d25c29d-6a33-4702-a740-65c33f969fef.png)

**Comment by Squinkerdoodle** [comment]
@Kyne09 do you have any rank points for rank 2 or is your bar empty? This seems to have a requirement of at least a few rank points / bar progress before becoming available.

**Comment by Squinkerdoodle** [comment]
@Kyne09 now that the crystal trade in for rank points is working again try trading some in and see if your 2-1 shows up afterwards.

**Comment by Kyne09** [comment]
Yep, the crystal trade in fixed this.  Going to close then.
