### ISSUE TITLE
🐛[BUG][Quest] Say it with Flowers Quest Bugged - Windurst

### ISSUE THREAD

**Issue by Kyne09** [HorizonFFXI/HorizonXI-Issues#466]
**What does this bug affect?**
The quest "Say it with Flowers" in Windurst is currently bugged.  After you get the quest from Maori-Kaaori at C-9, you're supposed to talk to Ohbiru-Dohbiru in the Rhinostery.  However, he will ONLY offer you the quest Water Way to Go, even if you decline the quest.  He does not move to or from any other prompt until you complete this quest to him. 

**Steps to Reproduce**
Accept Say it with Flowers and then go talk to Ohbiru-Dohbiru.  Zoning, logging out and back in, or declining the quest were all attempted and he is unable to give you ANY other chat prompt but this one.

![image](https://user-images.githubusercontent.com/113271225/205509650-86110334-cdf6-4f80-99f7-3ccb141fd500.png)

If you zone after turning Water Way to Go, he will "reset" and you must again complete Water Way to Go before he will resume Say it with Flowers.

![image](https://user-images.githubusercontent.com/113271225/205509408-5abcd997-f898-411d-ba32-366947721e77.png)

If you turn in Water to Go and then talk to him, he will give you the Say it with Flowers prompt correct.  Just don't zone.

![image](https://user-images.githubusercontent.com/113271225/205509867-7b935a38-62cc-4729-9adc-971b437dcbb4.png)

**Expected behavior**
Declining the quest Water Way to Go should allow the NPC to go to the next active quest prompt.  In this case, it just loops infinitely.

Accepting the quest should ALSO allow you to get the Say it with Flowers questline prompt **after you zone out and back in**.  Currently it doesn't do that either.  I've highlighted my !goto command to force the character to "zone".

![image](https://user-images.githubusercontent.com/113271225/205509775-7147472d-5cc1-43a5-9475-739b476ef810.png)

**Comment by Squinkerdoodle** [comment]
Issue reported on the beta github with #1257 & #1776. This ticket should be able to be closed as a duplicate report.

**Comment by Kyne09** [comment]
Those two tickets are for two separate issues, #1257 is running into a quest prompt related to an un-related quest: Food for Thought.  #1776 is reporting that Kenapa-Keppa will no longer interact with the player.

These are three separate issues, related to the same quest.

**Comment by CriticalXI** [comment]
Fixed in https://github.com/AirSkyBoat/AirSkyBoat/pull/2125
