### ISSUE TITLE
🐛[BUG][Quest] Quest Faded Promises 

### ISSUE THREAD

**Issue by Kyne09** [HorizonFFXI/HorizonXI-Issues#468]
**What does this bug affect?**
Quest Faded Promises does not trigger.  Main Job Ninja above level 20, I have completed Ayame and Kaede.

![image](https://user-images.githubusercontent.com/113271225/205514535-4634eff1-7362-4d51-b9d8-5c1106afde60.png)

https://ffxiclopedia.fandom.com/wiki/Faded_Promises

**Steps to Reproduce**
Unlock NIN and then go to Romualdo above level 20.  He does not trigger the cutscene to begin this quest.  Zoning, relogging, talking to Ayame and then back to him, talking to him multiple times, nothing causes the quest to trigger correctly.

**Expected behavior**
The quest should be activating.

**Comment by dallano** [comment]
You also need 4 or great tenshodo / norg fame. do you have that?

**Comment by Kyne09** [comment]
![image](https://user-images.githubusercontent.com/113271225/206879956-b6acb640-54a3-4ee7-8038-2d988ac21321.png)
