### ISSUE TITLE
🐛[BUG] Bastok 3-2 Blind Moby issue

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#469]
**What does this bug affect?**
NM Blind Moby will not come out of the pool of water that it spawns at, which is at J-7 on the first map and pictured below.

**Steps to Reproduce**
Spawn NM and see if it comes out of the water.

**Expected behavior**
NM should be able to come out of the water and onto the land to attack the player / be fought via melee.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/205515610-956737e2-8fbf-4475-8858-9679ff43b726.png)
![image](https://user-images.githubusercontent.com/112344508/205515648-e3992a3e-8acd-4ca2-9819-9ae3d6ca6413.png)

**Setup Information**
Version 30221103_1

**Comment by OpheliaXI** [comment]
This is no longer an issue with the new pathfind code.
