### ISSUE TITLE
🐛[BUG][Mission] Windurst Mission 2-2 A Testing Time does not properly give kill credits.

### ISSUE THREAD

**Issue by Kyne09** [HorizonFFXI/HorizonXI-Issues#470]
**What does this bug affect?**
Currently the player isn't getting correct credit for mob kills.  I killed 30 mobs with just autoattacks, went back and he claimed I had done 7.

![image](https://user-images.githubusercontent.com/113271225/205523832-c0b7789f-e5ae-45d6-bcda-fd00b5b1fc8a.png)

When I went back and killed a few more monsters, the counter only went up by 1.

![image](https://user-images.githubusercontent.com/113271225/205523902-08060799-b255-4a1d-a646-f4481a8204ea.png)

![image](https://user-images.githubusercontent.com/113271225/205523920-c6b336ce-68cf-40dd-b29c-95872197c660.png)

![image](https://user-images.githubusercontent.com/113271225/205523932-e2b1432e-6c12-4a2a-bbc8-80e3773a263d.png)

**Steps to Reproduce**
Go to the zone, kill mobs, come back and check the count.

**Expected behavior**
You should get 1 kill credit for each mob.

**Comment by panicstevenson** [comment]
It's actually reporting the hour where the kill count should be.....

Fixed in ASB.
