### ISSUE TITLE
🐛[BUG] Garrison Issues

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#474]
**What does this bug affect?**
Unable to trade the garrison starting item reliably across multiple players. When trading the nation's conquest npc will give the message that there's no attack currently (as if you had completed the garrison for that zone already for the week) or something saying the recruits lack experience. This is happening even in zones where the player has not attempted the garrison at all for that current tally period.

Additionally in the event the NPC does take the garrison start item trade and garrison actually starts, players will lose the level restriction buff before the garrison is completed making them unable to continue fighting the garrison mobs or healing the NPC guards. This seems to happen at random times and found no common cause for it.

**Just wanted to note that the zone is no longer crashing after the first mob is killed. (At least when it's started via GM command)**

**Setup Information**
Current test server on 12/6

@xkoredev

**Comment by xkoredev** [comment]
@Squinkerdoodle where all players rank 2? There is a minimum of rank 2 entry requirement for all players, which will cause the "lack of experience" message to show.

**Comment by Squinkerdoodle** [comment]
Is that a requirement? I know the person starting it must be rank 2 at least but when I looked it was stated anyone may participate regardless of rank. Also just to confirm can a player only start one garrisons week, regardless of zone?

Sent from Yahoo Mail on Android 
 
  On Wed, Dec 7, 2022 at 1:26 PM, ***@***.***> wrote:   


@Squinkerdoodle where all players rank 2? There is a minimum of rank 2 entry requirement for all players, which will cause the "lack of experience" message to show.

**Comment by xkoredev** [comment]
> Is that a requirement? I know the person starting it must be rank 2 at least but when I looked it was stated anyone may participate regardless of rank. Also just to confirm can a player only start one garrisons week, regardless of zone? Sent from Yahoo Mail on Android On Wed, Dec 7, 2022 at 1:26 PM, ***@***.***> wrote: @Squinkerdoodle where all players rank 2? There is a minimum of rank 2 entry requirement for all players, which will cause the "lack of experience" message to show. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

To be fair I wasn't sure if this was. I had assumed the requirement was everyone, and that the cooldown required was shared (for the cooldown at least, you could rotate who starts the garrison between 18 ppl and ignore the cooldown that way)

**Comment by Squinkerdoodle** [comment]
This is from wiki (so don't take it as absolute) but there it states 
"Anyone can participate in a Garrison, but only Rank 2 or higher citizens of the nation controlling the region can trade the item to the outpost guard and initiate the event." 
Also need clarification on this part:"   
   - A player can only trade the item to start a Garrison once per Conquest Tally regardless of zone." To me that reads as a player can only start 1 garrison a week, period. Instead of per zone. But I could be wrong.

The above is from wiki https://ffxiclopedia.fandom.com/wiki/Category:Garrison
Sent from Yahoo Mail on Android 
 
  On Wed, Dec 7, 2022 at 1:49 PM, ***@***.***> wrote:   



Is that a requirement? I know the person starting it must be rank 2 at least but when I looked it was stated anyone may participate regardless of rank. Also just to confirm can a player only start one garrisons week, regardless of zone? Sent from Yahoo Mail on Android On Wed, Dec 7, 2022 at 1:26 PM, @.> wrote: @Squinkerdoodle where all players rank 2? There is a minimum of rank 2 entry requirement for all players, which will cause the "lack of experience" message to show. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.>


To be fair I wasn't sure if this was. I had assumed the requirement was everyone, and that the cooldown required was shared (for the cooldown at least, you could rotate who starts the garrison between 18 ppl and ignore the cooldown that way)

**Comment by xkoredev** [comment]
>     - A player can only trade the item to start a Garrison once per Conquest Tally regardless of zone." To me that reads as a player can only start 1 garrison a week, period. Instead of per zone. But I could be wrong.

There is actually a setting (that we should test) for only allowing 1 garrison per tally.
I will fix the rank requirement so it only applies to the starting player. That's easy.

Open questions (I think) are:

- Is the per tally cooldown only applied to the starting player?
- Is the per zone cooldown only applied to the starting player?

**Comment by Squinkerdoodle** [comment]
Update my comments to get rid of the yahoo email / replies part. Didn't realize it did that when responding on mobile and didn't like the clutter.

**Comment by Squinkerdoodle** [comment]
Another thing to check in the coding:
Garrison cannot occur in an area where Ballista is occurring. This includes the day for entry, the actual match, and closing (3 game days).
There is a cool-down period between Garrisons in the same zone. Another Garrison can be initiated exactly 30 minutes after the initiation of the previous Garrison in the same area.
You have 30 minutes to complete a Garrison or it will end in failure and mobs will depop.

From your previous response~
Open questions (I think) are:

Is the per tally cooldown only applied to the starting player?
Is the per zone cooldown only applied to the starting player?

The per tally cooldown should only apply to the player that traded the item and started the garrison, not all participants. You are correct on your earlier comment where you could do it repeatedly with different players starting it.
The per zone cooldown is just in general I believe, as in another garrison can't be started in the same zone until 30 minutes have passed since the previous garrison has started.

**Comment by xkoredev** [comment]
Ok about the level sync being lost. That could actually affect the npc dying issue (if 1 npc dies, etc..) which I was unable to repro.
There is a bigger underlying issue here, that affects not only garrison but any other buffs lost on zone. I have mentioned it on discord, and a separate bug should be open. Has to do with how we save buffs periodically now, which removes any buffs lost on zone.

This PR: https://github.com/AirSkyBoat/AirSkyBoat/pull/2110 should be good enough for the other issues listed here.

**Comment by Squinkerdoodle** [comment]
Also just wanted to link your other Garrison report. https://github.com/HorizonFFXI/HorizonXI-Issues/issues/453
