### ISSUE TITLE
🐛[BUG][Mission] Gate guards are showing missions your character shouldn't have access to.

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#475]
**What does this bug affect?**

Mission progression.

**Steps to Reproduce**

Currently when you go to a gate guard they will show you missions that you shouldn't have access to. After I complete the 1-1 Sandy mission It will show 1-3 "Save the Children" as an option. I can click on this mission and it will show the cutscene for it, however the mission doesn't show up in my log and I cannot progress it. 

**Expected behavior**

You should only be able to see missions your character can accept/progress when taking a mission from a gate guard. 

**Screenshots**

![image](https://user-images.githubusercontent.com/2160211/206271073-46157923-0103-42d1-96b2-6b515e699890.png)

**Setup Information**

12/7/2022 test server. 

**Additional context**

I'm not sure if this issue is because my characters are flagged as GMs. (similar to how you can see all the fights when you click on a BCNM)

**Comment by panicstevenson** [comment]
> I'm not sure if this issue is because my characters are flagged as GMs.

Should only be true if !togglegm is on. I don't know how to fix the menu event options but preventing you from starting 1-3 was a stopgap for the time being if someone knows how to work the menu.

**Comment by montijin** [comment]
Going to close this
