### ISSUE TITLE
🐛[BUG][NPC/Quest] Cant speak to NPC Talib in bastok (for norg fame quest)

### ISSUE THREAD

**Issue by alessa89** [HorizonFFXI/HorizonXI-Issues#476]
**What does this bug affect?**
Unable to speak to the NPC Talib, port bastok, warehouse 2 bottom floor. Talking to him should start the quest "beauty and the galka" and then "shady business" to trade zinc ore for norg rep. looking at ffxiclopedia history, should be in era
https://ffxiclopedia.fandom.com/wiki/Beauty_and_the_Galka 

**Steps to Reproduce**
go talk to, and be ignored by talib

**Expected behavior**
get the quest

**Comment by Squinkerdoodle** [comment]
Yes, the PR with the fix isn't merged / live on test server yet.
