### ISSUE TITLE
🐛[BUG][Mission] Sandy 2-3 Mine Gravel is unresponsive

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#477]
**What does this bug affect?**

Sandy mission progression, namely 2-3 (The Journey abroad)

**Steps to Reproduce**

Progress mission 2-3 up to the Mine Gravel part of the Bastok side of the quest. Trade a pickaxe to either Mythril Seam and notice that both are unresponsive, stopping you from progressing the mission any further. 

**Expected behavior**

When trading the pickaxe you should have a high chance to get the mission item "Mine Gravel".

**Screenshots**

![image](https://user-images.githubusercontent.com/2160211/206279215-2998dc0e-d190-436d-b483-185d4d0bc738.png)
![image](https://user-images.githubusercontent.com/2160211/206279041-e251d523-40af-4904-8aac-111a8e3f2633.png)

**Setup Information**

12/7/2022 test server

**Comment by The-Aerec** [comment]
fixed
