### ISSUE TITLE
🐛[BUG] Dragvandil Additional effect 

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#478]
**What does this bug affect?**

I was going through a bunch of weapon additional effects and this weapon stood out. This weapons paralyze procs 100% of the time. You can see the animation appear every swing. Wiki says the proc chance is increased on iceday, but it was firesday when I tested it.
**Steps to Reproduce**

Grab a Dragvandil and start swinging. 
**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by StyrkaGG** [comment]
this is fixed
