### ISSUE TITLE
🐛[BUG] Broken additional effects list for sword, greatsword, axe, club, staff, and scythe

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#479]
**What does this bug affect?**

Here is a list of weapon with additional effects that dont proc:
Tiger hunter
Kabrak axe
Excalibur
Caduceus 
Time hammer
Shellbuster
Arcana Breaker
Walrus staff (Should be ice instead of earth)
Power Staff 
Diabolos's pole
Skofnung
Plantreaper
Webcutter
[A l'Outrance](https://ffxiclopedia.fandom.com/wiki/A_l%27Outrance)
Havoc Scythe
Scarecrow Scythe
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by Birdy-gif** [comment]
I would also like to add that there is already a ticket for charged additional effects so I didn't list them.

**Comment by Squinkerdoodle** [comment]
Some of these were reported on the ASB github in ticket #1304. Just mentioning it so both can be closed when fixed.
