### ISSUE TITLE
🐛[BUG] Broke additional effects for great axe, dagger, polearm, H2H, katana and great katana 

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#480]
**What does this bug affect?**

Another list of weapons with broken additional effects: 
Lizard Piercer
Orc Piercer
Heavy Lance
Dispel Couse
Chicken knife
Bano del sol
Ulfhedian Axe

All the great katanas, H2H, and katanas worked fine.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by Squinkerdoodle** [comment]
Some of these were reported on the ASB github in ticket #1304. Just mentioning it so both can be closed when fixed.

**Comment by LegenDAirie** [comment]
The Bano Del Sol proc rate isn't 100% as it should be.
https://discord.com/channels/933423693848260678/1236436751891828766

I also saw a bug report on the discord about Chicken Knife not over writing Flee when it procs and Flee is already active.
https://discord.com/channels/933423693848260678/1209075305336021033/1209075305336021033

Are these bugs related to this thread? Or should I open a new ticket?
