### ISSUE TITLE
🐛[BUG] Gawain axe paralyze procs almost every hit

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#481]
**What does this bug affect?**

Same as title. Wiki has nothing saying its proc rate should be this high.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by StyrkaGG** [comment]
this seems to be working but i have fought a bunch of mobs and havent got one proc so atleast its not procing all the time now?
