### ISSUE TITLE
🐛[BUG][Mission] Unable to progress CoP 4-3, Secrets of Worship.

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#482]
**What does this bug affect?**

Chains of Promathia mission progression.

**Steps to Reproduce**

Complete up to the part where you need to fight the old professor. Find the right desk and notice that somewhere the flags aren't set correctly and it will not let you spawn him. 

**Expected behavior**

After finding the right drawer you should spawn the old professor to progress the mission. 

**Screenshots**

![image](https://user-images.githubusercontent.com/2160211/206486574-8f92f0eb-36c4-486e-bd94-a7c4f9125a0f.png)
![image](https://user-images.githubusercontent.com/2160211/206486590-ea435d62-11c0-4383-bdd8-8bd3332aea94.png)

**Setup Information**

12/8/2022 test server

**Comment by panicstevenson** [comment]
PR up on ASB 🎉
