### ISSUE TITLE
🐛[BUG] Minstral Axe deletes tp if used out of range

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#483]
**What does this bug affect?**

Minstral axe is a ranged weaponskill and can be used up to 15.7' away from the target. If use the weaponskill outside of that range your tp gets deleted.
**Steps to Reproduce**

Use mistral axe outside of its normal range.
**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by Squinkerdoodle** [comment]
Isn't this normal behavior for when a target moves out of your range when readying a WS?

**Comment by StyrkaGG** [comment]
this is how it was it retail

**Comment by Squinkerdoodle** [comment]
@Birdy-gif or am I reading wrong and you meant if you try to use it while the mob is already out of range?

**Comment by Birdy-gif** [comment]
> @Birdy-gif or am I reading wrong and you meant if you try to use it while the mob is already out of range?

no when you use it completely out of range

**Comment by Birdy-gif** [comment]
Closing this cuz apparently it is normal behavior.
