### ISSUE TITLE
🐛[BUG][Combat] Subjob restriction is falling off when you move into range of Maat during LB5

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#486]
**What does this bug affect?**

When you move into range of Maat the subjob restriction falls off and you gain access to JAs, Spells, traits and WSs.

**Steps to Reproduce**

Approach Maat during a shattering stars attempt and notice that your restriction icon falls off and gain access to your subjob.

**Expected behavior**

You should not have access to your subjob.

**Screenshots**

Posted on the discord. 

**Setup Information**

12/9/2022 test server

**Comment by panicstevenson** [comment]
Should be fixed on merge from ASB
