### ISSUE TITLE
🐛[BUG][System] Unable to zone into Sealion's Den

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#488]
**What does this bug affect?**

Traveling to Sealion's Den.

**Steps to Reproduce**

Try to zone from Tavnazian Safehold to Sealion's Den. You'll end up black screening. 

**Expected behavior**

You zone into Sealion's Den,

**Setup Information**

12/9/2022 test server

**Comment by panicstevenson** [comment]
I had similar zoning issues starting today on the box where I would zone into a black screen as well?

**Comment by RetroPrez** [comment]
Can confirm, black screen / Error 4001 trying to zone into Sealion's Den atm

**Comment by panicstevenson** [comment]
The fix was merged into LSB, currently open on ASB. With some decent nudging the fix will be in tomorrow or worst case before the testing event tuesday
