### ISSUE TITLE
🐛[BUG][Mission] PM6-4 One to be Feared tuning issues Omega

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#489]
**What does this bug affect?**

This effects the difficulty of the airship fight. Currently under 25% HP the only two moves Omega will use are discharge and guided missile. The wiki states that pile pitch should also still be used in this phase.

Omega is missing target analysis. 

Guided Missile damage is too low. 
![image](https://user-images.githubusercontent.com/2160211/206865853-688e2d0d-4ae0-489d-9464-49ad60a4f92a.png)

Based on videos it also seems very likely that Omega has a custom damage value. 

**Steps to Reproduce**

Test the fight on the test server.

**Setup Information**

12/10/2022

**Comment by dallano** [comment]
https://github.com/AirSkyBoat/AirSkyBoat/pull/2129
