### ISSUE TITLE
🐛[BUG][COMBAT] Player stat calculation is wrong

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#49]
**What does this bug affect?**
Combat

I'm currently seeing extra base stats on the test server. I tested this on both a hume and a tarutaru. 

**Expected behavior**

Era retail stats as seen in the screenshot added.
The expected stats for a tarutaru 75BST/37WAR are:
HP: 1040 (correct)
MP: 0 (correct)
STR: 61 (+2 on TS)
DEX: 68 (+1 on TS)
VIT: 60 (+2 on TS)
AGI: 62 (+1 on TS)
INT: 65 (+2 on TS)
MND: 55 (+2 on TS)
CHR:  69 (+2 on TS)
**Screenshots**

![unknown](https://user-images.githubusercontent.com/2160211/189016247-75d6f254-d75d-40e5-b2d8-6d9c00a6e049.png)
![IMG_2022_09_07_20_30_19R](https://user-images.githubusercontent.com/2160211/189015910-39998495-3b13-43f3-9a5e-944636c5532e.jpg)
**Setup Information**

Test server 9/7/2022
version 30220802_3

**Additional context**

The stat order for the table in the book is:
WAR, MNK, WHM, BLM, RDM, THF, PLD, DRK, BST, BRD, RNG, SAM, NIN, DRG, SMN, BLU, COR, PUP

**Comment by OpheliaXI** [comment]
https://github.com/AirSkyBoat/AirSkyBoat/pull/423 will help bring us closer, but this is a long-term project as we will have to recursively solve for the appropriate grade values.
