### ISSUE TITLE
🐛[BUG][Mission] PM6-4 One to be Feared tuning issues Ultima

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#490]
**What does this bug affect?**

CoP mission progression and difficulty. 
1. Wirecutter isn't doing enough damage. 
![image](https://user-images.githubusercontent.com/2160211/206866697-8a4b4348-77fb-4167-abe6-a5002b678131.png)
2. Equalizer isn't doing enough damage. 
![image](https://user-images.githubusercontent.com/2160211/206866756-1900b504-82d7-40f4-83a7-e23b52b75776.png)
3. Nuclear waste is not lowering the resistances of the player by 50
4. In the final phase Ultima is not using three TP moves back to back. 

**Steps to Reproduce**

Test the fight on the test server.

**Setup Information**

12/10/2022 test server

**Comment by dallano** [comment]
https://github.com/AirSkyBoat/AirSkyBoat/pull/2129
