### ISSUE TITLE
🐛[BUG][Mission] Boggelmann (CoP 7-4)

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#491]
**What does this bug affect?**

The NM Boggelmann for CoP is missing 2hr (blood weapon) and also has an incorrect move list. 
This NM is suppose to use a special version of Bone Crunch called Heavy Crunch. Instead the ID is likely wrong because it was using "Chaos Breath" on me instead.

**Steps to Reproduce**

Boggelmann     : !pos -312.52 -34.233 187.217 25

**Expected behavior**

https://ffxiclopedia.fandom.com/wiki/Calm_Before_the_Storm

**Screenshots**

![image](https://user-images.githubusercontent.com/2160211/206869047-5a1bd69e-19e3-48f3-95d2-afd4e9465988.png)

**Setup Information**

12/10/2022 test server

**Comment by dallano** [comment]
I can fix the mob skill 100%. But the blood weapon usage is debated. I recently did a CoP run through on retail and kept this guy alive as long as possible. After slowly whittling his HP down he never used it.
