### ISSUE TITLE
🐛[BUG][Mission] A Fate Decided (CoP 8-2) unable to progress

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#492]
**What does this bug affect?**

This effects progressing through CoP. There is a missing mission progression after you click the gate of the gods and view the cutscene. 

**Steps to Reproduce**

-- !addmission 6 818
-- Grand Palace of Hu'Xzoi Particle Gate (!pos 1 0.1 -320 34)

**Expected behavior**

You should be able to progress the mission after the cutscene. 

**Screenshots**

![image](https://user-images.githubusercontent.com/2160211/206870173-07e3e2c9-5953-4a20-86aa-acce630239ca.png)

**Setup Information**

12/10/2022 test server

**Comment by panicstevenson** [comment]
The code implies you need to talk to the East Particle Gate, West Particle Gate, and Gate of the Gods. You'll know you've progressed once you'd received your Tavnazian Ring. Did that not happen for you?

**Comment by montijin** [comment]
> The code implies you need to talk to the East Particle Gate, West Particle Gate, and Gate of the Gods. You'll know you've progressed once you'd received your Tavnazian Ring. Did that not happen for you?

That did not happen for me
