### ISSUE TITLE
🐛[BUG][Quest/System]  Jeuno Fame Calculating Way Too High

### ISSUE THREAD

**Issue by Kyne09** [HorizonFFXI/HorizonXI-Issues#496]
**What does this bug affect?**
Currently Jeuno is getting far too much fame from associated cities.

**Steps to Reproduce**
Set all fames to 0, and start turning in Only the Best in Selbina.  Rep goes up by ~23 or so per turnin, while all the other reps go up by only 5 each.  

**Expected behavior**
Jeuno rep should not be catapulting ahead like this, it should be some average of the three cities from quests just involving those cities.  If anyone has literature on what exactly it's supposed to be please contribute.

**Screenshots**
![image](https://user-images.githubusercontent.com/113271225/206953043-8f16cc16-3d80-481d-a88c-678ac0fbf9b8.png)

**Comment by Squinkerdoodle** [comment]
https://ffxiclopedia.fandom.com/wiki/Only_the_Best
This Quest will raise Reputation in Bastok, San d'Oria, and Jeuno. So this may be working as intended since Jeuno is the average of either the 2 highest starter nations or all 3 (still unsure which) plus any fame Jeuno gets for itself.
