### ISSUE TITLE
🐛[BUG][Combat] Various minor issues related to Ward Bloodpact duration, value, mechanics

### ISSUE THREAD

**Issue by Jimmayus** [HorizonFFXI/HorizonXI-Issues#499]
Several Bloodpact Wards have duration and/or mechanical issues that are minor in scope but nonetheless ought to be corrected in a post-launch patch. Of these I would say Hastega is the most important. See below:

Lunar Cry: Values per moon phase appear to be incorrect. During the moon phase "Waning Crescent" Lunar Cry inflicted the monster with Accuracy - 6 and Evasion - 23. The era chart has Accuracy - 6 (so correct) and Evasion - 26 (thus incorrect) for this moon phase. The full chart is reproduced below https://ffxiclopedia.fandom.com/wiki/Lunar_Cry :

Moon Phase            Accuracy    Evasion
New Moon                Acc-1      Eva-31
Waxing Crescent       Acc-6      Eva-26
Waxing Crescent       Acc-11    Eva-21
First Quarter Moon   Acc-16    Eva-16
Waxing Gibbous       Acc-21    Eva-11
Waxing Gibbous       Acc-26    Eva-6
Full Moon                 Acc-31    Eva-1
Waning Gibbous       Acc-26    Eva-6
Waning Gibbous       Acc-21    Eva-11
Last Quarter Moon    Acc-16    Eva-16
Waning Crescent       Acc-11    Eva-21
Waning Crescent       Acc-6    Eva-26

Outside of these specifics these Blood Pacts are working as intended.

**Comment by TracentEden** [comment]
I could not recreate this on ASB/Horizon, can reopen if can recreate.
