### ISSUE TITLE
🐛[BUG][Quest] - Fit for a Prince

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#50]
**What does this bug affect?**
Unable to start quest.

**Steps to Reproduce**
Speak with Halver while meeting the quest's requirements: 
Requirements	San d'Oria Reputation: 3 / Access to Chateau d'Oraguille

**Expected behavior**
Quest should be given when speaking with Halver and meeting the requirements.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
N/A

**Comment by hookstar** [comment]
Quest doesn't appear to be written. Looks like a fun one though!
