### ISSUE TITLE
🐛[BUG][Combat] Monster, Pet, Avatar subjob functioning improperly

### ISSUE THREAD

**Issue by Jimmayus** [HorizonFFXI/HorizonXI-Issues#500]
As the title says, currently Monster/Pet/Avatar subjobs are still not properly operating as Monster level for the purposes of traits and skills, and Monster level * .5 for the purposes of attributes. This has significant ramifications for things like Avatar Magic Attack Bonus working properly, and then separately arbitrarily weaker monsters. 

If necessary I can provide the source work for this but I mean this bug report as more of an official reminder.

**Comment by Frankie-hz** [comment]
This is fixed
