### ISSUE TITLE
🐛[BUG][Combat] Diabolos Nightmare and Ultimate Terror bloodpacts mechanical issues (Nightmare is Major bug)

### ISSUE THREAD

**Issue by Jimmayus** [HorizonFFXI/HorizonXI-Issues#501]
On the test server Nightmare from the summoned avatar Diabolos is operating like the BCNM Diabolos. That is: when slept a monster will not wake up from any source of damage at all. The proper behavior is that a monster slept by the summoned Diabolos will only wake up if hit by direct damage, but it will wake up. It will properly not wake from dot damage. The practical consequence of this bug is that summoners can chain stun monsters for 90 seconds, so I thought to include Major in the title.

Ultimate Terror: On the test server this appears to be draining 15~21 attributes from monsters. The proper values should be 0~7
https://ffxiclopedia.fandom.com/wiki/Ultimate_Terror

**Comment by TracentEden** [comment]
The nightmare issue was fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2435 , ultimate terror issue could not recreate draining more than 7 from single mob.
