### ISSUE TITLE
🐛[BUG][System] Ru Lude Gardens Mog House 

### ISSUE THREAD

**Issue by ChaChang-Byte** [HorizonFFXI/HorizonXI-Issues#502]
**What does this bug affect?**

Entering Mog House causes a black screen but doesn't freeze game when trying to enter and did not rent a room.
**Steps to Reproduce**

Enter Ru Lude Gardens Mog House without having a rent a room in Jeuno. 
**Expected behavior**

Should return you to outside of the elevator. 
**Screenshots**

**Setup Information**

Windows 10, Ashita v3
**Additional context**

**Comment by dallano** [comment]
Fixed here: https://github.com/AirSkyBoat/AirSkyBoat/pull/2189
