### ISSUE TITLE
🐛[BUG] Single weaponskill magic burst?

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#53]
**What does this bug affect?**

Used blade EI at uninvited guests and 2 of our nukes Mbed after it. Went to Cape T to confirm.
**Steps to Reproduce**

Use Blade: Ei or possibly some other weaponskills then have a nuke happen right after.
**Expected behavior**

No MB
**Screenshots**

**Setup Information**

**Additional context**

**Comment by OpheliaXI** [comment]
This has been fixed.
