### ISSUE TITLE
🐛[BUG][NPC/Quest/Mission/System/Combat/Launcher/Website]?

### ISSUE THREAD

**Issue by tstr888** [HorizonFFXI/HorizonXI-Issues#537]
launcher not displaying fully useing a big screen tv as monitor
**What does this bug affect?**
as cant log in keep getting c;\WINDOWS\SYSTEM32\CMD.EXE ENOENT

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by BayaniTenzen** [comment]
Please go to the main discord server HorizonXI and use the #Launcher-Support channel for assistance

We are aware that the Launcher is sending people here however;

This github is for issues relating to problems/bugs within the server itself and not connecting to the Server
