### ISSUE TITLE
🐛[BUG][NPC/Quest/Mission/System/Combat/Launcher/Website]?

### ISSUE THREAD

**Issue by Inocuchino** [HorizonFFXI/HorizonXI-Issues#539]
**What does this bug affect?**

Horizon FFXI won't launch after installation.
**Steps to Reproduce**

1. download installer
2. install launcher
3. launcher installed game
4. attempted to launch, failed.
**Expected behavior**

it should launch the game
**Screenshots**

![Screenshot 2022-12-17 210642](https://user-images.githubusercontent.com/120868282/208276297-4fb4c653-4a05-491b-b86c-a481afe1a90b.jpg)

**Setup Information**

running windows 10, microsoft edge, 1.0
**Additional context**

**Comment by BayaniTenzen** [comment]
Please go to the main discord server HorizonXI and use the #Launcher-Support channel for assistance

We are aware that the Launcher is sending people here however;

This github is for issues relating to problems/bugs within the server itself and not connecting to the Server
