### ISSUE TITLE
🐛[BUG][Launcher]

### ISSUE THREAD

**Issue by RedBaren** [HorizonFFXI/HorizonXI-Issues#543]
**What does this bug affect?**
I needed to delete the game cause of addons that had issues so I wanted to reinstall the entire game and it does not re-download the game though all files are deleted.

**Steps to Reproduce**
I have deleted the launcher and reinstalled but it instantly says game files are good (they are still deleted) and login states error "spawn C:\WINDOWS\system32\cmd.exe ENOENT at ChildProcess._handle.oneit"

**Expected behavior**
Launcher should read that my files are gone and re-download 

**Screenshots**
![error](https://user-images.githubusercontent.com/90907417/208289923-9ccfb751-bfe9-4296-92e0-c8330bd5ed17.PNG)

**Additional context**

**Comment by BayaniTenzen** [comment]
Please go to the main discord server HorizonXI and use the #Launcher-Support channel for assistance

This github is for issues relating to problems/bugs within the server itself and not connecting to the Server

**Comment by RedBaren** [comment]
Ok I found it thank you... Just so you know it sent me to that GitHub from
the launcher incase there's a way to route it differently so you don't get
a lot of issues that need to be routed to the discord.

Thanks for your time...The community appreciates all that your team is
doing and it's going very well overall... /Bow
