### ISSUE TITLE
🐛[BUG][NPC] - Bibiki Bay Boat

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#55]
**What does this bug affect?**
The boat to Purgonorgo Isle in Bibiki Bay does not move when en route to the island, it just sits still in the spot it loaded in.

**Steps to Reproduce**
Board the boat in Bibiki Bay and see if it moves from the starting spot or not.

**Expected behavior**
Normal boat sailing behavior with the ship sailing and moving, able to see the surroundings move as you sail by.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
I did not check the other 2 routes, just the one that takes you to Purgonorgo Isle. The boat did load into Purgonorgo Isle properly after the normal travel time.

**Comment by CriticalXI** [comment]
Would @The-Aerec or @Frankie-hz know how to fix this one?

**Comment by The-Aerec** [comment]
Zone animations arn't set i'm guessing..

**Comment by Frankie-hz** [comment]
Worked fine for me. Showed up at 4:50 took me at 5:30 and gave correct event cs + put me on the boat. Can anyone replicate this?

**Comment by Squinkerdoodle** [comment]
@Frankie-hz that all works for me as well, the issue I'm running into is that once on board the ship / after the CS the ship doesn't move while en route. THough it does have the sailing animation.

![image](https://user-images.githubusercontent.com/112344508/196340797-663b60c8-767a-4497-8851-ecd30ebb404f.png)
![image](https://user-images.githubusercontent.com/112344508/196340864-ef408b54-21af-49f1-a964-29f0a697b9f5.png)
