### ISSUE TITLE
🐛[BUG][Launcher]?

### ISSUE THREAD

**Issue by Bryce-Du** [HorizonFFXI/HorizonXI-Issues#552]
**What does this bug affect?**
Launcher not launching the game, I can log in fine but when I click play it minimizes launcher and gives a warning that says: 

"spawn C:\WINDOWS\system32\cmd.exe ENOENT
at ChildProcess._handle.onexit (node:internal/child_process:283:19)
at onErrorNT (node:internal/child_process:478:16)
at process.processTicksAndRejections (node:internal/process/task_queues:83:21)"

I tried to uninstall and reinstall the launcher with the new version and got the same issue.

**Comment by BayaniTenzen** [comment]
Please go to the main discord server HorizonXI and use the #Launcher-Support channel for assistance

We are aware that the Launcher is sending people here however;

This github is for issues relating to problems/bugs within the server itself and not connecting to the Server
