### ISSUE TITLE
🐛[BUG][Launcher]

### ISSUE THREAD

**Issue by LunaBringsMischief** [HorizonFFXI/HorizonXI-Issues#554]
Launcher

Happens every time I try to open the launcher and get into the game even in run as admin.

![Screenshot 2022-12-19 204740](https://user-images.githubusercontent.com/118320432/208562103-621cebff-2c6b-44d0-80d7-0f8c0cfa2158.png)

![Screenshot 2022-12-19 204827](https://user-images.githubusercontent.com/118320432/208562189-20dfa8d3-6b83-440a-9323-5cb173f7ee96.png)

I updated and restarted launcher and was able to get into the game twice but with weird behavior the first time like not being able to type in the chat box or trying to type a msg kept changing the chat recipient type or doing other things.  Troubleshooting steps taken included restarting the launcher multiple times, tried rebooting the system 2x, uninstalled and reinstalled from website (which links to the original version) - issue persisted. Uninstalled and re-installed using the latest ver. link in discord - issue persists but now instead shows server offline while occasionally flashing online then offline again.  No longer prompting to restart for the new version but getting the error in the screengrab instead.

I see that there are some things you guys are still working on but since the server offline issue said resolved I thought this was worth posting.  Not sure what else to try or if I should just sit tight.  Ty all for your hard work!

**Comment by BayaniTenzen** [comment]
Please go to the main discord server HorizonXI and use the #Launcher-Support channel for assistance

We are aware that the Launcher is sending people here however;

This github is for issues relating to problems/bugs within the server itself and not connecting to the Server
