### ISSUE TITLE
🐛[BUG][Launcher]

### ISSUE THREAD

**Issue by Rueza** [HorizonFFXI/HorizonXI-Issues#557]
Launcher
**What does this bug affect?**
 when I hit "play horizonxi" on the launcher, an error pops up and the game doesn't launch.

**Steps to Reproduce**

-I tried to copy and paste my USER folder from a different private server to Horizon's USER folder and since then, i've got the error everytime.

**Expected behavior**
the ashita injector should pop up and the game launch, but the error happens instead.

**Screenshots**

![Untitled](https://user-images.githubusercontent.com/78386443/208625814-9c1ef59d-2a91-42b1-9898-1e138dcd231a.png)

**Setup Information**
 Horizon Launcher v1.1.0

**Additional context**

**Comment by Rueza** [comment]
I fixed the issue.

I changed the game directory location by removing an unnecessary empty folder, and that's when the error started happening.

I corrected the directory, and HorizonXI launches just fine.

**Comment by BayaniTenzen** [comment]
Thanks for updating the ticket with the additional information!!
