### ISSUE TITLE
🐛[BUG][Quest] - A Taste For Meat reward

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#56]
**What does this bug affect?**
Reward for completing the quest A Taste For Meat

**Steps to Reproduce**
Complete quest and verify reward given.

**Expected behavior**
Quest completion should give both 150 gil *and* a grilled hair

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
N/A

**Comment by CriticalXI** [comment]
I tested this myself on stream over the weekend and I properly received the grilled hare reward. You have to speak to the NPC again to receive the item.
