### ISSUE TITLE
🐛[BUG][NPC] Palborough Mines Kazham Key Mobs Not Accurate

### ISSUE THREAD

**Issue by SReyell** [HorizonFFXI/HorizonXI-Issues#562]
**What does this bug affect?**

There are only a couple mobs in the zone that drop these items (Old Quadav's are ALL of them). The other 2 groups of mobs that drop these are not implemented into the game.

**Steps to Reproduce**

Go to Palborough Mines and search for the mobs. 

**Expected behavior**

Mobs in each room leading to Burning circle from Era

**Screenshots**

**Setup Information**

**Additional context**

**Comment by BayaniTenzen** [comment]
This Issue should have been Resolved - thanks for the Report
