### ISSUE TITLE
🐛[BUG] Curaga healing never appears in chatlog

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#563]
**What does this bug affect?**

Same as title. Let me see those big numbers.
**Steps to Reproduce**

Curaga a party of 6 players
**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by TracentEden** [comment]
Fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2374
