### ISSUE TITLE
🐛[BUG][Quest] Smoke on The Mountain

### ISSUE THREAD

**Issue by angeleon94** [HorizonFFXI/HorizonXI-Issues#567]
**What does this bug affect?**
Prevents completion of the Quest. Trading Giant Sheep Meat with Campfire does not give you the Galkan Sausages.

**Steps to reproduce**
1) Start the 'Smoke on The Mountain Quest.
2) Attain the required Giant Sheep Meat.
3) Attempt to trade the Giant Sheep Meat with the Campfire in South Gustaberg (K-9).

**Expected behavior**
The Campfire should give 'Galkan Sausages' in return for the 'Giant Sheep Meat'.

**Screenshots**
<N/A>

**Setup Information**
Launcher ver. 1.10

**Additional context**
There is normally a timer for providing the 'Galkan Sausages' to the character of one real-world minute. When interacting with the Campfire, it says "It may take a little while more to cook the slice of giant meat" and it doesn't change.

**Comment by KyuuBuuh** [comment]
I did the quest, and it did work but needed to wait 24h ingame time instead of 1min irl time.

**Comment by BayaniTenzen** [comment]
https://ffxiclopedia.fandom.com/wiki/Smoke_on_the_Mountain?oldid=21662

**Comment by BayaniTenzen** [comment]
It is ERA Accurate - the quest takes one Vanadiel Day to Complete
