### ISSUE TITLE
🐛[BUG][Quest] - A Reputation in Ruins

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#57]
**What does this bug affect?**
Quest does not start. Already cleared and currently past CoP mission "The Road Forks".

**Steps to Reproduce**
Speak with quest giver NPC while on a CoP mission after The Road Forks.

**Expected behavior**
Quest should start and NPC should give you an item or key item.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
Attempted while active CoP mission was The Road Forks and also attempted again when on a later CoP mission.

**Comment by CriticalXI** [comment]
Implemented in AirSkyBoat/AirSkyBoat#588
