### ISSUE TITLE
🐛[BUG] Save the children

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#573]
**What does this bug affect?**

Orcs do not link in the "Save the Children" battlefield. I bound one and cast dia on another one from behind and there were no links. 
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by BayaniTenzen** [comment]
https://ffxiclopedia.fandom.com/wiki/Save_the_Children?oldid=763119
