### ISSUE TITLE
🐛[BUG] Mog safe 1 storage missing?

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#577]
**What does this bug affect?**

My mog storage should have 11/50 but it says it has 11/0 and I cant transfer any times to or from it. I tried to zone and log, but no luck. 
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/78566333/208995426-b013fc6f-1c11-4a3d-8961-3adaa6355558.png)
![image](https://user-images.githubusercontent.com/78566333/208995474-793e70ee-cb0f-4ce3-93fb-fbff572a29e5.png)

**Setup Information**

**Additional context**

**Comment by Birdy-gif** [comment]
I just noticed that my inventory is also 20/0. 
![image](https://user-images.githubusercontent.com/78566333/208995733-dd16eebc-353b-4787-b6ae-d87f27c18e84.png)

**Comment by Birdy-gif** [comment]
It just randomly fixed for me after I zoned again. Not sure what happened there, but its fine now.

**Comment by CriticalXI** [comment]
Unsure of what caused this but I haven't seen anyone else experiencing this. Closing this out as a weird one off issue.
