### ISSUE TITLE
🐛[BUG][Quest] - Ducal Hospitality

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#58]
**What does this bug affect?**
Unable to start quest. Attempted with level 3 Jeuno fame all the way to level 9 Jeuno fame.

**Steps to Reproduce**
Talk with NPC at any rep level.

**Expected behavior**
Quest should be given, uncertain of reputation level requirement.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
N/A

**Comment by dallano** [comment]
Should be an easy quest to implement. I'll get it done soon.
