### ISSUE TITLE
🐛[BUG][Launcher] Magnet Link Error

### ISSUE THREAD

**Issue by paige404** [HorizonFFXI/HorizonXI-Issues#582]
**What does this bug affect?**

Not sure, opened the launcher and I think the magnet link used to distribute patches is failing.

**Steps to Reproduce**

Open the launcher.

**Expected behavior**

Not this.

**Screenshots**

![img](https://user-images.githubusercontent.com/59348003/209237786-d4555028-a8cb-4dc6-ba84-1896a69c9c40.png)

**Setup Information**

Windows 10, HorizonXI Ver 1

**Additional context**

**Comment by paige404** [comment]
This issue looks like it was just temporary, after I closed and reopened the launcher a few times and let it sit, it stopped occuring.

**Comment by paige404** [comment]
Nevermind it's back

**Comment by rarcher** [comment]
This just happened to me too, and I've seen it happen on two different computers.  I'm thinking something happened at the server level that hit everybody.
