### ISSUE TITLE
🐛[BUG][Launcher]?

### ISSUE THREAD

**Issue by alexdsallas** [HorizonFFXI/HorizonXI-Issues#588]
**What does this bug affect?**
Launching the game

**Steps to Reproduce**
Trying to launch the game. Usually happens after server restarts? Maybe after launcher updates. Feels random.

**Screenshots**
![image](https://user-images.githubusercontent.com/54248951/209240772-440950f5-5080-4600-9dd7-07bd22303248.png)

**Setup Information**
Windows 10, Normal setup. Whatever version was released near 5:15 PM CST for the live server? I'm not sure what to put here.

**Comment by BayaniTenzen** [comment]
Please Refer to the Main Discord Server > Launcher Section for Troubleshooting Issues
