### ISSUE TITLE
🐛[BUG][NPC/Quest] - Hook, Line, and Sinker

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#59]
**What does this bug affect?**
Unable to get Egret Fishing Rod to drop, see additional context.

**Steps to Reproduce**
Fish in Qufim Island to see if a Kraken is ever fished up, or if the fished up Sea Bishops actually drop the Egret Fishing Rod.

**Expected behavior**
The wiki states both fished up sea bishops & krakens drop the item needed, however ffxidb only has fished up krakens as the loot source. Fishing should catch Krakens, or the fished up sea bishops should be able to drop it if krakens are unable to be fished up.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
Tried all fishing spots in Quifim Island and caught around 37 sea bishop mobs, but none dropped the item. Frank looked at the loot table and it showed as a 1% chance, however ffxidb.com only had krakens listed as a drop in Qufim. I spent about 2 hours fishing in Qufim and I fished up 0 Kraken, but had around 37 Sea Bishops. After fishing for so long with no Krakens I gave myself the egret fishing rod item and turned it in, which completed the quest so the only issue seems to be fishing up the krakens to get the drop legitimately. Additionally I did kill the kraken that spawns at the flowers needed for the BST unlock quest, but had no luck there either.

**Comment by dallano** [comment]
They definitely have the drop list. Sea biship having a 1% drop rate, and the kraken having a 5% drop rate.
As for the kraken not spawning - he definitely wasn't in the database. This should now be fixed. :)
