### ISSUE TITLE
🐛[BUG][Launcher] -

### ISSUE THREAD

**Issue by jwest384** [HorizonFFXI/HorizonXI-Issues#593]
**What does this bug affect?**
When I attempt to launch the Launcher I get an error popup with heading "provide magnet link in path".  If I click "Ignore" and attempt to log in I get a "bad gateway" error.  See screenshots for full error details.  I've gotten this error since launch but usually I can close and relaunch over and over again until it stops but since today's patch I get it every time and can't login.

**Screenshots**
![launcher error](https://user-images.githubusercontent.com/77185044/209241169-b0f9dcac-1ede-48d9-ad16-0944bb3f679d.png)
![bad gateway](https://user-images.githubusercontent.com/77185044/209241177-7e813243-9615-4a98-9bf9-7f952b493228.png)

**Setup Information**
Windows 11 22H2 Build 22621.963

**Additional context**
I have tried running as admin/no running as admin and have attempted to disable seeding.

**Comment by BayaniTenzen** [comment]
Please Refer to the Main Discord Server > Launcher Section for Troubleshooting Issues
