### ISSUE TITLE
🐛[BUG]Launcher Error: Provide magnetLink and path

### ISSUE THREAD

**Issue by whmq8** [HorizonFFXI/HorizonXI-Issues#597]
**What does this bug affect?**

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by whmq8** [comment]
![Screenshot 2022-12-23 023333](https://user-images.githubusercontent.com/121267279/209242692-0783f634-89ff-4778-aa15-84ee889f54b2.png)

**Comment by BayaniTenzen** [comment]
Please Refer to the Main Discord Server > Launcher Section for Troubleshooting Issues
