### ISSUE TITLE
🐛[BUG][NPC/Quest] A Squire's Test II Level Requirement Too High

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#6]
**What does this bug affect?**
Quest "A Squire's Test II"

**Steps to Reproduce**
Talk to Balasiel at level 10 and increase by 1 level until it gives you the quest. Exact level unknown as I went from lvl 10 to 29 to see if was given prior to level 30.

**Expected behavior**
Wiki says level 10 requirement, but was unable to start quest at 10 and received it at 29. I changed my level from 10 to 29 to see if would give it to me before level 30. Did not test level by level between level 10 to level 29.

**Screenshots**
N/A

**Setup Information**
Game version 30220802_3

**Additional context**
Most who do this quest will probably be level 30+ since that is the requirement for the following PLD unlock quest, but still seems to be a bug since it did not give the quest at level 10 as stated on the wiki.

**Comment by CriticalXI** [comment]
Fixed in AirSkyBoat/AirSkyBoat#370
