### ISSUE TITLE
🐛[BUG] Limbus NE issues

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#60]
**What does this bug affect?**

All similer mobs in the same area that were part of the same family would link throughout each level. EX we aggroed 1 mandy on floor 1 and they ALL agroed and attacked us. It seems nothing in NE has their immunities or resistances correct besides the gigas. There was a blue chest on the pot floor that couldn't be opened.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment]
Closing issue as there was a recent rework of the entirety of Apollyon. Please feel free to re-open if this issue still persists.
