### ISSUE TITLE
🐛[BUG]Launcher?

### ISSUE THREAD

**Issue by Davidtiptonjr** [HorizonFFXI/HorizonXI-Issues#601]
**What does this bug affect?**

Launcher
**Steps to Reproduce**

Open Launcher - error occurs
**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

Not logged in on UI and server shows offline.

**Comment by BayaniTenzen** [comment]
Please Refer to the Main Discord Server > Launcher Section for Troubleshooting Issues
