### ISSUE TITLE
🐛[BUG] Launcher

### ISSUE THREAD

**Issue by BlueForest86** [HorizonFFXI/HorizonXI-Issues#604]
**What does this bug affect?**

When opening the launcher and attempting to log-in, I get a Bad Gateway notification. 

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by BayaniTenzen** [comment]
Please Refer to the Main Discord Server > Launcher Section for Troubleshooting Issues
