### ISSUE TITLE
🐛[BUG]Launcher

### ISSUE THREAD

**Issue by elcuauh** [HorizonFFXI/HorizonXI-Issues#610]
**What does this bug affect?**

It has stoped the download of the game.

**Steps to Reproduce**

Just download the game from the client

**Expected behavior**

Nothing

**Screenshots**

**Setup Information**

Win 10 new instalation 12/2022

**Additional context**

**Comment by elcuauh** [comment]
Second time that this happened

**Comment by elcuauh** [comment]
second time this happened

**Comment by BayaniTenzen** [comment]
Please Refer to the Main Discord Server > Launcher Section for Troubleshooting Issues
