### ISSUE TITLE
🐛[BUG]Launcher

### ISSUE THREAD

**Issue by jmssmith1** [HorizonFFXI/HorizonXI-Issues#611]
**What does this bug affect?**

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by jmssmith1** [comment]
How do I report an issue to fix a file deletion problem? I couldn't access the gamepad config so I figured I would delete the installer and files and reinstall to see if that would fix the issue. I can access the gamepad config menu now having reinstalled the launcher, but bc the files were deleted, the launcher thinks the files are still downloaded and will not allow me to redownload them. The launcher just says Play HorizonXI, but will not load due to the deleted files.

**Comment by BayaniTenzen** [comment]
Please Refer to the Main Discord Server > Launcher Section for Troubleshooting Issues
