### ISSUE TITLE
🐛[BUG] SE Limbus

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#62]
**What does this bug affect?**

Any immunities listed on the ffxiclopedia page for this wing these mobs dont have at all. The damage immunities and weaknesses are fine. The manta boss on the 2nd floor has a low counter rate when the wiki mentions it being very high. Again every mob of the same family links throughout the entire floor. Skeletons should not link at all. Anier keeps getting brought to a different wing start after we complete a wing.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment]
Closing issue as there was a recent rework of the entirety of Apollyon. Please feel free to re-open if this issue still persists.
