### ISSUE TITLE
🐛[BUG][Mission] Windurst 5-1: The Final Seal

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#624]
**What does this bug affect?**
After clicking on the Star Sibyl's "Vestal Chamber" door on the top floor of Heavens Tower in Windy Walls and going through the cutscene / put on The Final Seal mission I was not given the key item "New Fei'Yin Seal". Additionally the KI "Message to Jeuno" is still in my Temp KI list, not sure if it was supposed to be removed when talking to the Star Sibyl and getting the 5-1 mission activated in my log.

**Setup Information**
Version 30221103_1

@dallano

**Comment by panicstevenson** [comment]
Fix on live.
