### ISSUE TITLE
🐛[BUG] - Launcher / game files

### ISSUE THREAD

**Issue by Zirin1** [HorizonFFXI/HorizonXI-Issues#630]
I installed the game, worked perfectly. exited the game to change the graphics settings using the default horizon XI sliders (not the ashita settings - the setting under the cog). upon reloading the game, i was met with an IDP.generic virus flag. i wasn't able to regain control of my mouse and had to alt+cntrl+delete to task manager and restart. upon reattempting to play the game i was met with the same error. After researching, i uninstalled all the files and launcher and went for a reinstall. upon loading the fresh launcher, the launcher said the game was 100% playable, but that cant be possible cause the game was uninstalled with all affiliated files. it seems that the launcher doesnt do a file check after an uninstallation and is causing a cmd.exe error...

**Comment by BayaniTenzen** [comment]
Please ask for help in the HorizonXI Main Discord - Launcher Section!
