### ISSUE TITLE
🐛[BUG][NPC/Quest/Mission/System/Combat/Launcher/Website]?

### ISSUE THREAD

**Issue by Kgmoney57** [HorizonFFXI/HorizonXI-Issues#631]
**What does this bug affect?**

Launching the game, I tried to delete all the game files and it is still showing that I have the game downloaded.

**Steps to Reproduce**

1. Launch the launcher.
2. Click play.
3. Error message appears.

**Expected behavior**

The launcher should allow me to reinstall again instead of showing the game downloaded.

**Screenshots**

**Setup Information**

![image](https://user-images.githubusercontent.com/121584590/209881727-31bcf47c-71a7-4064-b01e-94ee9153327d.png)

**Additional context**

**Comment by BayaniTenzen** [comment]
Please try asking for help on the HorizonXI Discord in the Launcher Section
