### ISSUE TITLE
🐛[BUG][NPC/Combat] Crypt Ghost missing PH

### ISSUE THREAD

**Issue by LoxleyXI** [HorizonFFXI/HorizonXI-Issues#632]
**What does this bug affect?**
On ASB there are 3 PHs (Tomb Bat) for Crypt Ghost. On Horizon there are only 2.
These are the IDs from ASB:
```
17555665
17555666
17555667
```

**Steps to Reproduce**
King Ranperre's Tomb inside the room at (G-8)

**Expected behavior**
Room should have 3 Tomb Bats.

**Comment by CriticalXI** [comment]
This should have been fixed from some recent mass PH fixes. Please feel free to re-open if still experiencing this.
