### ISSUE TITLE
🐛[BUG][System] Auction House Issue

### ISSUE THREAD

**Issue by HitGubz** [HorizonFFXI/HorizonXI-Issues#633]
**What does this bug affect?**

This Bug affects the Auction House, specifically how the auction house history is displayed to myself and I assume other players. 
**Steps to Reproduce**

1) Go to Auction House to buy stack of Earth Crystals 
2) Try to buy Earth Crystals for 10g less than Listed Price 
3) Successfully brought the stack for 160g instead of the 170g every other stack had sold for in the visible history 
4) Chat Log Shows Brought for 160g 
5) Auction House history shows it was brought for 170g 
**Expected behavior**

The listing should show as 160g, not 170g 
**Screenshots**

![image](https://user-images.githubusercontent.com/50017064/209901222-b7b302e7-0dc9-47ca-aaff-accc7dab56c7.png)

AH history had already moved on by the time I made this bug report so can't screenshot that but hopefully you can check the logs.  
Time is in GMT (UK) 
**Setup Information**

Launcher V1.1.3 i think 
Game - unknown /version doesn't work
OS: Windows 11
**Additional context**

I noticed the same thing earlier buying Courl Whiskers cheaper than listed but assumed I was imagining things.

**Comment by CriticalXI** [comment]
We had a recent AH fix and I have not seen anyone else reporting this issue. Closing this out.
