### ISSUE TITLE
🐛[BUG][Combat] Eagle Eye Shot misses, a lot

### ISSUE THREAD

**Issue by FletcherMartin** [HorizonFFXI/HorizonXI-Issues#635]
**What does this bug affect?**
Combat

**Steps to Reproduce**
Just try using Eagle Eye Shot

**Expected behavior**
It misses more often than it hits, even with Sharpshot

**Screenshots**
I'll try to grab a screenshot next time. Kinda dissuaded from playing RNG after seeing it perform at 30+.

**Setup Information**
Don't think this is necessary

**Additional context**

**Comment by TracentEden** [comment]
This is being fixed with incoming patch (watch patch notes).
