### ISSUE TITLE
🐛[BUG] Lumbus SW 

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#64]
**What does this bug affect?**

Mimics dont open their mouths. Entire floors of same family mobs link.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment]
Closing issue as there was a recent rework of the entirety of Apollyon. Please feel free to re-open if this issue still persists.
