### ISSUE TITLE
🐛[BUG][NPC/Quest/Mission/System/Combat/Launcher/Website]

### ISSUE THREAD

**Issue by zeshr** [HorizonFFXI/HorizonXI-Issues#642]
Launcher
**What does this bug affect?**
 Every time I try to log in,  character selection, I get the error "Transmission Error With Lobby Server". I was able to login fine before last night.

**Steps to Reproduce**

Open launcher
Click Play
Select Accept
Select character

**Expected behavior**
 Login successfully

**Screenshots**

**Setup Information**
 Windows 10

**Additional context**

**Comment by BayaniTenzen** [comment]
Please try asking for Help on the Main Discord in the Launcher Section
