### ISSUE TITLE
[BUG] [COMBAT] Summoning Magic Skillup

### ISSUE THREAD

**Issue by Raskia** [HorizonFFXI/HorizonXI-Issues#644]
I sent a ticket in first since I wasn’t sure if I should post 

Basically when using an aoe avatar buff such as shining ruby, you get a skillup for every person the buff targets as if you cast it individually on each person.

Kipling:
“Say in your ticket it you reported it and I told you to file the bug.”

**Comment by BayaniTenzen** [comment]
This is not a Bug - Goodluck with your Skillsups
