### ISSUE TITLE
🐛[BUG][System] Conquest supplies do not decay on conquest weekly reset

### ISSUE THREAD

**Issue by CriticalXI** [HorizonFFXI/HorizonXI-Issues#648]
Conquest supplies given by gate guards do not decay when it rolls into a new conquest week. This prevents players from picking up new supplies.

**Comment by paladindamarus** [comment]
What message is being given by the gate guards?

**Comment by Vandaloo** [comment]
Suffering the same issue. Hopefully it's not rude for me to add context on someone elses bug report.

For myself
Upon talking to a Sandorian gate guard with expired Ronfaure Supplies in KI you get the boilerplate response
![image](https://user-images.githubusercontent.com/121833850/210283997-eacc43fc-3abd-4a0b-8f13-cf4bbb19314b.png)

and then dialogue select pops up with:

Would you cast signet on me?
I want to spend my conquest points
I have some questions
Nothing sorry to bother you.
