### ISSUE TITLE
🐛[BUG][Quest] - In the Mood for Love

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#65]
**What does this bug affect?**
Unable to start quest while meeting the requirements.

**Steps to Reproduce**
Be on or past CoP 3-2 and speak with NPC.

**Expected behavior**
Quest should be given.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
N/A

**Comment by dallano** [comment]
fixed here: https://github.com/AirSkyBoat/AirSkyBoat/pull/413
