### ISSUE TITLE
🐛[BUG][System] Riding Chocobos in Qufim

### ISSUE THREAD

**Issue by AtrusFFXI** [HorizonFFXI/HorizonXI-Issues#651]
**What does this bug affect?**

This bug allowed me to ride a chocobo into Qufim Island.  You are not supposed to be able to use chocobos in Qufim.

**Steps to Reproduce**

I took a chocobo from Windurst to Jeuno, and I zoned into Port Jeuno while riding the chocobo (don't dismount).  When you zone into Jeuno, you will naturally not have your chocobo (though I did not check to see if the buff was active or not).  Then, I zoned out into Qufim and was immediately remounted on a chocobo and able to run around at high speeds avoiding aggro.

**Expected behavior**

I should not have been remounted after zoning into Qufim. The chocobo should have expired as soon as I zoned into Port Jeuno.

**Setup Information**

Windows 11 (/version doesn't seem to work?)

**Additional context**

I can't think of any additional context.  It seemed fairly straightforward.

**Comment by CriticalXI** [comment]
Fixed in AirSkyBoat/AirSkyBoat#2526
