### ISSUE TITLE
🐛[BUG]Launcher

### ISSUE THREAD

**Issue by viciousbreed** [HorizonFFXI/HorizonXI-Issues#652]
Is anyone else having issues logging in on a daily.. im on attempt number 20  the server is up but just fails to connect, sometimes it allows to select character other times the launcher doesnt get pass the dos window.. love this game would like to enjoy it please help error 3301

**Comment by viciousbreed** [comment]
up so 45mins of trying giving up today

**Comment by BayaniTenzen** [comment]
if you get into the game but can't connect through character select - try closing out the game and launcher and reconnecting

**Comment by viciousbreed** [comment]
thanks thats what i was doing with the attempts earlier guess im not the only one with issue atleast..

**Comment by Racingjaw** [comment]
A lot of other people having the same issues, including myself.

**Comment by PyrielDarkstar** [comment]
I have this problem..   click play and it fails to connect on the dos window and closes everything down..

**Comment by CriticalXI** [comment]
This was due to recent login server issues which have since been fixed
