### ISSUE TITLE
When I speak to NPC and AH 2-3x a day I get frozen and have to !unstuck 🐛[BUG][NPC/Quest/Mission/System/Combat/Launcher/Website]

### ISSUE THREAD

**Issue by Magnuss7654** [HorizonFFXI/HorizonXI-Issues#655]
**What does this bug affect?**

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by Magnuss7654** [comment]
Effects me

**Comment by HitGubz** [comment]
I have only ever got this bug after entering MH and interacting with Moogle, then interaction with NPC or AH freezes me. I also just relog which fixes it and it's quicker than unstuck, assuming you can get back in quickly.

**Comment by BayaniTenzen** [comment]
duplicate of #661
