### ISSUE TITLE
🐛[BUG] Quest Twinstone Bonding breaks for me after few turn ins

### ISSUE THREAD

**Issue by greena03** [HorizonFFXI/HorizonXI-Issues#659]
**What does this bug affect?**
Unable to repeat the repeatable turn in. 

**Steps to Reproduce**
Talk to Twinstone Bonding quest npc. I did the repeatable turn in about 4 or 5 times. Went back yesterday and talking to npc does not give correct dialogue even if I rezone. Trading the earring also does nothing.

**Expected behavior**
Zoning then talking to npc and trading earring should result in 900gil after first time completing. Unable to repeat at this point.

**Comment by BayaniTenzen** [comment]
Is this Still an Issue?

**Comment by Anode01** [comment]
Still an issue. I can’t turn in any at all, even the initial one. Quest is flagged, zoned after acquiring.

**Comment by greena03** [comment]
I still can't turn in or get the quest. Still broken.

**Comment by CorlaZodren** [comment]
Just tried this myself, and yes it is still a bug.
