### ISSUE TITLE
🐛[BUG][Quest] - A Chocobo's Tale

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#66]
What does this bug affect?
Unable to start quest while meeting the requirements. Wiki states Jeuno rep is required, but does not list what level. Attempted quest at Jeuno rep lvl 1/3/7/9 and still unable to start quest.

Steps to Reproduce
Be on or past CoP 3-2 and speak with NPC. 

Expected behavior
Quest should be given.

Screenshots
N/A

Setup Information
Version 30220802_3

Additional context
I was on CoP 5-1 when attempting this quest.

**Comment by dallano** [comment]
Fixed in: https://github.com/AirSkyBoat/AirSkyBoat/pull/435
