### ISSUE TITLE
🐛[BUG][System] Auction House - Sale Status Display Error

### ISSUE THREAD

**Issue by fabian-albertg** [HorizonFFXI/HorizonXI-Issues#662]
**What does this bug affect?**
AH Sales Status list of items
**Steps to Reproduce**
List items (10+), view list of items, list seems to display a different set of items each time viewed

**Expected behavior**
All items that player has for sale should be listed (with pages to scroll for 10+?)

**Screenshots**
![image](https://user-images.githubusercontent.com/73758307/210289540-12b2bcd6-c047-40b5-ba80-c09b059553c4.png)
![image](https://user-images.githubusercontent.com/73758307/210289556-fd0381be-b762-4f1a-97f9-16e225a03f50.png)

**Comment by BayaniTenzen** [comment]
This is a UI limitiation, every time you look at your status you check a chat message saying "Viewing page 1 of 12" or "Viewing Page 2 of 12" - you are tabbing between your two sales pages
