### ISSUE TITLE
🐛[BUG][NPC/Quest] A Flash in the pan

### ISSUE THREAD

**Issue by Ausaric** [HorizonFFXI/HorizonXI-Issues#665]
[BUG][NPC/Quest] A Flash in the pan
**What does this bug affect?**
The NPC Aquillina for the quest a flash in the pan will accept immediate consecutive turn ins of 4 flint stones. According to ffxi wiki, there should be a 15 earth minute wait before this quest is repeatable

**Steps to Reproduce**
Go to bastok markets, trade 4 flint stones to NPC Aquillina, and then try immediately again to see if she will accept 4 more

**Expected behavior**
The NPC should deny additional turn ins until 15 minutes have passed

**Comment by hookstar** [comment]
Was hotfixed on Dec 17, 2022
