### ISSUE TITLE
[NPC] Patient Wheel is not accepting  5 Eastern Gems as part of Chasing Dreams 

### ISSUE THREAD

**Issue by JohnnyGerbs** [HorizonFFXI/HorizonXI-Issues#667]
While doing the quest Chasing Dreams, you are tasked with trading 5 eastern gems to the NPC Patient Wheel in Port Bastok. However, attempting to trade him 5 eastern gems yields no results.

**Comment by TiberonKalkaz** [comment]
Just noting that you do not have to visit each Giant Clam in K Tunnel.
The first one you touch will fill the canteen entirely
![image](https://user-images.githubusercontent.com/105882290/210451381-fc2625e3-3109-47ef-9ab0-c9d351050e8d.png)

**Comment by JohnnyGerbs** [comment]
> Just noting that you do not have to visit each Giant Clam in K Tunnel.
> The first one you touch will fill the canteen entirely
> ![image](https://user-images.githubusercontent.com/105882290/210451381-fc2625e3-3109-47ef-9ab0-c9d351050e8d.png)

Yeah, I thought this might have happened. I visited every clam but only the first one gave me a notice that it was interacted with. Wasn't entirely sure if it was a bug.

**Comment by TiberonKalkaz** [comment]
The CS triggered by Kagetora (332) takes the Eastern Gem item ID in to display during the CS, however it appears to be a blank

![image](https://user-images.githubusercontent.com/105882290/210463922-073bace0-f3fd-4cde-9e74-19ba62a9875e.png)


Likely why the trade wont work either - its trying to make sure you trade 5 nothings.

Current globals/items.lua has the eastern_gem definition - https://github.com/AirSkyBoat/AirSkyBoat/blob/staging/scripts/globals/items.lua#L636
Quest file has the xi.items require

Patient Wheels CS has the same issue.  Despite the code passing in the item to the CS, its blank
![image](https://user-images.githubusercontent.com/105882290/210464080-5694d42d-70c6-4e01-94fd-111c66739273.png)

**Comment by TiberonKalkaz** [comment]
This is NOT an issue on the latest ASB code base - so there might be something off on live or in an era+ application
(I'd look to see if live has the updated globals/items.lua)

Local:
![image](https://user-images.githubusercontent.com/105882290/210466866-cdf4b8e6-e735-4f88-a0a5-16380b0fde18.png)

**Comment by TiberonKalkaz** [comment]
Reproduced locally by commenting out the eastern gem from the global/items.lua

![image](https://user-images.githubusercontent.com/105882290/210467558-4499bd96-bfa5-4645-9161-1e6071103b55.png)

https://github.com/AirSkyBoat/AirSkyBoat/blob/staging/scripts/globals/items.lua#L636

**Comment by TiberonKalkaz** [comment]
Now fixed on live
![image](https://user-images.githubusercontent.com/105882290/211074463-edf83b01-6aef-4178-b992-b979f139e413.png)

**Comment by TiberonKalkaz** [comment]
(at least that step - will continue forward)

**Comment by TiberonKalkaz** [comment]
Quest completes correctly - can close this out
