### ISSUE TITLE
🐛[BUG][System] Carpenter's landing barge from south landing to north landing took me to central landing instead.

### ISSUE THREAD

**Issue by JuffuJuffu** [HorizonFFXI/HorizonXI-Issues#668]
**What does this bug affect?**
Barge route from south to north, does not take you to north landing, but instead drops you off at Central Landing. During the travel, the npc who tells time of arrival said it will be arriving in central landing also. I took the 9:00 barge from south, even the NM that only spawns on this path popped, so i assume i was in the "right barge". Also the NPC in port announced it was the barge from south to north.

**Steps to Reproduce**
Step on barge leaving at 9:00 from south landing to north landing. See where you are dropped off to.

**Expected behavior**
Barge should drop you off at North Landing

**Screenshots**

**Setup Information**
Cant check version, unable to log in. Shouldve been most recent dated. 

**Additional context**

**Comment by BayaniTenzen** [comment]
linked to #660
