### ISSUE TITLE
🐛[BUG][NPC/System] Purchasing a chocobo ride occasionally dumps you outside town without a ride

### ISSUE THREAD

**Issue by Rynzer** [HorizonFFXI/HorizonXI-Issues#669]
**What does this bug affect?**
This bug is experienced occasionally (once for me personally) when purchasing a chocobo ride from a stable in town. After purchasing the chocobo, the player is deposited outside of town, but is not riding a chocobo. The gil used to hire the chocobo is still consumed.

**Steps to Reproduce**
1. Hire chocobo at stable.
2. Automatically zone out of town.
3. Have no chocobo to ride upon loading next zone.

**Expected behavior**
The player should have rideable chocobo after purchasing from the stable.

**Screenshots**
These are not my screenshots, they are from other users experiencing the issue. I was not able to get a screenshot for myself as I immediately attempted to zone back into town and got disconnected from a black loading screen.

https://imgur.com/xcdPQpt
https://imgur.com/CeWEGOC

**Additional context**
Unsure if related, but as mentioned in Screenshots, I immediately received a black loading screen disconnect after my chocobo ride failed. After logging back into the game I was floating in the sky in Windurst Woods at location E-22, which should be unreachable.

**Comment by SauronMX** [comment]
Confirming issue with my own experience last night.

Pick up chocobo at port jeuno stables, charged 1k gil and end up on my feet when zoning to Sauromuge. Character Sauron - Tarutaru

**Comment by CriticalXI** [comment]
Caused by the rampant black screens that was solved recently.
