### ISSUE TITLE
🐛[BUG] Totentanz

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#67]
**What does this bug affect?**

Boss is not immune to sleep, lullaby,  or bind. Blm/whm was able to land silence on ads that should be highly resistant to lullaby, bind, and silence. Cadaver warriors aren't tping with the boss. Not cleared due to lack of testers. Just getting all of the mechanics and immunities checked.
**Steps to Reproduce**

Give the boss tp with Cadaver Wars attacking you. The wars dont tp.
**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by dallano** [comment]
Fixes in PR: https://github.com/AirSkyBoat/AirSkyBoat/pull/376
