### ISSUE TITLE
🐛[BUG][Quest] Glyph Hanger

### ISSUE THREAD

**Issue by WelehoRogan** [HorizonFFXI/HorizonXI-Issues#670]
**What does this bug affect?**
Glyph Hanger Quest in Windurst does not award XP

**Steps to Reproduce**
Completing Glyph Hanger does not award 2000 XP, some other map quests award XP

**Expected behavior**
XP reward from quest

**Additional context**
Not sure if map quests on HXI are supposed to give XP or not, some of them give XP and others do not.

**Comment by BayaniTenzen** [comment]
Which other Map Quests are rewarding EXP? - I think that amount of EXP was a later addition to the game in Abyssea/Seekers but cannot find definitive information.

**Comment by WelehoRogan** [comment]
https://ffxiclopedia.fandom.com/wiki/Exit_the_Gambler I believe atleast this quest was giving XP

**Comment by BayaniTenzen** [comment]
I've checked a couple of other map quests and they are all set to reward zero exp (including "Exit the Gambler")
