### ISSUE TITLE
[BUG] [QUEST] Tenshodo Membership needs a full inventory check before giving item

### ISSUE THREAD

**Issue by Wyrdling** [HorizonFFXI/HorizonXI-Issues#671]
During the quest Tenshodo Membership, speaking to Ghebi Damomohe with the Tenshodo application form key item triggered quest completion- however my inventory was full and I could not receive the Tenshodo Invitation item. 

I cleared my inventory but could not trigger the quest completion again because the key item Tenshodo application form was no longer in my key items. The quest is still current in my quest log.
![Uploading Wyrdling_2023.01.02_144902.png…]()

**Comment by hookstar** [comment]
@Wyrdling, was this issue resolved?
