### ISSUE TITLE
🐛[BUG]Combat - Martial Arts trait / Monk is setting all H2H speed to base (7 seconds between attack rounds) regardless of delay on weapon. 

### ISSUE THREAD

**Issue by HitGubz** [HorizonFFXI/HorizonXI-Issues#672]
**What does this bug affect?**

Have Martial Arts trait active
Attack something with no H2H Weapon or +0 Delay Weapon
Attack something with H2H Weapon with + Delay
**Expected behavior**

Without a Weapon or a Delay +0 weapon attack speed should be base (480 + Martial Arts bonus) 
With a Weapon Delay +X should be added to the attack speed. 
Test Examples: 
MNK/THF - No weapon = 7s between attack rounds 
MNK/THF - +33 Delay weapon = 7s between attack rounds 
MNK/THF +66 Delay weapons = 7s between attack rounds 
WAR/THF +33 Delay weapon = 11s between attack rounds 
WAR/MNK +33 Delay weapon = 7s between attack rounds 
WAR/MNK No weapon = 6s between attack rounds 

**Setup Information**

Windows 11
**Additional context**

Needs more thorough testing as using the chatlog timestamp isn't by 0.x seconds, but so far it seems as if Martial Arts trait is setting H2H speed to base regardless of weapon used, regardless of whether it's monk main or monk sub job. 
If this is actually happening and it's not me testing incorrectly, then it renders purple / brown belt meaningless other than as a weapon skill piece. Also no point using any Cesti, Cross Counters would arguably be better than Destroyers etc.

**Comment by panicstevenson** [comment]
Hey there @HitGubz, thanks for the report. I have some data back for you that I'd love if you could look at. I've never played a hand-to-hand job nor did I code anything related to weapon delay, so please draw your own conclusions here as to me this looks correct but I'm not an expert:

MNK1 (bare) = 6667 milliseconds, 6.667 seconds, 400 / 60
MNK75 (bare) = 5000 milliseconds, 5 seconds, 300 / 60
MNK75 (+48 delay Cesti) = 5800 milliseconds, 5.8 seconds, 348 / 60
MNK75 (bare, +12% Haste Black Belt) = 4400 milliseconds, 4.4 seconds, 264 / 60

**Comment by HitGubz** [comment]
Amazing thank you @panicstevenson , data looks good. Was coming back to this anyway to say it had seemed to have fixed itself over time (or been fixed) Even using my chat log I can see the difference between using +48 delay Boreas Cesti and +91 Tactitician Magician's Hooks. (1 second difference between attack rounds).
