### ISSUE TITLE
🐛[BUG][System] Bokuto isn't craftable by alchemists

### ISSUE THREAD

**Issue by relliko** [HorizonFFXI/HorizonXI-Issues#674]
**What does this bug affect?**

Players attempting to craft Bokuto are unable to execute the synth.

**Steps to Reproduce**

Try to synth a Bokuto on Horizon, it doesn't work.

**Expected behavior**

Synth should be doable because it existed in era.

**Screenshots**

**Setup Information**

**Additional context**

Similar crafted katanas released around the same time such as Bosuto and Yoto should also be craftable, but I'm not sure that they are.

**Comment by CriticalXI** [comment]
Fixed in AirSkyBoat/AirSkyBoat#2500
