### ISSUE TITLE
🐛[BUG][Combat] Sneak Attack

### ISSUE THREAD

**Issue by 3ternalkarma** [HorizonFFXI/HorizonXI-Issues#675]
**What does this bug affect?**
Normal Critical hits override Sneak attack 

**Steps to Reproduce**
normal critical when you hit with Sneak attack

**Expected behavior**
Sneak Attack damage applied

**Comment by HorizonPotato** [comment]
I have this happen on unclaimed mobs standing completely still at least 10~+ times in my typical 3-4 hour farming sessions.  And it happens at least a dozen times per EXP party I'm in on mobs I'm definitely behind.   Definitely happening and its happening /often/ enough to be a nuisance. 

Not sure how I can provide evidence short of a video though for confirmation/verification, but its certainly such a common bug every THF ive spoken too has encountered it multiple times.

**Comment by TracentEden** [comment]
Fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2523
