### ISSUE TITLE
🐛[BUG] Age spells only hitting one target.

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#68]
**What does this bug affect?**

Title
**Steps to Reproduce**

Nuke a mob with abother mob next to it. Aga only hits the mob you target.
**Expected behavior**

Agas should hit all nearby targets. 
**Screenshots**

**Setup Information**

**Additional context**

**Comment by Squinkerdoodle** [comment]
Happening with Curaga and Protectra / Shellra as well.

**Comment by CriticalXI** [comment]
Fixed in https://github.com/AirSkyBoat/AirSkyBoat/pull/378
