### ISSUE TITLE
🐛[BUG][Combat] Mob counter is greatly increased dmg

### ISSUE THREAD

**Issue by TiberonKalkaz** [HorizonFFXI/HorizonXI-Issues#685]
**What does this bug affect?**
Combat, against mnk mobs

**Steps to Reproduce**
Fight mnk mobs
Be a level 13ish war w/ GAX fighting mandies in bubu penn.
Full scale set, and protect.
Normal hits can be as low as 8 or 9 dmg taken by the warrior.
Counters will hit for 40-60.  
Not hidden crit counters - straight counters.

**Expected behavior**
Cant imagine a 5x+ dmg rate is expected on counters by mobs.

**Screenshots**
I did not catch a screen shot of the countering I took leveling war. but here is a similar situation
![image](https://user-images.githubusercontent.com/105882290/210481777-1b0147f1-b97a-4ea6-9229-e7ffe2cec0da.png)
Votary vs 97 def, 1 hand axe war

**Comment by TiberonKalkaz** [comment]
Another example.
Level 45 Orcish Gladiator
Level 48 Warrior 190 defense, 144 Attack, 41+1 vit, 50+8 str

Note counter dmg is ~3x a normal hit.

![Counter](https://user-images.githubusercontent.com/105882290/210805347-c1eb5983-c496-4f17-95d1-6dfc79ffe152.PNG)

**Comment by CriticalXI** [comment]
Fixed in AirSkyBoat/AirSkyBoat#2552
