### ISSUE TITLE
🐛[BUG][System/Combat] Antlion Familiar Ready Bug

### ISSUE THREAD

**Issue by Bojangles123123** [HorizonFFXI/HorizonXI-Issues#686]
Neither Sandpit or Sandblast appear to be functioning. 
Consumes charge on use, no animation and seemingly no blind as I waited for long periods of time and didn't see it ever wear from mobs.

**Steps to Reproduce**

Just throw it at a mob and use either of the two ^^

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by ThoseWhoFight** [comment]
Posted this in the Discord bug report as well, but noticed that: 

Ready moves Sandpit and Sandblast also have their charge costs switched around in Horizon currently. BG wiki lists Sandpit costing 1 and Sandblast costing 2, but on Horizon they're reversed atm.
The tooltip text states the correct values, but they're swapped atm when you actually use the skills.
https://www.bg-wiki.com/ffxi/Antica_Broth

![image](https://user-images.githubusercontent.com/37572397/210675119-09eb52df-14b6-4149-9327-44080cd665b5.png)

**Comment by ThoseWhoFight** [comment]
One more issue, possibly doesn't have double attack trait despite being Warrior? Been keeping an eye out for it, but don't think I've seen it DA once.

**Comment by TracentEden** [comment]
The abilities were fixed in https://github.com/AirSkyBoat/AirSkyBoat/pull/2564

**Comment by ThoseWhoFight** [comment]
@TracentEden 
Additionally, noticed in the case of Chopsuey Chucky(possibly NQ too?) only lasts 30 minutes before depopping, whereas others all last 1 hour as far as I can tell.
