### ISSUE TITLE
🐛[BUG][NPC - Incorrect spawn of 'Jelly' at G-11 Ordelles Caves. Should be a fourth Stroper Chyme. 

### ISSUE THREAD

**Issue by HitGubz** [HorizonFFXI/HorizonXI-Issues#689]
**What does this bug affect?**

Jelly is spawning at G-11 instead of Stroper Chyme (western drop down) 
**Steps to Reproduce**

X
**Expected behavior**

Stroper Chyme should pop here not a jelly 
**Screenshots**

https://ffxiclopedia.fandom.com/wiki/Stroper_Chyme
**Setup Information**

Windows 11
**Additional context**

**Comment by CriticalXI** [comment]
We have an extremely detailed list of all zones in the game back during CoP era. According to that book, there is no Stroper Chyme at that location.

![image](https://user-images.githubusercontent.com/48370698/218180921-6b7014c4-ac37-4b98-b775-82a8a2e33dad.png)
![image](https://user-images.githubusercontent.com/48370698/218180938-c8cb665b-96d6-4589-a6d4-d50b6210b44f.png)

**Comment by HitGubz** [comment]
Interesting, thank you for this. Admittedly I don’t remember ever farming these in retail so my experience is based on Eden and Wiki. 
I will scout around the forums though just in case, it’s a nice chilled spot that I miss while working :( 


Sent from Yahoo Mail for iPhone


On Friday, February 10, 2023, 7:32 pm, Critical ***@***.***> wrote:




We have an extremely detailed list of all zones in the game back during CoP era. According to that book, there is no Stroper Chyme at that location.

**Comment by HitGubz** [comment]
Also where is that info from? Never seen it before. 


Sent from Yahoo Mail for iPhone


On Friday, February 10, 2023, 8:22 pm, Cameron Button ***@***.***> wrote:

Interesting, thank you for this. Admittedly I don’t remember ever farming these in retail so my experience is based on Eden and Wiki. 
I will scout around the forums though just in case, it’s a nice chilled spot that I miss while working :( 


Sent from Yahoo Mail for iPhone


On Friday, February 10, 2023, 7:32 pm, Critical ***@***.***> wrote:




We have an extremely detailed list of all zones in the game back during CoP era. According to that book, there is no Stroper Chyme at that location.
