### ISSUE TITLE
🐛[BUG] Bionic bug is non existent

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#69]
**What does this bug affect?**

:(
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by dallano** [comment]
Cannot replicate this in my local build. Are you giving yourself lever Key item instead of gate dial?

**Comment by Squinkerdoodle** [comment]
Yes. We gave ourselves the [Shaft 2716 Operating Lever](https://ffxiclopedia.fandom.com/wiki/Shaft_2716_Operating_Lever)

**Comment by Squinkerdoodle** [comment]
It's the same issue that I'm getting with the ENM Automaton Assault.
