### ISSUE TITLE
🐛[BUG][Combat] DRK Goblin absorb spells extremely potent over 60+ stats being absorbed

### ISSUE THREAD

**Issue by techno13337** [HorizonFFXI/HorizonXI-Issues#691]
DRK Goblin Absorb spells like "Absorb-DEX" etc are highly potent. Example in the attached picture below. I don't know how much it goes to but it seemed to be draining all my stat down to 1. Example in the picture is Absorb-DEX doing -63 DEX putting me to 1 DEX stat. Same with VIT and INT but those were casted earlier so the effects were scaling down already.

I don't know if this affects all DRK goblins but the ones I was fighting were in Beaucedine Glacier next to the Nue NM spawn.

I posted a bug report on Discord:

"I've been fighting the DRK goblins in Beaucedine and their absorb spells seem to be incredibly powerful. Not sure if this is intended or not? Seems a bit strong for a single spell? I also had VIT 52 -51 in the picture right before I took the attached picture but some time had passed already.

https://cdn.discordapp.com/attachments/1060010981448749166/1060010981759131758/image.png

"

-- I'm "Weissie" on the Discord server

**Comment by techno13337** [comment]
This also seems to be happening with the DRK Orcs in Davoi. Just had my STR be drained to 1. Probably is monster spell related rather than just a specific mob problem.

**Comment by siknoz** [comment]
Trying to bump this again, Mob 16 levels under me (Me: 59 mob: 43) took all of my STR, screenshot below:

![image](https://user-images.githubusercontent.com/78240569/213969775-0d6a93f8-a66a-493f-8d2f-39970a45ed28.png)

**Comment by CriticalXI** [comment]
Fixed in AirSkyBoat/AirSkyBoat#2513
