### ISSUE TITLE
🐛[BUG][System/Gameplay] Losing Extra Picks?

### ISSUE THREAD

**Issue by yueamyen** [HorizonFFXI/HorizonXI-Issues#694]
**What does this bug affect?** 
Mining. Losing picks even though not getting "pickaxe breaks" notification. I also would randomly lose multiple picks randomly when I was given a "Break" notice, I lost about 15 picks out of 5 stacks.

**Steps to Reproduce**
Seems to be completely random. Have macro set up as: /targetnpc (next line) /item Pickaxe <t>
Took out the line "/Targetnpc" to see if it made a difference but it did not.

**Expected behavior**
You should not lose pickaxes on a successful dig. Should only be losing 1 pickaxe when given "break" notice.

**Screenshots**
N/A

**Setup Information**
PC windows 11

**Additional context**
This was in Zeruhn Mines off bastok. Was also noticed by other miners in the area. I hope they put in tickets.

**Comment by yueamyen** [comment]
No i bought 5 stacks of exactly 12 picks each. I did not click the count to 99.

**Comment by CriticalXI** [comment]
I've mined very regularly since launch and I have not heard anyone else experiencing this. Feel free to re-open this though if you have proof of points taking away more than one pickaxe.
