### ISSUE TITLE
🐛[BUG][Quest] Onion Rings

### ISSUE THREAD

**Issue by AinhoaRR** [HorizonFFXI/HorizonXI-Issues#696]
Quest

**What does this bug affect?**
Can't receive rewards for the quest "Onion Rings", specifically Bouncer Club reward.

**Steps to Reproduce**
I first did Windurst Mission 3-1, obtained the Old Ring, then accepted the Onion Ring quest. Completed the quest immediately and got the cutscene. After zoning, and waiting for several (earth) days, I still can't get the reward when talking to the quest NPC. 

**Expected behavior**
NPC that issued the quest should reward the Bouncer Club for completing the quest.

**Comment by BayaniTenzen** [comment]
https://ffxiclopedia.fandom.com/wiki/Onion_Rings

**Comment by hookstar** [comment]
Player name?

**Comment by AinhoaRR** [comment]
> Player name?

Nain

**Comment by AinhoaRR** [comment]
> Player name?

Nain
