### ISSUE TITLE
🐛[BUG][Mission/System] Lost for Words Windurst Mission 2-1 No Fossil Key Item Given

### ISSUE THREAD

**Issue by Birdboy1985** [HorizonFFXI/HorizonXI-Issues#698]
**What does this bug affect?**
 Obtaining the Fossil key item to advance through the mission to complete.

**Steps to Reproduce**
 Followed instructions on the HorizonXI Wiki page for Windurst mission 2-1 and checked all the "Fossil Rock" points in the Maze of Shakhrami zone. The points all gave the message of "It is just a rock. There is no need to investigate it." and no key item has been received from either of them.

**Expected behavior**
 One of the "Fossil Rock" points should give the key item "Lapis Coral".

**Screenshots**

**Setup Information**
 HorizonXI 1.1.3 Launcher version

**Additional context**
 I have tried multiple times and died from mobs that aggro by sight and I can't afford to buy the silent oils and prism powders due to lack of gil currency.

**Comment by BayaniTenzen** [comment]
PR Pending to fix this quest on next Maintenance
