### ISSUE TITLE
🐛[BUG][Quest] The Circle of Time (BRD AF Body) - Wait time for Perennial Snow not correct

### ISSUE THREAD

**Issue by KiplingFFXI** [HorizonFFXI/HorizonXI-Issues#7]
**What does this bug affect?**

The wait time for the Perennial Snow in Xarcabard is supposed to be the next game day, but it let me dig it up after just a few minutes and before the game day changed.

**Steps to Reproduce**

Do the quest but you can obtain it immediately instead of waiting for the next game day.

**Expected behavior**

It should be a game day wait after burying the item.

**Screenshots**

N/A

**Setup Information**

N/A - Older report

**Additional context**

N/A

**Comment by dallano** [comment]
Fixed here! :) https://github.com/AirSkyBoat/AirSkyBoat/pull/408
