### ISSUE TITLE
[BUG] Wind Pillar in Bearclaw Pinnacle not working without GM tag

### ISSUE THREAD

**Issue by Kyne09** [HorizonFFXI/HorizonXI-Issues#70]
Interacting with the Wind Pillar does nothing.  By using !togglegm you can access to BCNMs tied to it, but without it interacting with the pillar does nothing.

**Comment by The-Aerec** [comment]
which one? There are technically three separate wind pillars. Some BCNMs / ENMs only work at certain ones. Make sure not to assume they are all the same as that is pserver jank

**Comment by Kyne09** [comment]
Honestly not sure which one I didn't think to grab an NPC ID but it's
whichever one that !zone (Bearclaw Pinnacle) command takes you to.

**Comment by The-Aerec** [comment]
Yes this might not be the proper one! As each entrance has a different wind pillar that is now associated properly with their BCNMs

**Comment by Kyne09** [comment]
Gotcha.  If the pillar is tied to a specific BCNM I'm not sure which one it
is because you you couldn't interact with it at all without the GM tag or
activate any BCNM whatsoever.

**Comment by The-Aerec** [comment]
Probably the wrong one then. I'd check the others

**Comment by Kyne09** [comment]
Closed
