### ISSUE TITLE
🐛[BUG][Combat] Whm not on Moonlight WS list

### ISSUE THREAD

**Issue by SpaggiG** [HorizonFFXI/HorizonXI-Issues#700]
**What does this bug affect?**

Moonlight should be usable by whm without one of the other jobs set as support job.

**Steps to Reproduce**

get 125 club skill and moonlight will not appear in ws list unless a support job that also should have access is set such as /war or /pld

**Expected behavior**

WHM should be able to use Moonlight

**Comment by CriticalXI** [comment]
Fixed in HorizonFFXI/HorizonXI#564
