### ISSUE TITLE
🐛[BUG][Quest] For the Birds (Jaguar Mantle Quest)

### ISSUE THREAD

**Issue by captainocd** [HorizonFFXI/HorizonXI-Issues#703]
[Quest] For the Birds

1. I completed the fight with the 4 NM Quadavs after speaking to Ge'Fhu Yagudoeye. Normal.

2. I spoke to Ge'Fhu a second time and triggered the cutscene featuring Zeelozok. Normal.

3. I then went back to Koblakiq in Oldton Movalpolos for my reward and he's instead directing me back to Beadeaux as though I never completed the fight and didn't watch the cutscene. Abnormal.

**Comment by relliko** [comment]
Had the same issue, confirmed it's the same behavior on vanilla ASB as well.
