### ISSUE TITLE
🐛[BUG][Quest] Trading a Garnet to the fire Cermet Headstone did not give an Opo-Opo necklace after defeating the NMs. 

### ISSUE THREAD

**Issue by ThrisStraizo** [HorizonFFXI/HorizonXI-Issues#704]
**What does this bug affect?**

Admittedly a GM had to give us the key item since that part didn't work either.  After killing [Carthi](https://ffxiclopedia.fandom.com/wiki/Carthi) and [Tipha](https://ffxiclopedia.fandom.com/wiki/Tipha) trading a garnet to the headstone didn't yield and Opo-Opo Necklace

**Steps to Reproduce**

Be on ZM5.  Pop [Carthi](https://ffxiclopedia.fandom.com/wiki/Carthi) and [Tipha](https://ffxiclopedia.fandom.com/wiki/Tipha) by interacting with the headstone.  Receive key item from interacting with the headstone again (This part didn't work so a GM had to give us key item.)  Trade Garnet to headstone.

**Expected behavior**

It gives you Opo-Opo Necklace.

**Screenshots**

![image](https://user-images.githubusercontent.com/45871917/210855926-8501d363-8bed-4058-b118-5f06b7c1dae0.png)

**Setup Information**

version 30221103_1

**Additional context**

**Comment by hookstar** [comment]
Were you able to get the one in Cape Terrigan?

**Comment by hookstar** [comment]
I was not able to replicate. Can you verify you have the quest in outlands "Wrath of the Opo-Opo"? If not - please contact a GM and put a ticket in with them there. Have them @ me on there.

Thanks.
