### ISSUE TITLE
🐛[BUG][BRD AF Weapon Painful Memory]

### ISSUE THREAD

**Issue by Bitterbuffaloh** [HorizonFFXI/HorizonXI-Issues#705]
I defeated Trios, then examined the "Waters of Oblivion" again and another Trios spawned instead of receiving the cut scene
![Trios 1](https://user-images.githubusercontent.com/122049325/210857153-36d1db60-1b48-41cc-9d54-1d3117c23092.PNG)
.

**Comment by CriticalXI** [comment]
Need more information about what is causing this as I know BRDs are completing their AF.

**Comment by CriticalXI** [comment]
Closed out due to no response
