### ISSUE TITLE
Purgonorgo Isle Jagils

### ISSUE THREAD

**Issue by lostidiot1** [HorizonFFXI/HorizonXI-Issues#706]
Some or possibly even all of the jagils on Purgonorgo Isle are flagged as aggressive monsters. According to most websites and their comments this should not be the case.  While a relatively minor issue it is a rather unpleasant surprise for anybody fishing or clamming.

**Comment by TracentEden** [comment]
Fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2621
