### ISSUE TITLE
🐛[BUG][Quest: A Timely Visit]

### ISSUE THREAD

**Issue by ciradan** [HorizonFFXI/HorizonXI-Issues#708]
**What does this bug affect?**
Everything works up to the NM fights, but after fighting them the CS won't trigger when examining the ??? again.

Tried the following:
1: killed the Fomor first (Guillermo B Fourma or whatever), then the Skelly Esquire: clicking the ??? again just says a power blocks it. Clicking it a few times will make the NMs respawn. No zoning during this fight.
2: Zoned because of respawn. Upon entering Jugner again the Skelly was gone, killed the Fomor, clicked ??? but the same as in 1 happened. Zone during this fight.
3: Zoned again, returned, both were still waiting for me, killed the Skelly first then the Fomor, glicked the ??? but it said it's blocked (no spawn because daytime). zoned during this fight.
4: Waited till nighttime again, spawned them, now killed Skelly first then Fomor, clicked the ???, same as in 1 happened. No zoning during this fight.

Still tried to talk to Phill and the Questgiver, but no reaction apart their standard dialogue.

**Expected behavior**
CS starting when clicking the ??? after the NMs are dead.

**Comment by BayaniTenzen** [comment]
https://cdn.discordapp.com/attachments/1060578090809573516/1060643178992119898/Ciradan_2023.01.05_161000.png
https://cdn.discordapp.com/attachments/1060578090809573516/1060643179692564600/Ciradan_2023.01.05_161026.png
https://cdn.discordapp.com/attachments/1060578090809573516/1060643180451725374/Ciradan_2023.01.05_161043.png
https://cdn.discordapp.com/attachments/1060578090809573516/1060643181005381693/Ciradan_2023.01.05_161048.png
https://cdn.discordapp.com/attachments/1060578090809573516/1060643181642907648/Ciradan_2023.01.05_161103.png
https://cdn.discordapp.com/attachments/1060578090809573516/1060643182116872312/Ciradan_2023.01.05_162649.png
https://cdn.discordapp.com/attachments/1060578090809573516/1060643182804729926/Ciradan_2023.01.05_165203.png
https://cdn.discordapp.com/attachments/1060578090809573516/1060643183610048574/Ciradan_2023.01.05_165247.png
https://cdn.discordapp.com/attachments/1060578090809573516/1060643184503431198/Ciradan_2023.01.05_165252.png
https://cdn.discordapp.com/attachments/1060578090809573516/1060643185275175073/Ciradan_2023.01.05_165258.png

**Comment by ciradan** [comment]
Not sure how important it is, but the .lua inside "/< zone >/mobs" also has the same spelling error.

**Comment by BayaniTenzen** [comment]
> 

i believe that was part of the fix hookstar already implemented!

**Comment by hookstar** [comment]
The OP was right, I didn't push the zone/mob/ name also. Would still function just now it uses 2hr 😈

**Comment by ciradan** [comment]
shouldn't have said anything >.>
