### ISSUE TITLE
🐛[BUG] Holy Cow

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#71]
**What does this bug affect?**

Holy Cow seems mostly fine ,but the immunity thing seems wrong. Sometimes when it switches immunitiy the damage gats reduced heavily instead of being completely immune. 
**Steps to Reproduce**

Wait until it pops magic immunitiy. Cast a damage spell. Spell sometimes does like 23 damage instead of 0.
**Expected behavior**

All spells should do 0 damage in magic immune mode.
**Screenshots**

**Setup Information**

**Additional context**

**Comment by Squinkerdoodle** [comment]
Just wanted to add to this that some of Moogle's tier 3 nukes were doing some (small) damage during the magic immunity and my tier 4 nukes as a blm were doing 20-30 damage during the magic immunity. Not sure if it's due to high elemental skill or not.

**Comment by dallano** [comment]
I don't think he's supposed to be entirely immune to magic or physical damage when he switches his resistances. I'll look further into this.

**Comment by dallano** [comment]
https://github.com/AirSkyBoat/AirSkyBoat/pull/376
