### ISSUE TITLE
🐛[BUG][Combat] Tachi: Gekko

### ISSUE THREAD

**Issue by bigggele** [HorizonFFXI/HorizonXI-Issues#711]
**What does this bug affect?**
Learning Gekko at 200 GK Skill.

**Steps to Reproduce**
Get 200 GK Skill.

**Expected behavior**
You are suppose to only get Tachi: Yukikaze at 200 skill.

**Screenshots**
![ERA+](https://user-images.githubusercontent.com/121577008/210892869-3132ed26-6acd-437c-83d7-2ac26ac86ff8.PNG)

**Setup Information**
version 30221103_1

**Comment by CriticalXI** [comment]
Fixed in HorizonFFXI/HorizonXI#563
