### ISSUE TITLE
🐛[BUG][Launcher]

### ISSUE THREAD

**Issue by jamesbradleym** [HorizonFFXI/HorizonXI-Issues#713]
**What does this bug affect?**

Error indicates missing prereqs.zip file after downloading the launcher from horizionxi.com on windows 11 (via parallels Mac M1 Ventura) 
**Steps to Reproduce**

Download from horizionxi.com and click install after opening launcher. May occur after uninstalling launcher previously.
**Expected behavior**

Launcher should begin installing horizonxi
**Screenshots**

**Setup Information**

**Additional context**

**Comment by jamesbradleym** [comment]
<img width="1281" alt="Screenshot 2023-01-05 at 6 28 07 PM" src="https://user-images.githubusercontent.com/33179100/210899500-289b7725-3e76-4c61-8c6f-09bb0fe0e18f.png">

**Comment by Flam9** [comment]
Sorry, not easy for me to reproduce Windows 11 on parallels. Try the things listed out in this thread: https://discord.com/channels/933423693848260678/1062224406216179804/1062224406216179804
A few people in discord have figured it out on Windows 11, just gotta use the Discord search
