### ISSUE TITLE
🐛[BUG][System] Will-O-Wisp Drop Bat Wings

### ISSUE THREAD

**Issue by pklwsl** [HorizonFFXI/HorizonXI-Issues#714]
**What does this bug affect?**
Will-o-the-Wisp in the Inner Horutoto Ruins near Three Mage Gate dropped Bat Wings.

**Steps to Reproduce**
Kill Bombs :)

**Expected behavior**
No Bat Wings

**Screenshots**
![batwing-bomb](https://user-images.githubusercontent.com/37595201/210901610-03e1b0a9-502e-44fb-818c-7fc61beaed48.PNG)

**Additional context**
I'm not sure if bomb arms are in the loot pool here. Maybe bat wings are in place of bomb arms by mistake?

**Comment by CriticalXI** [comment]
Fixed in AirSkyBoat/AirSkyBoat#2511
