### ISSUE TITLE
🐛[BUG] Follow the White Rabbit

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#72]
**What does this bug affect?**
At the beginning of the fight, only the Bearclaw Rabbit is visible in the arena. 5 Bearclaw Leveret mobs spawned when the Rabbit reached around 20% HP. The Bearclaw Leveret seem immune to charm as intended, however I was able to sleep both with Sleep and Lullaby (no godmode active with these spells). Additionally killing one Bearclaw Leveret did not despawn any of the others. Lastly none of the 5 Bearclaw Leveret used blood weapon.

**Expected behavior**
The Bearclaw Leveret should be visible in the arena behind the Rabbit far enough to where you can pull just the rabbit. When the rabbit is around 60% HP the 5 Bearclaw Leveret should move in and link. The Bearclaw Leveret should be immune to both sleep magic and lullaby. Wiki states "Killing a random [Bearclaw Leveret](https://ffxiclopedia.fandom.com/wiki/Bearclaw_Leveret) will trigger a despawn of the others." not sure if it's a specific one or just can happen randomly, or on some occasions not at all if you kill the wrong ones first. Bearclaw Leveret should be able to use Blood Weapon.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
Unable to enter fight without GM flag. Clicking on Wind Pillar in Bearclaw Pinnacle does nothing, even when you have the key item.

**Comment by dallano** [comment]
I believe this all very much works as intended.  However I will look into captures again to confirm that these are the proper behaviors. 
In the captures I based this from:
- Leveret is only mob initially
- Adds spawn in 60 seconds after engaging
- I'll double check the use of blood weapon. But I don't believe I ever witnessed this behaviour in captures.
- I'll double check the mob resistances
- And yes, all rabbits should despawn if the appropriate one is killed.

**Comment by Squinkerdoodle** [comment]
Is it just a case of the wiki info being wrong again?

The [Bearclaw Rabbit](https://ffxiclopedia.fandom.com/wiki/Bearclaw_Rabbit) is at the front of the battlefield; at around 60% HP, the 5 [Bearclaw Leveret](https://ffxiclopedia.fandom.com/wiki/Bearclaw_Leveret) move in and link.

**Comment by dallano** [comment]
Yeah just wiki error. Are you in the captures discord? you can see live retail captures of the fight. wikipedia tends to be rather unreliable for specific battlefield mechanics. 
https://discord.gg/RJFBTraT

**Comment by Squinkerdoodle** [comment]
Just joined it and thank you, this will be handy.

**Comment by Squinkerdoodle** [comment]
I watched the capture, the fight currently works like it does in the video aside from the Leverets despawning if the correct one is killed. Out of 3 fights I've had to kill all 5. I could just be that unlucky, but worth double checking. I didn't see blood weapon in the capture either, I was going off of what the wiki had for the fight so can't say for certain if that should be a thing or not.

**Comment by dallano** [comment]
Awesome! thank you for confirming that for me. and a good way to check which one you need to kill would be to get its ID.
the one that triggers the despawning of the others is set randomly between 1, to 5 higher than the main rabbit. So you could very much be getting unlucky :(
