### ISSUE TITLE
[BUG][/Launcher]

### ISSUE THREAD

**Issue by Doitwildly** [HorizonFFXI/HorizonXI-Issues#722]
Download and play game buttons are missing 

![RDT_20230106_0630261028326644740609729](https://user-images.githubusercontent.com/122095884/211008831-703ca69f-f64d-4e9f-ab2c-1391c3f3d744.jpg)

**Comment by BayaniTenzen** [comment]
Hello, you might find more immediate solutions for Login/PC or Launcher Issues on the Help Section of the HorizonXI Public Discord
