### ISSUE TITLE
🐛[BUG][System] Possible to ride chocobo in Ro'maeve

### ISSUE THREAD

**Issue by T3xan** [HorizonFFXI/HorizonXI-Issues#724]
**What does this bug affect?**
Carried chocobo riding status into Ro'maeve

**Steps to Reproduce**
Ride chocobo into zone from Zitah.

**Expected behavior**
Should automatically dismount prior to zoning in.

**Screenshots**
![image](https://user-images.githubusercontent.com/118692712/211063397-ae0f5132-0440-45ef-860b-09c70dd326db.png)

**Comment by BayaniTenzen** [comment]
when was this taken? - was this after the most recent maintenance?

**Comment by T3xan** [comment]
Funny enough, client crashed in zone pre-maint. I didn't log back on until after maint. Want me to test it again?

**Comment by T3xan** [comment]
Confirmed. Still able to ride a chocobo in zone.

**Comment by BayaniTenzen** [comment]
I've also tested it - it's still a thing!

**Comment by Frankie-hz** [comment]
Fixed in: https://github.com/AirSkyBoat/AirSkyBoat/pull/2526
