### ISSUE TITLE
🐛[BUG][System] Jelly in K. Tunnel don't drop Slime Oil

### ISSUE THREAD

**Issue by dave4988** [HorizonFFXI/HorizonXI-Issues#727]
System I guess? Mob if anything but didn't see it in the list.
**What does this bug affect?**
Jelly's in K Tunnel are supposed to have a 43% chance to drop slime oil, and can even drop up to 3. I've killed 30+ of them and not gotten a single drop besides a crystal. I've seen other people farming and asked if they got any drops, and 0/3 had either

**Steps to Reproduce**
Kill Jellies!

**Expected behavior**
Should be receiving Slime Oil.

**Screenshots**

**Setup Information**

**Additional context**

**Comment by TracentEden** [comment]
Fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2640 (watch patch notes)
