### ISSUE TITLE
🐛[BUG] NPC - Bhoyu Halpatacco

### ISSUE THREAD

**Issue by Relyk1** [HorizonFFXI/HorizonXI-Issues#728]
**What does this bug affect?**+

leaving Kazham 

unable to leave kazham on airship, Bhoyu Halpatacco will not talk to me and both sides say they are departure side and tell me to go on the other side. If you have less than 200 gil she will do nothing and break, over 200 she will talk to you but will not allow you to leave. I had to have exactly 200 gil on me to get out. 
**Steps to Reproduce**

Pretty much you need exact gil to talk to her to get out.  if you do not she will not talk to you and the gate guard will not tell you correct info. 

**Expected behavior**

payy 200 gil and get to leave

**Screenshots**

**Setup Information**

**Additional context**

I was not able to record this because I honestly did not think it would work, I had just logged in from the maint and that was the first thing that happened. not sure if my issue or on the server, but GM told me to post.

**Comment by CriticalXI** [comment]
I cannot reproduce this error, the NPC talked to me with no issues.
