### ISSUE TITLE
🐛[BUG][NPC] Lu Shangs should be able to break on Giant Chirai

### ISSUE THREAD

**Issue by towbes** [HorizonFFXI/HorizonXI-Issues#729]
**What does this bug affect?**
I started fishing Giant Chirai at 89 fishing (+4 from gear) to be within 10 levels (they are ~~103~~ 110 cap).  I was using Lu Shangs + Fly Lure. The fish always gave Good Feeling messages

**Steps to Reproduce**
1.  Equip Lu Shangs + Fly Lure (and 4 pieces of +fishing gear) with 89 fishing skill
2. Go to Boyadha Tree "Basin of Waterfall Pool" (H-11 Map 2) and fish
3. See Good Feeling message on !!! fish (Giant Chirai is only thing that will bite)

**Expected behavior**
These should be giving bad feeling messages as there is a chance they can break Lu Shangs

**Screenshots**
No screenshots

**Setup Information**
version 30221103_1

**Additional context**
Here is a link to the Great Blue page that shows lu shangs can break on giant chirai; https://www.great-blue.jp/?fid=058&lng=en  

Great blue also lists them at 103 cap not 110. Not sure if that is an intentional change here

As a counterpoint, ffxiclopedia and bg wiki do not list lu shangs as being breakable:
https://ffxiclopedia.fandom.com/wiki/Giant_Chirai
https://www.bg-wiki.com/ffxi/Giant_Chirai

However, I think most fishing data used in the code base is based of Great Blue, so for consistency should continue using those values (most players agree that it is the most accurate)

**Comment by The-Aerec** [comment]
@panicstevenson want to tag team this?

**Comment by towbes** [comment]
These fish are still giving good feeling on a lu shangs with 100+4 fishing skill
