### ISSUE TITLE
🐛[BUG] When Hell Freezes Over ENM

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#73]
**What does this bug affect?**
Wiki states the mobs are highly resistant to sleep, but I was able to reliably land sleep magic and lullaby. After entering the fight, there are 3 bombs waiting in the arena. After defeating these three the ENM was over.

**Expected behavior**
Bombs should be highly resistant to sleep / lullaby. There should be 4 waves of bombs total, with each wave consisting of 1 - 3 bombs (random).

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
Tested solo with godmode, tested sleep / lullaby with godmode disabled.

**Comment by dallano** [comment]
I think this is an issue that needs to be fixed overall with the database.
When we set mob resistances say to 75%, it's actually setting them to 7.5%. I believe we're waiting on a fix to fix this all at the same time rather than making temporary fixes all over the place.

**Comment by dallano** [comment]
I'll look into the battlefield ending when the first wave dies. it was working on my local build before I pushed it

**Comment by Squinkerdoodle** [comment]
I checked it again (using the correct wind pillar this time) and it lasted 4 waves.

**Comment by Squinkerdoodle** [comment]
So should we should be good to close this bug.
