### ISSUE TITLE
🐛[BUG]System Black screen w/downloading data on zone

### ISSUE THREAD

**Issue by bigcarl35** [HorizonFFXI/HorizonXI-Issues#731]
**What does this bug affect?**
Your client screen hangs and you have to close down the client and relogin.

When you zone, it's very likely that your screen will hang when it's black and "Downloading Data" is shown. It very occasionally happened prior to the maintenance, but since, it's happened to me 3 times in 5 zonings. Considering how hard it is to get back into the game, this is brutal.

**Steps to Reproduce**

I didn't do anything special, I entered Port Windhurst and it hung. Logged back in and entered my moghouse and it hung. Logged back in and exited to Port Windhurst and it hung. Makes me want to not zone any more.

**Expected behavior**

I should be able to enter a zone without the client hanging up.

**Screenshots**

**Setup Information**

Launcher: v1.1.3
Windows 10 Pro (19045.2364)

**Additional context**

The bug area on Horizon's discord has a lot of posts on this very issue

**Comment by coding4saudade** [comment]
This is happening to me repeatedly. Zoning from town to east sarutaburta, port windurst>windurst woods> windurst water to moghouse. Moghouse to windurst woods.

**Comment by BayaniTenzen** [comment]
this issue should now be fixed
