### ISSUE TITLE
🐛[BUG]Launcher//Reinstall

### ISSUE THREAD

**Issue by Xranadar** [HorizonFFXI/HorizonXI-Issues#732]
**What does this bug affect?**
It effects the ability for the launcher to identify that the game no longer exists on my computer after manually removing it from the HDD.

**Additional context**
When I download the launcher application, I see the normal Horizon launcher but i have a "Play HorizonXI" button and I need to log into my account. After clicking on the "Play HorizonXI" button, I am introduced with an error. This is it. When I click Ignore, it will get rid of the error box, exit will exit out of the error and the launcher, and report brings me to this website.
![FF11 Error](https://user-images.githubusercontent.com/122140566/211132425-1912d704-4039-49fd-9d32-11272eb14544.png)

**Comment by Flam9** [comment]
A few things you can try from Discord https://discord.com/channels/933423693848260678/1062224406216179804/1062224406216179804
