### ISSUE TITLE
🐛[BUG][NPC/System] - locked talking to NPCs

### ISSUE THREAD

**Issue by Vylandra** [HorizonFFXI/HorizonXI-Issues#734]
**What does this bug affect?**
Unable to use the new teleport Tarus in Windurst Woods and Port Windurst

**Steps to Reproduce**
Regardless of relogging, zoning, shutting down, etc. Whenever I click on either NPC I receive the dialogue as if I'm going to be teleported but given no option to teleport

**Expected behavior**
The option to teleport between the two locations should be given

**Screenshots**
https://gyazo.com/71e0e0f19500be31276fb5ed5a05f7ad

**Setup Information**
Windows 11

**Additional context**
When talking to either of the two newly added Warp Tarus the dialogue plays out properly but I'm not given the option to teleport between to the two zones regardless which taru I speak to. I've had multiple friends warp via these NPCs in front of me and I am unable to use either for about five days as of posting this report.

**Comment by CriticalXI** [comment]
Likely due to the same issue reported in AirSkyBoat/AirSkyBoat#2451
