### ISSUE TITLE
🐛[BUG][System/Combat] BCNM Entrance preventing Party Members

### ISSUE THREAD

**Issue by BayaniTenzen** [HorizonFFXI/HorizonXI-Issues#737]
**What does this bug affect?**
Entering a BCNM with an Orb and having Party Members unable to follow you in.

**Expected behavior**
After Using an Orb to enter a level capped BCNM - party members should be able to follow you in

Cause isn't currently identified - Replication has been inconsistent

**Comment by hookstar** [comment]
Which BCNM is this specifically that has happened to?
There is logic specifically for party members after orb is traded for individual BCNM.

**Comment by BayaniTenzen** [comment]
Apologies - i separated this from the original ticket - the Report was inside Royal Jelly

**Comment by TracentEden** [comment]
This was fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/3448
