### ISSUE TITLE
🐛[BUG][System/Combat] Royal Jelly - Mobs Healing from -aga Spells

### ISSUE THREAD

**Issue by BayaniTenzen** [HorizonFFXI/HorizonXI-Issues#738]
**What does this bug affect?**
Using an AoE Elemental Spell onto Slimes - chance for Healing to be reflected to other Slimes instead

**Steps to Reproduce**
Enter Royal Jelly - get several Slimes in close proximity - use AoE elemental magic - Slimes can take zero damage and then heal others

![image](https://user-images.githubusercontent.com/116040523/211156362-59306a5d-d5a1-4014-bfab-95a1a6e780fe.png)

**Screenshots**
![image](https://cdn.discordapp.com/attachments/168443898035699712/1061274897369808966/image.png)
![image](https://cdn.discordapp.com/attachments/168443898035699712/1061275860176474253/image.png)

**Additional context**
https://www.twitch.tv/videos/1700185783

**Comment by dallano** [comment]
This is intended behavior and was witnessed from captures <3
