### ISSUE TITLE
🐛[BUG] Like the Wind ENM

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#74]
**What does this bug affect?**
Once engaged the NM stays in the same spot and does not move. It will still cast spells, and use TP moves if you get within range as well as auto attacks if you get next to it. 

**Expected behavior**
NM should ignore pets and go after the master or whoever has highest threat. NM should be running around constantly, only stopping to use spells or TP moves (mainly toxic spit if target is out of melee range) after using a TP move it runs away again.

**Setup Information**
Version 30220802_3

**Additional context**
Tested solo with immortal active.

**Comment by dallano** [comment]
Works as intended
