### ISSUE TITLE
🐛[BUG][Combat] Opo-Opo Blank Gaze still dispels when not facing

### ISSUE THREAD

**Issue by Mujen84** [HorizonFFXI/HorizonXI-Issues#740]
**What does this bug affect?**

**Steps to Reproduce**

**Expected behavior**

Gaze ability shouldn't work when not facing user. Granted was tested on a pet, but have been able to cancel gaze attacks of other mobs when pet not facing mob.
**Screenshots**

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment]
Cannot reproduce. Blank gaze does not dispel anything from me with my back to the Opo-opo.
