### ISSUE TITLE
🐛[BUG][NPC/Guild Points] Craftsman level fishing GP today is incorrect

### ISSUE THREAD

**Issue by TraceIronworks** [HorizonFFXI/HorizonXI-Issues#744]
**What does this bug affect?**
Todays GP for Craftsman is bladefish and without turning in anything I have a limit of 480 points.

**Steps to Reproduce**
 Turn in no fish for points and ask for the current limits as a craftsman level fisher.

**Expected behavior**
 Bladefish should be worth 1200 each for 5040 (Quantity : 5)  

**Additional context**
I have turned in no fish and my limit is incorrect

**Comment by towbes** [comment]
Another one was titanictus.  Gave ~160 GP for two fish

![titanicusGPbug](https://user-images.githubusercontent.com/7587673/211237470-f1f71172-8c7f-4213-98fa-7c6c2c59a469.PNG)

Wiki for era shows it should be 2100 per fish with max of 2.78 items

https://ffxiclopedia.fandom.com/wiki/Titanictus?oldid=376797

**Comment by towbes** [comment]
With veteran fishing today, forest carp took only 8 fish and gave 320gp 
![image](https://user-images.githubusercontent.com/7587673/213809127-b5804a36-5df0-416d-a979-66580afe8b14.png)

I was expected 1600gp (3 stacks of fish) https://ffxiclopedia.fandom.com/wiki/Forest_Carp?oldid=291297

**Comment by towbes** [comment]
Another instance of bugged GP with zebra eel.  Only took 1 fish:

![image](https://user-images.githubusercontent.com/7587673/214692660-0fd4c58a-12a2-475c-8603-e5f34e6f90a8.png)

**Comment by towbes** [comment]
Seems to be fixed so far with patch https://discord.com/channels/933423693848260678/933752333668606002/1068554459719934145  (not sure what PR this was)

**Comment by towbes** [comment]
Just wanted to confirm this seems fixed since that patch still after a couple days of turn ins
