### ISSUE TITLE
🐛[BUG][System/Combat/] "Polearm  hitting for very low DMG numbers, including 0 DMG when  under the effects of Sonic Boom"

### ISSUE THREAD

**Issue by soupcans** [HorizonFFXI/HorizonXI-Issues#745]
**What does this bug affect?**
When I fight bat trios around "very tough" to "incredibly tough"  and they use sonic boom attack down, I hit for 0~6 DMG with a high DMG polearm like recently Peregrine, a 61 DMG polearm. 

**Steps to Reproduce**
Be a Level 47 DRG maybe with a Peregrine, a lvl 40 polearm with 61 DMG. Fight Funnel Bats while under the effects of their sonic boom/attack down. Funnel bats in Garliage citadel specifically, Funnel Bats Level ranged from Level 51~55. Was level synced down to 47. Bard minuet was active. 

The only STR or attack gear were spike necklace, beetle earrings x2, bastokan subligar, bastokan mittens, sandorian ring, hermit's ring, mercenary's captain doublet and headgear. 

**Expected behavior**
I expect to hit for more than 0 damage with a 61 DMG polearm I think, if I understand FFXI's DMG formula of: Damage = base damage x PDIF and level correction penalty. And bats should take extra damage against piercing right? I was hitting for less damage than pld who ate defense food, who was using a one-handed hammer

The PDIF calculation possibly doesn't seem right. With a 61 DMG 2-handed weapon and piercing bonus against bats, my PDIF would have to be like close to 0.0 to get damage ranges of 0~5 
 
I might be wrong though. 

**Screenshots**
"Nobark" is the me, the polearm character, doing 0 DMG while PLD hits for 22: https://i.imgur.com/g7UDBOF.png

Food active and minuet hitting for 2 damage, while thf with much lower dmg daggers hits for 13: https://i.imgur.com/4mBYJV1.png

![th2](https://user-images.githubusercontent.com/39206172/211170836-8277b9d6-2aa0-436a-b329-1f0f4d38291a.png)

**Additional context**
IIRC, my attack was around 150~ while under the effects of sonic boom 

I might be wrong though sorry. 

I have not seen any other job/weapon combo hit for 0 DMG like I have

**Comment by CriticalXI** [comment]
We've had a few rounds of damage adjustments to the server since this issue. Feel free to re-open if still experiencing, but this also sounds working as intended with an attack down debuff.
