### ISSUE TITLE
Hitting the Marquisate - Cannot trade Chandelier Coal to Hagain

### ISSUE THREAD

**Issue by benwelker** [HorizonFFXI/HorizonXI-Issues#746]
Upon attempting to trade the Chandelier Coal to Hagain, nothing happens.  Unsure what the issue is, a GM did resolve the issue for me and the rest of the quest worked flawlessly.  Not sure what's happening on that particular step, confirmed with another THF that they had the same issue.

**Comment by TracentEden** [comment]
Fixed in https://github.com/AirSkyBoat/AirSkyBoat/pull/2589
