### ISSUE TITLE
🐛[BUG][Mission] - Dawn

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#75]
**What does this bug affect?**
Promathia fight phase 1 & 2. Cutscenes after clearing the Promathia fights and waiting until after the following JP midnight.

**Steps to Reproduce**
Go through the mission and enter the Promathia fight. After clearing the fight try to trigger the cutscenes after the next JP midnight has passed.

**Expected behavior**
See the Additional Context section for issues found during the fight. Prishe & Selh'teus should be in both phases of the Promathia fight with you, with their correct spells & abilities. Promathia's Bastion of Twilight & Wheel of Impregnability effects should be temporary, and able to use either repeatedly after the previous effect has worn off. Promathia should only cast Meteor once per minute. After clearing the fights and waiting until the next JP midnight has passed the closing cutscenes for your allies should be able to be triggered so that you can proceed to the final cutscene and obtain the CoP ring.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
Prishe & Selh'teus missing from both fights.
In the Phase 2 fight:
Promathia casts Meteor multiple times a minute, should only be once a minute.
Once Promathia uses Bastion of Twilight or Wheel of Impregnability it's effect is permanent. Effect should only be temporary and then go away, and Promathia should be able to use either ability again once the original wears off with this repeating until the fight is over.

After fight cutscenes: (check again after 10am)

Reveived Shikarees - In the Name of Justice cutscene before the following JP midnight after clearing the Dawn fight and zoning into Mhaura.

Unable to trigger the cutscenes for Tenzen / Jabbos / Louverance / Chebukkis after waiting until the following JP midnight after clearing the Promathia fight.

**Comment by The-Aerec** [comment]
After clearing the fight would be @OpheliaXI 's mission interactions. I can look at prishe and selt.. They were there.
