### ISSUE TITLE
🐛[BUG][NPC - Mist Lizard - Konschtat Highlands]

### ISSUE THREAD

**Issue by Atigeve** [HorizonFFXI/HorizonXI-Issues#755]
**What does this bug affect?**

Mist Lizards seem to not be dropping lizard skins at all.

**Steps to Reproduce**

Personally spent 3 hours farming with TH1 got 0 Lizard Skins.  This was also reported by another user in the discord in the horizon-chat channel who reportedly spent 6 hours farming the lizards for 0 skins.

**Expected behavior**

I would expect at least a couple skins by this point, FFXIDB says avg drop is 6.4% and say with TH1 its 11% so getting none in this period of time is not right.

**Screenshots**

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment]
```
-- ZoneID: 108 - Mist Lizard
INSERT INTO `mob_droplist` VALUES (1702,0,0,1000,926,@COMMON); -- Lizard Tail (Common, 15%)
INSERT INTO `mob_droplist` VALUES (1702,0,0,1000,852,@RARE);   -- Lizard Skin (Rare, 5%)
```
Can confirm they do indeed drop skins. Random is random.
