### ISSUE TITLE
🐛[BUG][System/Combat] Cannot equip Tekko Kagi as a level 40 Monk. 

### ISSUE THREAD

**Issue by markcasper88** [HorizonFFXI/HorizonXI-Issues#756]
**What does this bug affect?**
After the maintenance on Friday 1/6/23 I logged in and found my AF weapon, Tekko Kagi, unequipped. I was a level 40 monk, and had been using the AF weapon for the two prior days. I was unable to re-equip the Tekko Kagi until I gained two levels. This suggests the requirement had gone back to level 42, even though the item still reads "MNK 40"

**Steps to Reproduce**
1. Have a Level 40-41 Monk 
2. Aqcuire the AF Weapon "Tekko Kagi"
3. Attempt to equip the Tekko Kagi while at level 40 or 41.

**Expected behavior**
The Era+ changes are supposed to allow you to equip your AF weapon at level 40, so the item should equip as normal.

**Screenshots**
Can be found on the discord, here: 
https://discord.com/channels/933423693848260678/1060988588319322220/1060988588319322220

**Setup Information**
Game is up-to-date.

**Additional context**
I have also verified this happening to other monks of the same level. Again, once hitting level 42 I was able to equip the AF weapon as normal.

**Comment by bobthevicious** [comment]
This has occurred to me as well while level syncing down to level 40, it becomes unequippable.

**Comment by TracentEden** [comment]
This is being fixed by incoming PR (watch patch notes)
