### ISSUE TITLE
🐛[BUG][NPC] Cooking guild npc selling hare meat for 999,999,999

### ISSUE THREAD

**Issue by AnneAltana** [HorizonFFXI/HorizonXI-Issues#759]
**What does this bug affect?**
Both cooking guild ingredient NPCS in windurst (Chomo and Kopopo) were selling Hare Meat for 999,999,999g

**Steps to Reproduce**
Unclear, occasionally this happens when opening either of their shops.

**Screenshots**
![rarerabbits](https://user-images.githubusercontent.com/122228796/211213383-d1743718-85ee-4012-9b83-dd7fae6fbd6c.png)
ts**

**Comment by mohad12211** [comment]
can we know if this is intentional or a bug?

**Comment by TracentEden** [comment]
Fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/3522
