### ISSUE TITLE
🐛[BUG] ENM - Automaton Assualt

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#76]
**What does this bug affect?**
Unable to enter ENM when in possession of required key item.

**Steps to Reproduce**
Attempt to enter ENM fight while in possession of key item [Shaft Gate Operating Dial](https://ffxiclopedia.fandom.com/wiki/Shaft_Gate_Operating_Dial)

**Expected behavior**
ENM fight should start properly.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
When trying to enter you receive chat message "You cannot enter the battlefield at present. Please wait a little longer."

**Comment by dallano** [comment]
can't replicate on my build. we'll have to look into this
