### ISSUE TITLE
🐛Phantom Worm is missing his BLM spell list

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#760]
**What does this bug affect?**

Phantom Worm NM in Kuftal Tunnel
**Steps to Reproduce**

Spawn Phantom Worm and move out of range, notice that he is a skill up piñata. 

**Additional context**

https://ffxiclopedia.fandom.com/wiki/Phantom_Worm

**Comment by gtarrantiii** [comment]
Was unable to reproduce. 
Using ASB latest on local server:
![image](https://user-images.githubusercontent.com/16801070/220016521-e098c7ae-bf99-499d-bd4e-5519466a00ce.png)
![image](https://user-images.githubusercontent.com/16801070/220016576-63f176c8-8d39-4bdd-9218-82e661b34507.png)

Spell list present and spams them all. 

Might be a horizon db specific issue.
