### ISSUE TITLE
🐛[BUG][Combat] Counterstance for MNK is nonfunctional

### ISSUE THREAD

**Issue by PapaSteel** [HorizonFFXI/HorizonXI-Issues#762]
**What does this bug affect?**
The monk job ability obtained at level 45, 'Counterstance'.

**Expected behavior**
Counter rate should be increased by +45%, and defense should be calculated by the user's full VIT score (era) or by half their total defense (retail).
Instead, counter rate is increased by **+0%** and defense becomes HALF of the user's VIT.

I hope that when the team re-examines Counterstance to fix this glaring bug that makes this ability have no benefit, they also reconsider balance in 1.1. Counterstance has historically been hyper-situational to avoid a monk tank meta, and many people hoped Horizon would adjust this job to allow monks to off-tank effectively.

**Setup Information**
Horizon XI, latest patch as of Jan 8

**Additional context**
Counters are behaving funny on Horizon in general, but this may be due to intentional server-specific changes as well. Following are some screenshots from the official discord. Current theories are counter calcs are done with the opponent's attack stats, not the user's?
![9e848155bff197f5329de9fc85814cea](https://user-images.githubusercontent.com/48939269/211216195-955e0a6c-0961-4d2f-9279-6c1be6c1b1dc.png)
![1626c06f8f656c72125e75cd8706715f](https://user-images.githubusercontent.com/48939269/211216196-b9905604-beb2-4303-8c9f-56a520f07ca2.png)
![Goodtimes_2023 01 02_210247](https://user-images.githubusercontent.com/48939269/211216197-97c89105-cf58-44d9-8f5d-4078fce53df8.png)
![tqdI7lG](https://user-images.githubusercontent.com/48939269/211216198-d1f69bc0-210c-45c5-a787-83db02b50f1b.png)

**Comment by markcasper88** [comment]
Can confirm. Seeing the exact same behavior. No counters procing in counterstance, defense going to 50% of VIT score.

**Comment by Relicffxi** [comment]
I'm also seeing the exact same behavior. Counterstance is not adding counter rate.

**Comment by dallano** [comment]
I believe this was fixed with the last maintenance. Thank you for the report!

**Comment by Relicffxi** [comment]
Counterstance still seems to be broken yea. I don't see it in any maintenance patch notes either.

**Comment by markcasper88** [comment]
I've been testing for a few hours with Counterstance and Counter+2 and have this rate:
83 Hits taken
17 Counters
--------------
20.5% Counter rate


I could be getting terrible luck, but 100 hits/counters I think is a fairly decent sample. Especially if others are reporting the same. Not to mention the overly harsh penalty to DEF.
