### ISSUE TITLE
🐛[BUG]Yuhtunga Jungle Digging Pool does not replenish

### ISSUE THREAD

**Issue by InChainsTV** [HorizonFFXI/HorizonXI-Issues#763]
[BUG]
**What does this bug affect?**
Players cannot rank up because the Test Item for Rank 2 is only available in Yuhtunga Jungle. 

**Steps to Reproduce**
No need to reproduce, just dig in Yuhtunga, you will never yield an item.

**Expected behavior**
Replenish pools each new game day

**Screenshots**
![image](https://user-images.githubusercontent.com/122233479/211218342-dd58c315-83c0-4646-83ce-c038d188a758.png)

**Setup Information**
HorizonXI - normal stuff

**Additional context**
Please fix this... it is unfair for those Diggers that already hit the required Digs but are stuck in the Rank.

**Comment by TracentEden** [comment]
This is being fixed by incoming PR (watch patch notes)
