### ISSUE TITLE
🐛[BUG][System] Gavial Finger Guantlets NPC price too high

### ISSUE THREAD

**Issue by Grover91** [HorizonFFXI/HorizonXI-Issues#765]
**What does this bug affect?**
 Gavial Finger Guantles are currently npcing for roughly 5k.  FFXIclopedia currently shows an npc price closer to 2k

**Steps to Reproduce**
Attempt to vendor a pair of Gavial Finger Guantlets to an npc to check price

**Expected behavior**
 Vendor price should be closer to 2k 

**Screenshots**

**Setup Information**

**Additional context**
 https://ffxiclopedia.fandom.com/wiki/Gavial_Finger_Gauntlets

**Comment by dallano** [comment]
Closing this as this was adressed. Thank you for the report
