### ISSUE TITLE
🐛[BUG][System] Sickle break frequency

### ISSUE THREAD

**Issue by AndenaXI** [HorizonFFXI/HorizonXI-Issues#767]
**What does this bug affect?**
Sickle breaks too often while harvesting in West Sarutabaruta

**Steps to Reproduce**
Did 2 trips. 1st time with 5 sickles and got 7 items. 2nd time used 7 sickles and got 5 items

**Expected behavior**
It should not be 1 item per sickle broken.

**Screenshots**
![Andena_2023 01 08_163322](https://user-images.githubusercontent.com/122237273/212464535-6d4d315f-a739-42fb-a75d-6b1e6dec359a.png)

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment]
Needs more information. How many field pieces did you have equipped? What evidence do you have that this break rate is actually too high?

**Comment by CriticalXI** [comment]
Closed due to no response.
