### ISSUE TITLE
🐛[BUG][System] Gavial Cuisses Recipe Not Working

### ISSUE THREAD

**Issue by Grover91** [HorizonFFXI/HorizonXI-Issues#768]
**What does this bug affect?**
 Bonecraft level 95 synth, Gavial Cuisses pops up with the message "Your skill is too low for this recipe.  This was attempted at level 88 Bonecrafting with level 60 Leathercrafting sub.  The recipe should be a lvl 95 BC synth with a subcraft LC synth of 1, according to ffxiclopedia

**Steps to Reproduce**
 Attempt to craft Gavial Cuisses with a character that has appropriate BC and LC skills

**Expected behavior**
 This recipe should be valid for a character only 7 levels in skill below cap.

**Screenshots**

**Setup Information**

**Additional context**
https://ffxiclopedia.fandom.com/wiki/Gavial_Cuisses

**Comment by panicstevenson** [comment]
The comment from the LandSandBoat codebase says:
> 2021.11.10 All agree on Bonecraft 95.  FFXIclopedia shows Leathercraft 1 where BGWiki states 1-15 and JPWiki states 5.  Implimented @ 15 to err on the side of more difficult.

This isn't meant to say it's right, you're wrong, or vice-versa, but hopefully gives you direction while the ticket is being triaged.

**Comment by ffxiWaxer** [comment]
Can we get an update on this? I just spent 600,000g in preparation for this synth and to see it's disabled over controversy regarding the leatherworking subcraft is frustrating.
