### ISSUE TITLE
🐛[BUG] ENM - Beloved of the Atlantes

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#77]
**What does this bug affect?**
Beloved of the Atlantes not listed in the fight list when clicking on the Spatial Displacement.

**Steps to Reproduce**
While in possession of the Monarch Beard key item, click on the spatial displacement in Monarch Linn and see if fight is listed. (The other 3 fights for this zone are there, just not this one.)

**Expected behavior**
ENM should be included in the list and able to be entered.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
Used GM toggle to enter the fight, after entering there was no mob and the Treasury Chest was already in the middle of the arena. After opening the chest the ENM gave loot and ended as normal.

**Comment by dallano** [comment]
Fix coming from the PR: https://github.com/AirSkyBoat/AirSkyBoat/pull/376
