### ISSUE TITLE
🐛[BUG][Craft Recipe - Shall Shell]

### ISSUE THREAD

**Issue by JadedXI** [HorizonFFXI/HorizonXI-Issues#770]
Shall Shell recipe does not seem to exist currently. 
 Shall shell recipe in era should be 1 wind crystal + Shall Shell = Pebble, HQ1 = Pearl HQ2 = Black Pearl. Currently when wind crystal is used on a shall shell, you get the error message for incorrect combination of materials for synthesis. 

https://ffxiclopedia.fandom.com/wiki/Pearl?direction=next&oldid=144833

**Steps to Reproduce**
 take 1 wind crystal and use it on a shall shell. 

**Setup Information**
 HorizonXI

**Comment by dallano** [comment]
This recipe is ToAU era and won't be on horizon until that expansion releases.
