### ISSUE TITLE
🐛[BUG][NPC]

### ISSUE THREAD

**Issue by Jibblesenbits** [HorizonFFXI/HorizonXI-Issues#771]
**What does this bug affect?**

Musshushu scorpions on LoO are using ws's back to back, possibly mimic'ing ODS
**Steps to Reproduce**

Engage scorpion, feed tp until it uses Wild Rage. Will use it twice in a row.
**Expected behavior**

Chould only use it once.
**Screenshots**

![image](https://user-images.githubusercontent.com/63336723/211240144-a7ed7fb0-504e-4e03-91b2-b4162bbf8991.png)

**Setup Information**

**Additional context**

**Comment by Jibblesenbits** [comment]
We have a ranger in party who apparently shot with Barrage inbetween moves, and has reported that barrage is completely refilling every monsters tp from 0 to 100 for another tp  move on everything he's shot with it.

**Comment by CriticalXI** [comment]
This sounds like working as intended. Barrage is 6 individual hits, which can feed a lot of TP. I haven't seen wide spread reports about this, and I don't see anything that would effect this specific mob or TP move.
