### ISSUE TITLE
🐛[BUG][Combat]Base DMG of Bastokan/Republic Hammer is incorrect/unadjusted

### ISSUE THREAD

**Issue by slitfin** [HorizonFFXI/HorizonXI-Issues#772]
**What does this bug affect?**

when u upgrade a Decurion's Hammer CP item, it reduces its DMG value
decurions was adjusted from 16 to 19 base dmg.
republic still reflects the old 16 base dmg, adding +2 for 18. it should be 21. (19 base +2)
**Steps to Reproduce**

when u upgrade a Decurion's Hammer CP item, it reduces its DMG value
**Expected behavior**

when u upgrade a Decurion's Hammer CP item, it should increase its DMG value
**Screenshots**

![image](https://user-images.githubusercontent.com/28990795/211386611-f7a2cad8-4f92-4334-9e4d-cd349dc09f13.png)
![image](https://user-images.githubusercontent.com/28990795/211386637-87165c4d-c366-4609-a67b-f78151ce9f46.png)

just try it
**Setup Information**

not relevant
**Additional context**

take a decurions hammer and upgrade it

**Comment by CriticalXI** [comment]
Fixed in HorizonFFXI/HorizonDats#1
