### ISSUE TITLE
🐛[BUG][ Quest - bstquest complete but no bst job

### ISSUE THREAD

**Issue by mchammer996** [HorizonFFXI/HorizonXI-Issues#776]
**What does this bug affect?**
 I can't play the bst job.

**Steps to Reproduce**
 I was on pld when i unlocked it.  Got the title, 2100 gil and the necklace, but not the job.

**Expected behavior**
 N/A

**Screenshots**
 N/A

**Setup Information**

**Additional context**

**Comment by hookstar** [comment]
After zoning, does BST not show up in your jobs list?

**Comment by CriticalXI** [comment]
Closed due to no response, not likely a bug
