### ISSUE TITLE
🐛[BUG][NPC/NM] "NM Zi'Ghi Boneeater not spawning"

### ISSUE THREAD

**Issue by zylakitty** [HorizonFFXI/HorizonXI-Issues#778]
**What does this bug affect?**
The NM Zi'Ghi Boneeater potentially may not be spawning correctly.

**Steps to Reproduce**
Spent around 6-7 hours one day camping the NM, and did not see it once. Camped it again today for a few hours (maybe 3 or so) and it also did not spawn. It is a lottery spawn off of the Veteran Quadav PH in the room at H-7/H-8 whose hexID is 105. There is normally only ever this Veteran Quadav, an Onyx Quadav with the hexID 107, and a Greater Quadav I can't remember the hexID for. However, one thing I did notice during these camping sessions is there would occasionally, every 1-2 hours roughly, spawn a second Onyx Quadav in the room that would normally not be there. My suspicion is that this second Onyx Quadav is spawning in place of the NM incorrectly. The hexID for this second Onyx Quadav as of the last time I noticed it spawning was 104.

**Expected behavior**
The NM should spawn instead of the second Onyx Quadav.

**Screenshots**
(https://ibb.co/3mKvR46)

**Setup Information**
ver: 30221103_1

**Additional context**
Nothing I can think of.

**Comment by TracentEden** [comment]
This will be fixed by incoming PR (watch patch notes)
