### ISSUE TITLE
🐛[BUG][Quest - The Stars of Ifrit

### ISSUE THREAD

**Issue by Sleepyeyez** [HorizonFFXI/HorizonXI-Issues#779]
I was trying to do Quest - The Stars of Ifrit quest and rode the Airship from Jueno TO Sandy then tried from Sandy TO Jueno trying to find the ??? on the airship with no luck. Both rides were between the IN GAME time of 20:00 - 0400. 

![Quest](https://user-images.githubusercontent.com/121367932/211444745-435c9619-eda3-4189-9457-79c43bff2cdb.JPG)
![Time](https://user-images.githubusercontent.com/121367932/211444773-9a82c915-c653-4060-b95b-13bfa5a08fc0.JPG)

**Comment by CriticalXI** [comment]
Fixed in AirSkyBoat/AirSkyBoat#2685
