### ISSUE TITLE
🐛[BUG] Level 30 Promy ENMs

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#78]
**What does this bug affect?**
Hysteroanima and Terroanima do not seem to work. Psychoanmia does work properly. Rest of the fights are fine.

**Steps to Reproduce**
Go into fight and use anima on the boss to see if they work.

**Expected behavior**
Hysteroanima - Created from a Recollection of Pain, this anima prevents the Empty from using special attacks for a short time.
Terroanima - Created from a Recollection of Guilt, this anima causes the Empty to flee from whomever holds the most enmity.

**Setup Information**
Version 30220802_3

**Comment by dallano** [comment]
bug fixed in PR: https://github.com/AirSkyBoat/AirSkyBoat/pull/376
