### ISSUE TITLE
🐛[BUG][Quest] Blast from the Past - Can't spawn Ichorous Ire

### ISSUE THREAD

**Issue by pklwsl** [HorizonFFXI/HorizonXI-Issues#781]
**What does this bug affect?**
After talking to Koru-Moru in Windurst and flagging the quest the next step is to touch the fossil rock at F-8 in the Maze of Shakrami. There is no effect after clicking the fossil rock. 

**Steps to Reproduce**
Flag quest and attempt to click the fossil rock.

**Expected behavior**
Spawn Ichorous Ire NM which drops the Burnite Shell.

**Comment by panicstevenson** [comment]
Thanks for the report!
