### ISSUE TITLE
🐛[BUG][System/Combat]Wyvern Healing Breath bug

### ISSUE THREAD

**Issue by Luaithel** [HorizonFFXI/HorizonXI-Issues#783]
**What does this bug affect?**

When in a party, if a Dragoon's Wyvern targets a party member with Healing Breath, but that party member dies before the breath fires off, the wyvern is unable to use Healing Breath on anyone else until the original breath target is revived.

**Steps to Reproduce**

Step one: Party member under 33%.
Step two: Cast a spell to trigger HB.
Step three: Party member dies before HB goes off, interrupting the breath.
Step four: Wyvern doesn't work until party member is revived.

**Expected behavior**

The wyvern should be able to use HB on other party members that are under the target hp threshhold, even if the original HB was interrupted due to the target dying before it resolved.

**Screenshots**

**Setup Information**

**Additional context**

**Comment by Luaithel** [comment]
Addendum on this: It might actually be happening if any dead party members are within the wyvern's range.  It will refuse to heal anyone else.

**Comment by TracentEden** [comment]
Fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2639
