### ISSUE TITLE
🐛[BUG][Crafting][NPC] Dragon Mask and Dragon Mask +1 NPC price is inaccurate

### ISSUE THREAD

**Issue by ffxiWaxer** [HorizonFFXI/HorizonXI-Issues#787]
**What does this bug affect?**
Crafters
**Steps to Reproduce**
Make a dragon mask or dragon mask +1 and NPC it
**Expected behavior**
NQ items are not supposed to sell for the same amount as an HQ item

**Screenshots**
![horizon-loader_nMLbbxRbAg](https://user-images.githubusercontent.com/94857791/211578242-a25c5582-b017-4239-924f-d71b738ce6e0.png)

**Setup Information**
103_1
**Additional context**

taken from airskyboat item_basics.sql

'dragon_mask','dragon_mask',1,2084,17,0,8036);
'dragon_mask_+1','dragon_mask_+1',1,2080,17,0,8000);

wiki
![image](https://user-images.githubusercontent.com/94857791/211578669-c2fcc9e5-1930-41b6-9887-dbfa01aec6bd.png)
![image](https://user-images.githubusercontent.com/94857791/211578718-f32a6d95-73b4-4d96-92a6-a80b82b41785.png)

Regardless of how you choose to solve this, 7245 is too low for Dragon Mask and Dragon Mask +1

**Comment by dallano** [comment]
this is an intended change done by the horizon team.
