### ISSUE TITLE
🐛[BUG][NPC] Goblin Wolfman NM attacking 3-4 times per second at low health

### ISSUE THREAD

**Issue by Shiftie-Bassturd** [HorizonFFXI/HorizonXI-Issues#789]
**What does this bug affect?**
Goblin Wolfman NM attacking up to 3-4 times a second when low on health.

**Steps to Reproduce**
First time NM was pop spawned with a goblin drink the fight went normally. Next two attempts the mob had super attack
speed at low health. Would attempt to reproduce again but prefer not to lose more exp/pop items.

**Expected behavior**
NM should have a slight attack speed increase during its use of Blood Weapon 2hr.

**Screenshots**
![goblinwolfman](https://user-images.githubusercontent.com/109208330/211594960-38764ea6-a5b4-446a-bb35-3fae97be6977.PNG)

**Comment by avogadro-war** [comment]
Did this get addressed with the Friday patch? Was some hint that it might be on the related discord thread.

**Comment by avogadro-war** [comment]
https://gfycat.com/cavernousfaroffkrill

Behavior is still bricked.

**Comment by TracentEden** [comment]
Fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2625
