### ISSUE TITLE
🐛[BUG] ENM Reward Exchange

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#79]
**What does this bug affect?**
Malicious Vision & Pristine Vision are not accepted by trade to turn in for their rewards.

**Steps to Reproduce**
Trade either of the above vision items you receive as a reward for clearing the promy ENMs to Venessa in Ru'Lude Gardens.

**Expected behavior**
https://ffxiclopedia.fandom.com/wiki/ENM_Reward_Exchange
Trade in: Pristine Vision *** Receive: Wind Earring	*** Stat: Wind Instrument Skill +3
Trade in: Malicious Vision *** Receive: Ninjutsu Earring *** Stat: Ninjutsu Skill +3

**Setup Information**
Version 30220802_3

**Additional context**
All other trade-ins work aside from these 2

**Comment by dallano** [comment]
bug fixed in PR: https://github.com/AirSkyBoat/AirSkyBoat/pull/376
