### ISSUE TITLE
🐛[BUG][Combat] Food taking away Song buffs

### ISSUE THREAD

**Issue by Leaute** [HorizonFFXI/HorizonXI-Issues#790]
**What does this bug affect?**
Currently if you eat any cookies/30 minute foot it removes bard buffs. 

**Steps to Reproduce**
1. Have songs sung
2. Eat something nice
3. Re sings songs but sadly

**Expected behavior**
They shouldn't overwrite. 

**Screenshots**

**Setup Information**

**Additional context**

**Comment by dallano** [comment]
This is a repeat bug report. But fix will be on the server soon.
