### ISSUE TITLE
🐛[BUG][Combat]Choke Breath not working.

### ISSUE THREAD

**Issue by flipcork** [HorizonFFXI/HorizonXI-Issues#791]
**What does this bug affect?**
This is an issue with the TP ability [Choke Breath](https://ffxiclopedia.fandom.com/wiki/Choke_Breath).  Currently the ability when used does nothing.

**Steps to Reproduce**
Engage with an enemy able to use the ability  [Choke Breath](https://ffxiclopedia.fandom.com/wiki/Choke_Breath).  The ability will not do anything at all.

**Expected behavior**
The ability  [Choke Breath](https://ffxiclopedia.fandom.com/wiki/Choke_Breath) should be a breath attack that does damage in a fan-shaped area, with the ability to also silence and paralysis the targets hit.

**Screenshots**

**Setup Information**
Version 30221103_1

**Additional context**
 [Choke Breath](https://ffxiclopedia.fandom.com/wiki/Choke_Breath) does no damage, and does not hit the target it is used on.  It will show up being used in combat log, then nothing happens.

**Comment by panicstevenson** [comment]
Thanks!
