### ISSUE TITLE
🐛[BUG] Crafting   Beast Horn Synthesis not in game

### ISSUE THREAD

**Issue by bliven-was-taken** [HorizonFFXI/HorizonXI-Issues#794]
**What does this bug affect?**

Bonecrafters

**Steps to Reproduce**

2 Ram horns should be able to be crafted into a beast horn with a wind crystal

**Expected behavior**

Synth should work. Probably flagged as ooe because of ffxiclopedia page creation date.

**Screenshots**

**Setup Information**

**Additional context**

The Ffxiclopedia page wasn't created until August 2006 so it looks like it's out of era, however, it was added in the October 2005 patch, which is the patch that introduced limbus. It is required to +1 the beastmaster AF head.  
Somepage lists it on the new page and the beast horn page as an October 2005 addition. There's also a comment on the allakhazam forum in december 2005 asking what it is used for.

http://ffxi.somepage.com/news/197
http://ffxi.somepage.com/itemdb/7711
https://ffxi.allakhazam.com/db/item.html?fitem=9728

**Comment by panicstevenson** [comment]
Thanks for the report!
