### ISSUE TITLE
🐛[BUG][System] Eating Food and/or Item use removes Song Buffs

### ISSUE THREAD

**Issue by Agetos** [HorizonFFXI/HorizonXI-Issues#797]
System Bug
**What does this bug affect?**
This bug affects song status effects. While having songs up, it appears that using any sort of food (we tested w/ Mithkabobs & ginger cookies) cause you to have your songs immediately wiped off. We also believe that a Chariot band use also caused this effect. That would imply that any item that gives a status effect would wipe your songs.

**Steps to Reproduce**
Cast songs on self, use food/exp band or other item

**Expected behavior**
Songs should not be lost upon gaining a status effect via item use.

**Screenshots**

**Setup Information**

**Additional context**

**Comment by murrain** [comment]
Seeing the same issue.

**Comment by CriticalXI** [comment]
Fixed in a recent patch by dallano
