### ISSUE TITLE
🐛[BUG]System/Combat/ - Elvaan M Ninja using /ra with Dart triggers brd singing animation / sound effect instead of throwing animation 

### ISSUE THREAD

**Issue by HitGubz** [HorizonFFXI/HorizonXI-Issues#798]
**What does this bug affect?**

Using /ra with Dart as elvaan male does singing animation 
**Steps to Reproduce**

Be Elf Male and uuse Dart (tested on nin only) 
**Expected behavior**

Should do throwing animation 
**Screenshots**

X
**Setup Information**

V1, Launcher V1.1.3, Windows 11
**Additional context**

Funny bug

**Comment by hookstar** [comment]
do you have lockstyle on? Often times this occurs when you equiip it after you apply lock style... if that is the case, add it to your lockstyle or equip prior to

**Comment by HitGubz** [comment]
Not that I'm aware of, not something i've put on, or toggled in addons. Didn't happen with pebbles so unique to dart.

**Comment by dallano** [comment]
This bug was already reported elsewhere
