### ISSUE TITLE
🐛[BUG][NPC/Quest] Enveloped in Darkness (RDM AF Feet) - Wait time wrong + Quest Progress Blocked by A General's Secret

### ISSUE THREAD

**Issue by KiplingFFXI** [HorizonFFXI/HorizonXI-Issues#8]
**What does this bug affect?**
Multiple issues:

(1) The wait time for the boots being buried in Crawler's Nest is supposed to be JST midnight, but it was basically instant.

(2) You are supposed to be able to accept the quest "The General's Secret" from the same quest NPC, but it isn't supposed to block your progress. Accepting "The General's Secret" forces you to complete it before you can do this quest. This should not be the case according to MODERN wiki: https://ffxiclopedia.fandom.com/wiki/Enveloped_in_Darkness - I could not find this on older versions, so it may be intended.

**Steps to Reproduce**

Complete the quest and bury the boots. Obtain item too quickly.

**Expected behavior**

The boots should require a JST midnight wait.

**Screenshots**

N/A

**Setup Information**

N/A - Older report

**Additional context**

N/A

**Comment by dallano** [comment]
Looks like @CriticalXI fixed this issue a couple weeks ago https://github.com/dallano/server/commit/6c8821b49fc79948d3c2ee0b94980f61e4b5a392
