### ISSUE TITLE
🐛[BUG] ENM - Fire in the Sky

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#80]
**What does this bug affect?**
Able to sleep NM with Sleep black magic, wiki and capture video suggest it should resist it. After first self destruct you are kicked out of the fight (happened on 3 attempts), which should only happen if all 3 self destructs go off.

**Setup Information**
Version 30220802_3

**Additional context**
Not sure if this is normal or not, but you can run out of range of the self destruct and the tp move won't go off / the NM won't lose a bomb visually.

**Comment by dallano** [comment]
Fix coming in PR: https://github.com/AirSkyBoat/AirSkyBoat/pull/376
