### ISSUE TITLE
🐛[BUG][NPC/COMBAT] Stealing wrong item from "Sabertooth Tiger"

### ISSUE THREAD

**Issue by rustyclippers** [HorizonFFXI/HorizonXI-Issues#800]
**What does this bug affect?**
Thief ability steal

Its stealing land crab meat from tigers 

**Steps to Reproduce**
Steal from Sabertooth tiger in batallia downs

**Expected behavior**
Not stealing land crab meat from a tiger? 

**Screenshots**
![image](https://user-images.githubusercontent.com/95000067/211875962-9d6d0f81-b541-4b83-90d2-abb721232f2d.png)

**Setup Information**

**Additional context**
It happens everytime I steal.   Im just assuming this isnt correct because it seems weird.  if its intended I am sorry.

**Comment by TracentEden** [comment]
This is actually the correct drop https://ffxiclopedia.fandom.com/wiki/Sabertooth_Tiger?oldid=44709
