### ISSUE TITLE
🐛[BUG]System] Tiger Mantle Desynth does not exist

### ISSUE THREAD

**Issue by mjkmike** [HorizonFFXI/HorizonXI-Issues#801]
**What does this bug affect?**

I am unable to desynth Tiger Mantles.  

**Steps to Reproduce**

Lightning Crystal + Tiger Mantle with open inventory slots.  

**Expected behavior**

I think this is an era recipe based on the fandom wiki?

**Screenshots**

**Setup Information**

**Additional context**

**Comment by dallano** [comment]
Evidence seems to point out that this desynth recipe was added in ToAU. Please look forward to it in upcoming patches!
Thank you for the report.

https://ffxiclopedia.fandom.com/wiki/Tiger_Mantle?action=history
