### ISSUE TITLE
🐛[BUG] Critical Bug - Logging out while a pet is out/fighting as SMN crashes the server or area

### ISSUE THREAD

**Issue by DuskLove** [HorizonFFXI/HorizonXI-Issues#802]
**What does this bug affect?**

crashes the area/server

**Steps to Reproduce**

log out while a pet is fighting a mob on smn

**Expected behavior**

i dont think you're supposed to be able to log out with a pet out but my memory isnt that great. at the very least it shouldnt crash the server/area.

**Screenshots**

hard to screenshot something when you're logged off.

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment]
Fixed in AirSkyBoat/AirSkyBoat#2754 and several other crash fixes by Shozokui
