### ISSUE TITLE
Stone Eater double pop in N Gustaburg

### ISSUE THREAD

**Issue by ElimLacuna** [HorizonFFXI/HorizonXI-Issues#803]
![IMG_20230111_125810322](https://user-images.githubusercontent.com/121478900/211895141-206fb29d-69f7-4e61-8d8b-e93d73a5fae9.jpg)
Stone eaters in North Gustaburg near Port Bastok exit are spawning x2 in one spot.

**Comment by CriticalXI** [comment]
This is due to our custom extra mobs due to the population. Will eventually go away once we remove this.
