### ISSUE TITLE
🐛[BUG][System] Lack of Skill Messages on 110+ Cap Fish

### ISSUE THREAD

**Issue by towbes** [HorizonFFXI/HorizonXI-Issues#810]
**What does this bug affect?**
Due to the changes in lack of skill messages, all fish 110+ are going to give lack of skill for a fisher at 100 with no bonuses. Any fish that is 133+ is going to give lack of skill messages to a level 100 fisher with max bonus.  

Max +skill should be +15 (lu's) + 6 (gear/gp items) + 2 (adv support).  That would put no lack of skill message at a max of 100+15+6+2+10 = 133.  

Some fish this will affect: (Some of these might be out of current era)
5476 - Abaia
5471 - Gerrothorax
5127 - Gugrusauraus
5129 - Lik
5468 - Matsya
5134 - Mola Mola
4305 - Ryugu Titan

**Steps to Reproduce**
1. With 100 fishing (and lu shang's + fishing gear) attempt to fish a Ryugyu titan on the ferry (150 cap fish)
2. Even if you reel in the fish, will lose due to lack of skill

**Expected behavior**
1. Reeling in the fish that is 110+ cap should result in either a snapped line, broken rod or a successful fish.  A "lack of skill" message for a 100 skill fisher does not seem appropriate.

**Screenshots**
N/A

**Setup Information**
30221103_1

**Additional context**

I think the intention here should be that a skill 100 should be able to encounter these fish with a high level of difficulty to deplete stamina.  If that stamina is depleted successfully, there should be either a successful catch, a line break, or a rod break.

Really I think this should apply even at anything over 128+ as that is more realistically obtainable without using support and all GP items.  I would understand if the intention is to force those items though.  I think it would be preferable to have the fight be more difficult, not have lack of skill messages.

**Comment by towbes** [comment]
Fishing Cave Cherax at 100 skill with +4 gear and lu shangs.  Only ~25% of the catches are successful

![image](https://user-images.githubusercontent.com/7587673/213339206-17ce212c-d731-440b-b6d3-2ee78c34493e.png)

**Comment by towbes** [comment]
In the talk page for this fish it seems there are line break messages but nothing about lack of skill messages: https://ffxiclopedia.fandom.com/wiki/Talk:Cave_Cherax

**Comment by towbes** [comment]
Grabbed adv support and confirmed that there were no longer lack of skill messages on Cave Cherax with adv support.

**Comment by towbes** [comment]
This youtube channel has quite a few videos of catching Lik / Guguru on retail:
https://youtu.be/VhdwkM61EUI?t=1404

**Comment by towbes** [comment]
Here is a comparison of fishing Lik with Lu Shangs + Minnow on both Retail and a stock local ASB server.  Way more casts for the day from ASB since I can instantly get minnows vs having to run back to town and buy more.

Lik retail:  348 casts, 15 catches, 23 line break, 8 rod break, 2 lack of skill
Lik ASB: 642 casts, 61 catches, 41 line break, 3 rod break, 24 lack of skill

Here is the spreadsheet with raw data.  This includes information from the 0x115 incoming fish packet to be able to compare fish HP and regen values (among other things)
https://docs.google.com/spreadsheets/d/1isqffC9y1_sltG23Kl62hzS_xI3InDSoP241N6ANq7c/edit?usp=sharing

**Comment by towbes** [comment]
Some stats for Cave Cherax:

527 casts - 91 catches (17.2%), 41 line break (7.9%), 2 lack skill (0.3%), 0 rod breaks

Raw data:
https://docs.google.com/spreadsheets/d/1isqffC9y1_sltG23Kl62hzS_xI3InDSoP241N6ANq7c/edit?usp=sharing

**Comment by towbes** [comment]
Stats for Gugrusaurus - (From retail - Lu Shangs with meatball, 100 skill + 4 from gear) (Ship to Al Zhabi)

436 casts - 33 catches (7.57%), 27 line break (6.19%), 9 rod break (2.06%), 0 lack of skill

**Comment by TraceIronworks** [comment]
No changes yet bud, fingers crossed they can just remove the damn skill nerf for people at 90-100. The bluetail clothespole bonanza is over, lets hope we can get fishing back.

**Comment by towbes** [comment]
Sounds good thanks for checking in

**Comment by MarkWaldron** [comment]
@Shozokui Any updates on the change that was made here? Is this something we can re-test now?
