### ISSUE TITLE
🐛[BUG]BCNM entry

### ISSUE THREAD

**Issue by xxrainaxx1** [HorizonFFXI/HorizonXI-Issues#811]
**What does this bug affect?**
Orb person trades orb, anyone else in party cannot enter

Step 1. Have more than 3 people in your party in the zone. Step 2. Trade orb and try to start bcnm. Step 3. Orb holder zones in and no one else can get inside bcnm..

**Expected behavior**
 ORB HOLDER PLUS TWO PEOPLE SHOULD BE ALLOWED TO ENTER BCNM ZONE DESPITE HOW MANY PEOPLE ARE INSIDE THE PARTY

**Screenshots**

![5DjMOvq](https://user-images.githubusercontent.com/122519272/212014949-9802c6c3-344c-48c8-a9ba-46959691735b.jpg)
achments/1055223674053087273/1062830650656301066/image.png
**Setup Information**
![image](https://user-images.githubusercontent.com/122519272/212015077-8b99b071-32a6-47fe-857a-8351dc41c1d3.png)

V1.1.3 launcher?

**Comment by CriticalXI** [comment]
Duplicate #777
