### ISSUE TITLE
🐛[BUG][System] Darksteel Maul Damage Unchanged 

### ISSUE THREAD

**Issue by avogadro-war** [HorizonFFXI/HorizonXI-Issues#816]
Darksteel Maul damage is lower than other lower level hammer-type weapons

![image](https://user-images.githubusercontent.com/109310871/212172377-57eabc22-7534-400e-aa0e-050998be7923.png)
![image](https://user-images.githubusercontent.com/109310871/212172399-6de0b977-36f7-43e9-915c-ad2008a29eea.png)
![image](https://user-images.githubusercontent.com/109310871/212172423-37cd2e26-2ba3-46f9-99ab-406aff1a0d6a.png)

**Comment by CriticalXI** [comment]
Fixed in HorizonFFXI/HorizonDats#1
