### ISSUE TITLE
🐛[BUG][NPC/Quest/Mission] Unable to go through Gilgamesh's door, Critical bug maybe?

### ISSUE THREAD

**Issue by ThrisStraizo** [HorizonFFXI/HorizonXI-Issues#818]
**What does this bug affect?**

When I entered Norg after getting rank 6, I didn't get the welcome to norg cutscene so a GM has to inject the key item for me to continue.  I did all the ZM quests and got access to Sky.  I then started to do Bastok 6-2, talked to Naji, then headed to get the cutscene from Gilgamesh.  I was unable to enter the room where Gilgamesh was at despite the fact the other 5 members of my static were all able to no problem.  I have no idea where to begin with this issue or how it happened, or even what is specifically the trigger that is suppose to give you access to that room.  So I'm just stuck like this, any time I need access to that room I'll need a GM to pull me in or some Poison pot tractor shananigans idk.

**Steps to Reproduce**

I have no idea, god help us all.

**Expected behavior**

LETMEINNNNN.gif

**Screenshots**

![image](https://user-images.githubusercontent.com/45871917/212189547-c9180342-cbcd-4a26-864d-5a76af16641c.png)

**Setup Information**

Ver.  30221103_1

**Additional context**

**Comment by CriticalXI** [comment]
Appears to be fixed, was able to do this quest on live with no issues or GM intervention
