### ISSUE TITLE
[BUG][Quest] 'Reap What You Sow' quest not accepting Deathball trade

### ISSUE THREAD

**Issue by Ziggomatica** [HorizonFFXI/HorizonXI-Issues#819]
This bug was reported and closed over a week ago, yet here I am trying to trade a Deathball to Mashuu-Ajuu and nothing happens.

**Comment by Evrae** [comment]
It is also not accepting Sobbing Fungus to complete the quest.

**Comment by MattyP00** [comment]
> It is also not accepting Sobbing Fungus to complete the quest.

Same issue with me.

**Comment by Brian-Frost** [comment]
This quest is not accepting Sobbing Fungus for me either. Still bugged.
