### ISSUE TITLE
🐛[BUG][System] Defense can underflow

### ISSUE THREAD

**Issue by CriticalXI** [HorizonFFXI/HorizonXI-Issues#82]
If you get yourself into negative defense numbers, it underflows and gives you 65k+ defense. 

![image](https://user-images.githubusercontent.com/48370698/189782041-23a5b735-80ca-48fc-9b79-f2f6ec312b54.png)

**Comment by OpheliaXI** [comment]
Fixing in ASB.

**Comment by OpheliaXI** [comment]
This has been merged and will be in the next Horizon update.
