### ISSUE TITLE
🐛[BUG][System] 100 Fishing did not give "First player to reach 100 fishing" message

### ISSUE THREAD

**Issue by towbes** [HorizonFFXI/HorizonXI-Issues#820]
**What does this bug affect?**
Yesterday there was a "XXX was first player to reach 100 bonecrafting" message.  There are multiple 100 fishers on the server now and there was no "First player to reach 100 fishing" server message

**Steps to Reproduce**
1. On a fresh server, get to 100 fishing, no message will be displayed

**Expected behavior**
1. As with other crafts, "XXX was the first player to reach 100 fishing" should appear

**Screenshots**
Attached screenshot of hitting 100 fishing on Jan 8th ~18:00 (Japan standard time).  This should have been first 100 fishing on server unless there is someone being very quiet about it. 

![100fish](https://user-images.githubusercontent.com/7587673/212210376-33d54141-d308-4dc4-b6f2-cd99e19551d2.png)

**Setup Information**
30221103_1

**Additional context**
This could be intended behavior as fishing isn't technically a main craft but just wanted to bring it to attention

**Comment by CriticalXI** [comment]
Unfortunately fishing was missed in coding the world first announcements and this situation has passed. Going to close this out as there really isn't anything to be done about this at this point.
