### ISSUE TITLE
🐛[BUG][NPC/Quest/Mission/System/Combat/Launcher/Website]

### ISSUE THREAD

**Issue by PyrielDarkstar** [HorizonFFXI/HorizonXI-Issues#825]
system
**What does this bug affect?**  getting stuck on black screen with zoning to other areas. Happens randomly.. Patch didnt fix anything.

**Steps to Reproduce** it's random

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by TracentEden** [comment]
Should be mostly fixed by recent updates
