### ISSUE TITLE
🐛[BUG][Quest][Bastok Quest-Faded Promises]

### ISSUE THREAD

**Issue by IldonandRastaban** [HorizonFFXI/HorizonXI-Issues#826]
**What does this bug affect?**
Unable to begin or complete quest in order to obatain Fukuro (Katana) weapon reward.

**Steps to Reproduce**
A ninja level 20+ must interact with the npc Romualdo at the cannonry in Bastok in order to trigger a cutscene and start the quest.  There may be a tenshodo/bastok fame requirement of 4 or less.

**Expected behavior**
When speaking with Romualdo a cutscene should trigger, however, he just repeats generic dialogue when interacting with him.

**Screenshots**

**Additional context**
I wasn't entirely sure if it's just that I am unable to trigger it or if it's actually bugged but I also haven't seen the weapon up at auction house either so I'm assuming the quest just isn't working here.  I am ninja level 24 and have both Bastok and Tenshodo rep at appropriate levels to receive the quest.

**Comment by hookstar** [comment]
Merged.
