### ISSUE TITLE
🐛[BUG][System] Parties are dissolving (and loot is lost) if the last member is removed/leaves. 

### ISSUE THREAD

**Issue by Leaute** [HorizonFFXI/HorizonXI-Issues#827]
**What does this bug affect?**
Currently if you /pcmd kick or the last party member /pcmd leaves the party fully dissolves -- it doesn't leave the last remaining party member as leader (retail behavior). 

Important because if the last person leaves the party all loot is lost since the party dissolves and it does not drop (similar to what happens when you create/dissolve an alliance). 
**Steps to Reproduce**
1. Form a party with another member. 
2. Have them leave or /pcmd kick
3. Party fully dissolves

**Expected behavior**
The last remaining party member should have leader status of an empty party (with themselves as the only member)
Loot should fall to the last remaining party member (if inventory space allows) instead of being lost to the void with no messaging
1. Form a party with another member
2. Have them /pcmd leave or /pcmd kick them
3. You should be the leader of an empty party

Someone tested on retail here : 
https://user-images.githubusercontent.com/118570028/212388665-6a8786ed-09bc-4a21-b214-0a04412e9a49.mp4

**Setup Information**

**Additional context**

**Comment by TracentEden** [comment]
will be fixed by this PR https://github.com/AirSkyBoat/AirSkyBoat/pull/2558
