### ISSUE TITLE
🐛[BUG][Quest] A Timely Visit 

### ISSUE THREAD

**Issue by Sennar1593** [HorizonFFXI/HorizonXI-Issues#828]
What does this bug affect?

**Steps to Reproduce**
After killing the NM  at (F-5) in Jugner Forest, he player is supposed to examine the the ??? again, and a Cutscene should play. What happens is that the intead of getting the cutscene to play out, the NM pops again, and again, and again, no matter how many times it get's defeated.

**Expected behavior**
https://www.bg-wiki.com/ffxi/A_Timely_Visit

**Screenshots**
https://imgur.com/a/uqSfInA
https://imgur.com/a/uqSfInA

**Setup Information**
Windows 10, Horizon XI client, game launched from Horizon Launcher 

**Additional context**
![Dinar_2023 01 12_234313](https://user-images.githubusercontent.com/90145418/212408515-1148777f-08ee-4854-b129-5bd5afd26a12.png)
![Dinar_2023 01 12_234549](https://user-images.githubusercontent.com/90145418/212408545-7244d50f-032f-4985-900a-47e5b5cfd9f6.png)
![Dinar_2023 01 12_234609](https://user-images.githubusercontent.com/90145418/212408558-f6250a3b-0607-4207-9d02-fbae8f8f3dec.png)

**Comment by dallano** [comment]
I believe I saw a PR that fixed this issue. Is this still occurring?

**Comment by Sennar1593** [comment]
Still happening for me

Il mar 17 gen 2023, 00:23 Abdiah ***@***.***> ha scritto:

**Comment by dallano** [comment]
grazie mille

**Comment by dallano** [comment]
Fixed here: https://github.com/dallano/server/commit/702b52b9bedc3de197c876bb1bd211b19aea40fa
