### ISSUE TITLE
🐛[BUG][Combat] Light Spirit is not using any beneficial spells

### ISSUE THREAD

**Issue by CriticalXI** [HorizonFFXI/HorizonXI-Issues#83]
Light Spirit is not using any beneficial spells. It will not cure/pro/shell/haste.

**Comment by Squinkerdoodle** [comment]
(75 smn while checking this) Just wanted to add that it does cast spells when in battle such as dia / banish / holy and I even had mine cast protect 4 / shell 4 / regen on me while fighting something, but while idle it would not cast anything on me even when I had red hp which should trigger cure 5 / curaga 4.

**Comment by Squinkerdoodle** [comment]
Also I noticed that in battle spirits cast spells as soon as they're summoned, and you can release / resummon after they cast a spell to have them cast another spell right after they're summoned. This allows you to skip the internal time spirit's have between casts - not sure if this is correct or not.
