### ISSUE TITLE
🐛[BUG][NPC] Phantom Worm ???s are respawning too fast

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#830]
**What does this bug affect?**

Phantom Worm and maybe Morion Worm
**Steps to Reproduce**

spawn and kill the worm NMs. Time the depop of the body to when the ??? respawns, observe that its 5~ minutes.

**Expected behavior**

15 minute respawn on the ???s 

**Additional context**

https://ffxiclopedia.fandom.com/wiki/Phantom_Worm?oldid=200003

**Comment by TracentEden** [comment]
Were you able to test Morion? Morion and Phantom are using different code for spawning at the moment, Morion was fixed some weeks ago but Phantom not yet so that is probably bugged.

**Comment by montijin** [comment]
Morion does seem fixed. 

> Were you able to test Morion? Morion and Phantom are using different code for spawning at the moment, Morion was fixed some weeks ago but Phantom not yet so that is probably bugged.
