### ISSUE TITLE
🐛[BUG]Combat. Benediction not removing debuffs

### ISSUE THREAD

**Issue by SpaggiG** [HorizonFFXI/HorizonXI-Issues#832]
**What does this bug affect?**

Was silenced and blinded fighting anticans, used Benediction and healed full hp, but was still silenced/blinded

**Steps to Reproduce**

get a debuff, use benediction

**Expected behavior**

Full heal HP and debuffs removed

**Comment by TracentEden** [comment]
Benediction did not remove debuffs in CoP Era :) (see [here](http://www.playonline.com/pcd/update/ff11us/2006041883vPh1/detail.html) for patch notes with the change)

**Comment by SpaggiG** [comment]
ahh i guess, the tooltip still says the debuff part so thats incorrect at least
