### ISSUE TITLE
🐛[BUG][NPC/Combat Tiamat sleeps in the air.]

### ISSUE THREAD

**Issue by Skold177** [HorizonFFXI/HorizonXI-Issues#84]
**What does this bug affect?**
Tiamat in Attowha Chasm

Tiamat is able to be slept in the air,

**Steps to Reproduce**

Sleep on Tiamat in the air.

**Expected behavior**

Tiamat should resist sleep in the air 100% of the time.

**Screenshots**

**Setup Information**

**Additional context**

**Comment by Frankie-hz** [comment]
> Tiamat should resist sleep in the air 100% of the time.

This is actually incorrect. Tiamat can be slept in the air but it instantly falls off following its next auto attack. I have a capture of this but it will take a little time to upload. Will link it here and in the capture discord when its up.

**Comment by dallano** [comment]
Does he currently wake up immediately after? or does that still need to be implemented? @Frankie-hz

**Comment by CriticalXI** [comment]
Fixed in https://github.com/AirSkyBoat/AirSkyBoat/pull/1197
