### ISSUE TITLE
🐛[BUG] Yhoator Jungle harvesting points do not spawn

### ISSUE THREAD

**Issue by ThecraftyLion** [HorizonFFXI/HorizonXI-Issues#840]
**What does this bug affect?**

Yhoator Jungle Harvesting points dont spawn.

Unable to farm
**Steps to Reproduce**
Login / out, zone in / out, etc. Camp all points with multiple people the entire day.

**Expected behavior**
Harvesting points should simply appear

**Screenshots**
Not needed
**Setup Information**
Has nothing to do with bug.... but windows pc

**Additional context**

Every private server I have played on, had the same issue and they just needed to be turned on or something. NAS, wings, eden all had the same bug. It was fixed rather quickly each time.

**Comment by CriticalXI** [comment]
Fixed is AirSkyBoat/AirSkyBoat#2437
