### ISSUE TITLE
🐛[BUG] [Launcher] 1.1.4 does not initiate

### ISSUE THREAD

**Issue by captOFP** [HorizonFFXI/HorizonXI-Issues#842]
**What does this bug affect?**
Unable to run the launcher to access the game.

**Steps to Reproduce**
refer to <https://horizonxi.com/play-now>, clicked step 2 to download the vers. 1.1.4 launcher
also refer <https://discordapp.com/channels/933423693848260678/1054105839931244674>, clicked v1.1.4 launcher link
...upon completion of setup.exe file download, i right clicked admin+run, and immediately got an "installation has failed" notice.

**Expected behavior**
v1.1.4 launcher setup.exe should run, and then be accessible 

**Screenshots**
![horizonpic](https://user-images.githubusercontent.com/121897136/212580737-d9f718ac-c067-46f4-8cb4-00172149af30.png)

**Setup Information**
windows11 / was using previous launcher version less than 12 hours ago and all was running smoothly.

**Additional context**
also attempted clearing %appdata% caches; as well as a FULL DELETE and redownload of everything, still no-joy.  same outcome occurs when trying to clean download launcher with no existing horizon files.

**Comment by Flam9** [comment]
There shouldn't be any difference to the install from 1.1.3 and 1.1.4, only scripts were changed, and not the binary. That said, you can try an older version from https://github.com/HorizonFFXI/HorizonXI-Launcher-Binaries/releases 

You may have had an Antivirus delete some files sneakily, and corrupted the launcher. Whitelist it and reinstall.
