### ISSUE TITLE
🐛[BUG][NPC/Quest] Reap What You Sow

### ISSUE THREAD

**Issue by Zacattack122** [HorizonFFXI/HorizonXI-Issues#844]
**What does this bug affect?**

NPC Mashuu - Ajuu does not take either items in order to complete quest. Sobbing Fungus or Deathball
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by Clonegoat** [comment]
Can add attempted to turn in deathball just now, Mashuu-Ajuu will not accept it

**Comment by Clonegoat** [comment]
This was marked as fixed as of 2 weeks ago, but I'm still unable to turn in a deathball for this quest

**Comment by hookstar** [comment]
Is the deathball for Let sleeping dogs lie?

**Comment by hookstar** [comment]
I see what happened. Someone else and I PR'd let sleeping dogs lie and the other person rolled reap what you sow into that same PR of theirs. Only the let sleeping dogs lie got pushed - I will work it tomorrow.

**Comment by Clonegoat** [comment]
Any updates? Another 2 weeks now and I know it's just a small quest for a piece of furniture, but..

**Comment by hookstar** [comment]
Not sure where the other author went to - will look into this weekend

**Comment by Clonegoat** [comment]
:) just wanted to check in again, another 3 weeks down and a few patches later and it's still broken.
