### ISSUE TITLE
🐛[BUG][Combat] Adamantoise gil is wrong.

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#845]
**What does this bug affect?**

Adamantoise
**Steps to Reproduce**

Kill Adamantoise, observe a sad amount of gil.
**Expected behavior**

Kill Adamantoise and get rich.

**Additional context**

https://ffxiclopedia.fandom.com/wiki/Adamantoise

**Comment by Leaute** [comment]
![image](https://user-images.githubusercontent.com/118570028/212623846-5535201b-4c5e-43e6-9710-c56d756b3b82.png)
9 People x 3.3k Each 

![image](https://user-images.githubusercontent.com/118570028/212624106-17213333-b60d-481b-b15e-cea1b943be33.png)
5 people x 6.2k Each

Both videos 13+ years old.
