### ISSUE TITLE
🐛[BUG][NPC] Traveling Troupe not appearing in 1st place Nation

### ISSUE THREAD

**Issue by Robynfb** [HorizonFFXI/HorizonXI-Issues#847]
**What does this bug affect?**
The Traveling Troupe that appears in the nation that is 1st place in conquest has not been manually added yet to the nation of Bastok for this conquest tally

**Steps to Reproduce**
N/A

**Expected behavior**
When visiting Bastok there should be a few npcs that have various functions, the only ones i'm aware of atm is Nokkhi Jinjahl who is used to quiver certain stacks of arrows given to her alongside a carnation.

**Screenshots**
N/A

**Setup Information**
N/A

**Additional context**
N/A

**Comment by greg-szrama** [comment]
Confirming this bug is present in other nations. Last week San d'Oria was first place and the travelling troupe was not there. The other key NPC is Ominous Cloud - he provides ninjutsu toolbags.
