### ISSUE TITLE
🐛[BUG][NPC] Tres Duendes Respawn Time Too Fast (21-24 hours) -> (15 minutes)

### ISSUE THREAD

**Issue by rafiina** [HorizonFFXI/HorizonXI-Issues#848]
**What does this bug affect?**
This NM originally had a 21-24 respawn time.  Currently, it is respawning after about 15 minutes.  This NM occupies the room closest to door for CoP 2-3 and only convenient location to farm for a Bronze Key.

**Steps to Reproduce**
Kill Tres Duendes, wait approximately 15 minutes for respawn.

**Expected behavior**
Kill Tres Duendes, wait 21-24 hours for respawn.

**Screenshots**
No screenshot on this one.

**Comment by hookstar** [comment]
This was addressed in a recent NM patch. Closing for now. Please reopen if it reverts back to being crazy! 

Thanks!
