### ISSUE TITLE
🐛[BUG][System] Chocobos are rideable in Romeave.

### ISSUE THREAD

**Issue by Slynkee** [HorizonFFXI/HorizonXI-Issues#849]
**What does this bug affect?**
Chocobos are rideable in Romeave.

**Steps to Reproduce**
Ride your chocobo from zitah into Romeave

**Expected behavior**
Should be dismounted off chocobo 

**Screenshots**
https://i.imgur.com/lNsnO3s.png

**Comment by Frankie-hz** [comment]
Fixed in: https://github.com/AirSkyBoat/AirSkyBoat/pull/2526
