### ISSUE TITLE
🐛[BUG][Combat] Mobs don't use abilities against wyverns in battlefields

### ISSUE THREAD

**Issue by dallano** [HorizonFFXI/HorizonXI-Issues#85]
**What does this bug affect?**

Mobs ability use on wyverns that were called before entering the battlefield

**Steps to Reproduce**

- Call a wyvern
- Enter the battlefield
- Have the wyvern get hate from a mob

**Expected behavior**

Mob should be able to use mob skills on it

**Actual behavior**
Mobs either don't use mob skills at all, or behave extremely strange. in some cases: https://github.com/HorizonFFXI/HorizonXI-Issues/issues/41

**Comment by Squinkerdoodle** [comment]
Did this happen with SMN or BST pets? They've been attacked while I've tested BCNM / ENMs, haven't really tested on DRG's pet but I did see it happen in that Toadal Recall bug report.

**Comment by The-Aerec** [comment]
The battlefield id is probably not being sent to the pets correctly, so while the pets are there. They arn't really in the bcnm. (Would be my guess.)

**Comment by dallano** [comment]
It seems to only happen wyverns as they can be called before entering the battlefield. Where BST and SMN (even PUP)'s pets must be summoned inside the battlefield.

**Comment by jmcmorris** [comment]
Submitted a PR to fix this over on LSB - https://github.com/LandSandBoat/server/pull/2743
![image](https://user-images.githubusercontent.com/1189557/190864577-8a1ef19b-a6ac-4d02-8e6b-a194237434de.png)

**Comment by dallano** [comment]
oh my god, you're great! Thank you!

**Comment by jmcmorris** [comment]
I'd leave this open until the PR is accepted :)

**Comment by dallano** [comment]
ope! misclicked close. my bad

**Comment by jmcmorris** [comment]
Fixed on LSB - https://github.com/LandSandBoat/server/pull/2743
