### ISSUE TITLE
🐛[BUG][NPC(?)/Combat] - Gigas' Bat(Pet) links with Other bats.

### ISSUE THREAD

**Issue by HorizonPotato** [HorizonFFXI/HorizonXI-Issues#850]
--Gigas' Bat is linking with other bats.

**Steps to Reproduce**
-Just pull a Bat, Ancient or Seekers, in Lower Delkfutt and if it runs near a Gigas' Bat (BST Pet), the Bat will link with it. 

**Expected behavior**
this should work vice-versa where pulling the Gigas' Bat links the other bats, but as the Gigas' Bat is a pet, it should not be linking with anything but its master.

**Screenshots**
Im sorry I don't have any.

**Setup Information**
Current Version (Up to date)

**Additional context**
Had the issue happen twice while exping in lower Delkfutt and knew it shouldn't work that way is all.

**Comment by Frankie-hz** [comment]
Fixed in : https://github.com/AirSkyBoat/AirSkyBoat/pull/2526

**Comment by HorizonPotato** [comment]
Exping in Delkfutt today and its still happening, so if it was fixed, its broken again.
