### ISSUE TITLE
🐛[BUG][NPC/Combat]White Rabbits using incorrect TP Move: Wild Ginseng

### ISSUE THREAD

**Issue by JowstonTTV** [HorizonFFXI/HorizonXI-Issues#851]
**What does this bug affect?**
White Rabbits are currently using Wild Ginseng instead of Wild Carrot. Wild Ginseng is a Monstrosity move that shouldn't be used by NPC Monsters. Observed with the Variable Hares in Uleleleguauguard Range

**Expected behavior**
White Rabbits should be using Wild Carrot not Wild Ginseng

**Additional context**
https://www.bg-wiki.com/ffxi/Category:Rabbit
https://www.bg-wiki.com/ffxi/Wild_Ginseng_(MON)
https://www.bg-wiki.com/ffxi/Rabbit_(MON)

**Comment by dallano** [comment]
This ability was based from live captures and recordings. The wikipedia is incomplete.

**Comment by HorizonPotato** [comment]
I'm sorry to bump this but where was this information gathered?  I've gathered information from every wiki and non-wiki source, in English and Japanese, and the >only< Mobs in the game who use this TP move, that isn't Monstrosity related, is a Rabbit in the ENM "Follow the White Rabbit".
