### ISSUE TITLE
🐛[BUG][System] PC Freezing and Crashing

### ISSUE THREAD

**Issue by Milozilla** [HorizonFFXI/HorizonXI-Issues#853]
**What does this bug affect?**
Every now and then my computer freezes then restarts, and seems to only happen while I Play FFXI

It started happening when I began adventuring in Buburimu Peninsula and especially in Meriphataud Mountains it happened in combat or simply walking.

**Expected behavior**
shouldn't be causing pc restarts

**Setup Information**
Horizon Launcher v1.1.4 Horizon XI Ver.30221103_1, Browser Chrome and Windows 10.

**Additional context**
PC info if needed
Processor	AMD Ryzen 5 1600 Six-Core Processor 3.20 GHz
Installed RAM	16.0 GB
System type	64-bit operating system, x64-based processor
Graphics Card  NVIDIA GeForce GTX 1050 TI

**Comment by CriticalXI** [comment]
Not an issue with the code repository, please seek support in the Horzion technical support channel
