### ISSUE TITLE
🐛[BUG][System/Combat]Spirit Link not removing paralysis from wyvern.

### ISSUE THREAD

**Issue by Luaithel** [HorizonFFXI/HorizonXI-Issues#854]
**What does this bug affect?**

Dragoon's Spirit Link doesn't remove Paralysis from wyvern.

**Steps to Reproduce**

Have wyvern get paralyzed.  Use Spirit link.

**Expected behavior**

Spirit link is supposed to remove paralysis from the wyvern when used in era.

**Screenshots**

![SL big](https://user-images.githubusercontent.com/121269267/212817390-25f83856-4611-4839-9f5a-15f7319a9394.jpg)

**Setup Information**

**Additional context**

Happened with Nival Raptor in Uleguerand Range from their frost breath.

**Comment by TracentEden** [comment]
Actually after further checking paralysis is not one of the effects that spirit link removes (can see testing [here](https://www.ffxiah.com/forum/topic/44396/sigurds-descendants-the-art-of-dragon-slaying/108/#3646578))
