### ISSUE TITLE
🐛[BUG][Quest] Unable to flag The Missing Piece

### ISSUE THREAD

**Issue by okronoss** [HorizonFFXI/HorizonXI-Issues#855]
**What does this bug affect?**
I am unable to flag The Missing Piece quest in Rabao. I have rank 4 reputation for Selbina/Rabao. I submitted a gm ticket and they verified I should be able to flag this quest and suggested I submit a bug report.

**Steps to Reproduce**
Attain rank 4 rep in Selbina/Rabao. 
Talk to Alfesar.

**Expected behavior**
Alfesar should give dialog to start the quest.

**Screenshots**
![image](https://user-images.githubusercontent.com/4312702/212955124-c35e0cf7-be52-451c-9488-c23c9d98dec5.png)
![image](https://user-images.githubusercontent.com/4312702/212955299-8e449304-64c2-4e0c-89a9-bbf8960c29ee.png)

**Setup Information**

**Additional context**

**Comment by hookstar** [comment]
I am unable to replicate this locally. Check to see what fame level you are in bastok and sandy.

**Comment by okronoss** [comment]
Bastok is fame 4, but Sandy is only fame 3.

For this quest I thought only the Rabao fame was taken into account? (which shows as fame 4)

**Comment by hookstar** [comment]
Were you able to get the quest after getting sandy rank 4?

**Comment by okronoss** [comment]
Yes, once I got Sandy rank 4 reputation I was able to get the quest.

**Comment by hookstar** [comment]
Very good. Thanks for the ticket.
