### ISSUE TITLE
🐛[BUG][System] Equipping Nadrs on my Galka THF crashed my game, unable to play now.

### ISSUE THREAD

**Issue by MedicXI** [HorizonFFXI/HorizonXI-Issues#857]
**What does this bug affect?**
Unable to get passed main menu. "Select Character" or even "Delete Character" results in everything shutting down, no errors, no anything.

**Steps to Reproduce**
Galka THF25/NIN12 wearing Nadrs (I went to put it offhand when all this started)

**Expected behavior**
As soon as you select the weapon Instant Crash, Unable to even play again due to model issues it seems?

**Screenshots**
Sorry nothing to screenshot beyond FFXI Main Menu there, then its gone.

**Comment by MedicXI** [comment]
Did a little research if it help at all. I was a Galka: Face 8, Style A, Large, Mnk starting job. 

https://horizonxi.com/players/Darkassassin

**Comment by MedicXI** [comment]
I'm sorry I don't want to sound needy or whine, but this bug is leaving me literally un able to play. At this point I wish a blackscreen was my only issue.

**Comment by The-Aerec** [comment]
> I'm sorry I don't want to sound needy or whine, but this bug is leaving me literally un able to play. At this point I wish a blackscreen was my only issue.

This issue ticket is only for bug reports, please submit a GM ticket via the discord to get the in game issue fixed. Most developers don't have the ability to help with in game issues.

**Comment by MedicXI** [comment]
> > I'm sorry I don't want to sound needy or whine, but this bug is leaving me literally un able to play. At this point I wish a blackscreen was my only issue.
> 
> This issue ticket is only for bug reports, please submit a GM ticket via the discord to get the in game issue fixed. Most developers don't have the ability to help with in game issues.

Henrik helped me on my ticket yesterday. Reinstalled the game and left a post on Technical Support, but was also told to come here and post this. Just doing what I'm told to get help, thanks.

**Comment by CriticalXI** [comment]
Issue is a corrupted DAT which a fix for can be found at https://discord.com/channels/933423693848260678/1072685158743949312/1072685158743949312

This should be pushed out to all players in 1.1 patch.
