### ISSUE TITLE
🐛[BUG][Combat] Hide does not deaggro scent tracking monsters when used in Water

### ISSUE THREAD

**Issue by jasonm323** [HorizonFFXI/HorizonXI-Issues#858]
**What does this bug affect?**
The Thief ability Hide should stop aggro on monsters.  Sight monsters deaggro instantly no problem.  Monsters that track by scent will continue to be aggressive unless Hide is used in a puddle of water (Example: Boyhada Tree) or any small ponds that you're character can run through.

**Steps to Reproduce**
Aggro a scent tracking monster and use hide in water.

**Expected behavior**
Monsters should deaggro and stay that way unless they reaggro via sound.

**Screenshots**
Unable to add

**Setup Information**
30221103_1

**Additional context**
Can be difficult to reproduce as some monsters will still aggro sound if they are too close when you use hide.

**Comment by TracentEden** [comment]
Yeah this is for sure an issue, however I will close as I am consolidating remaining hide special cases under the following issue https://github.com/AirSkyBoat/AirSkyBoat/issues/1384 . Thanks for the report.
