### ISSUE TITLE
🐛[BUG] BCNM - Eye of the Tiger

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#86]
**What does this bug affect?**
Gerjis' Grip (stun gaze tp move) stuns you even with your back turned.

**Steps to Reproduce**
Go into the BCNM and with your back turned to Gerjis, feed it tp until it uses the tp move Gerjis Grip.

**Expected behavior**
Gerjis Grip should have no effect on the player if they have their back facing Gerjis.

**Setup Information**
Version 30220802_3

**Additional context**
Watched capture and the move had no effect with back turned to NM.

**Comment by dallano** [comment]
bug fix in https://github.com/AirSkyBoat/AirSkyBoat/pull/376
