### ISSUE TITLE
🐛[BUG][Launcher] Permanent "unable to connect to world server"

### ISSUE THREAD

**Issue by SkullLeaderSDF** [HorizonFFXI/HorizonXI-Issues#860]
**What does this bug affect?**
Unable to login. Error FFXI-3305

**Steps to Reproduce**
Not sure how to reproduce but it started with a black screen while zoning out of the MH from Ru'Lude Gardens. When I tried to login back in I received a "unable to connect to world server" error. I made a ticket which Henrik and Ceodon cleared the login issue multiple times just to have it boot me again the first time I zoned after logging back in and giving me the "unable to connect to world server" error again.

**Expected behavior**

**Screenshots**

**Setup Information**
The Horizon launcher V1.1.4 (though I'm using Windower V4.37757.25903), HorizonXI Ver1 

**Additional context**
 I was able to login to my second character and zone without issue but as soon as I logged back on the character that the issue started on it continued to boot me the first time I zoned.  Also for some reason my main character run animation  was moving at flee speed but my actual character speed was normal. The animation speed looked similar to the speed during any CS while FastCS in enable which I do have enabled.

**Comment by Frankie-hz** [comment]
Please submit a ticket to our discord for things like this: https://discord.com/channels/933423693848260678/1048398756749520966/1063946126975324251
