### ISSUE TITLE
🐛[BUG][Quest]Issue with obtaining Nanaa's Charm.

### ISSUE THREAD

**Issue by flipcork** [HorizonFFXI/HorizonXI-Issues#863]
**What does this bug affect?**
While doing the quest for Nanaa's Charm, clicking on the final location to receive the charm the message "You find a lucky necklace made for you by Nanna Mihgo." the Nanaa's Charm however was not added to my inventory.

**Steps to Reproduce**
Do the steps leading up to obtaining the Nanaa's Charm.  Once told where to collect the item proceed to the location.  Click on the location to get the charm.  The message is given for completion however the reward is not received.

**Expected behavior**
Nanaa's Charm should be added to inventory once receiving the message, and completing the quest.

**Screenshots**
![charmglitch](https://user-images.githubusercontent.com/22583788/213062897-8951ad66-d47e-4b72-a316-d6013799fd8f.PNG)
![charmglitch2](https://user-images.githubusercontent.com/22583788/213062900-3672c1fe-650c-4930-a8a4-1157c1a6d436.PNG)

**Setup Information**
/ver 30221103_1

**Additional context**
Tried logging out/zoning to see if that would fix it and it did not.  To add, once you leave are unable to re-enter the area with the ???.  Door does not reopen for you.

**Comment by CriticalXI** [comment]
Fixed in a recent patch
