### ISSUE TITLE
🐛[BUG] BCNM - Up In Arms

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#87]
**What does this bug affect?**
Mob's sleep resistance for Sleep magic & Lullaby. Able to reliably sleep / lullaby NM (no godmode) with no equipment other than Light / Dark staff. Started getting some resists after the 25th time the mob was slept, seems the resists should start earlier though this may be a general issue with mob's resistances.

**Steps to Reproduce**
Go into the fight and cast Sleep / Lullaby on the NM repeatedly.

**Expected behavior**
NM should build resistance to sleep / lullaby.

**Setup Information**
Version 30220802_3

**Additional context**
This may be a general issue with mob's resistances, but wanted to submit a form for this BCNM specifically since repeated sleeps may make it easier than intended.

**Comment by dallano** [comment]
mob resistance builds should work properly now with fix PR : https://github.com/AirSkyBoat/AirSkyBoat/pull/376
