### ISSUE TITLE
🐛[BUG][Combat] Receiving skillups from under level mobs 

### ISSUE THREAD

**Issue by PasiXI** [HorizonFFXI/HorizonXI-Issues#873]
Combat bug

**What does this bug affect?**
I'm level 62 fighting tigers that are Level 29-34 receiving Evasion skill ups. 

**Steps to Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/108941476/213318637-1ffc975b-024c-487d-90e6-c5c2cc88f2db.png)

**Setup Information**

**Additional context**

**Comment by TiberonKalkaz** [comment]
+1 - im getting evasion skill ups for level 57+ as a level 60 war fighting an EP (lvl42) spider.

**Comment by ThiefFFXI** [comment]
I am getting skill ups on lvl 30 mobs at lvl 57.
