### ISSUE TITLE
🐛[BUG][Quest] Chasing Dreams does not require all 4 Giant Clams

### ISSUE THREAD

**Issue by siknoz** [HorizonFFXI/HorizonXI-Issues#879]
**What does this bug affect?**
In the Korroloka steps of Chasing Dreams (https://ffxiclopedia.fandom.com/wiki/Chasing_Dreams) clicking any of the Giant Clams will return a full flask. It should require clicking all 4, not just 1.

**Steps to Reproduce**
Flag Chasing Dreams quest, progress up to Korroloka steps, click any Giant Clam and receive full flask immediately.

**Expected behavior**
Should need to click all 4 giant clams before it becomes full.

**Screenshots**
Zoned in
![image](https://user-images.githubusercontent.com/78240569/213527973-6f2893ea-65db-4425-a79d-960bb88ec732.png)
Clicked first clam
![image](https://user-images.githubusercontent.com/78240569/213527913-ac0ad27d-267c-468b-a7f3-9b0be07cb648.png)

**Setup Information**
N/A

**Additional context**
N/A

**Comment by hookstar** [comment]
https://github.com/HorizonFFXI/HorizonXI-Issues/issues/667

Thank you for the ticket. Closing as duplicate.
