### ISSUE TITLE
🐛[BUG] BCNM - Wild Wild Whiskers

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#88]
**What does this bug affect?**
NM's silence resistance after first silence. After first silence NM casts spells other than Burst. NM does not use Frenzied Rage after it's casting is interrupted. After killing the NM there is no chest that spawns in the arena to award loot / fight completion.

**Steps to Reproduce**
Go into the BCNM and use silence on the NM, and paralyze after the silence wears off to try to interrupt the NM's casting. After the first silence the NM will cast it's thunder / thundaga spells, instead of only Burst as seen in the capture.

**Expected behavior**
NM should only cast Burst after the first silence wears off as seen in the capture. NM should use the move Frenzied Rage when it's casting is interrupted (due to paralyze or stun for example).  After beating the NM the normal treasure chest should spawn in the arena to award you loot and complete the fight.

**Setup Information**
Version 30220802_3

**Additional context**
The wiki states the NM should resist silence after the first one wears off, and I don't recall seeing a second silence land in the capture.  I was able to silence the NM repeatedly. Not sure if this should be a thing or not. Additionally the wiki states you should not be able to stun the NM while it is casting Burst, but I was able to stun with BLM 60. The capture is from a SMN pov using Thunderspark so not able to verify.

**Comment by dallano** [comment]
Partial fix in https://github.com/AirSkyBoat/AirSkyBoat/pull/376 for macan casting other spells at rank 5. The issue was he kept leveling after 5! lol

**Comment by dallano** [comment]
Full fix in: https://github.com/AirSkyBoat/AirSkyBoat/pull/376
