### ISSUE TITLE
🐛[BUG][Combat] Claimshield allows me to charm a mob.

### ISSUE THREAD

**Issue by ThiefFFXI** [HorizonFFXI/HorizonXI-Issues#881]
**What does this bug affect?**

Claimshield will allow me to charm a mob through it.
**Steps to Reproduce**

Go to a mob with Claimshield that is charmable. Spam Charge as it spawns
**Expected behavior**

It uses my charm as a ticket in the lottery and may bind the mob
**Screenshots**

![image](https://user-images.githubusercontent.com/123122366/213559368-178bb024-0538-4f35-8f7d-ce952bfc34bb.png)

**Setup Information**

**Additional context**

**Comment by Frankie-hz** [comment]
Stropher Chymes are charmable
