### ISSUE TITLE
🐛[BUG][NPC/Quest] Reap what you sow quest not working

### ISSUE THREAD

**Issue by Corwizard** [HorizonFFXI/HorizonXI-Issues#883]
**What does this bug affect?**
Cannot complete the quest, when attempting to trade the item [Sobbing Fungus]  to the NPC nothing happens, and the item "Stationery Set" cannot be rewarded.

**Steps to Reproduce**
Receive the quest 'Reap what you sow' from NPC [Mashuu-Ajuu]- [Windurst Waters] North (K-6), Get the item [Sobbing Fungus], attempt to trade the item to NPC

**Expected behavior**
The quest should complete and reward the player with 500-700gil and the 'Stationary Set' Mog House item

**Screenshots**

**Setup Information**
Current Version of Game & Launcher (as of 1/19/2023), Running Ashita v4.15, Windows 11, Intel 10850, 32g Ram, Nvidia RTX 3060ti. 

**Additional context**

**Comment by Leakitty13** [comment]
I have the same issue with this quest.

**Comment by dallano** [comment]
Fix is incoming guys! Sorry for the inconveniences
