### ISSUE TITLE
🐛[BUG][System] Desynth Flute results

### ISSUE THREAD

**Issue by MGramolini** [HorizonFFXI/HorizonXI-Issues#884]
**What does this bug affect?**

Desynth Flute HQ results always maple lumber.

**Steps to Reproduce**

Desynth lots of Flutes

**Expected behavior**

at least 50% of HQ results should be Parchment (HQ1)

**Screenshots**

**Setup Information**

30221103_1

**Additional context**

https://ffxiclopedia.fandom.com/wiki/Flute?oldid=152016

**Comment by hookstar** [comment]
https://ffxiclopedia.fandom.com/wiki/Flute

**Comment by hookstar** [comment]
NQ result is parchment, HQ desynth is maple lumber.
Not sure I follow?

**Comment by MGramolini** [comment]
That wasn't changed until around 2015, which is past any era we are considering.
