### ISSUE TITLE
🐛[BUG][NPC/Quest] Unable to start the quest "Healing the Land" for Teleport-Holla from Eperdur

### ISSUE THREAD

**Issue by guyjin37** [HorizonFFXI/HorizonXI-Issues#885]
**What does this bug affect?**
I have rank 5 fame in Sandy, yet I am unable to trigger the quest "Healing the Land" for the Teleport-Holla scroll from Eperdur in N Sandoria.

**Steps to Reproduce**
1. Be me.
2. Talk to Epurdur on any job above 10.
3. He does not mention a foul wind in Gusgen Mines and the quest does not appear in my log.

**Expected behavior**
1. Be me.
2. Talk to Epurdur on any job above 10.
3. He mentions a foul wind in Gusgen Mines and the quest appears in my log.

**Screenshots**

**Setup Information**

**Additional context**
I am not the only person with this issue according the the bug finder channel in Discord.

**Comment by hookstar** [comment]
What is your fame level?

**Comment by guyjin37** [comment]
Level 5, verified by NPC in Southern Sandy.

**Comment by Zenofire** [comment]
I believe i had a LS member with the same problem, did you try spam talking to him? my linkshell member mentioned he had to speak to him like 5+ times in a row before he finally got the quest.

**Comment by hookstar** [comment]
I'm at work currently but we believe it may be an issue where the npc is getting hung up if the player is also on the tele new quest. Either way I am in the process of rewriting them.

**Comment by guyjin37** [comment]
I hadn't tried to spam, I think I gave up after 3 tries. Understood Hookstar, thanks.
