### ISSUE TITLE
🐛[BUG][NPC/System] Barge Multi-ticket

### ISSUE THREAD

**Issue by Ystial** [HorizonFFXI/HorizonXI-Issues#887]
**What does this bug affect?**
The Barge Multi-ticket is not removed at 0 uses remaining nor rechargeable through the NPC at the Central Landing Docks.
It also reached 0 uses being used only one time, every other time I attempted to use the barge it failed and left me behind.
I was not able to even buy a single ticket, so I needed a GM to remove the KI entirely.

**Steps to Reproduce**
Purchase Multi-ticket
Board the barge (I died on the barge and HP'd a long time ago)
Try to repurchase Multi-ticket

**Expected behavior**
The Multi-ticket is rechargeable / repurchaseable.
It might be that it should be removed on 0 uses remaining.

**Screenshots**
![Edouart_2023 01 19_144818](https://user-images.githubusercontent.com/118680256/213723089-3a92d000-e906-4fca-8633-0c76a1ea6e61.png)
![Edouart_2023 01 19_144932](https://user-images.githubusercontent.com/118680256/213723105-96a71140-4fcb-450c-adad-d87afda9d0f3.png)

**Setup Information**

**Additional context**

**Comment by Frankie-hz** [comment]
@Ystial you should be all fixed!
