### ISSUE TITLE
[BUG][Combat] Counterstance for MNK is still nonfunctional

### ISSUE THREAD

**Issue by markcasper88** [HorizonFFXI/HorizonXI-Issues#889]
What does this bug affect?
The monk job ability obtained at level 45, 'Counterstance'. 

Expected behavior
Counter rate should be increased by +45%, and defense should be calculated by the user's full VIT score (era) or by half their total defense (retail).
Instead, counter rate is increased by +0% and defense becomes HALF of the user's VIT.

I hope that when the team re-examines Counterstance to fix this glaring bug that makes this ability have no benefit, they also reconsider balance in 1.1. Counterstance has historically been hyper-situational to avoid a monk tank meta, and many people hoped Horizon would adjust this job to allow monks to off-tank effectively.

Setup Information
Horizon XI, latest patch as of Jan 20

Additional context

Testing results 

Test #1
Pre-patch, no counterstance, no buffs, weak enemies (98%+ accuracy)
200 hits taken
21 counters

Counter rate 21/221 = 9.5%

Test #2
Pre-patch, counterstance, no additional buffs, weak enemies (98%+ accuracy)
200 hits taken
20 counters

Counter rate 20/220 = 9.1%

Test #3
Pre-patch, counterstance, counter +2 gear, EP enemies
83 hits taken
17 counters

Counter rate 17/100 = 17%

Test #4
Most recent patch, counterstance, counter +2 gear, EP/TW enemies
85 hits taken
8 counters

Counter rate 8/93 = 8.6%

Example encounter:
Counterstance on, Counter +2 gear, EP Enemy
![image](https://user-images.githubusercontent.com/12213955/213792548-fdd2c692-4a1b-457f-967d-66fbbb51bc59.png)

11 successful attacks by the enemy in a row with 0 counters. Estimating a counter rate of 50% with counterstance and counter +2 gear (a conservative estimate), this would be akin to flipping a coin and it landing on tails 11 times in a row. That odds outcome is a .05% if the counter rate was truly 50%. Given the rest of the testing, it is much more likely that the counter rate is staying around the base rate of 10%.

**Comment by TracentEden** [comment]
Yeah, this change was not included in any update yet, the closing of a github issue just means the fix has been merged into codebase, not that it has been pushed to live server, for that you have to check the patch notes. Sorry for the confusion.
