### ISSUE TITLE
🐛[BUG] BCNM - Demolition Squad

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#89]
**What does this bug affect?**
Main NM's (Moatfiller) sleep resistance. Mob's initial placement, currently spread in a square when capture has the main NM (Moatfiller) up front with the 3 smaller NMs behind but within sleepga range. Main NM (Moatfiller) currently used Familiar in the fight, in the capture it used Charm instead as it's 2hr. All NMs use Lightning Roar, should be Ice Roar per capture.

**Steps to Reproduce**
Check mob placement before engaging. Go into BCNM and cast Sleep magic & lullaby on main NM to see if it lands. Fight NM until it uses 2hr, which is currently Familiar.

**Expected behavior**
In the capture the mob's initial placement is different, it has them in a small group with Moatfiller up front and all 4 within sleepga range. Additionally in the capture Moatfiller uses a 2hr of Charm instead of Familiar. Lastly the capture showed that Moatfiller was completely immune to an Elemental Seal + Sleepga 2 so it seems it should be immune to sleep magic, and probably lullaby as well. NMs in this fight should use Ice Roar instead of Lightning Roar.

**Setup Information**
Version 30220802_3

**Additional context**
The BST NM (Moatfiller) does not have a pet in this fight so it's current 2hr of Familiar is pretty pointless.

**Comment by dallano** [comment]
Fix in PR: https://github.com/AirSkyBoat/AirSkyBoat/pull/376
Fixes for main mob using charm, added HP, added sleep immunity to main mob, fixed spawn positioning, removed lightning breath
