### ISSUE TITLE
[BUG][Party System] Removing the last party member aside from yourself will dissolve the party and all loot is lost from the treasure pool.

### ISSUE THREAD

**Issue by Savor** [HorizonFFXI/HorizonXI-Issues#891]
**Repro:**
1. Have 2 members in a party and make sure you're the leader.
2. Open the menu and select Party -> Remove Member to remove the other person in your party.
--->  Your party will be dissolved and all loot in the treasure pool will be lost.

**Expected behavior:**
The party should remain open even with only 1 member.

**Comment by TracentEden** [comment]
There is a fix pending that will fix this.
