### ISSUE TITLE
🐛Using Food in Maat Fight still removes Subjob Restriction

### ISSUE THREAD

**Issue by ArianneMinerva** [HorizonFFXI/HorizonXI-Issues#892]
**What does this bug affect?**

I ate food in Maat fight and it removed the subjob restriction thus allowing me my Subjob during the fight.
**Steps to Reproduce**

Eat Food
**Expected behavior**

Removes subjob restriction
**Screenshots**

**Setup Information**

**Additional context**

**Comment by TracentEden** [comment]
Yep the fix for this has not yet been applied to the live server, closing for now and can reopen if still an issue after the fix makes it onto the server.
