### ISSUE TITLE
🐛[BUG][System] Yhutunga Jungle Chocobo Digging Pools broken.

### ISSUE THREAD

**Issue by JoshLammi** [HorizonFFXI/HorizonXI-Issues#897]
**What does this bug affect?**
Chocobo digging in the Yhutunga jungle does not work and hasn't in a few weeks.

**Steps to Reproduce**
Attempt digging, fail repeatedly regardless of the time of day. Nothing fancy required.

**Expected behavior**
Normal digging behavior, a slowly depleting item pool that resets at 00:00.

**Screenshots**
Not necessary.

**Comment by TracentEden** [comment]
Will be fixed by recent PR (watch patch notes)
