### ISSUE TITLE
🐛[BUG][Quest] Peace for the Spirit (RDM AF Hat) - Miser Murphy and Guardian Statue Missing Mechanics

### ISSUE THREAD

**Issue by KiplingFFXI** [HorizonFFXI/HorizonXI-Issues#9]
**What does this bug affect?**

(1) Miser Murphy: missing en-drain additional effect on auto attacks. 

(2) Guardian Statute: seems to be missing regain effect, it barely used TP moves even at low health. It is supposed to have increasing regain as his HP goes down according to wiki. Also susceptible to sleep + slow + paralyze + blind but wiki says it is immune to all of them.

**Steps to Reproduce**

Do the quest and fight both NMs.

**Expected behavior**

See above.

**Screenshots**

N/A

**Setup Information**

N/A

**Additional context**

N/A

**Comment by dallano** [comment]
Fixed here! :) https://github.com/AirSkyBoat/AirSkyBoat/pull/408
