### ISSUE TITLE
Unable to Switch Language setting

### ISSUE THREAD

**Issue by Unleashedz** [HorizonFFXI/HorizonXI-Issues#901]
Hello, when I launch the horizon launcher, Japanese is selected and it won't unselect, is there a way to fix this?

**Comment by Flam9** [comment]
On the right side of the launcher, click the gear icon and then select English
![image](https://user-images.githubusercontent.com/1020214/223912551-7ecd439c-7226-48ea-969c-ae6f6a849914.png)


If that doesn't work for whatever reason, try running as admin.
