### ISSUE TITLE
🐛[BUG][Combat]  Zdei's reactor cool isn't applying ice spikes.

### ISSUE THREAD

**Issue by ThrisStraizo** [HorizonFFXI/HorizonXI-Issues#904]
**What does this bug affect?**

We've watched several Zdeis use reactor cool and they never got ice spikes from the effect.

**Steps to Reproduce**

Make any Zdei use reactor cool, then auto attack it.

**Expected behavior**

There should be ice spikes, which should paralyze you sometimes.

**Screenshots**

**Setup Information**

**Additional context**

**Comment by gtarrantiii** [comment]
Was able to reproduce. Server logs indicate a bug in the mob script.

**Comment by gtarrantiii** [comment]
Code will be submitted to fix this issue.
![image](https://user-images.githubusercontent.com/16801070/220256041-a0967454-93ad-444e-961b-cdd60d5b593e.png)

**Comment by TracentEden** [comment]
This was fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2974
