### ISSUE TITLE
 🐛[BUG][NPC/Quest] Starlight Celebration Bug

### ISSUE THREAD

**Issue by SilicateWolf** [HorizonFFXI/HorizonXI-Issues#907]
**What does this bug affect?**
One of the four NPCs you're required to deliver presents to in order to complete the Starlight Celebration Snow Token quest has disappeared. He was there as of a few days ago, but has now mysteriously vanished. This makes it impossible to complete the quest in Windhurst, despite the event Moogle still offering the quest and the quest still being completable in San d'Oria.

**Steps to Reproduce**
Go to G-7 north Windhurst Waters. Kayeel-Payeel, the NPC that is supposed to be there, is missing. The NPC should be there even after the Starlight Celebration event is over, so it now being technically past the end date is unlikely to be the cause of the problem.

**Comment by Frankie-hz** [comment]
The starlight has been disabled - due to wrong variables these NPCs should not be there

**Comment by BayaniTenzen** [comment]
Starlight should be disabled
