### ISSUE TITLE
🐛[BUG][NPC]Moblin Repairman has Ancient Bomb Drops

### ISSUE THREAD

**Issue by Ystial** [HorizonFFXI/HorizonXI-Issues#908]
**What does this bug affect?**
Moblin Repairman in Oldton Movalpolos drops Hoary Bomb Ash.

**Steps to Reproduce**
Kill Moblin Repairman to produce drops.

**Expected behavior**
Its droptable should just be Moblin Mask, Moblin Armor, Chest Key and gil.

**Screenshots**
![Edouart_2023 01 22_163641](https://user-images.githubusercontent.com/118680256/213927663-767c1f0e-c1a6-4c3f-b43e-835551049717.png)

**Setup Information**

**Additional context**

**Comment by dallano** [comment]
This appears to be fixed. Thank you for the report!
