### ISSUE TITLE
🐛[BUG][System] Cannot Use Horizon-Specific Warp NPCs 

### ISSUE THREAD

**Issue by Deirdre5017** [HorizonFFXI/HorizonXI-Issues#910]
Cannot Use Horizon-Specific Warp NPCs 

I've posted in the Discord but put it in here as well. My husband is having an issue where he is only able to use the original warp NPCs in Windurst but cannot use the new warp tarus in Windurst Woods/Port Windurst as well as Twinkstix or Rottata (I'm guessing because she was moved?). We didn't realize that this issue was affecting all of these NPCs until the treants were defeated today and he attempted to use the outpost warps.

Mumbo-Bumbo and his twin in Windurst Woods worked fine for him up until about three weeks ago then they began to give the dialogue in chat but not pop up the menu allowing him to confirm he wanted to be warped. 

He reinstalled the game and the issue persisted. He also attempted to login from a different device but still had the same issue (but if I login to that device, I don't have the same issue). 

When he went to talk to Twinkstix in Lower Jeuno once outpost warps were unlocked, he realized this issue is affecting that NPC as well. He tested the outpost warp NPC from Port Windy as well and had the same issue - both NPCs just give the correct dialogue in chat but the menu does not pop up to allow him to select where he wants to warp to. 

He's rank 3 and was on 40 bst at the time he was attempting to use Twinkstix and Rottata. 

He has no issue doing supply quests or OP warping back to Windurst from the outposts that he has completed the supplies quests for. He also has no issues using the original warp tarus in Windurst. He never black screened or crashed while using the warp tarus. So far it seems to be only affecting Mumbo-Bumbo/Polo-Colo, Twinkstix, and Rotatta. 

Edit: Issue continues even when loading the game without any addons or plugins loaded

Character Name: Vylandra
Version: 30221103_1
Launcher: 1.14
Ashitav4
Windows 11

![Twinkstix](https://user-images.githubusercontent.com/73006091/213941244-24bf5110-8ec3-42b1-872d-826324262fe6.png)

![Mumbo-Bumbo](https://user-images.githubusercontent.com/73006091/213941234-e37ff21a-1e13-4ef9-8713-e02d1abc5d88.png)

![Polo-Colo](https://user-images.githubusercontent.com/73006091/213941425-694803ea-d972-4650-bd5f-a4774eba562e.png)

**Comment by KyleStevenson3** [comment]
This is being widely reported and happens to people without IP exceptions as well. Just so someone doesn’t go chase that angle.

**Comment by CriticalXI** [comment]
This appeared to be an issue with how we were handling deleted characters. If you had a deleted character on your blacklist, it was preventing this from working.
