### ISSUE TITLE
🐛[BUG][Launcher] 3305 login error

### ISSUE THREAD

**Issue by billyism1** [HorizonFFXI/HorizonXI-Issues#915]
The game closed after dieing, attempted to log back in with 3305 error, left it over an hour and still get the same 3305 error after selecting character.

**Comment by Nimsrod** [comment]
same thing.
i've been stuck on the downloading content. rebooted. and now i keep getting the 3305 error.
Second time it happend since launch.
First time it lasted a week.

**Comment by Flam9** [comment]
Login issues with error codes like that are not a launcher issue. If the game is opening, the launcher works. Please file a GM-ticket in Discord for assistance. Apologies, it's outside my purview as a launcher dev.

**Comment by ChakalXI** [comment]
im having that 3305 error during all day,im uninstalling and install the client and the error persist,any suggerence?

**Comment by fahadtx** [comment]
im having same problem how i can solve it

**Comment by JourdainK** [comment]
you have to ask the discord channel ->  file a GM-ticket
