### ISSUE TITLE
"Rubbish Day" (Sleepga II Questline) not able to be started under normal situations.

### ISSUE THREAD

**Issue by ReeseWatanabe** [HorizonFFXI/HorizonXI-Issues#917]
Having the proper prerequisites for the quest Rubbish Day does not seem to allow you to actually start the quest.

How to reproduce:
Have the proper prerequisite quests and talk to Chululu on three different in-game days to have your fortune told.
On an additional fourth in-game day, talking to Chululu should allow you to start the quest Rubbish Day, however, it does not.

**Comment by TracentEden** [comment]
Yeah a fix is in the works for this, you can find a current workaround on discord [here](https://discord.com/channels/933423693848260678/1062571263668785154/1064752720596185208)
