### ISSUE TITLE
🐛[BUG] [NPC] Twinkstix offering more outpost warps than expected for my level

### ISSUE THREAD

**Issue by rotyler** [HorizonFFXI/HorizonXI-Issues#919]
**What does this bug affect?**

Twinkstix in Lower Jueno - Outpost Warp Goblin

**Steps to Reproduce**

Talk to Twinkstix with completed supply runs for the zones in question, but BELOW the level requirement to warp.

**Expected behavior**

Twinkstix does not allow you to use certain warps if you are below the level of that warp.

Important Note: To my understanding the various nation's outpost warp NPCs deny / do not show warps based on this in era list of level requirements: 
https://ffxiclopedia.fandom.com/wiki/Outpost_Teleportation?oldid=263466#Level_Requirements_and_Pricing

Conrad in Bastok behaved this way, and to my understanding that is the expected behaviour. ...but if Twinkstix is what the devs actually want in terms of the level requirements, then this would be a problem with conrad instead of twinkstix

**Screenshots**

![image](https://user-images.githubusercontent.com/45275744/214205991-e3a1e210-c6b2-41fb-ae2c-969e6aada011.png)

Setup Information

I spoke to Twinkstix on 33THF/16NIN, which wouls be below the level 35 requirement to warp to Elshimo Lowlands area. (33THF is my highest level)

**Additional context**
 (orignal discord bug tracker post I made:) https://discord.com/channels/933423693848260678/1067235495656046673
 making this now that I realized I needed to put it here as well as the discord... I can do more testing with different levels and different warp spots later

**Comment by CriticalXI** [comment]
This is working as intended on Horizon
