### ISSUE TITLE
🐛[BUG] Goblin Wolfman - Oldton Movalpolos

### ISSUE THREAD

**Issue by Drisk123** [HorizonFFXI/HorizonXI-Issues#921]
**What does this bug affect?**
The Behavior of the Notorious Monster "Goblin Wolfman"

**Steps to Reproduce**
1. Find Scrawled writing in Oldton Movalpolos (G-13), (I-11), (I-9)
2. Trade a "Goblin Drink" to the Scrawled Writing.
3. Fight him to around 50% where he uses Blood Weapon.
4. Watch the Attack Speed max out or see him stop using Auto attacks completely. (Hundred fists like)
5. Watch the Damage not go back to normal with the 2hour wearing off. 

**Expected behavior**
Wolfman should get a very mild attack speed and damage increase *during* Blood Weapon. 

**Setup Information**
HorizonXI Ver1 Windows 10

**Comment by TracentEden** [comment]
Yep, there is a fix for this but has not yet been pushed to live server (see [PR](https://github.com/AirSkyBoat/AirSkyBoat/pull/2625)), thanks for reporting!
