### ISSUE TITLE
🐛[BUG][NPC]Edacious Opo Opo NM does not drop Nanban Kariginu

### ISSUE THREAD

**Issue by Grentain** [HorizonFFXI/HorizonXI-Issues#924]
**What does this bug affect?**
>Nanban Kariginu is not dropping from the Edacious Opo Opo notorious monster. 

**Steps to Reproduce**
>Kill Edacious Opo Opo an indeterminate number of times
>Do not receive Nanban Kariginu

**Expected behavior**
>Nanban Kariginu should drop with an approximate 50% drop rate.

**Additional context**
>Records from 2005-2009 online that I can find report drop rates of roughly 33-50%, with almost every report showing a drop within that time frame, and with very few reports of the drop taking more kills than that. Recent attempts to farm the item showed 0 drops in 16 kills.

**Comment by dallano** [comment]
the problem with xiclopedia is that it doesn't differentiate whether or not the killer had TH. This provides implausible data. This mob does indeed drop the item you're seeking. But not at a 50% drop rate. The earliest drop rate I can even see on xiclopedia reports them as 25%. But again with a sample sample size and no report on TH or not.
