### ISSUE TITLE
🐛[BUG][System/Combat] Parrying consume shadows

### ISSUE THREAD

**Issue by Alohub0** [HorizonFFXI/HorizonXI-Issues#925]
**What does this bug affect?**

If i have shadows parrying give me skillups but consume my shadows when it should not
**Steps to Reproduce**

combat while shadows are up
**Expected behavior**

parrying massage in chat and no shadow get consumed
**Screenshots**

![Alo_2023 01 23_005653](https://user-images.githubusercontent.com/97781622/214399225-11425288-6d74-47fc-8368-a7c4d1a7ecb6.png)

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment]
Likely fixed in the 1.1 patch but feel free to re-open if not.
