### ISSUE TITLE
🐛[BUG][NPC] Korroloka Tunnel Map Not Available In Bastok

### ISSUE THREAD

**Issue by rarcher** [HorizonFFXI/HorizonXI-Issues#927]
**What does this bug affect?**
~~The in-game key item for the map of Korroloka Tunnel appears to be unattainable.  It is supposed to be purchasable, but is not available from any of the map-dealer NPCs in Bastok.~~

The map **can** be purchased...in Rabao.  This does not match retail, but may be desired era+ behavior.  Guidance from dev team is needed.

**Steps to Reproduce**
Talk to either Rex in Port Bastok or Karine in Bastok Markets.

**Expected behavior**
NPC will have the map for the Korroloka Tunnel zone available for purchase.

**Actual behavior**
Map of Korroloka Tunnel is not available for purchase.

**Setup Information**
Windows Home 10

**Comment by TracentEden** [comment]
I think this was the case in era (see https://ffxiclopedia.fandom.com/wiki/Map_of_the_Korroloka_Tunnel?oldid=270529) , can reopen if you have era proof it was sold in Bastok.
