### ISSUE TITLE
🐛[BUG][NPC]Kreutzet has incorrect respawn timer

### ISSUE THREAD

**Issue by TristtHXI** [HorizonFFXI/HorizonXI-Issues#928]
**What does this bug affect?**
Kreutzet is currently respawning too quick after been killed, saw it twice in 6 hours, also when it depops due to weather ending, it will repop as soon as weather starts again.

**Comment by TracentEden** [comment]
This was fixed in https://github.com/AirSkyBoat/AirSkyBoat/pull/2623
