### ISSUE TITLE
Unable to use Outpost warps

### ISSUE THREAD

**Issue by xGatackx** [HorizonFFXI/HorizonXI-Issues#929]
As title suggests, I am unable to use Outpost warps. Both from my home nation and Jeuno. I am rank 5 I have done all of the supply quests, 
NPC just says it's first line and nothing else.

**Comment by Cuckrtarlson** [comment]
Rank 4 Bastok, Conrad in Bastok. Lvl 44 BST. It worked fine for the first day or two, now it just says "Welcome to the regional Teleporation service!" (Typo is in game as well, not just here). 
![image](https://user-images.githubusercontent.com/123575008/214611164-bfd8339b-5935-4933-adf6-ce63807a4717.png)

**Comment by foxstriker9** [comment]
I am unable to use both Rottata (Windy OP npc) and Goblin. The experience is the same with both. I talk to them and they give me a one-liner welcome. Normally my UI freezes and I am given a pop up menu or further dialogue. In both cases, there is no UI freeze at all. I could be running past the NPCs, press enter, and they'd still just the same one liner as I run by them.

Strangely, I am able to see other people teleporting which never happened in retail. It's animating the NPC making a motion and I can see/hear the gfx of the teleport. In retail, that animation and accompanying sound fx is personal to you only.

I am rank 5, Lv37, and have multiple OP delivery quests completed.

**Comment by Tenkentaru** [comment]
Having the same issue. The patch today did not fix issue for me. Did it fix for anyone else?

**Comment by foxstriker9** [comment]
@Tenkentaru  no I still have the problem :(

**Comment by foxstriker9** [comment]
Update: since hotfix last night, I can use the teleport NPCs. Seems a little shaky due to the unusual responsivity of the NPCs, but it's technically working.

**Comment by xGatackx** [comment]
Patch did not work for me either. But eh, they're working on it and I appreciate it. I'm still having a lot of fun regardless of any small problems.

**Comment by CriticalXI** [comment]
This appeared to be an issue with how we were handling deleted characters. If you had a deleted character on your blacklist, it was preventing this from working.
