### ISSUE TITLE
🐛[BUG][Combat] Charm Bug

### ISSUE THREAD

**Issue by Kaiia01** [HorizonFFXI/HorizonXI-Issues#930]
**What does this bug affect?** Charm Ability
I was exping and noticed I couldn't charm this fly. Name stayed yellow as if nothing happened to it. I charmed twice and it stops attacking. Looking at video it looks like for a split second i charmed it and then instantly de-charms. I killed it for it to spawn again and still can't be charmed. I zoned and the same thing. I took a video as well. This also happened in Ordelle Caves with a bat. Has also happened multiple times to fellow Beastmasters.
**Steps to Reproduce**

I had this mob charmed, it de-charmed and couldn't charm again. Even after killing or zoning. 
**Expected behavior**

Being charmed or name turning red as if aggroed / resisted charm. Should not stop attacking. 
**Screenshots**
https://youtu.be/zGzkyNBUmAY
**Setup Information**

Windows 10
**Additional context**

**Comment by dallano** [comment]
Which mob was this specifically?

**Comment by CriticalXI** [comment]
Closed due to no response
