### ISSUE TITLE
🐛[BUG][System] OOE item Winterflower a result from gardening

### ISSUE THREAD

**Issue by AlysAkaino** [HorizonFFXI/HorizonXI-Issues#932]
**What does this bug affect?**

Gardening results

**Steps to Reproduce**

Brass Flowerpot + Vegetable Seeds = Fire Crystals / La Theine Cabbages / Winterflower

**Expected behavior**

Winterflower is OOE and shouldn't be included in the gardening results.

**Screenshots**

![Alys_2023 01 25_211857](https://user-images.githubusercontent.com/123610487/214743615-4c6a1e5c-6360-4ffe-a5a7-abb47ed77dd7.png)

**Setup Information**

HorizonXI current version as of Jan 20, 2023.

**Comment by TracentEden** [comment]
Will be fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2596
