### ISSUE TITLE
🐛[BUG][Crafting] Bugbear Mask LC Desynth Incorrect

### ISSUE THREAD

**Issue by perkuprightmeow** [HorizonFFXI/HorizonXI-Issues#937]
**What does this bug affect?**
Desynthing Bugbear masks with a WIND crystal should result in : 
Yield: [Ram Leather] x3
HQ1: [Ram Leather] x3
HQ2: [Ram Leather] x3
HQ3: [Gold Thread] x2

Right now it currently results in 2 Ram Leathers. 
![image](https://user-images.githubusercontent.com/52988064/214890802-14827ebe-8548-49b0-ba99-a8effe514359.png)
Not sure if important, but this was an HQ synth. 

------

Some old wiki entries : 
https://ffxiclopedia.fandom.com/wiki/Bugbear_Mask?oldid=40346
https://ffxiclopedia.fandom.com/wiki/Bugbear_Mask?oldid=157803

Somepage : 
http://ffxi.somepage.com/itemdb/5793

This is correct in the ASB respository:
`INSERT INTO `synth_recipes` VALUES (41517,1,0,0,0,0,0,35,0,0,0,4098,4240,1624,0,0,0,0,0,0,0,851,851,851,823,3,3,3,2,'Bugbear Mask (desynth)')`

So could be era+, just figured I'd file a report anyway.

**Comment by TracentEden** [comment]
Yep, should be fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2548 , thanks for reporting!
