### ISSUE TITLE
Fishing luetail bug

### ISSUE THREAD

**Issue by btgraham5** [HorizonFFXI/HorizonXI-Issues#938]
**What does this bug affect?**

I believe the fishing pool specifically for Bluetail is bugged or messed up, but could be other fish as well. I believe the bluetail pool is a total pool on the entire server rather than it being just the specific zone. The pool was replenished as I fish in Buburimu, I am the ONLY person here fishiing Bluetail. I caught 10 fish and now i cannot catch anymore. How is anyone supposed to make gil or skill up on this? This ruins the ability to make gil or level up via fishing. If this persists it will create congestion of fisherman in the level range of 50-55. 
**Steps to Reproduce**

**Expected behavior**

We could all fish endelessly and make the gil as normal allowing our time not to be wasted waiting for the pool to refill. 

**Screenshots**

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment]
Feel free to re-open if you have proof that this is the case but as of right now this comes off as not liking the system rather than it being an actual bug
