### ISSUE TITLE
🐛[BUG] KSNM - Contaminated Colosseum

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#94]
**What does this bug affect?**
TP move Extremely Bad Breath goes off faster than in capture. Currently goes off after about 2 seconds (or whatever the normal mob TP move ready time is) and capture shows it taking longer, around ~4 seconds.

**Steps to Reproduce**
Go into fight and wait for it to use Extremely Bad Breath and see the ready time.

**Expected behavior**
Extremely Bad Breath should take longer to ready and actually go off, around 4 seconds or so based on capture.

**Setup Information**
Version 30220802_3

**Additional context**
Everything else seems good with the fight.

**Comment by dallano** [comment]
Fix in PR: https://github.com/AirSkyBoat/AirSkyBoat/pull/376
