### ISSUE TITLE
🐛[BUG][NPC/System/] Shellbuster vendor price out of era (much lower than it should be)

### ISSUE THREAD

**Issue by setsuk0** [HorizonFFXI/HorizonXI-Issues#942]
<Npc/system/item/idk/>
**What does this bug affect?**
Shellbuster (drop from mobs in castle zvahl) vendors for an out of era price, which is significantly lower than it should be. It's possible other vendor-trash drops from castle zvahl may also vendor for incorrect/out of era price.

**Steps to Reproduce**
To reproduce: kill mobs in castle zvahl, obtain a shellbuster, try to vendor it to NPC and note the incorrect price.

**Expected behavior**
Shellbuster should vendor to the npc for ~4k.

https://ffxiclopedia.fandom.com/wiki/Shellbuster?oldid=579521 

**Screenshots**
![Setsuko_2023 01 26_153943](https://user-images.githubusercontent.com/48462732/215007006-8655c507-9216-4a6d-bcd5-979534d9d700.png)

**Setup Information**
game version 30221103_1

**Additional context**
Impacts player ability to farm mobs in castle zvahl and vendor the junk for an *ok* amount of gil

**Comment by dallano** [comment]
I believe this is an intended change to combat economic inflation.
