### ISSUE TITLE
🐛[BUG]Combat (En-spells do 0 damage now)

### ISSUE THREAD

**Issue by DJZeekyZeke** [HorizonFFXI/HorizonXI-Issues#944]
**What does this bug affect?**
The damage from en-spells (enfire, enaero, etc.) is now zero, sometimes a bit higher. 

**Steps to Reproduce**
Log on to your red mage, cast an en- spell, look at your damage when attacking.

**Expected behavior**
6*Enhancing skill divided by 100 then add 3, if your enhancing skill is less than 200. 

**Screenshots**
![image](https://user-images.githubusercontent.com/118415356/215167827-ce2756c9-9cf5-422b-8e70-6c2926e51a51.png)

**Setup Information**
Windows 10

**Additional context**
N/A, pretty easy bug to find.

**Comment by Grentain** [comment]
I did some testing on my own. 
-Myself and another RDM attacking mobs around level 30 (about 15 levels under us) would consistently deal 0 damage about 50% of the time. 
-Another RDM reported never hitting anything higher than a 0 on mobs 10 levels under them. 
-Another level 31 RDM attacking a level 5 mob reports hitting for 8s consistently, no 0s.

There might be something broken in the Enhancement Skill calculations causing them to not apply to Enspells, or something similar. Absolute monster level seems like it might be a factor?

**Comment by Shozokui** [comment]
This issue was resolved with the magic updates / fixes.
