### ISSUE TITLE
🐛[BUG][Elemental Magic Vs. Beastmen pets]

### ISSUE THREAD

**Issue by orcachan** [HorizonFFXI/HorizonXI-Issues#945]
The resist rate of elemental magic spells seems to be off. Most of the resists have come against Beastmen pets solo.

This was a level 38 Goblin's Bee in Yhoator Jungle. Black pudding food buff

**Screenshots**
![bug1](https://user-images.githubusercontent.com/123769049/215189918-2a081e9d-3373-4671-ab88-140019874773.png)
![bug2](https://user-images.githubusercontent.com/123769049/215190031-f64d53d6-1b76-4e88-9f7c-a06849421899.png)
![bug3](https://user-images.githubusercontent.com/123769049/215190159-4fe6db96-ee74-479e-9bd9-0437993e48ca.png)
![bug4](https://user-images.githubusercontent.com/123769049/215190163-d9e2de4d-e470-47f0-a52c-cd236f0e5be5.png)

**Comment by CriticalXI** [comment]
Magic has seen several adjustments since this issue was created. We also need a lot more information to be able to pinpoint where the issue is if you're still experiencing this.
