### ISSUE TITLE
🐛[BUG][Combat] Goblin double tp move

### ISSUE THREAD

**Issue by PfistoFFXI** [HorizonFFXI/HorizonXI-Issues#947]
Combat
**What does this bug affect?**

Goblin Gutterman will follow a TP move with suicide bombtoss back to back.
**Steps to Reproduce**

Feed Goblin Gutterman TP
**Expected behavior**

Using only 1 tp move
**Screenshots**

![image](https://user-images.githubusercontent.com/40551158/215197362-2397bb75-7985-4e34-b519-81ea837ac29e.png)
![image](https://user-images.githubusercontent.com/40551158/215197532-3feca19f-8356-49bd-a19b-f7e25d69c733.png)

**Comment by PfistoFFXI** [comment]
saw it with this type too, maybe just a goblin promblem 
![image](https://user-images.githubusercontent.com/40551158/215272824-0bb83cde-1c00-4c8c-a861-f402a25365f6.png)

**Comment by varxxx** [comment]
This might be affecting other mobs as well. Didn't get any screenshots last night but our group had a Raven do one of its TP moves 3 times in a row. I will try to get a screenshot of it if it happens again and im killing ravens in bibiki

**Comment by PfistoFFXI** [comment]
Might be a COP area thing then, I don't know atm.

**Comment by Clonegoat** [comment]
Failed to grab a screenshot but had this happen last night in Bubu with a Leecher, and today in Maze of S. with a Butcher, both times were Bomb Toss

**Comment by Clonegoat** [comment]
jk it just happened again 
![Screenshot 2023-01-28 210332](https://user-images.githubusercontent.com/80860333/215300319-729fa1fc-189f-41d6-bea3-c75f05100768.jpg)

**Comment by CriticalXI** [comment]
Issue was fixed a few weeks ago
