### ISSUE TITLE
[BUG][Crafting/GP Vendor]Cooking GP item requires KI

### ISSUE THREAD

**Issue by Phuckyufoo** [HorizonFFXI/HorizonXI-Issues#953]
What does this bug affect?
Ability to obtain Cooking Guild Points

Steps to Reproduce
Under the Craftsman rank talk to the NPC in Windurst Waters Qhum Knaidjn and see what she requests (screenshot included below)

Expected behavior
Should not be a requested item from the NPC>

Screenshots
![image](https://user-images.githubusercontent.com/12584874/215276462-8bae30bc-ce13-4265-a561-dca6fb8c42b9.png)
![image](https://user-images.githubusercontent.com/12584874/215276482-66553d65-cd53-4994-b7c1-e1fe5911de12.png)

**Comment by TracentEden** [comment]
This item is OoE and will be fixed by in progress PR (watch patch notes).
