### ISSUE TITLE
🐛[BUG][NPC/Quest]

### ISSUE THREAD

**Issue by shinjiku2008** [HorizonFFXI/HorizonXI-Issues#955]
**What does this bug affect?**
Spice Gals Quest in Southern San d'Oria.  

**Steps to Reproduce**
Rouva speaks of getting the Rivernewort but doesn't give the quest. Going out the Riv. A01 to retrieve the KI from the ??? doesn't yield aswell. Did not attempt Riv. B01.

**Setup Information**
Ashita, Windows 10

**Additional context**
2005 quest [Spice Gals](https://ffxiclopedia.fandom.com/wiki/Spice_Gals)

**Comment by dallano** [comment]
This was reported on the ASB database and has a fix coming. Thank you for your report
