### ISSUE TITLE
🐛[BUG][System] Rain Hat causing dungeon zones to crash.

### ISSUE THREAD

**Issue by squee88** [HorizonFFXI/HorizonXI-Issues#957]
Zoning out of a dungeon zone into another zone with Rain Hat equipped is crashing the dungeon.  The crash chance seems to be increased/guaranteed with sneak and invisible on, but I have noticed at least 1 instance of a crash w/o sneak or invisible on.  So far the zone connections that I have observed it happening with are:
Garlaige Citadel to Sauromugue Champaign
Ifrit's Cauldron to Yuhtunga Jungle
Quicksand Caves to Chamber of Oracles (without sneak/invis)
The Eldieme Necropolis to Batallia Downs

Going from Upper Jeuno back and forth to Batallia Downs with Rain Hat, sneak, and invisible did not reproduce the crash leading me to believe that this only affects dungeon zones.

**Comment by TracentEden** [comment]
This should now be fixed.
