### ISSUE TITLE
🐛[BUG][NPC] Bloodsucker NM Currently Has Single Spawn Point

### ISSUE THREAD

**Issue by ThoseWhoFight** [HorizonFFXI/HorizonXI-Issues#958]
**What does this bug affect?**
Bloodsucker NM currently has a single spawn point. Could use some auditing. 

**Expected behavior**
This NM is supposed to have a very large amount of spawn areas all over the third map. Unsure why this hasn't been reported yet as it's been getting killed on repop while very obviously not functioning correctly.

**Comment by TracentEden** [comment]
Will be fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2717
