### ISSUE TITLE
🐛[BUG][NPC] Bloodthirster Madkix spawn audit

### ISSUE THREAD

**Issue by ThoseWhoFight** [HorizonFFXI/HorizonXI-Issues#959]
**What does this bug affect?**
Common issue for this NM to not spawn correctly or at all on private servers, attempted spawning yesterday with no luck. Seeing mentions of other people in discord also mentioning having similar issues. Knowing this was an issue on other servers, this could probably use an audit to ensure it's not broken.

**Additional context**
https://github.com/EdenServer/community/issues/2739

**Comment by TracentEden** [comment]
Yep, this will be fixed by an in process PR (watch patch notes for update)
