### ISSUE TITLE
🐛[BUG] KSNM - Prehistoric Pigeons

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#96]
**What does this bug affect?**
Mob's sleep resistance. Able to sleep mobs repeatedly with sleep magic & lullaby. NMs only use 2hr once.

**Steps to Reproduce**
Cast sleep / lullaby on NMs repeatedly. Repeat after killing another NM.

**Expected behavior**
Based on wiki (no capture to pull from in discord / only video found on youtube was mana burn method that slept only once) mobs should build resistance to sleep / lullaby, with the mobs resisting sleep 2 (without elemental seal) after 2 NMs are killed. I'm assuming after 3 are killed the last one should just be immune. If wiki is to be believed the NMs should use their 2hr multiple times, though I feel this fight would still be hard enough without that.

**Setup Information**
Version 30220802_3

**Additional context**
No capture on discord to assess, only video I found on youtube was a mana burn method that slept the birds once with lullaby.
Wiki states:
All are susceptible to Sleep, Lullaby, and Bind. Resisted sleep (except with ES) after two of the birds were killed.
Can use 2 hour more than once.
Builds resistance to sleep quickly. Was only able to sleep them twice as BLM75/WHM37, before it was completely resisted all times except with elemental seal. Strategy was to weaken each one to 10% then finish all at once, yet without being able to sleep them it did not work well.

**Comment by dallano** [comment]
Crit and I did a personal capture for this one and we discovered they didn't build sleep resistance as they died whatsoever. Sleeps lasted the same amount of time each time one of the birbs died. Moreover we only witnessed them using their 2hr once.

We actually had this BCNM sit as a PR for a looong time until we got personal captures for this ourselves. Couldn't find any proper evidence anywhere.

**Comment by Squinkerdoodle** [comment]
Sounds good to me then
