### ISSUE TITLE
🐛[BUG][NPC] Phantom Worm doesn't depop

### ISSUE THREAD

**Issue by ThoseWhoFight** [HorizonFFXI/HorizonXI-Issues#960]
**What does this bug affect?**
Phantom Worm NM doesn't seem to deaggro or depop after player runs away, was gone for over an hour and it was still in aggro stance/sitting in room. Could see it on widescan the entire time while gone so I know it was the same pop.

**Comment by TracentEden** [comment]
Did the player that had aggro zone or logout at all during that time? I think worms might not deaggro otherwise. They might need special deaggro behavior added since they cannot chase players.

**Comment by ThoseWhoFight** [comment]
No logout or zone

**Comment by CriticalXI** [comment]
Phantom Worm just depopped for me, but it has a long timer to depop.
