### ISSUE TITLE
[BUG][ITEMS] Jar items giving out of era increased storage?

### ISSUE THREAD

**Issue by FahrosXI** [HorizonFFXI/HorizonXI-Issues#963]
Hello Horizon team!

It was recently brought to my attention that players can buy the item "White Jar" at a Windurst NPC for around 5k a pop, and it gives them 6 Mog Storage space per jar. My friends are new players and assumed this was intentional, and bought tons and tons of them. When I heard about it from them, I started investigating because I don't recall ever hearing about these items back in the day.

I found the associated oldschool ZAM pages and comments. It turns out there's a couple different jar items that you may want to check in to:

White Jar: https://ffxi.allakhazam.com/db/item.html?fitem=2588

Yellow Jar: https://ffxi.allakhazam.com/db/item.html?fitem=2587

Red Jar: https://ffxi.allakhazam.com/db/item.html?fitem=3720

It seems in era these items gave much less storage. During the June 2008 update it seems their storage skyrocketed. For example White Jars went from 2 storage to 6 storage. Currently HorizonXI is using those increased storage values from the June 2008 update. When I saw this I advised my friends that these items may not be functioning as intended for this server, and they should sell them and forego using them as extra storage for now.

I created a ticket in the HorizonXI Discord asking GMs if this was intentional or not, and they suggested I make a report here that the values seem to be out of era. I will assume that this is unintentional and will be patched, unless I hear from anyone that there's a greenlight to go ahead and use these for tons of storage.

Thanks for all your hard work on this server. We appreciate you!
~Fahros

**Comment by hookstar** [comment]
What does the dats say?

**Comment by bliven-was-taken** [comment]
@hookstar 

![image](https://user-images.githubusercontent.com/61694447/216628292-930fd97c-0cf8-478d-a17b-5f95593b1a09.png)

It's all of these that are technically wrong.

**Comment by hookstar** [comment]
@bliven-was-taken Thanks - was curious what the in-game dats looked like - do they reflect the new changes I am assuming so?

**Comment by hookstar** [comment]
I just dont know if it would be worth the effort to completely change 29 items dats over some storage spaces - can only get 80 so I am not sure its going to matter.

**Comment by bliven-was-taken** [comment]
Yea, the dats say the retail numbers of course. Also this would be changed back when wotg comes out, so I personally do not believe it is worth the effort.
