### ISSUE TITLE
[BUG][NPC/Quest] Angelica in Windurst Waters North is not giving out the quest A Pose by Any Other Name

### ISSUE THREAD

**Issue by 1Byte2Bits** [HorizonFFXI/HorizonXI-Issues#966]
**“What does this Bug Affect?”**

It is not possible currently to interact with the NPC Angelica in order to receive and attempt to complete the quest "A Pose by Any Other Name". Angelica just stands there motionless and does not say anything when interacted with at all.

**“Steps to Reproduce”**

1. Go to Windurst Waters North, F-10, at the top floor of the Rarab Tail Hostelry
2. Interact with NPC Angelica
3. Confirm that the NPC does not reply or interact back with the player character at all
4. Check quest log and confirm that player character has not received the quest "A Pose by Any Other Name"
5. Re-zone and repeat the steps above and confirm same result

**“What should be the intended functionality?”**

When interacting with Angelica, she would reply to the player character and give them the quest "A Pose by Any Other Name", asking the player character to wear a specific body equipment which depends on the player character job.
Angelica should definitely NOT just stand still without replying anything on interaction.

**Comment by 1Byte2Bits** [comment]
VERY IMPORTANT: I found out that this bug only happens when my player character's job is set to MNK (possibly others too?). I tried talking to Angelica as a WAR and she gave me the quest just fine.

**Comment by hookstar** [comment]
There is a mandatory zone check. It may have been from a previous quest. Either way, glad it got working for you.
Start with a clean zone-in. Have the necessary item in your inventory, but not on.
