### ISSUE TITLE
🐛[BUG][Quest] Quest sometimes blocking RDM AF Hat quest

### ISSUE THREAD

**Issue by TracentEden** [HorizonFFXI/HorizonXI-Issues#969]
**What does this bug affect?**
Despite being 60 RDM, Curilla will not give me the 'Peace for the Spirit' quest and just gives me the quest 'The General's Secret' (potentially after accepting the quest)

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by hookstar** [comment]
Thanks @TracentEden - this looks like it needs to be converted

**Comment by hookstar** [comment]
https://github.com/AirSkyBoat/AirSkyBoat/pull/2721
