### ISSUE TITLE
🐛[BUG] KSNM - The Scarlet King

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#97]
**What does this bug affect?**
NM seems to be missing the TP move "Greater Sandstorm" which is different from the manticore family's normal TP move "Great Sandstorm".
Greater Sandstorm: A hate-erasing AoE move.

**Steps to Reproduce**
Go into the fight and feed NM tp to see if it uses the above move.

**Expected behavior**
Per the wiki / bg-wiki / testimonies on allakhazam, the mob should be able to use the above move in addition to all the other normal manticore tp moves.

**Setup Information**
Version 30220802_3

**Additional context**
There is no capture available on discord and no official server vids found on youtube. So can't say this should be a thing for certain, however there are multiple sources claiming it to be legitimate.

**Comment by dallano** [comment]
We also did another personal capture on this one. Crit, Aerec, and I. We determined that great sandstorm wasn't actually wiping hate as wiki suggests. And great sandstorm is currently in his mob skill list so he should be using it.

**Comment by Squinkerdoodle** [comment]
Great Sandtorm is the normal move, the AOE hate wiping move is called "Greater Sandstorm" and would be a different move from the original.

**Comment by dallano** [comment]
hmm. That ability isn't even in our current code base. Might have to get another capture for this.

**Comment by dallano** [comment]
Going over my notes during the capture, he didn't even use it.
I'll get some buddies together and do another capture

**Comment by Squinkerdoodle** [comment]
Personally I'd be fine if it isn't a thing, the fight seems hard enough without hate resetting and bouncing around.

**Comment by dallano** [comment]
Yeah it's actually an insane fight! but for a 6 man with one mob, it's gotta be even tougher!!

**Comment by Squinkerdoodle** [comment]
I still can't find any hard proof that the NM should have this move, so we may be good to close it and mark as tested on the sheet.

**Comment by dallano** [comment]
Sure! I'll still keep note of this and make sure to do my best to get a capture of it.
