### ISSUE TITLE
🐛[BUG][Combat] Black Belt items are missing from NQ ground kings

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#970]
**What does this bug affect?**

Currently the three black belt items are not on the loot table according to ASB when they should be. Their loot table was changed when the kings were made pop item NMs.

**Expected behavior**

Fafnir, Behemoth and Adamantoise should all be able to drop their respective items for the black belt quest.

**Additional context**

https://ffxiclopedia.fandom.com/wiki/Wyrm_Beard?oldid=69533
https://ffxiclopedia.fandom.com/wiki/Behemoth_Tongue?oldid=182565
https://ffxiclopedia.fandom.com/wiki/Adamantoise_Egg?oldid=233953

**Comment by TheUndeadFish1** [comment]
I only remember the BB items being around a 10% drop rate on the normal versions. Could just be rng, but if not it's worth looking into.
