### ISSUE TITLE
🐛[BUG][NPC/Quest/Mission/System/Combat/Launcher/Website]

### ISSUE THREAD

**Issue by KTG03** [HorizonFFXI/HorizonXI-Issues#971]
**What does this bug affect?**
NM did not spawn on 24hr mark

Killed NM Steelfleece Baldarich at 12:33pm est yesterday. I came into the game an hour before the window opened. I been here since and the NM did not spawn as it should have. Waited until the 24hr mark 

**Steps to Reproduce**

Killed all PH or watched PH be killed. Waited for said mob to spawn under those conditions 
**Expected behavior**

The NM should have spawned with in the window
**Screenshots**

**Setup Information**

**Additional context**

**Comment by TiberonKalkaz** [comment]
This mob is a lotto at its core - there is no guarenteed force spawn for lottos, unless Era+ adds a new QoL.

**Comment by hookstar** [comment]
Additionally, it cannot pop if Lumbering Lambert is up. Closing this ticket for now. Thank you.
