### ISSUE TITLE
🐛[BUG][Quest] Waking Dreams Sometimes Gives Extra Rewards

### ISSUE THREAD

**Issue by KiplingFFXI** [HorizonFFXI/HorizonXI-Issues#972]
**What does this bug affect?**

I completed "Waking Dreams" (the diabolos prime avatar fight quest) and when I chose a pact with the avatar, I received the diabolos earring and a pact with the avatar at the same time. I should only receive one or the other.

**Steps to Reproduce**

1. Kill diabolos
2. Complete waking dreams
3. Select pact with the avatar
4. Get pact + diabolos earring at the same time

**Expected behavior**

I should only get one item or just a pact with the avatar.

**Screenshots**

![Kipling_2023 01 21_004722](https://user-images.githubusercontent.com/111715243/215349686-a6100323-ac24-4461-9d33-e15056e822b6.png)

**Setup Information**

N/A - Was a bit ago. I only use the Horizon client.

**Additional context**

I already submitted a GM ticket and had a GM remove my item.

**Comment by TracentEden** [comment]
Fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/2711
