### ISSUE TITLE
🐛[BUG] KSNM - Cactuar Suave

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#98]
**What does this bug affect?**
All mob's sleep / lullaby resistances. Main NM's (Campeon) bind resistance.

**Steps to Reproduce**
Go into fight and use sleep magic & lullaby on all mobs. Use Bind on main NM (Campeon).

**Expected behavior**
Per the capture even an elemental seal + sleepga was completely resisted suggesting the mobs should be highly resistant, if not straight immune to sleep magic / lullaby. Additionally the main NM (Campeon) gave the "completely resisted" message for Bind.

**Setup Information**
Version 30220802_3

**Additional context**
While testing lullaby was already getting resisted heavily, but it was able to land 2-3 times on each mob. Sleep / Sleep 2 were landing somewhat regularly. Able to bind the 2 helper NMs (Amante) but this was correct.

**Comment by dallano** [comment]
fix in PR: https://github.com/AirSkyBoat/AirSkyBoat/pull/376
