### ISSUE TITLE
🐛[BUG][System] Castle Zvahl Keep teleporters shouldn't always teleport you

### ISSUE THREAD

**Issue by CriticalXI** [HorizonFFXI/HorizonXI-Issues#984]
The teleports within Castle Zvhal Keep should only teleport you when a symbol is active on the platform. Needs a retail capture to watch how the symbol moves and how long it stays at each location.

**Comment by siknoz** [comment]
Retail Capture: https://youtu.be/_UK7aciZfMs

Seems to turn on for ~12s then turns off for a random 10-60s. There's times when two teleporters are lit up and one time all 3 were lit up. So I don't think it "moves" around, think it's just random timers. Can watch and draw your own conclusions though.
