### ISSUE TITLE
🐛[BUG]Dragon Cuisses +1 have incorrect NPC value.

### ISSUE THREAD

**Issue by ffxiWaxer** [HorizonFFXI/HorizonXI-Issues#987]
**What does this bug affect?**

**Steps to Reproduce**

!additem 14231 and sell to vendor.

**Expected behavior**
HQ shouldn't be < NQ
**Screenshots**
![image](https://user-images.githubusercontent.com/94857791/215650343-79055aec-4690-4a13-853f-8e5e8a9e65d0.png)
**Setup Information**
103_1
**Additional context**

**Comment by MarkWaldron** [comment]
@ffxiWaxer Do you have the correct price for this Era?

**Comment by ffxiWaxer** [comment]
> @ffxiWaxer Do you have the correct price for this Era?

![image](https://user-images.githubusercontent.com/94857791/215961066-190f13ce-6975-4776-845b-c9c99332cca8.png)

**Comment by dallano** [comment]
This appears to have been fixed. Please feel free to reopen the ticket if the problem persists
