### ISSUE TITLE
[Bug] Hellion not spawning

### ISSUE THREAD

**Issue by Vintererella** [HorizonFFXI/HorizonXI-Issues#989]
Hellion not spawning in Labyranth of Onzozo because only one placeholder is there.

**Comment by ThiefFFXI** [comment]
Hellion is spawning in LoO as I have killed him several times.

**Comment by siknoz** [comment]
Saw him killed by my onzozo party a few days ago.

**Comment by hookstar** [comment]
Can we get some amplifying data on this? A link to a timeline or a video showing PH's etc?
