### ISSUE TITLE
🐛[BUG] KSNM - Come Into My Parlor

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#99]
**What does this bug affect?**
The dogs from the BCNM Let Sleeping Dogs Die are dead on the floor when entering the KSNM Come Into My Parlor. Main NM and baby NMs missing additional effect: poison on auto attacks. Unable to charm baby spiders, went 0 / 50+ on charm attempts, though I was naked aside from Apollo's Staff.

**Steps to Reproduce**
Go in to the fight arena and see if the dead dogs are visible. Allow main NM and baby NMs to hit you to see if the additional effect: poison goes off. Attempt to charm the baby NM spiders to see if it works or not.

**Expected behavior**
Dead dogs shouldn't be present in this KSNM.
Should be able to charm the baby spiders, according to testimonies, somewhat easily.
There's no capture on discord, but wiki / bg-wiki states the spiders should have additional effect: poison on auto attacks. I found a youtube video that seems to be from retail where at least the baby son spiders have this effect so I believe the main NM should have it too though unable to verify, timestamp 2:14
https://youtu.be/XVaG_8QI9Ns?t=134

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/190229286-54b19da9-849e-4fd9-9b55-dc2e1525845e.png)

**Setup Information**
Version 30220802_3

**Additional context**
For timeframe context, I did the BCNM Let Sleeping Dogs Die yesterday, and logged out in between that and testing this KSNM.

**Comment by dallano** [comment]
Nice catch, Squink! Easy fix incoming in PR: https://github.com/AirSkyBoat/AirSkyBoat/pull/376
But I'll just check a few captures to determine rate of "en-poison". Whether it's 100% or not.

**Comment by Squinkerdoodle** [comment]
@dallano it's not a 100% effect for sure based on that youtube video, I'm guessing maybe a high~ish chance like between 50-65%?
