### ISSUE TITLE
[Bug] Royal Knights Breeches not available when sandy in 2nd place

### ISSUE THREAD

**Issue by Rocky-Johnson-82** [HorizonFFXI/HorizonXI-Issues#991]
**What does this bug affect?**
unable to purchase item at rank 6 with Sand in 2nd place

**Steps to Reproduce**
try to buy it and says rank is too low ( i am rank 6)

**Expected behavior**
purchase pants 

https://ffxiclopedia.fandom.com/wiki/San_d%27Oria_Conquest_Points_Items
Shows should be ale to purchase with sand in 1st and 2nd place

**Comment by bliven-was-taken** [comment]
https://ffxiclopedia.fandom.com/wiki/Royal_Knight%27s_Breeches  Conflicting info is why you can't.
