### ISSUE TITLE
🐛[BUG][Combat] Goblin's No Longer Suicide Bomb Tossing

### ISSUE THREAD

**Issue by ramorakomo** [HorizonFFXI/HorizonXI-Issues#993]
**What does this bug affect?**
None of the goblin's in the game are using the Suicidal bomb toss.

**Steps to Reproduce**
Fought lots of goblins, there's others experincing same issue on discord in Bug Finder.

**Expected behavior**
Not sure the correct number but a % of bomb toss should result in suicide(of the goblin).

**Screenshots**
N/A

**Setup Information**
N/A

**Additional context**

**Comment by TracentEden** [comment]
This was fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/3215
