### ISSUE TITLE
🐛[BUG][Quest] - Bait & Switch - Salim - Bastok Metalworks - does not give quest

### ISSUE THREAD

**Issue by Swoodend** [HorizonFFXI/HorizonXI-Issues#998]
**What does this bug affect?**

I believe the quest should be available from Salim in the metalworks. I am rank 9 Bastok fame but cannot receive the quest. It should be available at rank 3.

According to this site the quest was available in at least February 2006. Which I think means it IS era.
https://ffxiclopedia.fandom.com/wiki/Bait_and_Switch?oldid=51435

**Steps to Reproduce**

- Get rank 3 bastok
- Talk to Salim in metalworks
- He will not give you the quest

**Expected behavior**

He should give you the quest
**Screenshots**

**Setup Information**

**Additional context**

**Comment by hookstar** [comment]
We are aware of this issue - it is currently being worked on and will be implemented at a later date.
