### ISSUE TITLE
🐛[BUG][System] Hostile Herbivores reward chest doesn't spawn

### ISSUE THREAD

**Issue by Powercow1337** [HorizonFFXI/HorizonXI-Issues#999]
**What does this bug affect?**
Hostile Herbivores (BCNM50 in Horlais Peak) doesn't give out a treasure chest reward... sometimes. Our first run worked fine, the second run gave no chest. Called a GM (Ah Puch answered), who came and re-cleared a new one, where the chest again did not spawn after the last sheep died.

**Steps to Reproduce**
Kill the last sheep in Hostile Herbivores.  Do a repeat clear if the first one works fine.

**Expected behavior**
Chest should spawn after the third sheep dies.

**Screenshots**
[](https://cdn.discordapp.com/attachments/1070577206050431028/1070577764031270912/Powercow_2023.02.01_213336.png)

**Setup Information**
Windows 11

**Additional context**
Weird it worked the first time, but not second or third.

**Comment by TracentEden** [comment]
I was not able to recreate, can reopen if it happens again. Thanks!
